Mappel: mappel::estimator::Estimator< Model > Class Template Reference
mappel::estimator::Estimator< Model > Class Template Reference abstract
#include </home/travis/build/markjolah/Mappel/include/Mappel/estimator.h>
Public Member Functions
Estimator (const Model &_model)
virtual ~Estimator ()
virtual std::string name () const =0
const Model & get_model ()
void estimate_max (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, MLEData &mle_data, StencilT< Model > &mle_stencil)
void estimate_max (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, MLEData &mle_data)
void estimate_max (const ModelDataT< Model > &data, MLEData &mle_data)
void estimate_max_debug (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, MLEDebugData &mle_data, StencilT< Model > &mle_stencil)
void estimate_max_debug (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, MLEDebugData &mle_data)
virtual void estimate_max_stack (const ModelDataStackT< Model > &data_stack, const ParamVecT< Model > &theta_init_stack, MLEDataStack &mle_data_stack)=0
void estimate_max_stack (const ModelDataStackT< Model > &data_stack, MLEDataStack &mle_data_stack)
double estimate_profile_max (const ModelDataT< Model > &data, const IdxVecT &fixed_idxs, const ParamT< Model > &fixed_theta_init, StencilT< Model > &theta_max)
virtual void estimate_profile_max (const ModelDataT< Model > &data, const ParamVecT< Model > &fixed_theta_init, ProfileLikelihoodData &profile)=0
void estimate_profile_bounds (const ModelDataT< Model > &data, ProfileBoundsData &bounds_est)
virtual void estimate_profile_bounds_parallel (const ModelDataT< Model > &data, ProfileBoundsData &bounds_est)=0
void estimate_profile_bounds_debug (const ModelDataT< Model > &data, ProfileBoundsDebugData &bounds_est)
virtual void estimate_profile_bounds_stack (const ModelDataStackT< Model > &data_stack, ProfileBoundsDataStack &bounds_est)=0
virtual StatsT get_stats ()
virtual StatsT get_debug_stats ()=0
virtual void clear_stats ()
IdxVecT get_exit_counts () const
Protected Member Functions
virtual void compute_estimate (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, MLEData &mle_data, StencilT< Model > &mle_stencil)=0
virtual void compute_estimate_debug (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, MLEDebugData &mle_data, StencilT< Model > &mle_stencil)
virtual double compute_profile_estimate (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, const IdxVecT &fixed_idxs, StencilT< Model > &max_stencil)
virtual void compute_profile_bound (const ModelDataT< Model > &data, ProfileBoundsData &est, const VecT &init_step, IdxT param_idx, IdxT which_bound)
virtual void compute_profile_bound_debug (const ModelDataT< Model > &data, ProfileBoundsDebugData &est)
void record_walltime (ClockT::time_point start_walltime, int num_estimations)
virtual void record_exit_code (ExitCode code)=0
Protected Attributes
const Model & model
int num_estimations = 0
double total_walltime = 0.
IdxVecT exit_counts
Friends
template<class T >
std::ostream & operator<< (std::ostream &out, Estimator< T > &estimator)
Detailed Description
template<class Model>
class mappel::estimator::Estimator< Model >
Estimator base class defines the interface for estimator interactions designed to unify the ThreadedEstimator with future GPUEstimator types under a single API.
Design notes: Templated on the model type to allow for direct function call for models through the mappel::methods namespace templated model methods.
Definition at line 194 of file estimator.h.
Constructor & Destructor Documentation
template<class Model > mappel::estimator::Estimator< Model >::Estimator (const Model & _model)
Definition at line 102 of file estimator_impl.h.
template<class Model > virtual mappel::estimator::Estimator< Model >::~Estimator () inline virtual
Definition at line 197 of file estimator.h.
References mappel::methods::estimate_max(), mappel::methods::debug::estimate_max_debug(), and mappel::methods::openmp::estimate_max_stack().
Member Function Documentation
template<class Model > void mappel::estimator::Estimator< Model >::clear_stats () virtual
Run statistics.
Reimplemented in mappel::estimator::IterativeMaximizer< Model >, and mappel::estimator::ThreadedEstimator< Model >.
Definition at line 343 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::exit_counts, mappel::estimator::Estimator< Model >::num_estimations, and mappel::estimator::Estimator< Model >::total_walltime.
Referenced by mappel::estimator::ThreadedEstimator< Model >::clear_stats().
template<class Model > virtual void mappel::estimator::Estimator< Model >::compute_estimate (const ModelDataT< Model > & data, const ParamT< Model > & theta_init, MLEData & mle_data, StencilT< Model > & mle_stencil) protected pure virtual
Implemented in mappel::estimator::IterativeMaximizer< Model >.
Referenced by mappel::estimator::Estimator< Model >::compute_estimate_debug(), mappel::estimator::Estimator< Model >::estimate_max(), and mappel::estimator::ThreadedEstimator< Model >::estimate_max_stack().
template<class Model > void mappel::estimator::Estimator< Model >::compute_estimate_debug (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, MLEDebugData & mle_debug, StencilT< Model > & mle_stencil) protected virtual
Virtual estimate_debug interface
Estimators that produce a sequence of results (e.g. IterativeEstimators) can override this dummy debug implementation.
Reimplemented in mappel::estimator::IterativeMaximizer< Model >.
Definition at line 285 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_estimate(), mappel::estimator::Estimator< Model >::model, mappel::estimator::MLEData::obsI, mappel::estimator::MLEDebugData::obsI, mappel::estimator::MLEData::rllh, mappel::estimator::MLEDebugData::rllh, mappel::estimator::MLEDebugData::sequence, mappel::estimator::MLEDebugData::sequence_rllh, mappel::estimator::MLEData::theta, and mappel::estimator::MLEDebugData::theta.
Referenced by mappel::estimator::Estimator< Model >::estimate_max_debug().
template<class Model > void mappel::estimator::Estimator< Model >::compute_profile_bound (const ModelDataT< Model > & data, ProfileBoundsData & est, const VecT & init_step, IdxT param_idx, IdxT which_bound) protected virtual
Reimplemented in mappel::estimator::IterativeMaximizer< Model >.
Definition at line 309 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::model.
Referenced by mappel::estimator::Estimator< Model >::estimate_profile_bounds(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_parallel(), and mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_stack().
template<class Model > void mappel::estimator::Estimator< Model >::compute_profile_bound_debug (const ModelDataT< Model > & data, ProfileBoundsDebugData & est) protected virtual
Reimplemented in mappel::estimator::IterativeMaximizer< Model >.
Definition at line 318 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::model.
Referenced by mappel::estimator::Estimator< Model >::estimate_profile_bounds_debug().
template<class Model > double mappel::estimator::Estimator< Model >::compute_profile_estimate (const ModelDataT< Model > & data, const ParamT< Model > & theta_init, const IdxVecT & fixed_idxs, StencilT< Model > & max_stencil) protected virtual
Reimplemented in mappel::estimator::IterativeMaximizer< Model >.
Definition at line 300 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::model.
Referenced by mappel::estimator::Estimator< Model >::estimate_profile_max(), and mappel::estimator::ThreadedEstimator< Model >::estimate_profile_max().
template<class Model > void mappel::estimator::Estimator< Model >::estimate_max (const ModelDataT< Model > & data, const ParamT< Model > & theta_init, MLEData & mle_data, StencilT< Model > & mle_stencil)
Maximum likelihood point estimators Estimate for a single data starting at theta_init, fill in the MLEData struct with the estimated parameter, RLLH, and observed information. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
The stencil at the MLE is also returned but can be ignored if not needed as it is available at no extra cost.
Parameters
[in] data Model data to estimate for
[in] theta_init [Optional] Initial theta value.
[out] mle_data MLEData recording the maximum likelihood estimate and relevant data.
[out] stencil [Optional] StencilT at the MLE value.
Definition at line 128 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_estimate(), mappel::estimator::Error, mappel::estimator::MLEData::obsI, mappel::print_text_image(), mappel::estimator::Estimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), mappel::estimator::MLEData::rllh, and mappel::estimator::MLEData::theta.
Referenced by mappel::estimator::Estimator< Model >::estimate_max().
template<class Model > void mappel::estimator::Estimator< Model >::estimate_max (const ModelDataT< Model > & data, const ParamT< Model > & theta_init, MLEData & mle_data)
Maximum likelihood point estimators Estimate for a single data starting at theta_init, fill in the MLEData struct with the estimated parameter, RLLH, and observed information. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
The stencil at the MLE is also returned but can be ignored if not needed as it is available at no extra cost.
Parameters
[in] data Model data to estimate for
[in] theta_init [Optional] Initial theta value.
[out] mle_data MLEData recording the maximum likelihood estimate and relevant data.
[out] stencil [Optional] StencilT at the MLE value.
Definition at line 121 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::estimate_max().
template<class Model > void mappel::estimator::Estimator< Model >::estimate_max (const ModelDataT< Model > & data, MLEData & mle_data)
Maximum likelihood point estimators Estimate for a single data starting at theta_init, fill in the MLEData struct with the estimated parameter, RLLH, and observed information. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
The stencil at the MLE is also returned but can be ignored if not needed as it is available at no extra cost.
Parameters
[in] data Model data to estimate for
[in] theta_init [Optional] Initial theta value.
[out] mle_data MLEData recording the maximum likelihood estimate and relevant data.
[out] stencil [Optional] StencilT at the MLE value.
Definition at line 112 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::estimate_max(), and mappel::estimator::Estimator< Model >::model.
template<class Model > void mappel::estimator::Estimator< Model >::estimate_max_debug (const ModelDataT< Model > & data, const ParamT< Model > & theta_init, MLEDebugData & mle_data, StencilT< Model > & mle_stencil)
Debug estimation for a single data starting at theta_init, fill in the MLEDebugData struct with data including the sequence of evaluated points. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
The sequence and sequence_rllh parameters of the MLEDebugData struct record the entire sequence of evaluated points including theta_init and theta_mle, which should be first and last respectively.
The stencil at the MLE is also returned but can be ignored if not needed as it is available at no extra cost.
Parameters
[in] data Model data to estimate for
[in] theta_init Initial theta value.
[out] mle_data MLEDebugData recording the maximum likelihood estimate and relevant data.
[out] stencil [Optional] StencilT at the MLE value.
template<class Model > void mappel::estimator::Estimator< Model >::estimate_max_debug (const ModelDataT< Model > & data, const ParamT< Model > & theta_init, MLEDebugData & mle_data)
Maximum likelihood point estimators Estimate for a single data starting at theta_init, fill in the MLEData struct with the estimated parameter, RLLH, and observed information. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
The stencil at the MLE is also returned but can be ignored if not needed as it is available at no extra cost.
Parameters
[in] data Model data to estimate for
[in] theta_init [Optional] Initial theta value.
[out] mle_data MLEData recording the maximum likelihood estimate and relevant data.
[out] stencil [Optional] StencilT at the MLE value.
Definition at line 157 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_estimate_debug(), mappel::estimator::Error, mappel::estimator::MLEDebugData::obsI, mappel::print_text_image(), mappel::estimator::Estimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), mappel::estimator::MLEDebugData::rllh, and mappel::estimator::MLEDebugData::theta.
template<class Model > virtual void mappel::estimator::Estimator< Model >::estimate_max_stack (const ModelDataStackT< Model > & data_stack, const ParamVecT< Model > & theta_init_stack, MLEDataStack & mle_data_stack) pure virtual
Estimate for a stack of data and fill in the MLEDataStack struct with the estimated parameter, RLLH, and observed information for each data in parallel. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
Parameters
[in] data Model data to estimate for
[in] theta_init [optional] Initial theta value for each image.
[out] mle MLEStackData records the maximum likelihood estimate, RLLH, and Observed information for each data
Implemented in mappel::estimator::ThreadedEstimator< Model >.
Referenced by mappel::estimator::Estimator< Model >::estimate_max_stack().
template<class Model > void mappel::estimator::Estimator< Model >::estimate_max_stack (const ModelDataStackT< Model > & data_stack, MLEDataStack & mle_data_stack)
Maximum likelihood point estimators Estimate for a single data starting at theta_init, fill in the MLEData struct with the estimated parameter, RLLH, and observed information. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
The stencil at the MLE is also returned but can be ignored if not needed as it is available at no extra cost.
Parameters
[in] data Model data to estimate for
[in] theta_init [Optional] Initial theta value.
[out] mle_data MLEData recording the maximum likelihood estimate and relevant data.
[out] stencil [Optional] StencilT at the MLE value.
Definition at line 183 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::estimate_max_stack(), and mappel::estimator::Estimator< Model >::model.
template<class Model > void mappel::estimator::Estimator< Model >::estimate_profile_bounds (const ModelDataT< Model > & data, ProfileBoundsData & bounds_est)
Profile likelihood bounds computations with VM algorithm
Definition at line 220 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_profile_bound(), mappel::estimator::Error, mappel::estimator::ProfileBoundsData::estimated_idxs, mappel::estimator::ProfileBoundsData::initialize_arrays(), mappel::estimator::ProfileBoundsData::mle, mappel::estimator::Estimator< Model >::model, mappel::estimator::ProfileBoundsData::Nparams_est, mappel::estimator::MLEData::obsI, mappel::print_text_image(), mappel::estimator::ProfileBoundsData::profile_lb, mappel::estimator::ProfileBoundsData::profile_points_lb, mappel::estimator::ProfileBoundsData::profile_points_lb_rllh, mappel::estimator::ProfileBoundsData::profile_points_ub, mappel::estimator::ProfileBoundsData::profile_ub, mappel::estimator::Estimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), mappel::estimator::subroutine::solve_profile_initial_step(), mappel::estimator::ProfileBoundsData::target_rllh_delta, and mappel::estimator::MLEData::theta.
Referenced by mappel::methods::error_bounds_profile_likelihood().
template<class Model > void mappel::estimator::Estimator< Model >::estimate_profile_bounds_debug (const ModelDataT< Model > & data, ProfileBoundsDebugData & bounds_est)
Profile likelihood bounds computations with VM algorithm
Definition at line 258 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_profile_bound_debug(), mappel::estimator::Error, mappel::estimator::ProfileBoundsDebugData::estimated_idx, mappel::estimator::ProfileBoundsDebugData::mle, mappel::print_text_image(), mappel::estimator::Estimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), mappel::estimator::ProfileBoundsDebugData::target_rllh_delta, and mappel::estimator::MLEData::theta.
Referenced by mappel::methods::debug::error_bounds_profile_likelihood_debug().
template<class Model > virtual void mappel::estimator::Estimator< Model >::estimate_profile_bounds_parallel (const ModelDataT< Model > & data, ProfileBoundsData & bounds_est) pure virtual
Profile likelihood bounds computations with VM algorithm
Implemented in mappel::estimator::ThreadedEstimator< Model >.
template<class Model > virtual void mappel::estimator::Estimator< Model >::estimate_profile_bounds_stack (const ModelDataStackT< Model > & data_stack, ProfileBoundsDataStack & bounds_est) pure virtual
Profile likelihood bounds computations with VM algorithm
Implemented in mappel::estimator::ThreadedEstimator< Model >.
template<class Model > double mappel::estimator::Estimator< Model >::estimate_profile_max (const ModelDataT< Model > & data, const IdxVecT & fixed_idxs, const ParamT< Model > & fixed_theta_init, StencilT< Model > & theta_max)
Profile likelihood estimation methods
Definition at line 190 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_profile_estimate(), mappel::estimator::Error, mappel::print_text_image(), mappel::estimator::Estimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), and mappel::methods::objective::rllh().
template<class Model > virtual void mappel::estimator::Estimator< Model >::estimate_profile_max (const ModelDataT< Model > & data, const ParamVecT< Model > & fixed_theta_init, ProfileLikelihoodData & profile) pure virtual
Profile likelihood estimation methods
Implemented in mappel::estimator::ThreadedEstimator< Model >.
template<class Model > virtual StatsT mappel::estimator::Estimator< Model >::get_debug_stats () pure virtual
Run statistics.
Implemented in mappel::estimator::IterativeMaximizer< Model >, mappel::estimator::SimulatedAnnealingMaximizer< Model >, mappel::estimator::CGaussMLE< Model >, mappel::estimator::CGaussHeuristicEstimator< Model >, mappel::estimator::HeuristicEstimator< Model >, and mappel::estimator::ThreadedEstimator< Model >.
template<class Model > IdxVecT mappel::estimator::Estimator< Model >::get_exit_counts () const inline
Run statistics.
Definition at line 274 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > const Model & mappel::estimator::Estimator< Model >::get_model ()
Definition at line 108 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::model.
template<class Model > StatsT mappel::estimator::Estimator< Model >::get_stats () virtual
Run statistics.
Reimplemented in mappel::estimator::IterativeMaximizer< Model >, mappel::estimator::SimulatedAnnealingMaximizer< Model >, mappel::estimator::CGaussMLE< Model >, mappel::estimator::CGaussHeuristicEstimator< Model >, mappel::estimator::HeuristicEstimator< Model >, and mappel::estimator::ThreadedEstimator< Model >.
Definition at line 326 of file estimator_impl.h.
References mappel::estimator::Error, mappel::estimator::Estimator< Model >::exit_counts, mappel::estimator::GradRatio, mappel::estimator::MaxBacktracks, mappel::estimator::MaxIter, mappel::estimator::Estimator< Model >::num_estimations, mappel::estimator::StepSize, mappel::estimator::Success, mappel::estimator::Estimator< Model >::total_walltime, and mappel::estimator::TrustRegionRadius.
Referenced by mappel::estimator::ThreadedEstimator< Model >::get_stats().
template<class Model > virtual std::string mappel::estimator::Estimator< Model >::name () const pure virtual
Implemented in mappel::estimator::TrustRegionMaximizer< Model >, mappel::estimator::QuasiNewtonMaximizer< Model >, mappel::estimator::NewtonMaximizer< Model >, mappel::estimator::NewtonDiagonalMaximizer< Model >, mappel::estimator::SimulatedAnnealingMaximizer< Model >, mappel::estimator::CGaussMLE< Model >, mappel::estimator::CGaussHeuristicEstimator< Model >, and mappel::estimator::HeuristicEstimator< Model >.
Referenced by mappel::estimator::IterativeMaximizer< Model >::solve_profile_bound().
template<class Model > virtual void mappel::estimator::Estimator< Model >::record_exit_code (ExitCode code) protected pure virtual
Implemented in mappel::estimator::ThreadedEstimator< Model >.
Referenced by mappel::estimator::Estimator< Model >::estimate_max(), mappel::estimator::Estimator< Model >::estimate_max_debug(), mappel::estimator::Estimator< Model >::estimate_profile_bounds(), mappel::estimator::Estimator< Model >::estimate_profile_bounds_debug(), and mappel::estimator::Estimator< Model >::estimate_profile_max().
template<class Model > void mappel::estimator::Estimator< Model >::record_walltime (ClockT::time_point start_walltime, int num_estimations) protected
Definition at line 360 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::num_estimations, and mappel::estimator::Estimator< Model >::total_walltime.
Referenced by mappel::estimator::Estimator< Model >::estimate_max(), mappel::estimator::Estimator< Model >::estimate_max_debug(), mappel::estimator::ThreadedEstimator< Model >::estimate_max_stack(), mappel::estimator::Estimator< Model >::estimate_profile_bounds(), mappel::estimator::Estimator< Model >::estimate_profile_bounds_debug(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_parallel(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_stack(), mappel::estimator::Estimator< Model >::estimate_profile_max(), and mappel::estimator::ThreadedEstimator< Model >::estimate_profile_max().
Friends And Related Function Documentation
template<class Model > template<class T > std::ostream& operator<< (std::ostream & out, Estimator< T > & estimator) friend
Member Data Documentation
template<class Model > IdxVecT mappel::estimator::Estimator< Model >::exit_counts protected
Definition at line 299 of file estimator.h.
Referenced by mappel::estimator::Estimator< Model >::clear_stats(), mappel::estimator::Estimator< Model >::get_stats(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::ThreadedEstimator< Model >::record_exit_code().
template<class Model > const Model& mappel::estimator::Estimator< Model >::model protected
Definition at line 294 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::IterativeMaximizer< Model >::compute_estimate(), mappel::estimator::Estimator< Model >::compute_estimate_debug(), mappel::estimator::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::estimator::Estimator< Model >::compute_profile_bound(), mappel::estimator::IterativeMaximizer< Model >::compute_profile_bound(), mappel::estimator::Estimator< Model >::compute_profile_bound_debug(), mappel::estimator::IterativeMaximizer< Model >::compute_profile_bound_debug(), mappel::estimator::Estimator< Model >::compute_profile_estimate(), mappel::estimator::IterativeMaximizer< Model >::compute_profile_estimate(), mappel::estimator::Estimator< Model >::estimate_max(), mappel::estimator::Estimator< Model >::estimate_max_stack(), mappel::estimator::ThreadedEstimator< Model >::estimate_max_stack(), mappel::estimator::Estimator< Model >::estimate_profile_bounds(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_parallel(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_stack(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_max(), mappel::estimator::HeuristicEstimator< Model >::get_debug_stats(), mappel::estimator::CGaussMLE< Model >::get_debug_stats(), mappel::estimator::Estimator< Model >::get_model(), mappel::estimator::IterativeMaximizer< Model >::local_maximize(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack(), and mappel::estimator::ThreadedEstimator< Model >::record_exit_code().
template<class Model > int mappel::estimator::Estimator< Model >::num_estimations = 0 protected
Definition at line 297 of file estimator.h.
Referenced by mappel::estimator::Estimator< Model >::clear_stats(), mappel::estimator::Estimator< Model >::get_stats(), mappel::estimator::ThreadedEstimator< Model >::get_stats(), mappel::estimator::HeuristicEstimator< Model >::get_stats(), mappel::estimator::CGaussHeuristicEstimator< Model >::get_stats(), mappel::estimator::CGaussMLE< Model >::get_stats(), mappel::estimator::SimulatedAnnealingMaximizer< Model >::get_stats(), mappel::estimator::IterativeMaximizer< Model >::get_stats(), and mappel::estimator::Estimator< Model >::record_walltime().
template<class Model > double mappel::estimator::Estimator< Model >::total_walltime = 0. protected
Definition at line 298 of file estimator.h.
Referenced by mappel::estimator::Estimator< Model >::clear_stats(), mappel::estimator::Estimator< Model >::get_stats(), mappel::estimator::ThreadedEstimator< Model >::get_stats(), and mappel::estimator::Estimator< Model >::record_walltime().
The documentation for this class was generated from the following files:
estimator.h
estimator_impl.h