Mappel: mappel::IterativeMaximizer< Model > Class Template Reference
mappel::IterativeMaximizer< Model > Class Template Reference abstract
#include </home/travis/build/markjolah/Mappel/include/Mappel/estimator.h>
Classes
class MaximizerData
Public Types
enum ExitCode : IdxT {
ExitCode::Unassigned = 99, ExitCode::MaxIter = 6, ExitCode::MaxBacktracks = 5, ExitCode::TrustRegionRadius = 4,
ExitCode::GradRatio = 3, ExitCode::FunctionChange = 2, ExitCode::StepSize = 1, ExitCode::Error = 0
}
Public Member Functions
IterativeMaximizer (Model &model, int max_iterations=DEFAULT_ITERATIONS)
double mean_iterations ()
double mean_backtracks ()
double mean_fun_evals ()
double mean_der_evals ()
StatsT get_stats ()
StatsT get_debug_stats ()
void clear_stats ()
void local_maximize (const ModelDataT< Model > &im, const StencilT< Model > &theta_init, StencilT< Model > &stencil, double &rllh)
Perform a local maximization to finish off a simulated annealing run.
void estimate_max_stack (const ModelDataStackT< Model > &im, const ParamVecT< Model > &theta_init, ParamVecT< Model > &theta, VecT &rllh, CubeT &obsI)
void estimate_max_stack (const ModelDataStackT< Model > &im_stack, ParamVecT< Model > &theta_est_stack, VecT &rllh_stack, CubeT &obsI_stack)
void estimate_profile_stack (const ModelDataT< Model > &data, const IdxVecT &fixed_parameters, const MatT &values, const ParamVecT< Model > &theta_init, VecT &profile_likelihood, ParamVecT< Model > &profile_parameters)
virtual std::string name () const =0
Model & get_model ()
void set_model (Model &new_model)
StencilT< Model > estimate_max (const ModelDataT< Model > &im)
StencilT< Model > estimate_max (const ModelDataT< Model > &im, const ParamT< Model > &theta_init)
StencilT< Model > estimate_max (const ModelDataT< Model > &im, double &rllh)
StencilT< Model > estimate_max (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, double &rllh)
void estimate_max (const ModelDataT< Model > &im, ParamT< Model > &theta, double &rllh, MatT &obsI)
void estimate_max (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamT< Model > &theta, double &rllh, MatT &obsI)
void estimate_max_debug (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamT< Model > &theta_est, double &rllh, MatT &obsI, MatT &sequence, VecT &sequence_rllh)
Static Public Attributes
static constexpr int NumExitCodes = 7
Protected Member Functions
void record_run_statistics (const MaximizerData &data)
StencilT< Model > compute_estimate (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, double &rllh)
StencilT< Model > compute_estimate_debug (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamVecT< Model > &sequence, VecT &sequence_rllh)
void compute_profile_estimate (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, const IdxVecT &fixed_parameters, ParamT< Model > &theta_est, double &rllh)
virtual void maximize (MaximizerData &data)=0
bool backtrack (MaximizerData &data)
bool convergence_test (MaximizerData &data)
virtual void compute_estimate (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamT< Model > &theta_est, double &rllh, MatT &obsI)
Default base class implementation computes rllh and obsI seperately from stencil This should be overridden by Estimator subclasses that already have access to this information.
void record_walltime (ClockT::time_point start_walltime, int nimages)
Protected Attributes
int max_iterations
double epsilon = sqrt(std::numeric_limits<double>::epsilon())
double delta = sqrt(std::numeric_limits<double>::epsilon())
double lambda_min = 0.05
double alpha = 1e-4
int max_backtracks = 8
int total_iterations = 0
int total_backtracks = 0
int total_fun_evals = 0
int total_der_evals = 0
IdxVecT exit_counts
IdxVecT last_backtrack_idxs
int max_threads
int num_threads
std::mutex mtx
Model & model
int num_estimations = 0
double total_walltime = 0.
Detailed Description
template<class Model>
class mappel::IterativeMaximizer< Model >
Definition at line 195 of file estimator.h.
Member Enumeration Documentation
template<class Model > enum mappel::IterativeMaximizer::ExitCode : IdxT strong
Enumerator
Unassigned
MaxIter
MaxBacktracks
TrustRegionRadius
GradRatio
FunctionChange
StepSize
Error
Definition at line 198 of file estimator.h.
Constructor & Destructor Documentation
template<class Model > mappel::IterativeMaximizer< Model >::IterativeMaximizer (Model & model, int max_iterations = DEFAULT_ITERATIONS)
Definition at line 391 of file estimator_impl.h.
Member Function Documentation
template<class Model > bool mappel::IterativeMaximizer< Model >::backtrack (MaximizerData & data) protected
Definition at line 530 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::alpha, mappel::IterativeMaximizer< Model >::convergence_test(), mappel::IterativeMaximizer< Model >::MaximizerData::fixed_parameter_scalar, mappel::IterativeMaximizer< Model >::MaximizerData::grad, mappel::IterativeMaximizer< Model >::MaximizerData::has_fixed_parameters, mappel::IterativeMaximizer< Model >::MaximizerData::im, mappel::IterativeMaximizer< Model >::max_backtracks, mappel::IterativeMaximizer< Model >::MaxBacktracks, mappel::Estimator< Model >::model, mappel::IterativeMaximizer< Model >::MaximizerData::record_backtrack(), mappel::IterativeMaximizer< Model >::MaximizerData::record_exit(), mappel::IterativeMaximizer< Model >::MaximizerData::record_iteration(), mappel::IterativeMaximizer< Model >::MaximizerData::restore_stencil(), mappel::methods::objective::rllh(), mappel::IterativeMaximizer< Model >::MaximizerData::rllh, mappel::IterativeMaximizer< Model >::MaximizerData::save_stencil(), mappel::IterativeMaximizer< Model >::MaximizerData::saved_theta(), mappel::IterativeMaximizer< Model >::MaximizerData::set_stencil(), mappel::IterativeMaximizer< Model >::MaximizerData::stencil(), and mappel::IterativeMaximizer< Model >::MaximizerData::step.
Referenced by mappel::NewtonDiagonalMaximizer< Model >::maximize(), mappel::NewtonMaximizer< Model >::maximize(), and mappel::QuasiNewtonMaximizer< Model >::maximize().
template<class Model > void mappel::IterativeMaximizer< Model >::clear_stats () virtual
Reimplemented from mappel::ThreadedEstimator< Model >.
Definition at line 504 of file estimator_impl.h.
References mappel::ThreadedEstimator< Model >::clear_stats(), mappel::IterativeMaximizer< Model >::exit_counts, mappel::ThreadedEstimator< Model >::mtx, mappel::IterativeMaximizer< Model >::total_backtracks, mappel::IterativeMaximizer< Model >::total_der_evals, mappel::IterativeMaximizer< Model >::total_fun_evals, and mappel::IterativeMaximizer< Model >::total_iterations.
template<class Model > void mappel::Estimator< Model >::compute_estimate (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamT< Model > & theta_est, double & rllh, MatT & obsI) protected virtual inherited
Default base class implementation computes rllh and obsI seperately from stencil This should be overridden by Estimator subclasses that already have access to this information.
Definition at line 142 of file estimator_impl.h.
References mappel::methods::observed_information().
template<class Model > StencilT< Model > mappel::IterativeMaximizer< Model >::compute_estimate (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, double & rllh) protected virtual
Implements mappel::Estimator< Model >.
Definition at line 628 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::Error, mappel::IterativeMaximizer< Model >::MaximizerData::get_theta_sequence(), mappel::IterativeMaximizer< Model >::maximize(), mappel::Estimator< Model >::model, mappel::print_image(), mappel::IterativeMaximizer< Model >::MaximizerData::record_exit(), mappel::IterativeMaximizer< Model >::record_run_statistics(), mappel::IterativeMaximizer< Model >::MaximizerData::rllh, mappel::IterativeMaximizer< Model >::MaximizerData::stencil(), and mappel::IterativeMaximizer< Model >::MaximizerData::theta().
template<class Model > StencilT< Model > mappel::IterativeMaximizer< Model >::compute_estimate_debug (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamVecT< Model > & sequence, VecT & sequence_rllh) protected virtual
Estimators that produce a sequence of results (e.g. IterativeEstimators) can override this dummy debug implementation.
Reimplemented from mappel::Estimator< Model >.
Definition at line 653 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::Error, mappel::IterativeMaximizer< Model >::MaximizerData::get_theta_sequence(), mappel::IterativeMaximizer< Model >::MaximizerData::get_theta_sequence_rllh(), mappel::IterativeMaximizer< Model >::max_backtracks, mappel::IterativeMaximizer< Model >::max_iterations, mappel::IterativeMaximizer< Model >::maximize(), mappel::Estimator< Model >::model, mappel::IterativeMaximizer< Model >::MaximizerData::record_exit(), mappel::IterativeMaximizer< Model >::record_run_statistics(), and mappel::IterativeMaximizer< Model >::MaximizerData::stencil().
template<class Model > void mappel::IterativeMaximizer< Model >::compute_profile_estimate (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, const IdxVecT & fixed_parameters, ParamT< Model > & theta_est, double & rllh) protected virtual
Reimplemented from mappel::Estimator< Model >.
Definition at line 672 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::Error, mappel::IterativeMaximizer< Model >::maximize(), mappel::Estimator< Model >::model, mappel::IterativeMaximizer< Model >::MaximizerData::record_exit(), mappel::IterativeMaximizer< Model >::record_run_statistics(), mappel::IterativeMaximizer< Model >::MaximizerData::rllh, mappel::IterativeMaximizer< Model >::MaximizerData::set_fixed_parameters(), and mappel::IterativeMaximizer< Model >::MaximizerData::theta().
template<class Model > bool mappel::IterativeMaximizer< Model >::convergence_test (MaximizerData & data) protected
Definition at line 606 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::delta, mappel::IterativeMaximizer< Model >::epsilon, mappel::IterativeMaximizer< Model >::MaximizerData::fixed_parameter_scalar, mappel::IterativeMaximizer< Model >::FunctionChange, mappel::IterativeMaximizer< Model >::MaximizerData::grad, mappel::IterativeMaximizer< Model >::MaximizerData::has_fixed_parameters, mappel::IterativeMaximizer< Model >::MaximizerData::record_exit(), mappel::IterativeMaximizer< Model >::MaximizerData::rllh, mappel::IterativeMaximizer< Model >::MaximizerData::saved_theta(), mappel::IterativeMaximizer< Model >::StepSize, and mappel::IterativeMaximizer< Model >::MaximizerData::theta().
Referenced by mappel::IterativeMaximizer< Model >::backtrack(), mappel::NewtonDiagonalMaximizer< Model >::maximize(), mappel::NewtonMaximizer< Model >::maximize(), and mappel::QuasiNewtonMaximizer< Model >::maximize().
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im) inherited
Definition at line 59 of file estimator_impl.h.
References mappel::methods::estimate_max().
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, const ParamT< Model > & theta_init) inherited
Definition at line 77 of file estimator_impl.h.
References mappel::methods::estimate_max(), and mappel::methods::objective::rllh().
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, double & rllh) inherited
Definition at line 68 of file estimator_impl.h.
References mappel::methods::estimate_max().
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, double & rllh) inherited
Definition at line 85 of file estimator_impl.h.
template<class Model > void mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, ParamT< Model > & theta, double & rllh, MatT & obsI) inherited
Definition at line 97 of file estimator_impl.h.
References mappel::methods::estimate_max().
template<class Model > void mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamT< Model > & theta, double & rllh, MatT & obsI) inherited
Definition at line 106 of file estimator_impl.h.
template<class Model > void mappel::Estimator< Model >::estimate_max_debug (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamT< Model > & theta_est, double & rllh, MatT & obsI, MatT & sequence, VecT & sequence_rllh) inherited
Definition at line 117 of file estimator_impl.h.
References mappel::methods::observed_information(), and mappel::methods::objective::rllh().
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > void mappel::Estimator< Model >::estimate_max_stack (const ModelDataStackT< Model > & im_stack, ParamVecT< Model > & theta_est_stack, VecT & rllh_stack, CubeT & obsI_stack) inherited
Definition at line 129 of file estimator_impl.h.
References mappel::methods::openmp::estimate_max_stack().
template<class Model > void mappel::ThreadedEstimator< Model >::estimate_max_stack (const ModelDataStackT< Model > & im, const ParamVecT< Model > & theta_init, ParamVecT< Model > & theta, VecT & rllh, CubeT & obsI) virtual inherited
Implements mappel::Estimator< Model >.
Definition at line 222 of file estimator_impl.h.
References mappel::Estimator< Model >::model, mappel::ThreadedEstimator< Model >::num_threads, mappel::Estimator< Model >::record_walltime(), omp_exception_catcher::impl_::OMPExceptionCatcher< IntType >::rethrow(), and omp_exception_catcher::impl_::OMPExceptionCatcher< IntType >::run().
template<class Model > void mappel::ThreadedEstimator< Model >::estimate_profile_stack (const ModelDataT< Model > & data, const IdxVecT & fixed_parameters, const MatT & values, const ParamVecT< Model > & theta_init, VecT & profile_likelihood, ParamVecT< Model > & profile_parameters) virtual inherited
Implements mappel::Estimator< Model >.
Definition at line 246 of file estimator_impl.h.
References mappel::Estimator< Model >::model, mappel::ThreadedEstimator< Model >::num_threads, mappel::Estimator< Model >::record_walltime(), omp_exception_catcher::impl_::OMPExceptionCatcher< IntType >::rethrow(), and omp_exception_catcher::impl_::OMPExceptionCatcher< IntType >::run().
template<class Model > StatsT mappel::IterativeMaximizer< Model >::get_debug_stats () virtual
Reimplemented from mappel::ThreadedEstimator< Model >.
Definition at line 488 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::MaximizerData::backtrack_idxs, mappel::IterativeMaximizer< Model >::get_stats(), and mappel::IterativeMaximizer< Model >::last_backtrack_idxs.
template<class Model > Model & mappel::Estimator< Model >::get_model () inherited
Definition at line 45 of file estimator_impl.h.
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > StatsT mappel::IterativeMaximizer< Model >::get_stats () virtual
Reimplemented from mappel::ThreadedEstimator< Model >.
Definition at line 459 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::delta, mappel::IterativeMaximizer< Model >::epsilon, mappel::IterativeMaximizer< Model >::Error, mappel::IterativeMaximizer< Model >::exit_counts, mappel::IterativeMaximizer< Model >::FunctionChange, mappel::ThreadedEstimator< Model >::get_stats(), mappel::IterativeMaximizer< Model >::GradRatio, mappel::IterativeMaximizer< Model >::max_backtracks, mappel::IterativeMaximizer< Model >::max_iterations, mappel::IterativeMaximizer< Model >::MaxBacktracks, mappel::IterativeMaximizer< Model >::MaxIter, mappel::ThreadedEstimator< Model >::mtx, mappel::Estimator< Model >::num_estimations, mappel::IterativeMaximizer< Model >::StepSize, mappel::IterativeMaximizer< Model >::total_backtracks, mappel::IterativeMaximizer< Model >::total_der_evals, mappel::IterativeMaximizer< Model >::total_fun_evals, mappel::IterativeMaximizer< Model >::total_iterations, and mappel::IterativeMaximizer< Model >::TrustRegionRadius.
Referenced by mappel::IterativeMaximizer< Model >::get_debug_stats().
template<class Model > void mappel::IterativeMaximizer< Model >::local_maximize (const ModelDataT< Model > & im, const StencilT< Model > & theta_init, StencilT< Model > & stencil, double & rllh)
Perform a local maximization to finish off a simulated annealing run.
Definition at line 690 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::maximize(), mappel::Estimator< Model >::model, mappel::IterativeMaximizer< Model >::MaximizerData::rllh, and mappel::IterativeMaximizer< Model >::MaximizerData::stencil().
Referenced by mappel::SimulatedAnnealingMaximizer< Model >::anneal().
template<class Model > virtual void mappel::IterativeMaximizer< Model >::maximize (MaximizerData & data) protected pure virtual
Referenced by mappel::IterativeMaximizer< Model >::compute_estimate(), mappel::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::compute_profile_estimate(), and mappel::IterativeMaximizer< Model >::local_maximize().
template<class Model > double mappel::IterativeMaximizer< Model >::mean_backtracks ()
template<class Model > double mappel::IterativeMaximizer< Model >::mean_der_evals ()
template<class Model > double mappel::IterativeMaximizer< Model >::mean_fun_evals ()
template<class Model > double mappel::IterativeMaximizer< Model >::mean_iterations ()
template<class Model > virtual std::string mappel::Estimator< Model >::name () const pure virtual inherited
Implemented in mappel::TrustRegionMaximizer< Model >, mappel::QuasiNewtonMaximizer< Model >, mappel::NewtonMaximizer< Model >, mappel::NewtonDiagonalMaximizer< Model >, mappel::SimulatedAnnealingMaximizer< Model >, mappel::CGaussMLE< Model >, mappel::CGaussHeuristicEstimator< Model >, and mappel::HeuristicEstimator< Model >.
Referenced by mappel::Estimator< Model >::compute_profile_estimate(), and mappel::Estimator< Model >::~Estimator().
template<class Model > void mappel::IterativeMaximizer< Model >::record_run_statistics (const MaximizerData & data) protected
Definition at line 517 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::MaximizerData::exit_code, mappel::IterativeMaximizer< Model >::exit_counts, mappel::IterativeMaximizer< Model >::MaximizerData::get_backtrack_idxs(), mappel::IterativeMaximizer< Model >::last_backtrack_idxs, mappel::ThreadedEstimator< Model >::mtx, mappel::IterativeMaximizer< Model >::MaximizerData::nBacktracks, mappel::IterativeMaximizer< Model >::MaximizerData::nIterations, mappel::IterativeMaximizer< Model >::MaximizerData::save_seq, mappel::IterativeMaximizer< Model >::total_backtracks, mappel::IterativeMaximizer< Model >::total_der_evals, mappel::IterativeMaximizer< Model >::total_fun_evals, and mappel::IterativeMaximizer< Model >::total_iterations.
Referenced by mappel::IterativeMaximizer< Model >::compute_estimate(), mappel::IterativeMaximizer< Model >::compute_estimate_debug(), and mappel::IterativeMaximizer< Model >::compute_profile_estimate().
template<class Model > void mappel::Estimator< Model >::record_walltime (ClockT::time_point start_walltime, int nimages) protected inherited
Definition at line 203 of file estimator_impl.h.
Referenced by mappel::ThreadedEstimator< Model >::estimate_max_stack(), and mappel::ThreadedEstimator< Model >::estimate_profile_stack().
template<class Model > void mappel::Estimator< Model >::set_model (Model & new_model) inherited
Definition at line 49 of file estimator_impl.h.
Referenced by mappel::Estimator< Model >::~Estimator().
Member Data Documentation
template<class Model > double mappel::IterativeMaximizer< Model >::alpha = 1e-4 protected
Definition at line 232 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::backtrack(), and mappel::TrustRegionMaximizer< Model >::bound_step().
template<class Model > double mappel::IterativeMaximizer< Model >::delta = sqrt(std::numeric_limits<double>::epsilon()) protected
Definition at line 229 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::convergence_test(), mappel::IterativeMaximizer< Model >::get_stats(), mappel::NewtonDiagonalMaximizer< Model >::maximize(), mappel::TrustRegionMaximizer< Model >::maximize(), mappel::TrustRegionMaximizer< Model >::solve_restricted_step_length_newton(), and mappel::TrustRegionMaximizer< Model >::solve_TR_subproblem().
template<class Model > double mappel::IterativeMaximizer< Model >::epsilon = sqrt(std::numeric_limits<double>::epsilon()) protected
Definition at line 228 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::convergence_test(), mappel::IterativeMaximizer< Model >::get_stats(), mappel::NewtonDiagonalMaximizer< Model >::maximize(), mappel::TrustRegionMaximizer< Model >::maximize(), and mappel::TrustRegionMaximizer< Model >::solve_restricted_step_length_newton().
template<class Model > IdxVecT mappel::IterativeMaximizer< Model >::exit_counts protected
Definition at line 240 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::clear_stats(), mappel::IterativeMaximizer< Model >::get_stats(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > double mappel::IterativeMaximizer< Model >::lambda_min = 0.05 protected
Definition at line 231 of file estimator.h.
Referenced by mappel::TrustRegionMaximizer< Model >::solve_restricted_step_length_newton(), and mappel::TrustRegionMaximizer< Model >::solve_TR_subproblem().
template<class Model > IdxVecT mappel::IterativeMaximizer< Model >::last_backtrack_idxs protected
Definition at line 242 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::get_debug_stats(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::IterativeMaximizer< Model >::max_backtracks = 8 protected
Definition at line 233 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::backtrack(), mappel::IterativeMaximizer< Model >::compute_estimate_debug(), and mappel::IterativeMaximizer< Model >::get_stats().
template<class Model > int mappel::IterativeMaximizer< Model >::max_iterations protected
Definition at line 225 of file estimator.h.
Referenced by mappel::SimulatedAnnealingMaximizer< Model >::anneal(), mappel::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::get_stats(), mappel::NewtonDiagonalMaximizer< Model >::maximize(), mappel::NewtonMaximizer< Model >::maximize(), and mappel::QuasiNewtonMaximizer< Model >::maximize().
template<class Model > int mappel::ThreadedEstimator< Model >::max_threads protected inherited
Definition at line 127 of file estimator.h.
template<class Model > Model& mappel::Estimator< Model >::model protected inherited
Definition at line 97 of file estimator.h.
Referenced by mappel::SimulatedAnnealingMaximizer< Model >::anneal(), mappel::IterativeMaximizer< Model >::backtrack(), mappel::ThreadedEstimator< Model >::clear_stats(), mappel::CGaussMLE< Model >::compute_estimate(), mappel::SimulatedAnnealingMaximizer< Model >::compute_estimate(), mappel::IterativeMaximizer< Model >::compute_estimate(), mappel::CGaussMLE< Model >::compute_estimate_debug(), mappel::SimulatedAnnealingMaximizer< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::compute_profile_estimate(), mappel::ThreadedEstimator< Model >::estimate_max_stack(), mappel::ThreadedEstimator< Model >::estimate_profile_stack(), mappel::IterativeMaximizer< Model >::local_maximize(), mappel::NewtonDiagonalMaximizer< Model >::maximize(), mappel::NewtonMaximizer< Model >::maximize(), mappel::QuasiNewtonMaximizer< Model >::maximize(), and mappel::TrustRegionMaximizer< Model >::maximize().
template<class Model > std::mutex mappel::ThreadedEstimator< Model >::mtx protected inherited
Definition at line 129 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::clear_stats(), mappel::IterativeMaximizer< Model >::get_stats(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::Estimator< Model >::num_estimations = 0 protected inherited
Definition at line 100 of file estimator.h.
Referenced by mappel::ThreadedEstimator< Model >::get_stats(), and mappel::IterativeMaximizer< Model >::get_stats().
template<class Model > int mappel::ThreadedEstimator< Model >::num_threads protected inherited
Definition at line 128 of file estimator.h.
Referenced by mappel::ThreadedEstimator< Model >::clear_stats(), mappel::ThreadedEstimator< Model >::estimate_max_stack(), mappel::ThreadedEstimator< Model >::estimate_profile_stack(), and mappel::ThreadedEstimator< Model >::get_stats().
template<class Model > constexpr int mappel::IterativeMaximizer< Model >::NumExitCodes = 7 static
Definition at line 197 of file estimator.h.
template<class Model > int mappel::IterativeMaximizer< Model >::total_backtracks = 0 protected
Definition at line 237 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::clear_stats(), mappel::IterativeMaximizer< Model >::get_stats(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::IterativeMaximizer< Model >::total_der_evals = 0 protected
Definition at line 239 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::clear_stats(), mappel::IterativeMaximizer< Model >::get_stats(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::IterativeMaximizer< Model >::total_fun_evals = 0 protected
Definition at line 238 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::clear_stats(), mappel::IterativeMaximizer< Model >::get_stats(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::IterativeMaximizer< Model >::total_iterations = 0 protected
Definition at line 236 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::clear_stats(), mappel::IterativeMaximizer< Model >::get_stats(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > double mappel::Estimator< Model >::total_walltime = 0. protected inherited
Definition at line 101 of file estimator.h.
Referenced by mappel::ThreadedEstimator< Model >::get_stats().
The documentation for this class was generated from the following files:
estimator.h
estimator_impl.h