Mappel: mappel::SimulatedAnnealingMaximizer< Model > Class Template Reference
mappel::SimulatedAnnealingMaximizer< Model > Class Template Reference
#include </home/travis/build/markjolah/Mappel/include/Mappel/estimator.h>
Public Member Functions
std::string name () const
SimulatedAnnealingMaximizer (Model &model)
void estimate_max_stack (const ModelDataStackT< Model > &im, const ParamVecT< Model > &theta_init, ParamVecT< Model > &theta, VecT &rllh, CubeT &obsI)
void estimate_max_stack (const ModelDataStackT< Model > &im_stack, ParamVecT< Model > &theta_est_stack, VecT &rllh_stack, CubeT &obsI_stack)
void estimate_profile_stack (const ModelDataT< Model > &data, const IdxVecT &fixed_parameters, const MatT &values, const ParamVecT< Model > &theta_init, VecT &profile_likelihood, ParamVecT< Model > &profile_parameters)
StatsT get_stats ()
StatsT get_debug_stats ()
void clear_stats ()
Model & get_model ()
void set_model (Model &new_model)
StencilT< Model > estimate_max (const ModelDataT< Model > &im)
StencilT< Model > estimate_max (const ModelDataT< Model > &im, const ParamT< Model > &theta_init)
StencilT< Model > estimate_max (const ModelDataT< Model > &im, double &rllh)
StencilT< Model > estimate_max (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, double &rllh)
void estimate_max (const ModelDataT< Model > &im, ParamT< Model > &theta, double &rllh, MatT &obsI)
void estimate_max (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamT< Model > &theta, double &rllh, MatT &obsI)
void estimate_max_debug (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamT< Model > &theta_est, double &rllh, MatT &obsI, MatT &sequence, VecT &sequence_rllh)
Public Attributes
double T_init =100.
double cooling_rate =1.02
int max_iterations =500
Protected Member Functions
StencilT< Model > compute_estimate (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, double &rllh)
StencilT< Model > compute_estimate_debug (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamVecT< Model > &sequence, VecT &sequence_rllh)
StencilT< Model > anneal (const ModelDataT< Model > &im, const StencilT< Model > &theta_init, double &rllh, MatT &sequence, VecT &sequence_rllh)
virtual void compute_estimate (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamT< Model > &theta_est, double &rllh, MatT &obsI)
Default base class implementation computes rllh and obsI seperately from stencil This should be overridden by Estimator subclasses that already have access to this information.
virtual void compute_profile_estimate (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, const IdxVecT &fixed_parameters, ParamT< Model > &theta_est, double &rllh)
void record_walltime (ClockT::time_point start_walltime, int nimages)
Protected Attributes
int max_threads
int num_threads
std::mutex mtx
Model & model
int num_estimations = 0
double total_walltime = 0.
Detailed Description
template<class Model>
class mappel::SimulatedAnnealingMaximizer< Model >
Definition at line 176 of file estimator.h.
Constructor & Destructor Documentation
template<class Model > mappel::SimulatedAnnealingMaximizer< Model >::SimulatedAnnealingMaximizer (Model & model) inline
Definition at line 183 of file estimator.h.
References mappel::Estimator< Model >::compute_estimate(), mappel::Estimator< Model >::compute_estimate_debug(), and mappel::methods::objective::rllh().
Member Function Documentation
template<class Model > StencilT< Model > mappel::SimulatedAnnealingMaximizer< Model >::anneal (const ModelDataT< Model > & im, const StencilT< Model > & theta_init, double & rllh, MatT & sequence, VecT & sequence_rllh) protected
Definition at line 1319 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::local_maximize(), mappel::IterativeMaximizer< Model >::max_iterations, mappel::Estimator< Model >::model, and mappel::methods::objective::rllh().
template<class Model > void mappel::ThreadedEstimator< Model >::clear_stats () virtual inherited
Reimplemented from mappel::Estimator< Model >.
Reimplemented in mappel::IterativeMaximizer< Model >.
Definition at line 287 of file estimator_impl.h.
References mappel::cgauss_heuristic_compute_estimate(), mappel::Estimator< Model >::clear_stats(), mappel::Estimator< Model >::model, mappel::ThreadedEstimator< Model >::num_threads, and mappel::methods::objective::rllh().
Referenced by mappel::IterativeMaximizer< Model >::clear_stats().
template<class Model > void mappel::Estimator< Model >::compute_estimate (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamT< Model > & theta_est, double & rllh, MatT & obsI) protected virtual inherited
Default base class implementation computes rllh and obsI seperately from stencil This should be overridden by Estimator subclasses that already have access to this information.
Definition at line 142 of file estimator_impl.h.
References mappel::methods::observed_information().
template<class Model > StencilT< Model > mappel::SimulatedAnnealingMaximizer< Model >::compute_estimate (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, double & rllh) protected virtual
Implements mappel::Estimator< Model >.
Definition at line 1300 of file estimator_impl.h.
References mappel::Estimator< Model >::model, and mappel::IterativeMaximizer< Model >::MaximizerData::rllh.
template<class Model > StencilT< Model > mappel::SimulatedAnnealingMaximizer< Model >::compute_estimate_debug (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamVecT< Model > & sequence, VecT & sequence_rllh) protected virtual
Estimators that produce a sequence of results (e.g. IterativeEstimators) can override this dummy debug implementation.
Reimplemented from mappel::Estimator< Model >.
Definition at line 1309 of file estimator_impl.h.
References mappel::Estimator< Model >::model, and mappel::IterativeMaximizer< Model >::MaximizerData::rllh.
template<class Model > void mappel::Estimator< Model >::compute_profile_estimate (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, const IdxVecT & fixed_parameters, ParamT< Model > & theta_est, double & rllh) protected virtual inherited
Reimplemented in mappel::IterativeMaximizer< Model >.
Definition at line 151 of file estimator_impl.h.
References mappel::Estimator< Model >::name().
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im) inherited
Definition at line 59 of file estimator_impl.h.
References mappel::methods::estimate_max().
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, const ParamT< Model > & theta_init) inherited
Definition at line 77 of file estimator_impl.h.
References mappel::methods::estimate_max(), and mappel::methods::objective::rllh().
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, double & rllh) inherited
Definition at line 68 of file estimator_impl.h.
References mappel::methods::estimate_max().
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, double & rllh) inherited
Definition at line 85 of file estimator_impl.h.
template<class Model > void mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, ParamT< Model > & theta, double & rllh, MatT & obsI) inherited
Definition at line 97 of file estimator_impl.h.
References mappel::methods::estimate_max().
template<class Model > void mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamT< Model > & theta, double & rllh, MatT & obsI) inherited
Definition at line 106 of file estimator_impl.h.
template<class Model > void mappel::Estimator< Model >::estimate_max_debug (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamT< Model > & theta_est, double & rllh, MatT & obsI, MatT & sequence, VecT & sequence_rllh) inherited
Definition at line 117 of file estimator_impl.h.
References mappel::methods::observed_information(), and mappel::methods::objective::rllh().
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > void mappel::Estimator< Model >::estimate_max_stack (const ModelDataStackT< Model > & im_stack, ParamVecT< Model > & theta_est_stack, VecT & rllh_stack, CubeT & obsI_stack) inherited
Definition at line 129 of file estimator_impl.h.
References mappel::methods::openmp::estimate_max_stack().
template<class Model > void mappel::ThreadedEstimator< Model >::estimate_max_stack (const ModelDataStackT< Model > & im, const ParamVecT< Model > & theta_init, ParamVecT< Model > & theta, VecT & rllh, CubeT & obsI) virtual inherited
Implements mappel::Estimator< Model >.
Definition at line 222 of file estimator_impl.h.
References mappel::Estimator< Model >::model, mappel::ThreadedEstimator< Model >::num_threads, mappel::Estimator< Model >::record_walltime(), omp_exception_catcher::impl_::OMPExceptionCatcher< IntType >::rethrow(), and omp_exception_catcher::impl_::OMPExceptionCatcher< IntType >::run().
template<class Model > void mappel::ThreadedEstimator< Model >::estimate_profile_stack (const ModelDataT< Model > & data, const IdxVecT & fixed_parameters, const MatT & values, const ParamVecT< Model > & theta_init, VecT & profile_likelihood, ParamVecT< Model > & profile_parameters) virtual inherited
Implements mappel::Estimator< Model >.
Definition at line 246 of file estimator_impl.h.
References mappel::Estimator< Model >::model, mappel::ThreadedEstimator< Model >::num_threads, mappel::Estimator< Model >::record_walltime(), omp_exception_catcher::impl_::OMPExceptionCatcher< IntType >::rethrow(), and omp_exception_catcher::impl_::OMPExceptionCatcher< IntType >::run().
template<class Model > StatsT mappel::ThreadedEstimator< Model >::get_debug_stats () virtual inherited
Implements mappel::Estimator< Model >.
Reimplemented in mappel::IterativeMaximizer< Model >, and mappel::CGaussMLE< Model >.
Definition at line 281 of file estimator_impl.h.
References mappel::ThreadedEstimator< Model >::get_stats().
template<class Model > Model & mappel::Estimator< Model >::get_model () inherited
Definition at line 45 of file estimator_impl.h.
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > StatsT mappel::ThreadedEstimator< Model >::get_stats () virtual inherited
Reimplemented from mappel::Estimator< Model >.
Reimplemented in mappel::IterativeMaximizer< Model >, and mappel::CGaussMLE< Model >.
Definition at line 271 of file estimator_impl.h.
References mappel::Estimator< Model >::get_stats(), mappel::Estimator< Model >::num_estimations, mappel::ThreadedEstimator< Model >::num_threads, and mappel::Estimator< Model >::total_walltime.
Referenced by mappel::ThreadedEstimator< Model >::get_debug_stats(), mappel::CGaussMLE< Model >::get_stats(), and mappel::IterativeMaximizer< Model >::get_stats().
template<class Model > std::string mappel::SimulatedAnnealingMaximizer< Model >::name () const inline virtual
Implements mappel::Estimator< Model >.
Definition at line 182 of file estimator.h.
template<class Model > void mappel::Estimator< Model >::record_walltime (ClockT::time_point start_walltime, int nimages) protected inherited
Definition at line 203 of file estimator_impl.h.
Referenced by mappel::ThreadedEstimator< Model >::estimate_max_stack(), and mappel::ThreadedEstimator< Model >::estimate_profile_stack().
template<class Model > void mappel::Estimator< Model >::set_model (Model & new_model) inherited
Definition at line 49 of file estimator_impl.h.
Referenced by mappel::Estimator< Model >::~Estimator().
Member Data Documentation
template<class Model > double mappel::SimulatedAnnealingMaximizer< Model >::cooling_rate =1.02
Definition at line 179 of file estimator.h.
template<class Model > int mappel::SimulatedAnnealingMaximizer< Model >::max_iterations =500
Definition at line 180 of file estimator.h.
template<class Model > int mappel::ThreadedEstimator< Model >::max_threads protected inherited
Definition at line 127 of file estimator.h.
template<class Model > Model& mappel::Estimator< Model >::model protected inherited
Definition at line 97 of file estimator.h.
Referenced by mappel::SimulatedAnnealingMaximizer< Model >::anneal(), mappel::IterativeMaximizer< Model >::backtrack(), mappel::ThreadedEstimator< Model >::clear_stats(), mappel::CGaussMLE< Model >::compute_estimate(), mappel::SimulatedAnnealingMaximizer< Model >::compute_estimate(), mappel::IterativeMaximizer< Model >::compute_estimate(), mappel::CGaussMLE< Model >::compute_estimate_debug(), mappel::SimulatedAnnealingMaximizer< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::compute_profile_estimate(), mappel::ThreadedEstimator< Model >::estimate_max_stack(), mappel::ThreadedEstimator< Model >::estimate_profile_stack(), mappel::IterativeMaximizer< Model >::local_maximize(), mappel::NewtonDiagonalMaximizer< Model >::maximize(), mappel::NewtonMaximizer< Model >::maximize(), mappel::QuasiNewtonMaximizer< Model >::maximize(), and mappel::TrustRegionMaximizer< Model >::maximize().
template<class Model > std::mutex mappel::ThreadedEstimator< Model >::mtx protected inherited
Definition at line 129 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::clear_stats(), mappel::IterativeMaximizer< Model >::get_stats(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::Estimator< Model >::num_estimations = 0 protected inherited
Definition at line 100 of file estimator.h.
Referenced by mappel::ThreadedEstimator< Model >::get_stats(), and mappel::IterativeMaximizer< Model >::get_stats().
template<class Model > int mappel::ThreadedEstimator< Model >::num_threads protected inherited
Definition at line 128 of file estimator.h.
Referenced by mappel::ThreadedEstimator< Model >::clear_stats(), mappel::ThreadedEstimator< Model >::estimate_max_stack(), mappel::ThreadedEstimator< Model >::estimate_profile_stack(), and mappel::ThreadedEstimator< Model >::get_stats().
template<class Model > double mappel::SimulatedAnnealingMaximizer< Model >::T_init =100.
Definition at line 178 of file estimator.h.
template<class Model > double mappel::Estimator< Model >::total_walltime = 0. protected inherited
Definition at line 101 of file estimator.h.
Referenced by mappel::ThreadedEstimator< Model >::get_stats().
The documentation for this class was generated from the following files:
estimator.h
estimator_impl.h