Mappel: mappel::MAPEstimator Class Reference
mappel::MAPEstimator Class Reference
A Mixin class to configure a for MLE estimation (null prior).
#include </home/travis/build/markjolah/Mappel/include/Mappel/MAPEstimator.h>
Public Types
using ParamT = arma::vec
using ParamVecT = arma::mat
Public Member Functions
StatsT get_stats () const
IdxT get_num_params () const
void check_param_shape (const ParamT &theta) const
void check_param_shape (const ParamVecT &theta) const
void check_psf_sigma (double psf_sigma) const
void check_psf_sigma (const VecT &psf_sigma) const
ParamT make_param () const
template<class FillT >
ParamT make_param (FillT fill) const
ParamVecT make_param_stack (IdxT n) const
template<class FillT >
ParamVecT make_param_stack (IdxT n, FillT fill) const
MatT make_param_mat () const
template<class FillT >
MatT make_param_mat (FillT fill) const
CubeT make_param_mat_stack (IdxT n) const
template<class FillT >
CubeT make_param_mat_stack (IdxT n, FillT fill) const
CompositeDist & get_prior ()
const CompositeDist & get_prior () const
void set_prior (CompositeDist &&prior_)
void set_prior (const CompositeDist &prior_)
IdxT get_num_hyperparams () const
void set_hyperparams (const VecT &hyperparams)
VecT get_hyperparams () const
bool has_hyperparam (const std::string &name) const
double get_hyperparam_value (const std::string &name) const
int get_hyperparam_index (const std::string &name) const
void set_hyperparam_value (const std::string &name, double value)
void rename_hyperparam (const std::string &old_name, const std::string &new_name)
StringVecT get_param_names () const
void set_param_names (const StringVecT &desc)
StringVecT get_hyperparam_names () const
void set_hyperparam_names (const StringVecT &desc)
template<class RngT >
ParamT sample_prior (RngT &rng) const
ParamT sample_prior () const
void set_bounds (const ParamT &lbound, const ParamT &ubound)
void set_lbound (const ParamT &lbound)
void set_ubound (const ParamT &ubound)
const ParamT & get_lbound () const
const ParamT & get_ubound () const
bool theta_in_bounds (const ParamT &theta) const
void bound_theta (ParamT &theta, double epsilon=bounds_epsilon) const
ParamT bounded_theta (const ParamT &theta, double epsilon=bounds_epsilon) const
ParamT reflected_theta (const ParamT &theta) const
BoolVecT theta_stack_in_bounds (const ParamVecT &theta) const
ParamVecT bounded_theta_stack (const ParamVecT &theta, double epsilon=bounds_epsilon) const
ParamVecT reflected_theta_stack (const ParamVecT &theta) const
Static Public Member Functions
static prior_hessian::TruncatedNormalDist make_prior_component_position_normal (IdxT size, double pos_sigma=DefaultPriorSigmaPos)
static prior_hessian::ScaledSymmetricBetaDist make_prior_component_position_beta (IdxT size, double pos_beta=DefaultPriorBetaPos)
static prior_hessian::TruncatedGammaDist make_prior_component_intensity (double mean=DefaultPriorMeanI, double kappa=DefaultPriorIntensityKappa)
static prior_hessian::TruncatedParetoDist make_prior_component_sigma (double min_sigma, double max_sigma, double alpha=DefaultPriorPSFSigmaAlpha)
static void set_rng_seed (RngSeedT seed)
static ParallelRngManagerT & get_rng_manager ()
static ParallelRngGeneratorT & get_rng_generator ()
Static Public Attributes
static const std::string DefaultEstimatorMethod = "TrustRegion"
Default optimization method for MLE/MAP estimation.
static const std::string DefaultProfileBoundsEstimatorMethod = "Newton"
Default optimization method for profile bounds optimizations.
static const std::string DefaultSeperableInitEstimator = "TrustRegion"
static const IdxT DefaultMCMCNumSamples = 300
Number of final samples to use in estimation of posterior properties (mean, credible interval, cov, etc.)
static const IdxT DefaultMCMCBurnin = 10
Number of samples to throw away (burn-in) on initialization.
static const IdxT DefaultMCMCThin = 0
Keep every # samples. [Value of 0 indicates use the model default. This is suggested.].
static const double DefaultConfidenceLevel = 0.95
Default level at which to estimate confidence intervals must be in range (0,1).
static const double DefaultPriorBetaPos = 3
static const double DefaultPriorSigmaPos = 1
static const double DefaultPriorMeanI = 300
static const double DefaultPriorMaxI = INFINITY
static const double DefaultPriorIntensityKappa = 2
static const double DefaultPriorPixelMeanBG = 4
static const double DefaultPriorPSFSigmaAlpha = 2
static const double bounds_epsilon = 1.0E-6
static const double global_min_psf_sigma = 1E-1
static const double global_max_psf_sigma = 1E2
Protected Member Functions
MAPEstimator ()
MAPEstimator (const MAPEstimator &o)
MAPEstimator (MAPEstimator &&o)
MAPEstimator & operator= (const MAPEstimator &o)
MAPEstimator & operator= (MAPEstimator &&o)
Protected Attributes
CompositeDist prior
IdxT num_params
IdxT num_hyperparams
ParamT lbound
ParamT ubound
Detailed Description
A Mixin class to configure a for MLE estimation (null prior).
Inheriting from this class modifies the objective function undergoing optimization to use a Null prior, by simply ignoreing the effect of the prior on the objective. This which effectively turns the objective function into a pure likelihood function, and the estimator becomes an MLE estimator.
Definition at line 22 of file MAPEstimator.h.
Member Typedef Documentation
using mappel::PointEmitterModel::ParamT = arma::vec inherited
Parameter vector
Definition at line 47 of file PointEmitterModel.h.
using mappel::PointEmitterModel::ParamVecT = arma::mat inherited
Vector of parameter vectors
Definition at line 48 of file PointEmitterModel.h.
Constructor & Destructor Documentation
mappel::MAPEstimator::MAPEstimator () inline protected
Definition at line 24 of file MAPEstimator.h.
mappel::MAPEstimator::MAPEstimator (const MAPEstimator & o) inline protected
Definition at line 25 of file MAPEstimator.h.
mappel::MAPEstimator::MAPEstimator (MAPEstimator && o) inline protected
Definition at line 26 of file MAPEstimator.h.
Member Function Documentation
void mappel::PointEmitterModel::bound_theta (ParamT & theta, double epsilon = bounds_epsilon) const inherited
Definition at line 255 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::check_param_shape(), mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, and mappel::PointEmitterModel::ubound.
PointEmitterModel::ParamT mappel::PointEmitterModel::bounded_theta (const ParamT & theta, double epsilon = bounds_epsilon) const inherited
Definition at line 272 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::check_param_shape(), mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, and mappel::PointEmitterModel::ubound.
Referenced by mappel::PointEmitterModel::bounded_theta_stack().
PointEmitterModel::ParamVecT mappel::PointEmitterModel::bounded_theta_stack (const ParamVecT & theta, double epsilon = bounds_epsilon) const inherited
Definition at line 313 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::bounded_theta(), mappel::PointEmitterModel::check_param_shape(), and mappel::PointEmitterModel::make_param_stack().
void mappel::PointEmitterModel::check_param_shape (const ParamT & theta) const inherited
Definition at line 174 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::num_params.
Referenced by mappel::PointEmitterModel::bound_theta(), mappel::PointEmitterModel::bounded_theta(), mappel::PointEmitterModel::bounded_theta_stack(), mappel::PointEmitterModel::reflected_theta(), mappel::PointEmitterModel::reflected_theta_stack(), mappel::PointEmitterModel::theta_in_bounds(), and mappel::PointEmitterModel::theta_stack_in_bounds().
void mappel::PointEmitterModel::check_param_shape (const ParamVecT & theta) const inherited
Definition at line 183 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::num_params.
void mappel::PointEmitterModel::check_psf_sigma (double psf_sigma) const inherited
Definition at line 192 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::global_max_psf_sigma, and mappel::PointEmitterModel::global_min_psf_sigma.
Referenced by mappel::Gauss1DModel::Gauss1DModel(), mappel::Gauss2DModel::Gauss2DModel(), mappel::Gauss2DsModel::Gauss2DsModel(), mappel::Gauss1DsModel::set_max_sigma(), mappel::Gauss2DsModel::set_max_sigma(), mappel::Gauss1DsModel::set_min_sigma(), mappel::Gauss2DsModel::set_min_sigma(), mappel::Gauss1DModel::set_psf_sigma(), and mappel::Gauss2DModel::set_psf_sigma().
void mappel::PointEmitterModel::check_psf_sigma (const VecT & psf_sigma) const inherited
Definition at line 204 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::global_max_psf_sigma, and mappel::PointEmitterModel::global_min_psf_sigma.
int mappel::PointEmitterModel::get_hyperparam_index (const std::string & name) const inline inherited
Definition at line 243 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
StringVecT mappel::PointEmitterModel::get_hyperparam_names () const inline inherited
Definition at line 263 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
double mappel::PointEmitterModel::get_hyperparam_value (const std::string & name) const inline inherited
Definition at line 239 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
Referenced by mappel::MCMCAdaptor1D::set_background_mcmc_sampling(), and mappel::MCMCAdaptor1D::set_intensity_mcmc_sampling().
PointEmitterModel::ParamT mappel::PointEmitterModel::get_hyperparams () const inline inherited
Definition at line 231 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
const PointEmitterModel::ParamT & mappel::PointEmitterModel::get_lbound () const inline inherited
Definition at line 219 of file PointEmitterModel.h.
References mappel::PointEmitterModel::lbound.
Referenced by mappel::MCMCAdaptor1D::MCMCAdaptor1D(), mappel::MCMCAdaptor2D::MCMCAdaptor2D(), and mappel::MCMCAdaptor1D::set_background_mcmc_sampling().
IdxT mappel::PointEmitterModel::get_num_hyperparams () const inline inherited
Definition at line 215 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_hyperparams.
IdxT mappel::PointEmitterModel::get_num_params () const inline inherited
Definition at line 167 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
StringVecT mappel::PointEmitterModel::get_param_names () const inline inherited
Definition at line 255 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
CompositeDist & mappel::PointEmitterModel::get_prior () inline inherited
Definition at line 207 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
Referenced by mappel::Gauss2DModel::update_internal_1Dsum_estimators(), and mappel::Gauss2DsModel::update_internal_1Dsum_estimators().
const CompositeDist & mappel::PointEmitterModel::get_prior () const inline inherited
Definition at line 211 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
ParallelRngGeneratorT & mappel::PointEmitterModel::get_rng_generator () static inherited
Definition at line 127 of file PointEmitterModel.cpp.
References mappel::rng_manager.
ParallelRngManagerT & mappel::PointEmitterModel::get_rng_manager () static inherited
Definition at line 122 of file PointEmitterModel.cpp.
References mappel::rng_manager.
StatsT mappel::PointEmitterModel::get_stats () const inherited
Definition at line 132 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_hyperparams, mappel::PointEmitterModel::num_params, mappel::PointEmitterModel::prior, mappel::rng_manager, and mappel::PointEmitterModel::ubound.
Referenced by mappel::Gauss1DModel::get_stats(), mappel::Gauss1DsModel::get_stats(), mappel::Gauss2DModel::get_stats(), and mappel::Gauss2DsModel::get_stats().
const PointEmitterModel::ParamT & mappel::PointEmitterModel::get_ubound () const inline inherited
Definition at line 223 of file PointEmitterModel.h.
References mappel::PointEmitterModel::ubound.
Referenced by mappel::Gauss2DsxyModel::get_max_sigma_ratio(), mappel::Gauss2DsModel::get_max_sigma_ratio(), mappel::MCMCAdaptor1D::MCMCAdaptor1D(), mappel::MCMCAdaptor2D::MCMCAdaptor2D(), mappel::MCMCAdaptor1D::set_background_mcmc_sampling(), and mappel::Gauss2DsModel::set_max_sigma_ratio().
bool mappel::PointEmitterModel::has_hyperparam (const std::string & name) const inline inherited
Definition at line 235 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
PointEmitterModel::ParamT mappel::PointEmitterModel::make_param () const inline inherited
Definition at line 171 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
Referenced by mappel::Gauss1DModel::initial_theta_estimate(), mappel::Gauss1DsModel::initial_theta_estimate(), mappel::Gauss2DModel::initial_theta_estimate(), mappel::Gauss2DsxyModel::initial_theta_estimate(), mappel::Gauss2DsModel::initial_theta_estimate(), mappel::Gauss1DModel::pixel_hess_update(), mappel::Gauss1DsModel::pixel_hess_update(), mappel::Gauss2DModel::pixel_hess_update(), and mappel::Gauss2DsModel::pixel_hess_update().
template<class FillT > PointEmitterModel::ParamT mappel::PointEmitterModel::make_param (FillT fill) const inherited
Definition at line 188 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
MatT mappel::PointEmitterModel::make_param_mat () const inline inherited
Definition at line 179 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
template<class FillT > MatT mappel::PointEmitterModel::make_param_mat (FillT fill) const inherited
Definition at line 198 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
CubeT mappel::PointEmitterModel::make_param_mat_stack (IdxT n) const inline inherited
Definition at line 183 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
template<class FillT > CubeT mappel::PointEmitterModel::make_param_mat_stack (IdxT n, FillT fill) const inherited
Definition at line 203 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
PointEmitterModel::ParamVecT mappel::PointEmitterModel::make_param_stack (IdxT n) const inline inherited
Definition at line 175 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
Referenced by mappel::PointEmitterModel::bounded_theta_stack(), and mappel::PointEmitterModel::reflected_theta_stack().
template<class FillT > PointEmitterModel::ParamVecT mappel::PointEmitterModel::make_param_stack (IdxT n, FillT fill) const inherited
Definition at line 193 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
prior_hessian::TruncatedGammaDist mappel::PointEmitterModel::make_prior_component_intensity (double mean = DefaultPriorMeanI, double kappa = DefaultPriorIntensityKappa) static inherited
Definition at line 105 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::DefaultPriorMaxI.
Referenced by mappel::Gauss1DsModel::make_default_prior_beta_position(), mappel::Gauss2DModel::make_default_prior_beta_position(), mappel::Gauss1DModel::make_default_prior_beta_position(), mappel::Gauss2DsModel::make_default_prior_beta_position(), mappel::Gauss2DModel::make_default_prior_normal_position(), mappel::Gauss1DsModel::make_default_prior_normal_position(), mappel::Gauss1DModel::make_default_prior_normal_position(), mappel::Gauss2DsModel::make_default_prior_normal_position(), mappel::Gauss2DModel::make_prior_beta_position(), mappel::Gauss1DsModel::make_prior_beta_position(), mappel::Gauss1DModel::make_prior_beta_position(), mappel::Gauss2DsModel::make_prior_beta_position(), mappel::Gauss2DModel::make_prior_normal_position(), mappel::Gauss1DsModel::make_prior_normal_position(), mappel::Gauss1DModel::make_prior_normal_position(), and mappel::Gauss2DsModel::make_prior_normal_position().
prior_hessian::ScaledSymmetricBetaDist mappel::PointEmitterModel::make_prior_component_position_beta (IdxT size, double pos_beta = DefaultPriorBetaPos) static inherited
Definition at line 99 of file PointEmitterModel.cpp.
Referenced by mappel::Gauss1DsModel::make_default_prior_beta_position(), mappel::Gauss2DModel::make_default_prior_beta_position(), mappel::Gauss1DModel::make_default_prior_beta_position(), mappel::Gauss2DsModel::make_default_prior_beta_position(), mappel::Gauss1DsModel::make_prior_beta_position(), mappel::Gauss2DModel::make_prior_beta_position(), mappel::Gauss1DModel::make_prior_beta_position(), and mappel::Gauss2DsModel::make_prior_beta_position().
prior_hessian::TruncatedNormalDist mappel::PointEmitterModel::make_prior_component_position_normal (IdxT size, double pos_sigma = DefaultPriorSigmaPos) static inherited
Definition at line 92 of file PointEmitterModel.cpp.
Referenced by mappel::Gauss1DsModel::make_default_prior_normal_position(), mappel::Gauss2DModel::make_default_prior_normal_position(), mappel::Gauss1DModel::make_default_prior_normal_position(), mappel::Gauss2DsModel::make_default_prior_normal_position(), mappel::Gauss2DModel::make_prior_normal_position(), mappel::Gauss1DsModel::make_prior_normal_position(), mappel::Gauss1DModel::make_prior_normal_position(), and mappel::Gauss2DsModel::make_prior_normal_position().
prior_hessian::TruncatedParetoDist mappel::PointEmitterModel::make_prior_component_sigma (double min_sigma, double max_sigma, double alpha = DefaultPriorPSFSigmaAlpha) static inherited
Definition at line 111 of file PointEmitterModel.cpp.
Referenced by mappel::Gauss1DsModel::make_default_prior_beta_position(), mappel::Gauss2DsModel::make_default_prior_beta_position(), mappel::Gauss1DsModel::make_default_prior_normal_position(), mappel::Gauss2DsModel::make_default_prior_normal_position(), mappel::Gauss1DsModel::make_prior_beta_position(), mappel::Gauss2DsModel::make_prior_beta_position(), mappel::Gauss1DsModel::make_prior_normal_position(), and mappel::Gauss2DsModel::make_prior_normal_position().
MAPEstimator& mappel::MAPEstimator::operator= (const MAPEstimator & o) inline protected
Definition at line 27 of file MAPEstimator.h.
Referenced by mappel::Gauss1DMAP::operator=(), mappel::Gauss1DsMAP::operator=(), mappel::Gauss2DsMAP::operator=(), and mappel::Gauss2DMAP::operator=().
MAPEstimator& mappel::MAPEstimator::operator= (MAPEstimator && o) inline protected
Definition at line 28 of file MAPEstimator.h.
PointEmitterModel::ParamT mappel::PointEmitterModel::reflected_theta (const ParamT & theta) const inherited
Definition at line 283 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::check_param_shape(), mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, and mappel::PointEmitterModel::ubound.
Referenced by mappel::PointEmitterModel::reflected_theta_stack().
PointEmitterModel::ParamVecT mappel::PointEmitterModel::reflected_theta_stack (const ParamVecT & theta) const inherited
Definition at line 323 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::check_param_shape(), mappel::PointEmitterModel::make_param_stack(), and mappel::PointEmitterModel::reflected_theta().
void mappel::PointEmitterModel::rename_hyperparam (const std::string & old_name, const std::string & new_name) inline inherited
Definition at line 251 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
template<class RngT > PointEmitterModel::ParamT mappel::PointEmitterModel::sample_prior (RngT & rng) const inherited
Definition at line 271 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
PointEmitterModel::ParamT mappel::PointEmitterModel::sample_prior () const inline inherited
Definition at line 275 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior, and mappel::rng_manager.
void mappel::PointEmitterModel::set_bounds (const ParamT & lbound_, const ParamT & ubound_) inherited
Box-type parameter bounds
Modifies the prior bounds to prevent sampling outside the valid box-constraints.
Definition at line 220 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::bounds_epsilon, mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, mappel::PointEmitterModel::prior, and mappel::PointEmitterModel::ubound.
void mappel::PointEmitterModel::set_hyperparam_names (const StringVecT & desc) inline inherited
Definition at line 267 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
void mappel::PointEmitterModel::set_hyperparam_value (const std::string & name, double value) inline inherited
Definition at line 247 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
void mappel::PointEmitterModel::set_hyperparams (const VecT & hyperparams) inline inherited
Definition at line 227 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
Referenced by mappel::Gauss2DModel::set_hyperparams(), and mappel::Gauss2DsModel::set_hyperparams().
void mappel::PointEmitterModel::set_lbound (const ParamT & lbound) inherited
Definition at line 233 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::bounds_epsilon, mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, mappel::PointEmitterModel::prior, and mappel::PointEmitterModel::ubound.
Referenced by mappel::Gauss1DsModel::set_min_sigma().
void mappel::PointEmitterModel::set_param_names (const StringVecT & desc) inline inherited
Definition at line 259 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
void mappel::PointEmitterModel::set_prior (CompositeDist && prior_) inherited
Definition at line 165 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_hyperparams, mappel::PointEmitterModel::num_params, mappel::PointEmitterModel::prior, and mappel::PointEmitterModel::ubound.
Referenced by mappel::Gauss2DModel::set_prior(), and mappel::Gauss2DsModel::set_prior().
void mappel::PointEmitterModel::set_prior (const CompositeDist & prior_) inherited
Definition at line 156 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_hyperparams, mappel::PointEmitterModel::num_params, mappel::PointEmitterModel::prior, and mappel::PointEmitterModel::ubound.
void mappel::PointEmitterModel::set_rng_seed (RngSeedT seed) static inherited
Definition at line 117 of file PointEmitterModel.cpp.
References mappel::rng_manager.
void mappel::PointEmitterModel::set_ubound (const ParamT & ubound) inherited
Definition at line 244 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::bounds_epsilon, mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, mappel::PointEmitterModel::prior, and mappel::PointEmitterModel::ubound.
Referenced by mappel::Gauss1DsModel::set_max_sigma(), and mappel::Gauss2DsModel::set_max_sigma_ratio().
bool mappel::PointEmitterModel::theta_in_bounds (const ParamT & theta) const inherited
Definition at line 264 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::check_param_shape(), mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, and mappel::PointEmitterModel::ubound.
Referenced by mappel::Gauss2DModel::initial_theta_estimate(), mappel::Gauss2DsModel::initial_theta_estimate(), mappel::Gauss1DModel::make_stencil(), mappel::Gauss1DsModel::make_stencil(), mappel::Gauss2DModel::make_stencil(), mappel::Gauss2DsxyModel::make_stencil(), mappel::Gauss2DsModel::make_stencil(), and mappel::PointEmitterModel::theta_stack_in_bounds().
BoolVecT mappel::PointEmitterModel::theta_stack_in_bounds (const ParamVecT & theta) const inherited
Definition at line 303 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::check_param_shape(), and mappel::PointEmitterModel::theta_in_bounds().
Member Data Documentation
const double mappel::PointEmitterModel::bounds_epsilon = 1.0E-6 static inherited
Distance from the boundary to constrain in bound_theta and bounded_theta methods
Definition at line 67 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::set_bounds(), mappel::PointEmitterModel::set_lbound(), mappel::Gauss2DsModel::set_max_sigma_ratio(), and mappel::PointEmitterModel::set_ubound().
const double mappel::PointEmitterModel::DefaultConfidenceLevel = 0.95 static inherited
Default level at which to estimate confidence intervals must be in range (0,1).
Definition at line 57 of file PointEmitterModel.h.
const std::string mappel::PointEmitterModel::DefaultEstimatorMethod = "TrustRegion" static inherited
Default optimization method for MLE/MAP estimation.
Definition at line 51 of file PointEmitterModel.h.
const IdxT mappel::PointEmitterModel::DefaultMCMCBurnin = 10 static inherited
Number of samples to throw away (burn-in) on initialization.
Definition at line 55 of file PointEmitterModel.h.
const IdxT mappel::PointEmitterModel::DefaultMCMCNumSamples = 300 static inherited
Number of final samples to use in estimation of posterior properties (mean, credible interval, cov, etc.)
Definition at line 54 of file PointEmitterModel.h.
const IdxT mappel::PointEmitterModel::DefaultMCMCThin = 0 static inherited
Keep every # samples. [Value of 0 indicates use the model default. This is suggested.].
Definition at line 56 of file PointEmitterModel.h.
const double mappel::PointEmitterModel::DefaultPriorBetaPos = 3 static inherited
Default position parameter in symmetric beta-distributions
Definition at line 59 of file PointEmitterModel.h.
const double mappel::PointEmitterModel::DefaultPriorIntensityKappa = 2 static inherited
Default shape for intensity gamma distributions
Definition at line 63 of file PointEmitterModel.h.
const double mappel::PointEmitterModel::DefaultPriorMaxI = INFINITY static inherited
Default maximum emitter intensity
Definition at line 62 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::make_prior_component_intensity().
const double mappel::PointEmitterModel::DefaultPriorMeanI = 300 static inherited
Default emitter intensity mean
Definition at line 61 of file PointEmitterModel.h.
Referenced by mappel::MCMCAdaptor1D::set_intensity_mcmc_sampling().
const double mappel::PointEmitterModel::DefaultPriorPixelMeanBG = 4 static inherited
Default per-pixel mean background counts
Definition at line 64 of file PointEmitterModel.h.
Referenced by mappel::Gauss1DsModel::make_default_prior_beta_position(), mappel::Gauss2DModel::make_default_prior_beta_position(), mappel::Gauss1DModel::make_default_prior_beta_position(), mappel::Gauss2DsModel::make_default_prior_beta_position(), mappel::Gauss1DsModel::make_default_prior_normal_position(), mappel::Gauss2DModel::make_default_prior_normal_position(), mappel::Gauss1DModel::make_default_prior_normal_position(), mappel::Gauss2DsModel::make_default_prior_normal_position(), and mappel::MCMCAdaptor1D::set_background_mcmc_sampling().
const double mappel::PointEmitterModel::DefaultPriorPSFSigmaAlpha = 2 static inherited
Default per-pixel background gamma distribution shape
Definition at line 65 of file PointEmitterModel.h.
const double mappel::PointEmitterModel::DefaultPriorSigmaPos = 1 static inherited
Default position parameter in symmetric beta-distributions
Definition at line 60 of file PointEmitterModel.h.
const std::string mappel::PointEmitterModel::DefaultProfileBoundsEstimatorMethod = "Newton" static inherited
Default optimization method for profile bounds optimizations.
Definition at line 52 of file PointEmitterModel.h.
const std::string mappel::PointEmitterModel::DefaultSeperableInitEstimator = "TrustRegion" static inherited
Estimator name to use in 1D separable initializations
Definition at line 53 of file PointEmitterModel.h.
Referenced by mappel::Gauss2DModel::initial_theta_estimate(), mappel::Gauss2DsxyModel::initial_theta_estimate(), and mappel::Gauss2DsModel::initial_theta_estimate().
const double mappel::PointEmitterModel::global_max_psf_sigma = 1E2 static inherited
Global maxmimum for any psf_sigma. Sizes above this value are invalid, and nowhere near useful for practical point emitter localization
Definition at line 69 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::check_psf_sigma().
const double mappel::PointEmitterModel::global_min_psf_sigma = 1E-1 static inherited
Global minimum for any psf_sigma. Sizes below this value are invalid, and nowhere near useful for practical point emitter localization
Definition at line 68 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::check_psf_sigma().
ParamT mappel::PointEmitterModel::lbound protected inherited
Definition at line 155 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::bound_theta(), mappel::PointEmitterModel::bounded_theta(), mappel::PointEmitterModel::get_lbound(), mappel::PointEmitterModel::get_stats(), mappel::Gauss1DsModel::initial_theta_estimate(), mappel::Gauss2DModel::initial_theta_estimate(), mappel::Gauss2DsModel::initial_theta_estimate(), mappel::PointEmitterModel::operator=(), mappel::PointEmitterModel::reflected_theta(), mappel::PointEmitterModel::set_bounds(), mappel::PointEmitterModel::set_lbound(), mappel::PointEmitterModel::set_prior(), mappel::PointEmitterModel::set_ubound(), and mappel::PointEmitterModel::theta_in_bounds().
IdxT mappel::PointEmitterModel::num_hyperparams protected inherited
Definition at line 154 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::get_num_hyperparams(), mappel::PointEmitterModel::get_stats(), mappel::PointEmitterModel::operator=(), and mappel::PointEmitterModel::set_prior().
IdxT mappel::PointEmitterModel::num_params protected inherited
Definition at line 153 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::bound_theta(), mappel::PointEmitterModel::bounded_theta(), mappel::PointEmitterModel::check_param_shape(), mappel::PointEmitterModel::get_num_params(), mappel::PointEmitterModel::get_stats(), mappel::Gauss1DModel::initial_theta_estimate(), mappel::Gauss2DModel::initial_theta_estimate(), mappel::Gauss2DsModel::initial_theta_estimate(), mappel::PointEmitterModel::make_param(), mappel::PointEmitterModel::make_param_mat(), mappel::PointEmitterModel::make_param_mat_stack(), mappel::PointEmitterModel::make_param_stack(), mappel::PointEmitterModel::operator=(), mappel::PointEmitterModel::reflected_theta(), mappel::PointEmitterModel::set_bounds(), mappel::PointEmitterModel::set_lbound(), mappel::PointEmitterModel::set_prior(), mappel::PointEmitterModel::set_ubound(), and mappel::PointEmitterModel::theta_in_bounds().
CompositeDist mappel::PointEmitterModel::prior protected inherited
Definition at line 152 of file PointEmitterModel.h.
Referenced by mappel::Gauss2DModel::debug_internal_sum_model_y(), mappel::Gauss2DsModel::debug_internal_sum_model_y(), mappel::Gauss2DModel::Gauss2DModel(), mappel::Gauss2DsModel::Gauss2DsModel(), mappel::PointEmitterModel::get_hyperparam_index(), mappel::PointEmitterModel::get_hyperparam_names(), mappel::PointEmitterModel::get_hyperparam_value(), mappel::PointEmitterModel::get_hyperparams(), mappel::Gauss1DsModel::get_max_sigma(), mappel::Gauss1DsModel::get_min_sigma(), mappel::PointEmitterModel::get_param_names(), mappel::PointEmitterModel::get_prior(), mappel::PointEmitterModel::get_stats(), mappel::PointEmitterModel::has_hyperparam(), mappel::PointEmitterModel::operator=(), mappel::PointEmitterModel::PointEmitterModel(), mappel::PointEmitterModel::rename_hyperparam(), mappel::PointEmitterModel::sample_prior(), mappel::PointEmitterModel::set_bounds(), mappel::PointEmitterModel::set_hyperparam_names(), mappel::PointEmitterModel::set_hyperparam_value(), mappel::PointEmitterModel::set_hyperparams(), mappel::PointEmitterModel::set_lbound(), mappel::Gauss1DsModel::set_max_sigma(), mappel::Gauss1DsModel::set_min_sigma(), mappel::PointEmitterModel::set_param_names(), mappel::PointEmitterModel::set_prior(), and mappel::PointEmitterModel::set_ubound().
ParamT mappel::PointEmitterModel::ubound protected inherited
Definition at line 155 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::bound_theta(), mappel::PointEmitterModel::bounded_theta(), mappel::PointEmitterModel::get_stats(), mappel::PointEmitterModel::get_ubound(), mappel::Gauss1DsModel::initial_theta_estimate(), mappel::Gauss2DModel::initial_theta_estimate(), mappel::Gauss2DsModel::initial_theta_estimate(), mappel::PointEmitterModel::operator=(), mappel::PointEmitterModel::reflected_theta(), mappel::PointEmitterModel::set_bounds(), mappel::PointEmitterModel::set_lbound(), mappel::PointEmitterModel::set_prior(), mappel::PointEmitterModel::set_ubound(), and mappel::PointEmitterModel::theta_in_bounds().
The documentation for this class was generated from the following file:
MAPEstimator.h