Mappel: mappel::estimator::TrustRegionMaximizer< Model > Class Template Reference
mappel::estimator::TrustRegionMaximizer< Model > Class Template Reference abstract
#include </home/travis/build/markjolah/Mappel/include/Mappel/estimator.h>
Public Types
using MaximizerData = typename IterativeMaximizer< Model >::MaximizerData
Public Member Functions
TrustRegionMaximizer (const Model &model, int max_iterations=IterativeMaximizer< Model >::DefaultIterations)
std::string name () const
double mean_iterations ()
double mean_backtracks ()
double mean_fun_evals ()
double mean_der_evals ()
StatsT get_stats ()
StatsT get_debug_stats ()
void clear_stats ()
int get_total_iterations () const
int get_total_backtracks () const
int get_total_fun_evals () const
int get_total_der_evals () const
void local_maximize (const ModelDataT< Model > &im, StencilT< Model > &stencil, MLEData &data)
Perform a local maximization to finish off a simulated annealing run.
void local_maximize (const ModelDataT< Model > &im, StencilT< Model > &stencil, MLEDebugData &debug_data)
void local_profile_maximize (const ModelDataT< Model > &im, const IdxVecT &fixed_param_idxs, StencilT< Model > &stencil, MLEDebugData &mle)
void estimate_max_stack (const ModelDataStackT< Model > &data, const ParamVecT< Model > &theta_init_stack, MLEDataStack &mle_data_stack) override
void estimate_profile_max (const ModelDataT< Model > &data, const ParamVecT< Model > &theta_init, ProfileLikelihoodData &profile) override
void estimate_profile_bounds_parallel (const ModelDataT< Model > &data, ProfileBoundsData &bounds_est) override
void estimate_profile_bounds_stack (const ModelDataStackT< Model > &data, ProfileBoundsDataStack &bounds_est_stack) override
const Model & get_model ()
void estimate_max_stack (const ModelDataStackT< Model > &data_stack, MLEDataStack &mle_data_stack)
void estimate_max (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, MLEData &mle_data, StencilT< Model > &mle_stencil)
void estimate_max (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, MLEData &mle_data)
void estimate_max (const ModelDataT< Model > &data, MLEData &mle_data)
void estimate_max_debug (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, MLEDebugData &mle_data, StencilT< Model > &mle_stencil)
void estimate_max_debug (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, MLEDebugData &mle_data)
double estimate_profile_max (const ModelDataT< Model > &data, const IdxVecT &fixed_idxs, const ParamT< Model > &fixed_theta_init, StencilT< Model > &theta_max)
void estimate_profile_bounds (const ModelDataT< Model > &data, ProfileBoundsData &bounds_est)
void estimate_profile_bounds_debug (const ModelDataT< Model > &data, ProfileBoundsDebugData &bounds_est)
IdxVecT get_exit_counts () const
Static Public Attributes
static const double rho_cauchy_min = 0.1
Minimum acceptable rho for cauchy point: Coleman beta / Bellavia beta_1.
static const double rho_obj_min = 0.25
Minimum acceptable rho: Coleman mu / Bellavia beta_2.
static const double rho_obj_opt = 0.75
Optimal step rho: Coleman eta / Bellavia beta_2.
static const double trust_radius_decrease_min = 0.125
Smallest alowable trust radius decrease ratio: Coleman gamma_0 / Bellavia alpha_1.
static const double trust_radius_decrease = 0.25
Trust radius decrease ratio to step size: Coleman gamma_1 / Bellavia alpha_2.
static const double trust_radius_increase = 2
Trust radius increase ratio: Coleman gamma_2 / Bellavia alpha_3.
static const double convergence_min_trust_radius = 1.0e-8
Convergence criteria: Minimum trust region radius.
static const int DefaultIterations =100
Protected Member Functions
void record_run_statistics (const MaximizerData &data)
void compute_estimate (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, MLEData &mle_data, StencilT< Model > &mle_stencil) override
void compute_estimate_debug (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, MLEDebugData &mle_data, StencilT< Model > &mle_stencil) override
double compute_profile_estimate (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, const IdxVecT &fixed_idxs, StencilT< Model > &theta_max) override
void compute_profile_bound (const ModelDataT< Model > &data, ProfileBoundsData &est, const VecT &init_step, IdxT param_idx, IdxT which_bound) override
void compute_profile_bound_debug (const ModelDataT< Model > &data, ProfileBoundsDebugData &bounds) override
bool backtrack (MaximizerData &data)
bool profile_bound_backtrack (MaximizerData &data, IdxT fixed_idx, double target_rllh, double old_fval, const VecT &fgrad)
virtual void maximize (MaximizerData &data)=0
virtual void solve_profile_bound (MaximizerData &data, MLEData &mle, double llh_delta, IdxT fixed_idx, IdxT which_bound)
bool convergence_test_grad_ratio (const VecT &grad, double fval)
bool convergence_test_step_size (const VecT &new_theta, const VecT &old_theta)
void record_exit_code (ExitCode code) override
void record_walltime (ClockT::time_point start_walltime, int num_estimations)
Protected Attributes
int max_iterations
int total_iterations = 0
int total_backtracks = 0
int total_fun_evals = 0
int total_der_evals = 0
IdxVecT last_backtrack_idxs
Debugging: Stores last set of backtrack_idxs when data.save_seq==true.
int max_threads
int num_threads
std::mutex mtx
const Model & model
int num_estimations = 0
double total_walltime = 0.
IdxVecT exit_counts
Static Protected Attributes
static const double min_eigenvalue_correction_delta = 1e-3
Ensure the minimum eigenvalue is at least this big when correcting indefinite matrix.
static const double convergence_min_function_change_ratio = 1.0e-9
Convergence criteria: tolerance for function-value change.
static const double convergence_min_step_size_ratio = 1.0e-9
Convergence criteria: tolerance of relative step size.
static const double backtrack_min_ratio = 0.05
static const double backtrack_max_ratio = 0.50
static const double backtrack_min_linear_step_ratio = 1e-3
static const int max_backtracks = 8
static const double min_profile_bound_residual = 1e-4
Minimum residual in quadratic solutions of equation (8) to accept. Revert to newton step.
Detailed Description
template<class Model>
class mappel::estimator::TrustRegionMaximizer< Model >
Definition at line 614 of file estimator.h.
Member Typedef Documentation
template<class Model> using mappel::estimator::TrustRegionMaximizer< Model >::MaximizerData = typename IterativeMaximizer<Model>::MaximizerData
Definition at line 617 of file estimator.h.
Constructor & Destructor Documentation
template<class Model> mappel::estimator::TrustRegionMaximizer< Model >::TrustRegionMaximizer (const Model & model, int max_iterations = IterativeMaximizer<Model>::DefaultIterations) inline
Definition at line 627 of file estimator.h.
Member Function Documentation
template<class Model > bool mappel::estimator::IterativeMaximizer< Model >::backtrack (MaximizerData & data) protected inherited
Definition at line 870 of file estimator_impl.h.
References mappel::estimator::IterativeMaximizer< Model >::backtrack_min_linear_step_ratio, mappel::clamp(), mappel::estimator::IterativeMaximizer< Model >::convergence_min_step_size_ratio, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::grad, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::im, mappel::estimator::IterativeMaximizer< Model >::max_backtracks, mappel::estimator::MaxBacktracks, mappel::estimator::Estimator< Model >::model, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_backtrack(), mappel::estimator::ThreadedEstimator< Model >::record_exit_code(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_iteration(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::restore_stencil(), mappel::methods::objective::rllh(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::rllh, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::save_stencil(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::saved_theta(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::set_stencil(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::stencil(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::step, mappel::estimator::StepSize, and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::theta().
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::clear_stats () virtual inherited
Run statistics.
Reimplemented from mappel::estimator::ThreadedEstimator< Model >.
Definition at line 848 of file estimator_impl.h.
References mappel::estimator::ThreadedEstimator< Model >::clear_stats(), mappel::estimator::ThreadedEstimator< Model >::mtx, mappel::estimator::IterativeMaximizer< Model >::total_backtracks, mappel::estimator::IterativeMaximizer< Model >::total_der_evals, mappel::estimator::IterativeMaximizer< Model >::total_fun_evals, and mappel::estimator::IterativeMaximizer< Model >::total_iterations.
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::compute_estimate (const ModelDataT< Model > & data, const ParamT< Model > & theta_init, MLEData & mle_data, StencilT< Model > & mle_stencil) override protected virtual inherited
Implements mappel::estimator::Estimator< Model >.
Definition at line 1043 of file estimator_impl.h.
References mappel::estimator::IterativeMaximizer< Model >::maximize(), mappel::estimator::Estimator< Model >::model, mappel::methods::observed_information(), mappel::estimator::MLEData::obsI, mappel::estimator::IterativeMaximizer< Model >::record_run_statistics(), mappel::estimator::MLEData::rllh, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::rllh, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::stencil(), mappel::estimator::MLEData::theta, and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::theta().
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::compute_estimate_debug (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, MLEDebugData & mle_debug, StencilT< Model > & mle_stencil) override protected virtual inherited
Virtual estimate_debug interface
Estimators that produce a sequence of results (e.g. IterativeEstimators) can override this dummy debug implementation.
Reimplemented from mappel::estimator::Estimator< Model >.
Definition at line 1057 of file estimator_impl.h.
References mappel::estimator::IterativeMaximizer< Model >::MaximizerData::get_theta_sequence(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::get_theta_sequence_rllh(), mappel::estimator::IterativeMaximizer< Model >::maximize(), mappel::estimator::Estimator< Model >::model, mappel::methods::observed_information(), mappel::estimator::MLEDebugData::obsI, mappel::estimator::IterativeMaximizer< Model >::record_run_statistics(), mappel::estimator::MLEDebugData::rllh, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::rllh, mappel::estimator::MLEDebugData::sequence, mappel::estimator::MLEDebugData::sequence_rllh, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::stencil(), mappel::estimator::MLEDebugData::theta, and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::theta().
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::compute_profile_bound (const ModelDataT< Model > & data, ProfileBoundsData & est, const VecT & init_step, IdxT param_idx, IdxT which_bound) override protected virtual inherited
Reimplemented from mappel::estimator::Estimator< Model >.
Definition at line 1088 of file estimator_impl.h.
References mappel::estimator::ProfileBoundsData::estimated_idxs, mappel::estimator::ProfileBoundsData::mle, mappel::estimator::Estimator< Model >::model, mappel::estimator::ProfileBoundsData::profile_lb, mappel::estimator::ProfileBoundsData::profile_points_lb, mappel::estimator::ProfileBoundsData::profile_points_lb_rllh, mappel::estimator::ProfileBoundsData::profile_points_ub, mappel::estimator::ProfileBoundsData::profile_points_ub_rllh, mappel::estimator::ProfileBoundsData::profile_ub, mappel::estimator::IterativeMaximizer< Model >::record_run_statistics(), mappel::estimator::IterativeMaximizer< Model >::solve_profile_bound(), mappel::estimator::ProfileBoundsData::target_rllh_delta, and mappel::estimator::MLEData::theta.
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::compute_profile_bound_debug (const ModelDataT< Model > & data, ProfileBoundsDebugData & bounds) override protected virtual inherited
Reimplemented from mappel::estimator::Estimator< Model >.
Definition at line 1114 of file estimator_impl.h.
References mappel::estimator::ProfileBoundsDebugData::estimated_idx, mappel::estimator::ProfileBoundsDebugData::mle, mappel::estimator::Estimator< Model >::model, mappel::estimator::ProfileBoundsDebugData::Nseq_lb, mappel::estimator::ProfileBoundsDebugData::Nseq_ub, mappel::estimator::MLEData::obsI, mappel::estimator::ProfileBoundsDebugData::profile_lb, mappel::estimator::ProfileBoundsDebugData::profile_ub, mappel::estimator::IterativeMaximizer< Model >::record_run_statistics(), mappel::estimator::ProfileBoundsDebugData::sequence_lb, mappel::estimator::ProfileBoundsDebugData::sequence_lb_rllh, mappel::estimator::ProfileBoundsDebugData::sequence_ub, mappel::estimator::ProfileBoundsDebugData::sequence_ub_rllh, mappel::estimator::IterativeMaximizer< Model >::solve_profile_bound(), mappel::estimator::subroutine::solve_profile_initial_step(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::step, mappel::estimator::ProfileBoundsDebugData::target_rllh_delta, and mappel::estimator::MLEData::theta.
template<class Model > double mappel::estimator::IterativeMaximizer< Model >::compute_profile_estimate (const ModelDataT< Model > & data, const ParamT< Model > & theta_init, const IdxVecT & fixed_idxs, StencilT< Model > & theta_max) override protected virtual inherited
Reimplemented from mappel::estimator::Estimator< Model >.
Definition at line 1074 of file estimator_impl.h.
References mappel::estimator::IterativeMaximizer< Model >::maximize(), mappel::estimator::Estimator< Model >::model, mappel::estimator::IterativeMaximizer< Model >::record_run_statistics(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::rllh, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::set_fixed_parameters(), and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::stencil().
template<class Model > bool mappel::estimator::IterativeMaximizer< Model >::convergence_test_grad_ratio (const VecT & grad, double fval) protected inherited
Definition at line 1015 of file estimator_impl.h.
References mappel::estimator::IterativeMaximizer< Model >::convergence_min_function_change_ratio, mappel::estimator::GradRatio, mappel::norm_sq(), mappel::estimator::ThreadedEstimator< Model >::record_exit_code(), and mappel::square().
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > bool mappel::estimator::IterativeMaximizer< Model >::convergence_test_step_size (const VecT & new_theta, const VecT & old_theta) protected inherited
Definition at line 1027 of file estimator_impl.h.
References mappel::estimator::IterativeMaximizer< Model >::convergence_min_step_size_ratio, mappel::norm_sq(), mappel::estimator::ThreadedEstimator< Model >::record_exit_code(), and mappel::estimator::StepSize.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > void mappel::estimator::Estimator< Model >::estimate_max (const ModelDataT< Model > & data, const ParamT< Model > & theta_init, MLEData & mle_data, StencilT< Model > & mle_stencil) inherited
Maximum likelihood point estimators Estimate for a single data starting at theta_init, fill in the MLEData struct with the estimated parameter, RLLH, and observed information. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
The stencil at the MLE is also returned but can be ignored if not needed as it is available at no extra cost.
Parameters
[in] data Model data to estimate for
[in] theta_init [Optional] Initial theta value.
[out] mle_data MLEData recording the maximum likelihood estimate and relevant data.
[out] stencil [Optional] StencilT at the MLE value.
Definition at line 128 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_estimate(), mappel::estimator::Error, mappel::estimator::MLEData::obsI, mappel::print_text_image(), mappel::estimator::Estimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), mappel::estimator::MLEData::rllh, and mappel::estimator::MLEData::theta.
Referenced by mappel::estimator::Estimator< Model >::estimate_max().
template<class Model > void mappel::estimator::Estimator< Model >::estimate_max (const ModelDataT< Model > & data, const ParamT< Model > & theta_init, MLEData & mle_data) inherited
Maximum likelihood point estimators Estimate for a single data starting at theta_init, fill in the MLEData struct with the estimated parameter, RLLH, and observed information. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
The stencil at the MLE is also returned but can be ignored if not needed as it is available at no extra cost.
Parameters
[in] data Model data to estimate for
[in] theta_init [Optional] Initial theta value.
[out] mle_data MLEData recording the maximum likelihood estimate and relevant data.
[out] stencil [Optional] StencilT at the MLE value.
Definition at line 121 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::estimate_max().
template<class Model > void mappel::estimator::Estimator< Model >::estimate_max (const ModelDataT< Model > & data, MLEData & mle_data) inherited
Maximum likelihood point estimators Estimate for a single data starting at theta_init, fill in the MLEData struct with the estimated parameter, RLLH, and observed information. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
The stencil at the MLE is also returned but can be ignored if not needed as it is available at no extra cost.
Parameters
[in] data Model data to estimate for
[in] theta_init [Optional] Initial theta value.
[out] mle_data MLEData recording the maximum likelihood estimate and relevant data.
[out] stencil [Optional] StencilT at the MLE value.
Definition at line 112 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::estimate_max(), and mappel::estimator::Estimator< Model >::model.
template<class Model > void mappel::estimator::Estimator< Model >::estimate_max_debug (const ModelDataT< Model > & data, const ParamT< Model > & theta_init, MLEDebugData & mle_data, StencilT< Model > & mle_stencil) inherited
Debug estimation for a single data starting at theta_init, fill in the MLEDebugData struct with data including the sequence of evaluated points. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
The sequence and sequence_rllh parameters of the MLEDebugData struct record the entire sequence of evaluated points including theta_init and theta_mle, which should be first and last respectively.
The stencil at the MLE is also returned but can be ignored if not needed as it is available at no extra cost.
Parameters
[in] data Model data to estimate for
[in] theta_init Initial theta value.
[out] mle_data MLEDebugData recording the maximum likelihood estimate and relevant data.
[out] stencil [Optional] StencilT at the MLE value.
template<class Model > void mappel::estimator::Estimator< Model >::estimate_max_debug (const ModelDataT< Model > & data, const ParamT< Model > & theta_init, MLEDebugData & mle_data) inherited
Maximum likelihood point estimators Estimate for a single data starting at theta_init, fill in the MLEData struct with the estimated parameter, RLLH, and observed information. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
The stencil at the MLE is also returned but can be ignored if not needed as it is available at no extra cost.
Parameters
[in] data Model data to estimate for
[in] theta_init [Optional] Initial theta value.
[out] mle_data MLEData recording the maximum likelihood estimate and relevant data.
[out] stencil [Optional] StencilT at the MLE value.
Definition at line 157 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_estimate_debug(), mappel::estimator::Error, mappel::estimator::MLEDebugData::obsI, mappel::print_text_image(), mappel::estimator::Estimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), mappel::estimator::MLEDebugData::rllh, and mappel::estimator::MLEDebugData::theta.
template<class Model > void mappel::estimator::Estimator< Model >::estimate_max_stack (const ModelDataStackT< Model > & data_stack, MLEDataStack & mle_data_stack) inherited
Maximum likelihood point estimators Estimate for a single data starting at theta_init, fill in the MLEData struct with the estimated parameter, RLLH, and observed information. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
The stencil at the MLE is also returned but can be ignored if not needed as it is available at no extra cost.
Parameters
[in] data Model data to estimate for
[in] theta_init [Optional] Initial theta value.
[out] mle_data MLEData recording the maximum likelihood estimate and relevant data.
[out] stencil [Optional] StencilT at the MLE value.
Definition at line 183 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::estimate_max_stack(), and mappel::estimator::Estimator< Model >::model.
template<class Model > void mappel::estimator::ThreadedEstimator< Model >::estimate_max_stack (const ModelDataStackT< Model > & data_stack, const ParamVecT< Model > & theta_init_stack, MLEDataStack & mle_data_stack) override virtual inherited
Estimate for a stack of data and fill in the MLEDataStack struct with the estimated parameter, RLLH, and observed information for each data in parallel. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
Parameters
[in] data Model data to estimate for
[in] theta_init [optional] Initial theta value for each image.
[out] mle MLEStackData records the maximum likelihood estimate, RLLH, and Observed information for each data
Implements mappel::estimator::Estimator< Model >.
Definition at line 377 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_estimate(), mappel::estimator::Error, mappel::estimator::Estimator< Model >::model, mappel::estimator::MLEDataStack::Ndata, mappel::estimator::ThreadedEstimator< Model >::num_threads, mappel::estimator::MLEData::obsI, mappel::estimator::MLEDataStack::obsI, mappel::print_text_image(), mappel::estimator::ThreadedEstimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), mappel::estimator::MLEData::rllh, mappel::estimator::MLEDataStack::rllh, mappel::estimator::MLEData::theta, and mappel::estimator::MLEDataStack::theta.
template<class Model > void mappel::estimator::Estimator< Model >::estimate_profile_bounds (const ModelDataT< Model > & data, ProfileBoundsData & bounds_est) inherited
Profile likelihood bounds computations with VM algorithm
Definition at line 220 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_profile_bound(), mappel::estimator::Error, mappel::estimator::ProfileBoundsData::estimated_idxs, mappel::estimator::ProfileBoundsData::initialize_arrays(), mappel::estimator::ProfileBoundsData::mle, mappel::estimator::Estimator< Model >::model, mappel::estimator::ProfileBoundsData::Nparams_est, mappel::estimator::MLEData::obsI, mappel::print_text_image(), mappel::estimator::ProfileBoundsData::profile_lb, mappel::estimator::ProfileBoundsData::profile_points_lb, mappel::estimator::ProfileBoundsData::profile_points_lb_rllh, mappel::estimator::ProfileBoundsData::profile_points_ub, mappel::estimator::ProfileBoundsData::profile_ub, mappel::estimator::Estimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), mappel::estimator::subroutine::solve_profile_initial_step(), mappel::estimator::ProfileBoundsData::target_rllh_delta, and mappel::estimator::MLEData::theta.
Referenced by mappel::methods::error_bounds_profile_likelihood().
template<class Model > void mappel::estimator::Estimator< Model >::estimate_profile_bounds_debug (const ModelDataT< Model > & data, ProfileBoundsDebugData & bounds_est) inherited
Profile likelihood bounds computations with VM algorithm
Definition at line 258 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_profile_bound_debug(), mappel::estimator::Error, mappel::estimator::ProfileBoundsDebugData::estimated_idx, mappel::estimator::ProfileBoundsDebugData::mle, mappel::print_text_image(), mappel::estimator::Estimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), mappel::estimator::ProfileBoundsDebugData::target_rllh_delta, and mappel::estimator::MLEData::theta.
Referenced by mappel::methods::debug::error_bounds_profile_likelihood_debug().
template<class Model > void mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_parallel (const ModelDataT< Model > & data, ProfileBoundsData & bounds_est) override virtual inherited
Profile likelihood bounds computations with VM algorithm
Implements mappel::estimator::Estimator< Model >.
Definition at line 464 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_profile_bound(), mappel::estimator::Error, mappel::estimator::ProfileBoundsData::estimated_idxs, mappel::estimator::ProfileBoundsData::initialize_arrays(), mappel::estimator::ProfileBoundsData::mle, mappel::estimator::Estimator< Model >::model, mappel::estimator::ProfileBoundsData::Nparams_est, mappel::estimator::ThreadedEstimator< Model >::num_threads, mappel::estimator::MLEData::obsI, mappel::print_text_image(), mappel::estimator::ThreadedEstimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), mappel::estimator::subroutine::solve_profile_initial_step(), mappel::estimator::ProfileBoundsData::target_rllh_delta, and mappel::estimator::MLEData::theta.
Referenced by mappel::methods::openmp::error_bounds_profile_likelihood_parallel().
template<class Model > void mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_stack (const ModelDataStackT< Model > & data_stack, ProfileBoundsDataStack & bounds_est) override virtual inherited
Profile likelihood bounds computations with VM algorithm
Implements mappel::estimator::Estimator< Model >.
Definition at line 500 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_profile_bound(), mappel::estimator::Error, mappel::estimator::ProfileBoundsData::estimated_idxs, mappel::estimator::ProfileBoundsDataStack::estimated_idxs, mappel::estimator::ProfileBoundsData::initialize_arrays(), mappel::estimator::ProfileBoundsDataStack::initialize_arrays(), mappel::estimator::ProfileBoundsData::mle, mappel::estimator::ProfileBoundsDataStack::mle, mappel::estimator::Estimator< Model >::model, mappel::estimator::ProfileBoundsDataStack::Ndata, mappel::estimator::ProfileBoundsDataStack::Nparams_est, mappel::estimator::ThreadedEstimator< Model >::num_threads, mappel::estimator::MLEData::obsI, mappel::estimator::MLEDataStack::obsI, mappel::print_text_image(), mappel::estimator::ProfileBoundsData::profile_lb, mappel::estimator::ProfileBoundsDataStack::profile_lb, mappel::estimator::ProfileBoundsData::profile_points_lb, mappel::estimator::ProfileBoundsDataStack::profile_points_lb, mappel::estimator::ProfileBoundsData::profile_points_lb_rllh, mappel::estimator::ProfileBoundsDataStack::profile_points_lb_rllh, mappel::estimator::ProfileBoundsData::profile_points_ub, mappel::estimator::ProfileBoundsDataStack::profile_points_ub, mappel::estimator::ProfileBoundsData::profile_points_ub_rllh, mappel::estimator::ProfileBoundsDataStack::profile_points_ub_rllh, mappel::estimator::ProfileBoundsData::profile_ub, mappel::estimator::ProfileBoundsDataStack::profile_ub, mappel::estimator::ThreadedEstimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), mappel::estimator::MLEData::rllh, mappel::estimator::MLEDataStack::rllh, mappel::estimator::subroutine::solve_profile_initial_step(), mappel::estimator::ProfileBoundsData::target_rllh_delta, mappel::estimator::ProfileBoundsDataStack::target_rllh_delta, mappel::estimator::MLEData::theta, and mappel::estimator::MLEDataStack::theta.
Referenced by mappel::methods::openmp::error_bounds_profile_likelihood_stack().
template<class Model > double mappel::estimator::Estimator< Model >::estimate_profile_max (const ModelDataT< Model > & data, const IdxVecT & fixed_idxs, const ParamT< Model > & fixed_theta_init, StencilT< Model > & theta_max) inherited
Profile likelihood estimation methods
Definition at line 190 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_profile_estimate(), mappel::estimator::Error, mappel::print_text_image(), mappel::estimator::Estimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), and mappel::methods::objective::rllh().
template<class Model > void mappel::estimator::ThreadedEstimator< Model >::estimate_profile_max (const ModelDataT< Model > & data, const ParamVecT< Model > & fixed_theta_init, ProfileLikelihoodData & profile) override virtual inherited
Profile likelihood estimation methods
Implements mappel::estimator::Estimator< Model >.
Definition at line 418 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_profile_estimate(), mappel::estimator::Error, mappel::estimator::ProfileLikelihoodData::fixed_idxs, mappel::estimator::ProfileLikelihoodData::fixed_values, mappel::estimator::Estimator< Model >::model, mappel::estimator::ProfileLikelihoodData::Nfixed, mappel::estimator::ThreadedEstimator< Model >::num_threads, mappel::estimator::ProfileLikelihoodData::Nvalues, mappel::print_text_image(), mappel::estimator::ProfileLikelihoodData::profile_likelihood, mappel::estimator::ProfileLikelihoodData::profile_parameters, mappel::estimator::ThreadedEstimator< Model >::record_exit_code(), and mappel::estimator::Estimator< Model >::record_walltime().
template<class Model > StatsT mappel::estimator::IterativeMaximizer< Model >::get_debug_stats () virtual inherited
Run statistics.
Reimplemented from mappel::estimator::ThreadedEstimator< Model >.
Definition at line 832 of file estimator_impl.h.
References mappel::estimator::IterativeMaximizer< Model >::MaximizerData::backtrack_idxs, mappel::estimator::IterativeMaximizer< Model >::get_stats(), and mappel::estimator::IterativeMaximizer< Model >::last_backtrack_idxs.
template<class Model > IdxVecT mappel::estimator::Estimator< Model >::get_exit_counts () const inline inherited
Run statistics.
Definition at line 274 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > const Model & mappel::estimator::Estimator< Model >::get_model () inherited
Definition at line 108 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::model.
template<class Model > StatsT mappel::estimator::IterativeMaximizer< Model >::get_stats () virtual inherited
Run statistics.
Reimplemented from mappel::estimator::ThreadedEstimator< Model >.
Definition at line 811 of file estimator_impl.h.
References mappel::estimator::IterativeMaximizer< Model >::convergence_min_function_change_ratio, mappel::estimator::IterativeMaximizer< Model >::convergence_min_step_size_ratio, mappel::estimator::ThreadedEstimator< Model >::get_stats(), mappel::estimator::IterativeMaximizer< Model >::max_backtracks, mappel::estimator::IterativeMaximizer< Model >::max_iterations, mappel::estimator::ThreadedEstimator< Model >::mtx, mappel::estimator::Estimator< Model >::num_estimations, mappel::estimator::IterativeMaximizer< Model >::total_backtracks, mappel::estimator::IterativeMaximizer< Model >::total_der_evals, mappel::estimator::IterativeMaximizer< Model >::total_fun_evals, and mappel::estimator::IterativeMaximizer< Model >::total_iterations.
Referenced by mappel::methods::error_bounds_profile_likelihood(), mappel::methods::debug::error_bounds_profile_likelihood_debug(), mappel::methods::openmp::error_bounds_profile_likelihood_parallel(), mappel::methods::openmp::error_bounds_profile_likelihood_stack(), mappel::estimator::SimulatedAnnealingMaximizer< Model >::get_debug_stats(), and mappel::estimator::IterativeMaximizer< Model >::get_debug_stats().
template<class Model > int mappel::estimator::IterativeMaximizer< Model >::get_total_backtracks () const inline inherited
Definition at line 441 of file estimator.h.
template<class Model > int mappel::estimator::IterativeMaximizer< Model >::get_total_der_evals () const inline inherited
Definition at line 443 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > int mappel::estimator::IterativeMaximizer< Model >::get_total_fun_evals () const inline inherited
Definition at line 442 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > int mappel::estimator::IterativeMaximizer< Model >::get_total_iterations () const inline inherited
Definition at line 440 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::local_maximize (const ModelDataT< Model > & im, StencilT< Model > & stencil, MLEData & data) inherited
Perform a local maximization to finish off a simulated annealing run.
Definition at line 1145 of file estimator_impl.h.
References mappel::estimator::IterativeMaximizer< Model >::maximize(), mappel::estimator::Estimator< Model >::model, mappel::methods::observed_information(), mappel::estimator::MLEData::obsI, mappel::estimator::IterativeMaximizer< Model >::record_run_statistics(), mappel::estimator::MLEData::rllh, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::rllh, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::stencil(), mappel::estimator::MLEData::theta, and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::theta().
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::local_maximize (const ModelDataT< Model > & im, StencilT< Model > & stencil, MLEDebugData & debug_data) inherited
Definition at line 1158 of file estimator_impl.h.
References mappel::estimator::IterativeMaximizer< Model >::MaximizerData::get_theta_sequence(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::get_theta_sequence_rllh(), mappel::estimator::IterativeMaximizer< Model >::maximize(), mappel::estimator::Estimator< Model >::model, mappel::methods::observed_information(), mappel::estimator::MLEDebugData::obsI, mappel::estimator::IterativeMaximizer< Model >::record_run_statistics(), mappel::estimator::MLEDebugData::rllh, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::rllh, mappel::estimator::MLEDebugData::sequence, mappel::estimator::MLEDebugData::sequence_rllh, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::stencil(), mappel::estimator::MLEDebugData::theta, and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::theta().
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize (const ModelDataT< Model > & im, const IdxVecT & fixed_param_idxs, StencilT< Model > & stencil, MLEDebugData & mle) inherited
Definition at line 1173 of file estimator_impl.h.
References mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::subroutine::bound_step(), mappel::clamp(), mappel::estimator::subroutine::compute_bound_scaling_vec(), mappel::estimator::subroutine::compute_cauchy_point(), mappel::estimator::subroutine::compute_initial_trust_radius(), mappel::estimator::subroutine::compute_quadratic_model_value(), mappel::estimator::subroutine::compute_scaled_problem(), mappel::estimator::IterativeMaximizer< Model >::convergence_test_grad_ratio(), mappel::estimator::IterativeMaximizer< Model >::convergence_test_step_size(), mappel::estimator::Estimator< Model >::exit_counts, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::fixed_idxs, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::free_idxs, mappel::estimator::Estimator< Model >::get_exit_counts(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::get_theta_sequence(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::get_theta_sequence_rllh(), mappel::estimator::IterativeMaximizer< Model >::get_total_der_evals(), mappel::estimator::IterativeMaximizer< Model >::get_total_fun_evals(), mappel::estimator::IterativeMaximizer< Model >::get_total_iterations(), mappel::methods::objective::grad(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::grad, mappel::methods::objective::grad2(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::has_fixed_parameters(), mappel::methods::objective::hessian(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::im, mappel::is_positive_definite(), mappel::estimator::IterativeMaximizer< Model >::local_maximize(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), mappel::estimator::IterativeMaximizer< Model >::max_iterations, mappel::estimator::IterativeMaximizer< Model >::maximize(), mappel::estimator::MaxIter, mappel::estimator::IterativeMaximizer< Model >::min_profile_bound_residual, mappel::estimator::Estimator< Model >::model, mappel::estimator::ThreadedEstimator< Model >::mtx, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::num_fixed_parameters(), mappel::methods::observed_information(), mappel::estimator::MLEData::obsI, mappel::estimator::MLEDebugData::obsI, mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_backtrack(), mappel::estimator::ThreadedEstimator< Model >::record_exit_code(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_iteration(), mappel::estimator::IterativeMaximizer< Model >::record_run_statistics(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::restore_stencil(), mappel::estimator::MLEData::rllh, mappel::methods::objective::rllh(), mappel::estimator::MLEDebugData::rllh, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::rllh, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::s0, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::s1, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::save_stencil(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::saved_theta(), mappel::estimator::MLEDebugData::sequence, mappel::estimator::MLEDebugData::sequence_rllh, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::set_fixed_parameters(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::set_stencil(), mappel::estimator::subroutine::solve_TR_subproblem(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::stencil(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::step, mappel::estimator::MLEData::theta, mappel::estimator::MLEDebugData::theta, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::theta(), mappel::estimator::IterativeMaximizer< Model >::total_der_evals, mappel::estimator::IterativeMaximizer< Model >::total_fun_evals, mappel::estimator::IterativeMaximizer< Model >::total_iterations, and mappel::estimator::TrustRegionRadius.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > virtual void mappel::estimator::IterativeMaximizer< Model >::maximize (MaximizerData & data) protected pure virtual inherited
Referenced by mappel::estimator::IterativeMaximizer< Model >::compute_estimate(), mappel::estimator::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::estimator::IterativeMaximizer< Model >::compute_profile_estimate(), mappel::estimator::IterativeMaximizer< Model >::local_maximize(), and mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > double mappel::estimator::IterativeMaximizer< Model >::mean_backtracks () inherited
template<class Model > double mappel::estimator::IterativeMaximizer< Model >::mean_der_evals () inherited
template<class Model > double mappel::estimator::IterativeMaximizer< Model >::mean_fun_evals () inherited
template<class Model > double mappel::estimator::IterativeMaximizer< Model >::mean_iterations () inherited
template<class Model> std::string mappel::estimator::TrustRegionMaximizer< Model >::name () const inline virtual
Implements mappel::estimator::Estimator< Model >.
Definition at line 630 of file estimator.h.
template<class Model > bool mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack (MaximizerData & data, IdxT fixed_idx, double target_rllh, double old_fval, const VecT & fgrad) protected inherited
Definition at line 943 of file estimator_impl.h.
References mappel::estimator::IterativeMaximizer< Model >::backtrack_max_ratio, mappel::estimator::IterativeMaximizer< Model >::backtrack_min_linear_step_ratio, mappel::estimator::IterativeMaximizer< Model >::backtrack_min_ratio, mappel::clamp(), mappel::estimator::IterativeMaximizer< Model >::convergence_min_step_size_ratio, mappel::methods::objective::grad(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::im, mappel::estimator::IterativeMaximizer< Model >::max_backtracks, mappel::estimator::MaxBacktracks, mappel::estimator::Estimator< Model >::model, mappel::norm_sq(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_backtrack(), mappel::estimator::ThreadedEstimator< Model >::record_exit_code(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_iteration(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::restore_stencil(), mappel::methods::objective::rllh(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::rllh, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::save_stencil(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::saved_theta(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::set_stencil(), mappel::square(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::stencil(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::step, mappel::estimator::StepSize, and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::theta().
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > void mappel::estimator::ThreadedEstimator< Model >::record_exit_code (ExitCode code) override protected virtual inherited
Implements mappel::estimator::Estimator< Model >.
Definition at line 578 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::exit_counts, mappel::estimator::Estimator< Model >::model, mappel::estimator::ThreadedEstimator< Model >::mtx, mappel::methods::observed_information(), mappel::estimator::MLEData::obsI, mappel::estimator::MLEData::rllh, mappel::methods::objective::rllh(), mappel::estimator::Success, and mappel::estimator::MLEData::theta.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::IterativeMaximizer< Model >::convergence_test_grad_ratio(), mappel::estimator::IterativeMaximizer< Model >::convergence_test_step_size(), mappel::estimator::ThreadedEstimator< Model >::estimate_max_stack(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_parallel(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_stack(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_max(), mappel::estimator::HeuristicEstimator< Model >::get_debug_stats(), mappel::estimator::CGaussMLE< Model >::get_debug_stats(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack().
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::record_run_statistics (const MaximizerData & data) protected inherited
Definition at line 859 of file estimator_impl.h.
References mappel::estimator::IterativeMaximizer< Model >::MaximizerData::get_backtrack_idxs(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::has_theta_sequence(), mappel::estimator::IterativeMaximizer< Model >::last_backtrack_idxs, mappel::estimator::ThreadedEstimator< Model >::mtx, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::nBacktracks, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::nIterations, mappel::estimator::IterativeMaximizer< Model >::total_backtracks, mappel::estimator::IterativeMaximizer< Model >::total_der_evals, mappel::estimator::IterativeMaximizer< Model >::total_fun_evals, and mappel::estimator::IterativeMaximizer< Model >::total_iterations.
Referenced by mappel::estimator::IterativeMaximizer< Model >::compute_estimate(), mappel::estimator::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::estimator::IterativeMaximizer< Model >::compute_profile_bound(), mappel::estimator::IterativeMaximizer< Model >::compute_profile_bound_debug(), mappel::estimator::IterativeMaximizer< Model >::compute_profile_estimate(), mappel::estimator::IterativeMaximizer< Model >::local_maximize(), and mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > void mappel::estimator::Estimator< Model >::record_walltime (ClockT::time_point start_walltime, int num_estimations) protected inherited
Definition at line 360 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::num_estimations, and mappel::estimator::Estimator< Model >::total_walltime.
Referenced by mappel::estimator::Estimator< Model >::estimate_max(), mappel::estimator::Estimator< Model >::estimate_max_debug(), mappel::estimator::ThreadedEstimator< Model >::estimate_max_stack(), mappel::estimator::Estimator< Model >::estimate_profile_bounds(), mappel::estimator::Estimator< Model >::estimate_profile_bounds_debug(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_parallel(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_stack(), mappel::estimator::Estimator< Model >::estimate_profile_max(), and mappel::estimator::ThreadedEstimator< Model >::estimate_profile_max().
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::solve_profile_bound (MaximizerData & data, MLEData & mle, double llh_delta, IdxT fixed_idx, IdxT which_bound) protected virtual inherited
Definition at line 1137 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::name().
Referenced by mappel::estimator::IterativeMaximizer< Model >::compute_profile_bound(), and mappel::estimator::IterativeMaximizer< Model >::compute_profile_bound_debug().
Member Data Documentation
template<class Model > const double mappel::estimator::IterativeMaximizer< Model >::backtrack_max_ratio = 0.50 static protected inherited
Definition at line 460 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack().
template<class Model > const double mappel::estimator::IterativeMaximizer< Model >::backtrack_min_linear_step_ratio = 1e-3 static protected inherited
Definition at line 461 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), and mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack().
template<class Model > const double mappel::estimator::IterativeMaximizer< Model >::backtrack_min_ratio = 0.05 static protected inherited
Definition at line 459 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack().
template<class Model > const double mappel::estimator::IterativeMaximizer< Model >::convergence_min_function_change_ratio = 1.0e-9 static protected inherited
Convergence criteria: tolerance for function-value change.
Definition at line 456 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::convergence_test_grad_ratio(), and mappel::estimator::IterativeMaximizer< Model >::get_stats().
template<class Model > const double mappel::estimator::IterativeMaximizer< Model >::convergence_min_step_size_ratio = 1.0e-9 static protected inherited
Convergence criteria: tolerance of relative step size.
Definition at line 457 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::IterativeMaximizer< Model >::convergence_test_step_size(), mappel::estimator::IterativeMaximizer< Model >::get_stats(), and mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack().
template<class Model> const double mappel::estimator::TrustRegionMaximizer< Model >::convergence_min_trust_radius = 1.0e-8 static
Convergence criteria: Minimum trust region radius.
Definition at line 625 of file estimator.h.
template<class Model > const int mappel::estimator::IterativeMaximizer< Model >::DefaultIterations =100 static inherited
Definition at line 428 of file estimator.h.
template<class Model > IdxVecT mappel::estimator::Estimator< Model >::exit_counts protected inherited
Definition at line 299 of file estimator.h.
Referenced by mappel::estimator::Estimator< Model >::clear_stats(), mappel::estimator::Estimator< Model >::get_stats(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::ThreadedEstimator< Model >::record_exit_code().
template<class Model > IdxVecT mappel::estimator::IterativeMaximizer< Model >::last_backtrack_idxs protected inherited
Debugging: Stores last set of backtrack_idxs when data.save_seq==true.
Definition at line 475 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::get_debug_stats(), and mappel::estimator::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > const int mappel::estimator::IterativeMaximizer< Model >::max_backtracks = 8 static protected inherited
Definition at line 462 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::IterativeMaximizer< Model >::get_stats(), and mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack().
template<class Model > int mappel::estimator::IterativeMaximizer< Model >::max_iterations protected inherited
Definition at line 466 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::get_stats(), and mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > int mappel::estimator::ThreadedEstimator< Model >::max_threads protected inherited
Definition at line 324 of file estimator.h.
template<class Model > const double mappel::estimator::IterativeMaximizer< Model >::min_eigenvalue_correction_delta = 1e-3 static protected inherited
Ensure the minimum eigenvalue is at least this big when correcting indefinite matrix.
Definition at line 454 of file estimator.h.
template<class Model > const double mappel::estimator::IterativeMaximizer< Model >::min_profile_bound_residual = 1e-4 static protected inherited
Minimum residual in quadratic solutions of equation (8) to accept. Revert to newton step.
Definition at line 464 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > const Model& mappel::estimator::Estimator< Model >::model protected inherited
Definition at line 294 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::IterativeMaximizer< Model >::compute_estimate(), mappel::estimator::Estimator< Model >::compute_estimate_debug(), mappel::estimator::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::estimator::Estimator< Model >::compute_profile_bound(), mappel::estimator::IterativeMaximizer< Model >::compute_profile_bound(), mappel::estimator::Estimator< Model >::compute_profile_bound_debug(), mappel::estimator::IterativeMaximizer< Model >::compute_profile_bound_debug(), mappel::estimator::Estimator< Model >::compute_profile_estimate(), mappel::estimator::IterativeMaximizer< Model >::compute_profile_estimate(), mappel::estimator::Estimator< Model >::estimate_max(), mappel::estimator::Estimator< Model >::estimate_max_stack(), mappel::estimator::ThreadedEstimator< Model >::estimate_max_stack(), mappel::estimator::Estimator< Model >::estimate_profile_bounds(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_parallel(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_stack(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_max(), mappel::estimator::HeuristicEstimator< Model >::get_debug_stats(), mappel::estimator::CGaussMLE< Model >::get_debug_stats(), mappel::estimator::Estimator< Model >::get_model(), mappel::estimator::IterativeMaximizer< Model >::local_maximize(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack(), and mappel::estimator::ThreadedEstimator< Model >::record_exit_code().
template<class Model > std::mutex mappel::estimator::ThreadedEstimator< Model >::mtx protected inherited
Definition at line 326 of file estimator.h.
Referenced by mappel::estimator::ThreadedEstimator< Model >::clear_stats(), mappel::estimator::IterativeMaximizer< Model >::clear_stats(), mappel::estimator::ThreadedEstimator< Model >::get_stats(), mappel::estimator::HeuristicEstimator< Model >::get_stats(), mappel::estimator::CGaussHeuristicEstimator< Model >::get_stats(), mappel::estimator::CGaussMLE< Model >::get_stats(), mappel::estimator::SimulatedAnnealingMaximizer< Model >::get_stats(), mappel::estimator::IterativeMaximizer< Model >::get_stats(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), mappel::estimator::ThreadedEstimator< Model >::record_exit_code(), and mappel::estimator::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::estimator::Estimator< Model >::num_estimations = 0 protected inherited
Definition at line 297 of file estimator.h.
Referenced by mappel::estimator::Estimator< Model >::clear_stats(), mappel::estimator::Estimator< Model >::get_stats(), mappel::estimator::ThreadedEstimator< Model >::get_stats(), mappel::estimator::HeuristicEstimator< Model >::get_stats(), mappel::estimator::CGaussHeuristicEstimator< Model >::get_stats(), mappel::estimator::CGaussMLE< Model >::get_stats(), mappel::estimator::SimulatedAnnealingMaximizer< Model >::get_stats(), mappel::estimator::IterativeMaximizer< Model >::get_stats(), and mappel::estimator::Estimator< Model >::record_walltime().
template<class Model > int mappel::estimator::ThreadedEstimator< Model >::num_threads protected inherited
Definition at line 325 of file estimator.h.
Referenced by mappel::estimator::ThreadedEstimator< Model >::clear_stats(), mappel::estimator::ThreadedEstimator< Model >::estimate_max_stack(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_parallel(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_stack(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_max(), and mappel::estimator::ThreadedEstimator< Model >::get_stats().
template<class Model> const double mappel::estimator::TrustRegionMaximizer< Model >::rho_cauchy_min = 0.1 static
Minimum acceptable rho for cauchy point: Coleman beta / Bellavia beta_1.
Definition at line 619 of file estimator.h.
template<class Model> const double mappel::estimator::TrustRegionMaximizer< Model >::rho_obj_min = 0.25 static
Minimum acceptable rho: Coleman mu / Bellavia beta_2.
Definition at line 620 of file estimator.h.
template<class Model> const double mappel::estimator::TrustRegionMaximizer< Model >::rho_obj_opt = 0.75 static
Optimal step rho: Coleman eta / Bellavia beta_2.
Definition at line 621 of file estimator.h.
template<class Model > int mappel::estimator::IterativeMaximizer< Model >::total_backtracks = 0 protected inherited
Definition at line 470 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::clear_stats(), mappel::estimator::IterativeMaximizer< Model >::get_stats(), and mappel::estimator::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::estimator::IterativeMaximizer< Model >::total_der_evals = 0 protected inherited
Definition at line 472 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::clear_stats(), mappel::estimator::SimulatedAnnealingMaximizer< Model >::get_stats(), mappel::estimator::IterativeMaximizer< Model >::get_stats(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::estimator::IterativeMaximizer< Model >::total_fun_evals = 0 protected inherited
Definition at line 471 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::clear_stats(), mappel::estimator::SimulatedAnnealingMaximizer< Model >::get_stats(), mappel::estimator::IterativeMaximizer< Model >::get_stats(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::estimator::IterativeMaximizer< Model >::total_iterations = 0 protected inherited
Definition at line 469 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::clear_stats(), mappel::estimator::SimulatedAnnealingMaximizer< Model >::get_stats(), mappel::estimator::IterativeMaximizer< Model >::get_stats(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > double mappel::estimator::Estimator< Model >::total_walltime = 0. protected inherited
Definition at line 298 of file estimator.h.
Referenced by mappel::estimator::Estimator< Model >::clear_stats(), mappel::estimator::Estimator< Model >::get_stats(), mappel::estimator::ThreadedEstimator< Model >::get_stats(), and mappel::estimator::Estimator< Model >::record_walltime().
template<class Model> const double mappel::estimator::TrustRegionMaximizer< Model >::trust_radius_decrease = 0.25 static
Trust radius decrease ratio to step size: Coleman gamma_1 / Bellavia alpha_2.
Definition at line 623 of file estimator.h.
template<class Model> const double mappel::estimator::TrustRegionMaximizer< Model >::trust_radius_decrease_min = 0.125 static
Smallest alowable trust radius decrease ratio: Coleman gamma_0 / Bellavia alpha_1.
Definition at line 622 of file estimator.h.
template<class Model> const double mappel::estimator::TrustRegionMaximizer< Model >::trust_radius_increase = 2 static
Trust radius increase ratio: Coleman gamma_2 / Bellavia alpha_3.
Definition at line 624 of file estimator.h.
The documentation for this class was generated from the following files:
estimator.h
estimator_impl.h