Mappel: mappel::estimator::CGaussMLE< Model > Class Template Reference
mappel::estimator::CGaussMLE< Model > Class Template Reference
#include </home/travis/build/markjolah/Mappel/include/Mappel/estimator.h>
Public Member Functions
CGaussMLE (const Model &model, int num_iterations=DefaultIterations)
StatsT get_stats ()
StatsT get_debug_stats ()
std::string name () const
void estimate_max_stack (const ModelDataStackT< Model > &data, const ParamVecT< Model > &theta_init_stack, MLEDataStack &mle_data_stack) override
void estimate_profile_max (const ModelDataT< Model > &data, const ParamVecT< Model > &theta_init, ProfileLikelihoodData &profile) override
void estimate_profile_bounds_parallel (const ModelDataT< Model > &data, ProfileBoundsData &bounds_est) override
void estimate_profile_bounds_stack (const ModelDataStackT< Model > &data, ProfileBoundsDataStack &bounds_est_stack) override
void clear_stats ()
const Model & get_model ()
void estimate_max_stack (const ModelDataStackT< Model > &data_stack, MLEDataStack &mle_data_stack)
void estimate_max (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, MLEData &mle_data, StencilT< Model > &mle_stencil)
void estimate_max (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, MLEData &mle_data)
void estimate_max (const ModelDataT< Model > &data, MLEData &mle_data)
void estimate_max_debug (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, MLEDebugData &mle_data, StencilT< Model > &mle_stencil)
void estimate_max_debug (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, MLEDebugData &mle_data)
double estimate_profile_max (const ModelDataT< Model > &data, const IdxVecT &fixed_idxs, const ParamT< Model > &fixed_theta_init, StencilT< Model > &theta_max)
void estimate_profile_bounds (const ModelDataT< Model > &data, ProfileBoundsData &bounds_est)
void estimate_profile_bounds_debug (const ModelDataT< Model > &data, ProfileBoundsDebugData &bounds_est)
IdxVecT get_exit_counts () const
Static Public Attributes
static const int DefaultIterations =50
Protected Member Functions
void record_exit_code (ExitCode code) override
virtual double compute_profile_estimate (const ModelDataT< Model > &data, const ParamT< Model > &theta_init, const IdxVecT &fixed_idxs, StencilT< Model > &max_stencil)
virtual void compute_profile_bound (const ModelDataT< Model > &data, ProfileBoundsData &est, const VecT &init_step, IdxT param_idx, IdxT which_bound)
virtual void compute_profile_bound_debug (const ModelDataT< Model > &data, ProfileBoundsDebugData &est)
void record_walltime (ClockT::time_point start_walltime, int num_estimations)
Protected Attributes
int max_threads
int num_threads
std::mutex mtx
const Model & model
int num_estimations = 0
double total_walltime = 0.
IdxVecT exit_counts
Detailed Description
template<class Model>
class mappel::estimator::CGaussMLE< Model >
Definition at line 361 of file estimator.h.
Constructor & Destructor Documentation
template<class Model > mappel::estimator::CGaussMLE< Model >::CGaussMLE (const Model & model, int num_iterations = DefaultIterations) inline
Definition at line 366 of file estimator.h.
Member Function Documentation
template<class Model > void mappel::estimator::ThreadedEstimator< Model >::clear_stats () virtual inherited
Run statistics.
Reimplemented from mappel::estimator::Estimator< Model >.
Reimplemented in mappel::estimator::IterativeMaximizer< Model >.
Definition at line 570 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::clear_stats(), mappel::estimator::ThreadedEstimator< Model >::mtx, and mappel::estimator::ThreadedEstimator< Model >::num_threads.
Referenced by mappel::estimator::IterativeMaximizer< Model >::clear_stats().
template<class Model > void mappel::estimator::Estimator< Model >::compute_profile_bound (const ModelDataT< Model > & data, ProfileBoundsData & est, const VecT & init_step, IdxT param_idx, IdxT which_bound) protected virtual inherited
Reimplemented in mappel::estimator::IterativeMaximizer< Model >.
Definition at line 309 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::model.
Referenced by mappel::estimator::Estimator< Model >::estimate_profile_bounds(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_parallel(), and mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_stack().
template<class Model > void mappel::estimator::Estimator< Model >::compute_profile_bound_debug (const ModelDataT< Model > & data, ProfileBoundsDebugData & est) protected virtual inherited
Reimplemented in mappel::estimator::IterativeMaximizer< Model >.
Definition at line 318 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::model.
Referenced by mappel::estimator::Estimator< Model >::estimate_profile_bounds_debug().
template<class Model > double mappel::estimator::Estimator< Model >::compute_profile_estimate (const ModelDataT< Model > & data, const ParamT< Model > & theta_init, const IdxVecT & fixed_idxs, StencilT< Model > & max_stencil) protected virtual inherited
Reimplemented in mappel::estimator::IterativeMaximizer< Model >.
Definition at line 300 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::model.
Referenced by mappel::estimator::Estimator< Model >::estimate_profile_max(), and mappel::estimator::ThreadedEstimator< Model >::estimate_profile_max().
template<class Model > void mappel::estimator::Estimator< Model >::estimate_max (const ModelDataT< Model > & data, const ParamT< Model > & theta_init, MLEData & mle_data, StencilT< Model > & mle_stencil) inherited
Maximum likelihood point estimators Estimate for a single data starting at theta_init, fill in the MLEData struct with the estimated parameter, RLLH, and observed information. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
The stencil at the MLE is also returned but can be ignored if not needed as it is available at no extra cost.
Parameters
[in] data Model data to estimate for
[in] theta_init [Optional] Initial theta value.
[out] mle_data MLEData recording the maximum likelihood estimate and relevant data.
[out] stencil [Optional] StencilT at the MLE value.
Definition at line 128 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_estimate(), mappel::estimator::Error, mappel::estimator::MLEData::obsI, mappel::print_text_image(), mappel::estimator::Estimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), mappel::estimator::MLEData::rllh, and mappel::estimator::MLEData::theta.
Referenced by mappel::estimator::Estimator< Model >::estimate_max().
template<class Model > void mappel::estimator::Estimator< Model >::estimate_max (const ModelDataT< Model > & data, const ParamT< Model > & theta_init, MLEData & mle_data) inherited
Maximum likelihood point estimators Estimate for a single data starting at theta_init, fill in the MLEData struct with the estimated parameter, RLLH, and observed information. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
The stencil at the MLE is also returned but can be ignored if not needed as it is available at no extra cost.
Parameters
[in] data Model data to estimate for
[in] theta_init [Optional] Initial theta value.
[out] mle_data MLEData recording the maximum likelihood estimate and relevant data.
[out] stencil [Optional] StencilT at the MLE value.
Definition at line 121 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::estimate_max().
template<class Model > void mappel::estimator::Estimator< Model >::estimate_max (const ModelDataT< Model > & data, MLEData & mle_data) inherited
Maximum likelihood point estimators Estimate for a single data starting at theta_init, fill in the MLEData struct with the estimated parameter, RLLH, and observed information. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
The stencil at the MLE is also returned but can be ignored if not needed as it is available at no extra cost.
Parameters
[in] data Model data to estimate for
[in] theta_init [Optional] Initial theta value.
[out] mle_data MLEData recording the maximum likelihood estimate and relevant data.
[out] stencil [Optional] StencilT at the MLE value.
Definition at line 112 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::estimate_max(), and mappel::estimator::Estimator< Model >::model.
template<class Model > void mappel::estimator::Estimator< Model >::estimate_max_debug (const ModelDataT< Model > & data, const ParamT< Model > & theta_init, MLEDebugData & mle_data, StencilT< Model > & mle_stencil) inherited
Debug estimation for a single data starting at theta_init, fill in the MLEDebugData struct with data including the sequence of evaluated points. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
The sequence and sequence_rllh parameters of the MLEDebugData struct record the entire sequence of evaluated points including theta_init and theta_mle, which should be first and last respectively.
The stencil at the MLE is also returned but can be ignored if not needed as it is available at no extra cost.
Parameters
[in] data Model data to estimate for
[in] theta_init Initial theta value.
[out] mle_data MLEDebugData recording the maximum likelihood estimate and relevant data.
[out] stencil [Optional] StencilT at the MLE value.
template<class Model > void mappel::estimator::Estimator< Model >::estimate_max_debug (const ModelDataT< Model > & data, const ParamT< Model > & theta_init, MLEDebugData & mle_data) inherited
Maximum likelihood point estimators Estimate for a single data starting at theta_init, fill in the MLEData struct with the estimated parameter, RLLH, and observed information. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
The stencil at the MLE is also returned but can be ignored if not needed as it is available at no extra cost.
Parameters
[in] data Model data to estimate for
[in] theta_init [Optional] Initial theta value.
[out] mle_data MLEData recording the maximum likelihood estimate and relevant data.
[out] stencil [Optional] StencilT at the MLE value.
Definition at line 157 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_estimate_debug(), mappel::estimator::Error, mappel::estimator::MLEDebugData::obsI, mappel::print_text_image(), mappel::estimator::Estimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), mappel::estimator::MLEDebugData::rllh, and mappel::estimator::MLEDebugData::theta.
template<class Model > void mappel::estimator::Estimator< Model >::estimate_max_stack (const ModelDataStackT< Model > & data_stack, MLEDataStack & mle_data_stack) inherited
Maximum likelihood point estimators Estimate for a single data starting at theta_init, fill in the MLEData struct with the estimated parameter, RLLH, and observed information. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
The stencil at the MLE is also returned but can be ignored if not needed as it is available at no extra cost.
Parameters
[in] data Model data to estimate for
[in] theta_init [Optional] Initial theta value.
[out] mle_data MLEData recording the maximum likelihood estimate and relevant data.
[out] stencil [Optional] StencilT at the MLE value.
Definition at line 183 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::estimate_max_stack(), and mappel::estimator::Estimator< Model >::model.
template<class Model > void mappel::estimator::ThreadedEstimator< Model >::estimate_max_stack (const ModelDataStackT< Model > & data_stack, const ParamVecT< Model > & theta_init_stack, MLEDataStack & mle_data_stack) override virtual inherited
Estimate for a stack of data and fill in the MLEDataStack struct with the estimated parameter, RLLH, and observed information for each data in parallel. Estimation is initialized with theta_init, theta_init is empty, it is estimated with the Heuristic estimator. If any individual parameters are infinite or are not in the interior of the feasible region, they will be estimated with the Heuristic method. Valid parameters of theta_init will not be modified in the initialization process.
Parameters
[in] data Model data to estimate for
[in] theta_init [optional] Initial theta value for each image.
[out] mle MLEStackData records the maximum likelihood estimate, RLLH, and Observed information for each data
Implements mappel::estimator::Estimator< Model >.
Definition at line 377 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_estimate(), mappel::estimator::Error, mappel::estimator::Estimator< Model >::model, mappel::estimator::MLEDataStack::Ndata, mappel::estimator::ThreadedEstimator< Model >::num_threads, mappel::estimator::MLEData::obsI, mappel::estimator::MLEDataStack::obsI, mappel::print_text_image(), mappel::estimator::ThreadedEstimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), mappel::estimator::MLEData::rllh, mappel::estimator::MLEDataStack::rllh, mappel::estimator::MLEData::theta, and mappel::estimator::MLEDataStack::theta.
template<class Model > void mappel::estimator::Estimator< Model >::estimate_profile_bounds (const ModelDataT< Model > & data, ProfileBoundsData & bounds_est) inherited
Profile likelihood bounds computations with VM algorithm
Definition at line 220 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_profile_bound(), mappel::estimator::Error, mappel::estimator::ProfileBoundsData::estimated_idxs, mappel::estimator::ProfileBoundsData::initialize_arrays(), mappel::estimator::ProfileBoundsData::mle, mappel::estimator::Estimator< Model >::model, mappel::estimator::ProfileBoundsData::Nparams_est, mappel::estimator::MLEData::obsI, mappel::print_text_image(), mappel::estimator::ProfileBoundsData::profile_lb, mappel::estimator::ProfileBoundsData::profile_points_lb, mappel::estimator::ProfileBoundsData::profile_points_lb_rllh, mappel::estimator::ProfileBoundsData::profile_points_ub, mappel::estimator::ProfileBoundsData::profile_ub, mappel::estimator::Estimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), mappel::estimator::subroutine::solve_profile_initial_step(), mappel::estimator::ProfileBoundsData::target_rllh_delta, and mappel::estimator::MLEData::theta.
Referenced by mappel::methods::error_bounds_profile_likelihood().
template<class Model > void mappel::estimator::Estimator< Model >::estimate_profile_bounds_debug (const ModelDataT< Model > & data, ProfileBoundsDebugData & bounds_est) inherited
Profile likelihood bounds computations with VM algorithm
Definition at line 258 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_profile_bound_debug(), mappel::estimator::Error, mappel::estimator::ProfileBoundsDebugData::estimated_idx, mappel::estimator::ProfileBoundsDebugData::mle, mappel::print_text_image(), mappel::estimator::Estimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), mappel::estimator::ProfileBoundsDebugData::target_rllh_delta, and mappel::estimator::MLEData::theta.
Referenced by mappel::methods::debug::error_bounds_profile_likelihood_debug().
template<class Model > void mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_parallel (const ModelDataT< Model > & data, ProfileBoundsData & bounds_est) override virtual inherited
Profile likelihood bounds computations with VM algorithm
Implements mappel::estimator::Estimator< Model >.
Definition at line 464 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_profile_bound(), mappel::estimator::Error, mappel::estimator::ProfileBoundsData::estimated_idxs, mappel::estimator::ProfileBoundsData::initialize_arrays(), mappel::estimator::ProfileBoundsData::mle, mappel::estimator::Estimator< Model >::model, mappel::estimator::ProfileBoundsData::Nparams_est, mappel::estimator::ThreadedEstimator< Model >::num_threads, mappel::estimator::MLEData::obsI, mappel::print_text_image(), mappel::estimator::ThreadedEstimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), mappel::estimator::subroutine::solve_profile_initial_step(), mappel::estimator::ProfileBoundsData::target_rllh_delta, and mappel::estimator::MLEData::theta.
Referenced by mappel::methods::openmp::error_bounds_profile_likelihood_parallel().
template<class Model > void mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_stack (const ModelDataStackT< Model > & data_stack, ProfileBoundsDataStack & bounds_est) override virtual inherited
Profile likelihood bounds computations with VM algorithm
Implements mappel::estimator::Estimator< Model >.
Definition at line 500 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_profile_bound(), mappel::estimator::Error, mappel::estimator::ProfileBoundsData::estimated_idxs, mappel::estimator::ProfileBoundsDataStack::estimated_idxs, mappel::estimator::ProfileBoundsData::initialize_arrays(), mappel::estimator::ProfileBoundsDataStack::initialize_arrays(), mappel::estimator::ProfileBoundsData::mle, mappel::estimator::ProfileBoundsDataStack::mle, mappel::estimator::Estimator< Model >::model, mappel::estimator::ProfileBoundsDataStack::Ndata, mappel::estimator::ProfileBoundsDataStack::Nparams_est, mappel::estimator::ThreadedEstimator< Model >::num_threads, mappel::estimator::MLEData::obsI, mappel::estimator::MLEDataStack::obsI, mappel::print_text_image(), mappel::estimator::ProfileBoundsData::profile_lb, mappel::estimator::ProfileBoundsDataStack::profile_lb, mappel::estimator::ProfileBoundsData::profile_points_lb, mappel::estimator::ProfileBoundsDataStack::profile_points_lb, mappel::estimator::ProfileBoundsData::profile_points_lb_rllh, mappel::estimator::ProfileBoundsDataStack::profile_points_lb_rllh, mappel::estimator::ProfileBoundsData::profile_points_ub, mappel::estimator::ProfileBoundsDataStack::profile_points_ub, mappel::estimator::ProfileBoundsData::profile_points_ub_rllh, mappel::estimator::ProfileBoundsDataStack::profile_points_ub_rllh, mappel::estimator::ProfileBoundsData::profile_ub, mappel::estimator::ProfileBoundsDataStack::profile_ub, mappel::estimator::ThreadedEstimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), mappel::estimator::MLEData::rllh, mappel::estimator::MLEDataStack::rllh, mappel::estimator::subroutine::solve_profile_initial_step(), mappel::estimator::ProfileBoundsData::target_rllh_delta, mappel::estimator::ProfileBoundsDataStack::target_rllh_delta, mappel::estimator::MLEData::theta, and mappel::estimator::MLEDataStack::theta.
Referenced by mappel::methods::openmp::error_bounds_profile_likelihood_stack().
template<class Model > double mappel::estimator::Estimator< Model >::estimate_profile_max (const ModelDataT< Model > & data, const IdxVecT & fixed_idxs, const ParamT< Model > & fixed_theta_init, StencilT< Model > & theta_max) inherited
Profile likelihood estimation methods
Definition at line 190 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_profile_estimate(), mappel::estimator::Error, mappel::print_text_image(), mappel::estimator::Estimator< Model >::record_exit_code(), mappel::estimator::Estimator< Model >::record_walltime(), and mappel::methods::objective::rllh().
template<class Model > void mappel::estimator::ThreadedEstimator< Model >::estimate_profile_max (const ModelDataT< Model > & data, const ParamVecT< Model > & fixed_theta_init, ProfileLikelihoodData & profile) override virtual inherited
Profile likelihood estimation methods
Implements mappel::estimator::Estimator< Model >.
Definition at line 418 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::compute_profile_estimate(), mappel::estimator::Error, mappel::estimator::ProfileLikelihoodData::fixed_idxs, mappel::estimator::ProfileLikelihoodData::fixed_values, mappel::estimator::Estimator< Model >::model, mappel::estimator::ProfileLikelihoodData::Nfixed, mappel::estimator::ThreadedEstimator< Model >::num_threads, mappel::estimator::ProfileLikelihoodData::Nvalues, mappel::print_text_image(), mappel::estimator::ProfileLikelihoodData::profile_likelihood, mappel::estimator::ProfileLikelihoodData::profile_parameters, mappel::estimator::ThreadedEstimator< Model >::record_exit_code(), and mappel::estimator::Estimator< Model >::record_walltime().
template<class Model > StatsT mappel::estimator::CGaussMLE< Model >::get_debug_stats () virtual
Run statistics.
Reimplemented from mappel::estimator::ThreadedEstimator< Model >.
Definition at line 675 of file estimator_impl.h.
References mappel::cgauss_compute_estimate(), mappel::cgauss_compute_estimate_debug(), mappel::cgauss_heuristic_compute_estimate(), mappel::estimator::Error, mappel::estimator::ThreadedEstimator< Model >::get_stats(), mappel::estimator::Estimator< Model >::model, mappel::methods::observed_information(), mappel::estimator::MLEData::obsI, mappel::estimator::MLEDebugData::obsI, mappel::estimator::ThreadedEstimator< Model >::record_exit_code(), mappel::estimator::MLEData::rllh, mappel::methods::objective::rllh(), mappel::estimator::MLEDebugData::rllh, mappel::methods::objective::openmp::rllh_stack(), mappel::estimator::MLEDebugData::sequence, mappel::estimator::MLEDebugData::sequence_rllh, mappel::estimator::Success, mappel::estimator::MLEData::theta, and mappel::estimator::MLEDebugData::theta.
template<class Model > IdxVecT mappel::estimator::Estimator< Model >::get_exit_counts () const inline inherited
Run statistics.
Definition at line 274 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > const Model & mappel::estimator::Estimator< Model >::get_model () inherited
Definition at line 108 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::model.
template<class Model > StatsT mappel::estimator::CGaussMLE< Model >::get_stats () virtual
Run statistics.
Reimplemented from mappel::estimator::ThreadedEstimator< Model >.
Definition at line 660 of file estimator_impl.h.
References mappel::estimator::ThreadedEstimator< Model >::get_stats(), mappel::estimator::ThreadedEstimator< Model >::mtx, and mappel::estimator::Estimator< Model >::num_estimations.
template<class Model > std::string mappel::estimator::CGaussMLE< Model >::name () const inline virtual
Implements mappel::estimator::Estimator< Model >.
Definition at line 371 of file estimator.h.
template<class Model > void mappel::estimator::ThreadedEstimator< Model >::record_exit_code (ExitCode code) override protected virtual inherited
Implements mappel::estimator::Estimator< Model >.
Definition at line 578 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::exit_counts, mappel::estimator::Estimator< Model >::model, mappel::estimator::ThreadedEstimator< Model >::mtx, mappel::methods::observed_information(), mappel::estimator::MLEData::obsI, mappel::estimator::MLEData::rllh, mappel::methods::objective::rllh(), mappel::estimator::Success, and mappel::estimator::MLEData::theta.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::IterativeMaximizer< Model >::convergence_test_grad_ratio(), mappel::estimator::IterativeMaximizer< Model >::convergence_test_step_size(), mappel::estimator::ThreadedEstimator< Model >::estimate_max_stack(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_parallel(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_stack(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_max(), mappel::estimator::HeuristicEstimator< Model >::get_debug_stats(), mappel::estimator::CGaussMLE< Model >::get_debug_stats(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack().
template<class Model > void mappel::estimator::Estimator< Model >::record_walltime (ClockT::time_point start_walltime, int num_estimations) protected inherited
Definition at line 360 of file estimator_impl.h.
References mappel::estimator::Estimator< Model >::num_estimations, and mappel::estimator::Estimator< Model >::total_walltime.
Referenced by mappel::estimator::Estimator< Model >::estimate_max(), mappel::estimator::Estimator< Model >::estimate_max_debug(), mappel::estimator::ThreadedEstimator< Model >::estimate_max_stack(), mappel::estimator::Estimator< Model >::estimate_profile_bounds(), mappel::estimator::Estimator< Model >::estimate_profile_bounds_debug(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_parallel(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_stack(), mappel::estimator::Estimator< Model >::estimate_profile_max(), and mappel::estimator::ThreadedEstimator< Model >::estimate_profile_max().
Member Data Documentation
template<class Model > const int mappel::estimator::CGaussMLE< Model >::DefaultIterations =50 static
Definition at line 364 of file estimator.h.
template<class Model > IdxVecT mappel::estimator::Estimator< Model >::exit_counts protected inherited
Definition at line 299 of file estimator.h.
Referenced by mappel::estimator::Estimator< Model >::clear_stats(), mappel::estimator::Estimator< Model >::get_stats(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::ThreadedEstimator< Model >::record_exit_code().
template<class Model > int mappel::estimator::ThreadedEstimator< Model >::max_threads protected inherited
Definition at line 324 of file estimator.h.
template<class Model > const Model& mappel::estimator::Estimator< Model >::model protected inherited
Definition at line 294 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::IterativeMaximizer< Model >::compute_estimate(), mappel::estimator::Estimator< Model >::compute_estimate_debug(), mappel::estimator::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::estimator::Estimator< Model >::compute_profile_bound(), mappel::estimator::IterativeMaximizer< Model >::compute_profile_bound(), mappel::estimator::Estimator< Model >::compute_profile_bound_debug(), mappel::estimator::IterativeMaximizer< Model >::compute_profile_bound_debug(), mappel::estimator::Estimator< Model >::compute_profile_estimate(), mappel::estimator::IterativeMaximizer< Model >::compute_profile_estimate(), mappel::estimator::Estimator< Model >::estimate_max(), mappel::estimator::Estimator< Model >::estimate_max_stack(), mappel::estimator::ThreadedEstimator< Model >::estimate_max_stack(), mappel::estimator::Estimator< Model >::estimate_profile_bounds(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_parallel(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_stack(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_max(), mappel::estimator::HeuristicEstimator< Model >::get_debug_stats(), mappel::estimator::CGaussMLE< Model >::get_debug_stats(), mappel::estimator::Estimator< Model >::get_model(), mappel::estimator::IterativeMaximizer< Model >::local_maximize(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack(), and mappel::estimator::ThreadedEstimator< Model >::record_exit_code().
template<class Model > std::mutex mappel::estimator::ThreadedEstimator< Model >::mtx protected inherited
Definition at line 326 of file estimator.h.
Referenced by mappel::estimator::ThreadedEstimator< Model >::clear_stats(), mappel::estimator::IterativeMaximizer< Model >::clear_stats(), mappel::estimator::ThreadedEstimator< Model >::get_stats(), mappel::estimator::HeuristicEstimator< Model >::get_stats(), mappel::estimator::CGaussHeuristicEstimator< Model >::get_stats(), mappel::estimator::CGaussMLE< Model >::get_stats(), mappel::estimator::SimulatedAnnealingMaximizer< Model >::get_stats(), mappel::estimator::IterativeMaximizer< Model >::get_stats(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), mappel::estimator::ThreadedEstimator< Model >::record_exit_code(), and mappel::estimator::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::estimator::Estimator< Model >::num_estimations = 0 protected inherited
Definition at line 297 of file estimator.h.
Referenced by mappel::estimator::Estimator< Model >::clear_stats(), mappel::estimator::Estimator< Model >::get_stats(), mappel::estimator::ThreadedEstimator< Model >::get_stats(), mappel::estimator::HeuristicEstimator< Model >::get_stats(), mappel::estimator::CGaussHeuristicEstimator< Model >::get_stats(), mappel::estimator::CGaussMLE< Model >::get_stats(), mappel::estimator::SimulatedAnnealingMaximizer< Model >::get_stats(), mappel::estimator::IterativeMaximizer< Model >::get_stats(), and mappel::estimator::Estimator< Model >::record_walltime().
template<class Model > int mappel::estimator::ThreadedEstimator< Model >::num_threads protected inherited
Definition at line 325 of file estimator.h.
Referenced by mappel::estimator::ThreadedEstimator< Model >::clear_stats(), mappel::estimator::ThreadedEstimator< Model >::estimate_max_stack(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_parallel(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_stack(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_max(), and mappel::estimator::ThreadedEstimator< Model >::get_stats().
template<class Model > double mappel::estimator::Estimator< Model >::total_walltime = 0. protected inherited
Definition at line 298 of file estimator.h.
Referenced by mappel::estimator::Estimator< Model >::clear_stats(), mappel::estimator::Estimator< Model >::get_stats(), mappel::estimator::ThreadedEstimator< Model >::get_stats(), and mappel::estimator::Estimator< Model >::record_walltime().
The documentation for this class was generated from the following files:
estimator.h
estimator_impl.h