Mappel: mappel::PoissonNoise1DObjective Class Reference
mappel::PoissonNoise1DObjective Class Reference
A base class for 1D objectives with Poisson read noise. This objective function and its subclasses are for models where the only source of noise is the "shot" or "counting" or Poisson noise inherent to a discrete capture of phontons given a certain mean rate of incidence on each pixel.
#include </home/travis/build/markjolah/Mappel/include/Mappel/PoissonNoise1DObjective.h>
Public Types
using ModelDataT = ImageT
using ModelDataStackT = ImageStackT
using ImageCoordT = uint32_t
using ImagePixelT = double
template<class CoordT >
using ImageSizeShapeT = CoordT
template<class CoordT >
using ImageSizeVecShapeT = arma::Col< CoordT >
using ImageSizeT = ImageSizeShapeT< ImageCoordT >
using ImageSizeVecT = ImageSizeVecShapeT< ImageCoordT >
template<class PixelT >
using ImageShapeT = arma::Col< PixelT >
template<class PixelT >
using ImageStackShapeT = arma::Mat< PixelT >
using ImageT = ImageShapeT< ImagePixelT >
using ImageStackT = ImageStackShapeT< ImagePixelT >
Public Member Functions
StatsT get_stats () const
ImageT make_image () const
ImageStackT make_image_stack (ImageCoordT n) const
ImageCoordT get_size_image_stack (const ImageStackT &stack) const
ImageT get_image_from_stack (const ImageStackT &stack, ImageCoordT n) const
template<class ImT >
void set_image_in_stack (ImageStackT &stack, ImageCoordT n, const ImT &im) const
ImageSizeT get_size () const
ImageCoordT get_size (IdxT idx) const
ImageCoordT get_num_pixels () const
void set_size (const ImageSizeT &size_)
void check_image_shape (const ImageT &im) const
Check the shape of a single images is correct for model size.
void check_image_shape (const ImageStackT &ims) const
Check the shape of a stack of images is correct for model size.
Static Public Member Functions
static void check_size (const ImageSizeT &size_)
Check the size argument for the model.
Static Public Attributes
static const std::vector< std::string > estimator_names
static const ImageCoordT num_dim = 1
static const ImageCoordT global_min_size = 3
static const ImageCoordT global_max_size = 512
Protected Member Functions
PoissonNoise1DObjective ()
PoissonNoise1DObjective (const PoissonNoise1DObjective &o)
PoissonNoise1DObjective (PoissonNoise1DObjective &&o)
PoissonNoise1DObjective & operator= (const PoissonNoise1DObjective &o)
PoissonNoise1DObjective & operator= (PoissonNoise1DObjective &&o)
Protected Attributes
ImageSizeT size
Detailed Description
A base class for 1D objectives with Poisson read noise. This objective function and its subclasses are for models where the only source of noise is the "shot" or "counting" or Poisson noise inherent to a discrete capture of phontons given a certain mean rate of incidence on each pixel.
Definition at line 22 of file PoissonNoise1DObjective.h.
Member Typedef Documentation
using mappel::ImageFormat1DBase::ImageCoordT = uint32_t inherited
Image size coordinate storage type
Definition at line 25 of file ImageFormat1DBase.h.
using mappel::ImageFormat1DBase::ImagePixelT = double inherited
Image pixel storage type
Definition at line 26 of file ImageFormat1DBase.h.
template<class PixelT > using mappel::ImageFormat1DBase::ImageShapeT = arma::Col<PixelT> inherited
Shape of the data type for a single image
Definition at line 33 of file ImageFormat1DBase.h.
template<class CoordT > using mappel::ImageFormat1DBase::ImageSizeShapeT = CoordT inherited
Shape of the data type to store 1-image's coordinates
Definition at line 28 of file ImageFormat1DBase.h.
using mappel::ImageFormat1DBase::ImageSizeT = ImageSizeShapeT<ImageCoordT> inherited
Data type for a single image size
Definition at line 30 of file ImageFormat1DBase.h.
template<class CoordT > using mappel::ImageFormat1DBase::ImageSizeVecShapeT = arma::Col<CoordT> inherited
Shape of the data type to store a vector of image's coordinates
Definition at line 29 of file ImageFormat1DBase.h.
using mappel::ImageFormat1DBase::ImageSizeVecT = ImageSizeVecShapeT<ImageCoordT> inherited
Data type for a sequence of image sizes
Definition at line 31 of file ImageFormat1DBase.h.
template<class PixelT > using mappel::ImageFormat1DBase::ImageStackShapeT = arma::Mat<PixelT> inherited
Shape of the data type for a sequence of images
Definition at line 34 of file ImageFormat1DBase.h.
using mappel::ImageFormat1DBase::ImageStackT = ImageStackShapeT<ImagePixelT> inherited
Data type to represent a sequence of images
Definition at line 36 of file ImageFormat1DBase.h.
using mappel::ImageFormat1DBase::ImageT = ImageShapeT<ImagePixelT> inherited
Data type to represent single image
Definition at line 35 of file ImageFormat1DBase.h.
using mappel::PoissonNoise1DObjective::ModelDataStackT = ImageStackT
Objective function data stack type: 1D double precision image stack, of images gain-corrected to approximate photons counts
Definition at line 26 of file PoissonNoise1DObjective.h.
using mappel::PoissonNoise1DObjective::ModelDataT = ImageT
Objective function data type: 1D double precision image, gain-corrected to approximate photons counts
Definition at line 25 of file PoissonNoise1DObjective.h.
Constructor & Destructor Documentation
mappel::PoissonNoise1DObjective::PoissonNoise1DObjective () protected
Definition at line 14 of file PoissonNoise1DObjective.cpp.
mappel::PoissonNoise1DObjective::PoissonNoise1DObjective (const PoissonNoise1DObjective & o) protected
Definition at line 18 of file PoissonNoise1DObjective.cpp.
mappel::PoissonNoise1DObjective::PoissonNoise1DObjective (PoissonNoise1DObjective && o) protected
Definition at line 22 of file PoissonNoise1DObjective.cpp.
Member Function Documentation
void ImageFormat1DBase::check_image_shape (const ImageT & im) const inherited
Check the shape of a single images is correct for model size.
Definition at line 59 of file ImageFormat1DBase.cpp.
References mappel::ImageFormat1DBase::size.
void ImageFormat1DBase::check_image_shape (const ImageStackT & ims) const inherited
Check the shape of a stack of images is correct for model size.
Definition at line 71 of file ImageFormat1DBase.cpp.
References mappel::ImageFormat1DBase::size.
void ImageFormat1DBase::check_size (const ImageSizeT & size_) static inherited
Check the size argument for the model.
Definition at line 39 of file ImageFormat1DBase.cpp.
References mappel::ImageFormat1DBase::global_max_size, and mappel::ImageFormat1DBase::global_min_size.
Referenced by mappel::ImageFormat1DBase::ImageFormat1DBase(), and mappel::ImageFormat1DBase::set_size().
ImageFormat1DBase::ImageT ImageFormat1DBase::get_image_from_stack (const ImageStackT & stack, ImageCoordT n) const inline inherited
Definition at line 101 of file ImageFormat1DBase.h.
ImageFormat1DBase::ImageCoordT ImageFormat1DBase::get_num_pixels () const inline inherited
Definition at line 75 of file ImageFormat1DBase.h.
References mappel::ImageFormat1DBase::size.
Referenced by mappel::ImageFormat1DBase::get_stats().
ImageFormat1DBase::ImageSizeT ImageFormat1DBase::get_size () const inline inherited
Definition at line 70 of file ImageFormat1DBase.h.
References mappel::ImageFormat1DBase::size.
Referenced by mappel::ImageFormat1DBase::get_stats().
ImageFormat1DBase::ImageCoordT ImageFormat1DBase::get_size (IdxT idx) const inherited
Definition at line 20 of file ImageFormat1DBase.cpp.
References mappel::ImageFormat1DBase::size.
ImageFormat1DBase::ImageCoordT ImageFormat1DBase::get_size_image_stack (const ImageStackT & stack) const inline inherited
Definition at line 94 of file ImageFormat1DBase.h.
StatsT ImageFormat1DBase::get_stats () const inherited
Definition at line 81 of file ImageFormat1DBase.cpp.
References mappel::ImageFormat1DBase::get_num_pixels(), mappel::ImageFormat1DBase::get_size(), and mappel::ImageFormat1DBase::num_dim.
Referenced by mappel::Gauss1DModel::get_stats(), and mappel::Gauss1DsModel::get_stats().
ImageFormat1DBase::ImageT ImageFormat1DBase::make_image () const inline inherited
Definition at line 80 of file ImageFormat1DBase.h.
References mappel::ImageFormat1DBase::size.
ImageFormat1DBase::ImageStackT ImageFormat1DBase::make_image_stack (ImageCoordT n) const inline inherited
Definition at line 87 of file ImageFormat1DBase.h.
References mappel::ImageFormat1DBase::size.
PoissonNoise1DObjective & mappel::PoissonNoise1DObjective::operator= (const PoissonNoise1DObjective & o) protected
Definition at line 26 of file PoissonNoise1DObjective.cpp.
Referenced by mappel::Gauss1DMAP::operator=(), mappel::Gauss1DMLE::operator=(), mappel::Gauss1DsMAP::operator=(), and mappel::Gauss1DsMLE::operator=().
PoissonNoise1DObjective & mappel::PoissonNoise1DObjective::operator= (PoissonNoise1DObjective && o) protected
Definition at line 31 of file PoissonNoise1DObjective.cpp.
template<class ImT > void ImageFormat1DBase::set_image_in_stack (ImageStackT & stack, ImageCoordT n, const ImT & im) const inherited
Definition at line 108 of file ImageFormat1DBase.h.
void ImageFormat1DBase::set_size (const ImageSizeT & size_) inherited
Definition at line 30 of file ImageFormat1DBase.cpp.
References mappel::ImageFormat1DBase::check_size(), and mappel::ImageFormat1DBase::size.
Referenced by mappel::Gauss2DModel::set_size(), and mappel::Gauss2DsModel::set_size().
Member Data Documentation
const std::vector< std::string > mappel::PoissonNoise1DObjective::estimator_names static
Definition at line 24 of file PoissonNoise1DObjective.h.
const ImageFormat1DBase::ImageCoordT ImageFormat1DBase::global_max_size = 512 static inherited
Maximum size along any dimension of the image. This is insanely big to catch obvious errors
Definition at line 40 of file ImageFormat1DBase.h.
Referenced by mappel::ImageFormat1DBase::check_size().
const ImageFormat1DBase::ImageCoordT ImageFormat1DBase::global_min_size = 3 static inherited
Minimum size along any dimension of the image.
Definition at line 39 of file ImageFormat1DBase.h.
Referenced by mappel::ImageFormat1DBase::check_size().
const ImageFormat1DBase::ImageCoordT ImageFormat1DBase::num_dim = 1 static inherited
Number of image dimensions.
Definition at line 38 of file ImageFormat1DBase.h.
Referenced by mappel::ImageFormat1DBase::get_stats().
ImageSizeT mappel::ImageFormat1DBase::size protected inherited
Number of pixels in X dimension for 1D image
Definition at line 64 of file ImageFormat1DBase.h.
Referenced by mappel::ImageFormat1DBase::check_image_shape(), mappel::Gauss1DsModel::Stencil::compute_derivatives(), mappel::Gauss1DModel::Stencil::compute_derivatives(), mappel::ImageFormat1DBase::get_num_pixels(), mappel::ImageFormat1DBase::get_size(), mappel::Gauss1DModel::initial_theta_estimate(), mappel::Gauss1DsModel::initial_theta_estimate(), mappel::ImageFormat1DBase::make_image(), mappel::ImageFormat1DBase::make_image_stack(), mappel::ImageFormat1DBase::set_size(), mappel::Gauss1DsModel::Stencil::Stencil(), and mappel::Gauss1DModel::Stencil::Stencil().
The documentation for this class was generated from the following files:
PoissonNoise1DObjective.h
PoissonNoise1DObjective.cpp