Mappel: mappel::TrustRegionMaximizer< Model > Class Template Reference
mappel::TrustRegionMaximizer< Model > Class Template Reference abstract
#include </home/travis/build/markjolah/Mappel/include/Mappel/estimator.h>
Public Types
using MaximizerData = typename IterativeMaximizer< Model >::MaximizerData
enum ExitCode : IdxT {
ExitCode::Unassigned = 8, ExitCode::MaxIter = 7, ExitCode::MaxBacktracks = 6, ExitCode::TrustRegionRadius = 5,
ExitCode::GradRatio = 4, ExitCode::FunctionChange = 3, ExitCode::StepSize = 2, ExitCode::Success = 1,
ExitCode::Error = 0
}
Public Member Functions
TrustRegionMaximizer (Model &model, int max_iterations=DEFAULT_ITERATIONS)
std::string name () const
double mean_iterations ()
double mean_backtracks ()
double mean_fun_evals ()
double mean_der_evals ()
StatsT get_stats ()
StatsT get_debug_stats ()
void clear_stats ()
void local_maximize (const ModelDataT< Model > &im, const StencilT< Model > &theta_init, StencilT< Model > &stencil, double &rllh)
Perform a local maximization to finish off a simulated annealing run.
void estimate_max_stack (const ModelDataStackT< Model > &im, const ParamVecT< Model > &theta_init, ParamVecT< Model > &theta, VecT &rllh, CubeT &obsI)
void estimate_max_stack (const ModelDataStackT< Model > &im_stack, ParamVecT< Model > &theta_est_stack, VecT &rllh_stack, CubeT &obsI_stack)
void estimate_profile_stack (const ModelDataT< Model > &data, const IdxVecT &fixed_parameters, const MatT &values, const ParamVecT< Model > &theta_init, VecT &profile_likelihood, ParamVecT< Model > &profile_parameters)
Model & get_model ()
void set_model (Model &new_model)
StencilT< Model > estimate_max (const ModelDataT< Model > &im)
StencilT< Model > estimate_max (const ModelDataT< Model > &im, const ParamT< Model > &theta_init)
StencilT< Model > estimate_max (const ModelDataT< Model > &im, double &rllh)
StencilT< Model > estimate_max (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, double &rllh)
void estimate_max (const ModelDataT< Model > &im, ParamT< Model > &theta, double &rllh, MatT &obsI)
void estimate_max (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamT< Model > &theta, double &rllh, MatT &obsI)
void estimate_max_debug (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamT< Model > &theta_est, double &rllh, MatT &obsI, MatT &sequence, VecT &sequence_rllh)
Static Public Attributes
static const double rho_cauchy_min = 0.1
static const double rho_obj_min = 0.25
static const double rho_obj_opt = 0.75
static const double delta_decrease_min = 0.125
static const double delta_decrease = 0.25
static const double delta_increase = 2
static const double min_scaling = 1.0e-5
static const double max_scaling = 1.0e5
static const double delta_init_min = 1.0e-3
static const double delta_init_max = 1.0e3
static const double boundary_stepback_min_kappa = 1.0 - 1.0e-5
static constexpr int NumExitCodes = 9
Protected Member Functions
void maximize (MaximizerData &data)
VecT bound_step (const VecT &step_hat, const VecT &D, const VecT &theta, const VecT &lbound, const VecT &ubound)
void record_run_statistics (const MaximizerData &data)
StencilT< Model > compute_estimate (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, double &rllh)
virtual void compute_estimate (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamT< Model > &theta_est, double &rllh, MatT &obsI)
Default base class implementation computes rllh and obsI seperately from stencil This should be overridden by Estimator subclasses that already have access to this information.
StencilT< Model > compute_estimate_debug (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamVecT< Model > &sequence, VecT &sequence_rllh)
void compute_profile_estimate (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, const IdxVecT &fixed_parameters, ParamT< Model > &theta_est, double &rllh)
virtual void maximize (MaximizerData &data)=0
bool backtrack (MaximizerData &data)
bool convergence_test (MaximizerData &data)
void record_exit_code (ExitCode code)
void record_walltime (ClockT::time_point start_walltime, int nimages)
Static Protected Member Functions
static VecT compute_D_scale (const VecT &oldDscale, const VecT &grad2)
static double compute_initial_trust_radius (const VecT &ghat)
static double quadratic_model_value (const VecT &step, const VecT &grad, const MatT &hess)
Quadratic model value at given step Compute a quadratic model.
static void compute_bound_scaling_vec (const VecT &theta, const VecT &grad, const VecT &lbound, const VecT &ubound, VecT &v, VecT &Jv)
The vector used for bound constrained TR scaling.
static VecT compute_cauchy_point (const VecT &g, const MatT &H, double delta)
static VecT solve_TR_subproblem (const VecT &g, const MatT &H, double delta, double epsilon)
Exactly solver the TR subproblem even for non-positive definite H.
static VecT solve_restricted_step_length_newton (const VecT &g, const MatT &H, double delta, double lambda_lb, double lambda_ub, double epsilon)
Protected Attributes
int max_iterations
double epsilon = 1e-6
double delta = 1e-6
double lambda_min = 0.05
double alpha = 1e-4
int max_backtracks = 8
int total_iterations = 0
int total_backtracks = 0
int total_fun_evals = 0
int total_der_evals = 0
IdxVecT last_backtrack_idxs
int max_threads
int num_threads
std::mutex mtx
Model & model
int num_estimations = 0
double total_walltime = 0.
IdxVecT exit_counts
Detailed Description
template<class Model>
class mappel::TrustRegionMaximizer< Model >
Definition at line 375 of file estimator.h.
Member Typedef Documentation
template<class Model > using mappel::TrustRegionMaximizer< Model >::MaximizerData = typename IterativeMaximizer<Model>::MaximizerData
Definition at line 377 of file estimator.h.
Member Enumeration Documentation
template<class Model > enum mappel::Estimator::ExitCode : IdxT strong inherited
Enumerator
Unassigned
MaxIter
MaxBacktracks
TrustRegionRadius
GradRatio
FunctionChange
StepSize
Success
Error
Definition at line 40 of file estimator.h.
Constructor & Destructor Documentation
template<class Model > mappel::TrustRegionMaximizer< Model >::TrustRegionMaximizer (Model & model, int max_iterations = DEFAULT_ITERATIONS) inline
Definition at line 392 of file estimator.h.
Member Function Documentation
template<class Model > bool mappel::IterativeMaximizer< Model >::backtrack (MaximizerData & data) protected inherited
Definition at line 647 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::alpha, mappel::IterativeMaximizer< Model >::convergence_test(), mappel::IterativeMaximizer< Model >::MaximizerData::free_parameters, mappel::IterativeMaximizer< Model >::MaximizerData::grad, mappel::IterativeMaximizer< Model >::MaximizerData::im, mappel::IterativeMaximizer< Model >::max_backtracks, mappel::Estimator< Model >::model, mappel::IterativeMaximizer< Model >::MaximizerData::num_fixed_parameters, mappel::IterativeMaximizer< Model >::MaximizerData::record_backtrack(), mappel::ThreadedEstimator< Model >::record_exit_code(), mappel::IterativeMaximizer< Model >::MaximizerData::record_iteration(), mappel::IterativeMaximizer< Model >::MaximizerData::restore_stencil(), mappel::methods::objective::rllh(), mappel::IterativeMaximizer< Model >::MaximizerData::rllh, mappel::IterativeMaximizer< Model >::MaximizerData::save_stencil(), mappel::IterativeMaximizer< Model >::MaximizerData::saved_theta(), mappel::IterativeMaximizer< Model >::MaximizerData::set_stencil(), mappel::IterativeMaximizer< Model >::MaximizerData::stencil(), and mappel::IterativeMaximizer< Model >::MaximizerData::step.
Referenced by mappel::NewtonDiagonalMaximizer< Model >::maximize(), mappel::NewtonMaximizer< Model >::maximize(), and mappel::QuasiNewtonMaximizer< Model >::maximize().
template<class Model > VecT mappel::TrustRegionMaximizer< Model >::bound_step (const VecT & step_hat, const VecT & D, const VecT & theta, const VecT & lbound, const VecT & ubound) protected
This is alpha[d] from Coleman and Li
Definition at line 1301 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::alpha, and mappel::IterativeMaximizer< Model >::MaximizerData::step.
template<class Model > void mappel::IterativeMaximizer< Model >::clear_stats () virtual inherited
Reimplemented from mappel::ThreadedEstimator< Model >.
Definition at line 625 of file estimator_impl.h.
References mappel::ThreadedEstimator< Model >::clear_stats(), mappel::ThreadedEstimator< Model >::mtx, mappel::IterativeMaximizer< Model >::total_backtracks, mappel::IterativeMaximizer< Model >::total_der_evals, mappel::IterativeMaximizer< Model >::total_fun_evals, and mappel::IterativeMaximizer< Model >::total_iterations.
template<class Model > void mappel::TrustRegionMaximizer< Model >::compute_bound_scaling_vec (const VecT & theta, const VecT & g, const VecT & lbound, const VecT & ubound, VecT & v, VecT & Jv) static protected
The vector used for bound constrained TR scaling.
This v is from Coleman&Li (1996). It represents a scaling factor for bound constrained problems. For unconstrained problems v = sgn(grad);
In all cases
Definition at line 1265 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::MaximizerData::lbound, mappel::sgn(), mappel::IterativeMaximizer< Model >::MaximizerData::theta(), and mappel::IterativeMaximizer< Model >::MaximizerData::ubound.
template<class Model > VecT mappel::TrustRegionMaximizer< Model >::compute_cauchy_point (const VecT & g, const MatT & H, double delta) static protected
Definition at line 1342 of file estimator_impl.h.
template<class Model > VecT mappel::TrustRegionMaximizer< Model >::compute_D_scale (const VecT & oldDscale, const VecT & grad2) static protected
This works for either minimization or maximization. sign(grad2) is not important
Definition at line 1226 of file estimator_impl.h.
template<class Model > void mappel::Estimator< Model >::compute_estimate (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamT< Model > & theta_est, double & rllh, MatT & obsI) protected virtual inherited
Default base class implementation computes rllh and obsI seperately from stencil This should be overridden by Estimator subclasses that already have access to this information.
Definition at line 183 of file estimator_impl.h.
References mappel::Estimator< Model >::compute_estimate(), mappel::Estimator< Model >::model, and mappel::methods::observed_information().
template<class Model > StencilT< Model > mappel::IterativeMaximizer< Model >::compute_estimate (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, double & rllh) protected virtual inherited
Implements mappel::Estimator< Model >.
Definition at line 753 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::maximize(), mappel::Estimator< Model >::model, mappel::IterativeMaximizer< Model >::record_run_statistics(), mappel::IterativeMaximizer< Model >::MaximizerData::rllh, and mappel::IterativeMaximizer< Model >::MaximizerData::stencil().
template<class Model > StencilT< Model > mappel::IterativeMaximizer< Model >::compute_estimate_debug (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamVecT< Model > & sequence, VecT & sequence_rllh) protected virtual inherited
Estimators that produce a sequence of results (e.g. IterativeEstimators) can override this dummy debug implementation.
Reimplemented from mappel::Estimator< Model >.
Definition at line 768 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::MaximizerData::get_theta_sequence(), mappel::IterativeMaximizer< Model >::MaximizerData::get_theta_sequence_rllh(), mappel::IterativeMaximizer< Model >::max_backtracks, mappel::IterativeMaximizer< Model >::max_iterations, mappel::IterativeMaximizer< Model >::maximize(), mappel::Estimator< Model >::model, mappel::print_image(), mappel::ThreadedEstimator< Model >::record_exit_code(), mappel::IterativeMaximizer< Model >::record_run_statistics(), and mappel::IterativeMaximizer< Model >::MaximizerData::stencil().
template<class Model > double mappel::TrustRegionMaximizer< Model >::compute_initial_trust_radius (const VecT & ghat) inline static protected
Works for minimization or maximization. Indepdendet of sign or grad
Definition at line 1239 of file estimator_impl.h.
template<class Model > void mappel::IterativeMaximizer< Model >::compute_profile_estimate (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, const IdxVecT & fixed_parameters, ParamT< Model > & theta_est, double & rllh) protected virtual inherited
Reimplemented from mappel::Estimator< Model >.
Definition at line 797 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::maximize(), mappel::Estimator< Model >::model, mappel::IterativeMaximizer< Model >::record_run_statistics(), mappel::IterativeMaximizer< Model >::MaximizerData::rllh, mappel::IterativeMaximizer< Model >::MaximizerData::set_fixed_parameters(), and mappel::IterativeMaximizer< Model >::MaximizerData::theta().
template<class Model > bool mappel::IterativeMaximizer< Model >::convergence_test (MaximizerData & data) protected inherited
Definition at line 731 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::delta, mappel::IterativeMaximizer< Model >::epsilon, mappel::IterativeMaximizer< Model >::MaximizerData::free_parameters, mappel::IterativeMaximizer< Model >::MaximizerData::grad, mappel::IterativeMaximizer< Model >::MaximizerData::num_fixed_parameters, mappel::ThreadedEstimator< Model >::record_exit_code(), mappel::IterativeMaximizer< Model >::MaximizerData::rllh, mappel::IterativeMaximizer< Model >::MaximizerData::saved_theta(), and mappel::IterativeMaximizer< Model >::MaximizerData::theta().
Referenced by mappel::IterativeMaximizer< Model >::backtrack().
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im) inherited
Definition at line 64 of file estimator_impl.h.
References mappel::Estimator< Model >::model.
Referenced by mappel::Estimator< Model >::estimate_max(), and mappel::Estimator< Model >::~Estimator().
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, const ParamT< Model > & theta_init) inherited
Definition at line 82 of file estimator_impl.h.
References mappel::Estimator< Model >::estimate_max(), and mappel::methods::objective::rllh().
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, double & rllh) inherited
Definition at line 73 of file estimator_impl.h.
References mappel::Estimator< Model >::estimate_max(), and mappel::Estimator< Model >::model.
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, double & rllh) inherited
Definition at line 90 of file estimator_impl.h.
References mappel::Estimator< Model >::compute_estimate(), mappel::Estimator< Model >::Error, mappel::Estimator< Model >::model, mappel::print_image(), mappel::Estimator< Model >::record_exit_code(), and mappel::Estimator< Model >::record_walltime().
template<class Model > void mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, ParamT< Model > & theta, double & rllh, MatT & obsI) inherited
Definition at line 119 of file estimator_impl.h.
References mappel::Estimator< Model >::estimate_max(), and mappel::Estimator< Model >::model.
template<class Model > void mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamT< Model > & theta, double & rllh, MatT & obsI) inherited
Definition at line 128 of file estimator_impl.h.
References mappel::Estimator< Model >::compute_estimate(), mappel::Estimator< Model >::Error, mappel::print_image(), mappel::Estimator< Model >::record_exit_code(), mappel::Estimator< Model >::record_walltime(), and mappel::methods::objective::rllh().
template<class Model > void mappel::Estimator< Model >::estimate_max_debug (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamT< Model > & theta_est, double & rllh, MatT & obsI, MatT & sequence, VecT & sequence_rllh) inherited
Definition at line 158 of file estimator_impl.h.
References mappel::Estimator< Model >::compute_estimate_debug(), mappel::Estimator< Model >::model, mappel::methods::observed_information(), mappel::Estimator< Model >::record_walltime(), and mappel::methods::objective::rllh().
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > void mappel::Estimator< Model >::estimate_max_stack (const ModelDataStackT< Model > & im_stack, ParamVecT< Model > & theta_est_stack, VecT & rllh_stack, CubeT & obsI_stack) inherited
Definition at line 170 of file estimator_impl.h.
References mappel::Estimator< Model >::estimate_max_stack(), and mappel::Estimator< Model >::model.
template<class Model > void mappel::ThreadedEstimator< Model >::estimate_max_stack (const ModelDataStackT< Model > & im, const ParamVecT< Model > & theta_init, ParamVecT< Model > & theta, VecT & rllh, CubeT & obsI) virtual inherited
Implements mappel::Estimator< Model >.
Definition at line 285 of file estimator_impl.h.
References mappel::Estimator< Model >::compute_estimate(), mappel::Estimator< Model >::Error, mappel::Estimator< Model >::model, mappel::ThreadedEstimator< Model >::num_threads, mappel::print_image(), mappel::ThreadedEstimator< Model >::record_exit_code(), mappel::Estimator< Model >::record_walltime(), and mappel::methods::objective::openmp::rllh_stack().
template<class Model > void mappel::ThreadedEstimator< Model >::estimate_profile_stack (const ModelDataT< Model > & data, const IdxVecT & fixed_parameters, const MatT & values, const ParamVecT< Model > & theta_init, VecT & profile_likelihood, ParamVecT< Model > & profile_parameters) virtual inherited
Implements mappel::Estimator< Model >.
Definition at line 323 of file estimator_impl.h.
References mappel::Estimator< Model >::compute_profile_estimate(), mappel::Estimator< Model >::Error, mappel::Estimator< Model >::model, mappel::ThreadedEstimator< Model >::num_threads, mappel::print_image(), mappel::ThreadedEstimator< Model >::record_exit_code(), and mappel::Estimator< Model >::record_walltime().
template<class Model > StatsT mappel::IterativeMaximizer< Model >::get_debug_stats () virtual inherited
Reimplemented from mappel::ThreadedEstimator< Model >.
Definition at line 609 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::MaximizerData::backtrack_idxs, mappel::IterativeMaximizer< Model >::get_stats(), and mappel::IterativeMaximizer< Model >::last_backtrack_idxs.
template<class Model > Model & mappel::Estimator< Model >::get_model () inherited
Definition at line 50 of file estimator_impl.h.
References mappel::Estimator< Model >::model.
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > StatsT mappel::IterativeMaximizer< Model >::get_stats () virtual inherited
Reimplemented from mappel::ThreadedEstimator< Model >.
Definition at line 588 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::delta, mappel::IterativeMaximizer< Model >::epsilon, mappel::ThreadedEstimator< Model >::get_stats(), mappel::IterativeMaximizer< Model >::max_backtracks, mappel::IterativeMaximizer< Model >::max_iterations, mappel::ThreadedEstimator< Model >::mtx, mappel::Estimator< Model >::num_estimations, mappel::IterativeMaximizer< Model >::total_backtracks, mappel::IterativeMaximizer< Model >::total_der_evals, mappel::IterativeMaximizer< Model >::total_fun_evals, and mappel::IterativeMaximizer< Model >::total_iterations.
Referenced by mappel::SimulatedAnnealingMaximizer< Model >::get_debug_stats(), and mappel::IterativeMaximizer< Model >::get_debug_stats().
template<class Model > void mappel::IterativeMaximizer< Model >::local_maximize (const ModelDataT< Model > & im, const StencilT< Model > & theta_init, StencilT< Model > & stencil, double & rllh) inherited
Perform a local maximization to finish off a simulated annealing run.
Definition at line 811 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::maximize(), mappel::Estimator< Model >::model, mappel::IterativeMaximizer< Model >::MaximizerData::rllh, and mappel::IterativeMaximizer< Model >::MaximizerData::stencil().
Referenced by mappel::SimulatedAnnealingMaximizer< Model >::anneal().
template<class Model > virtual void mappel::IterativeMaximizer< Model >::maximize (MaximizerData & data) protected pure virtual inherited
Referenced by mappel::IterativeMaximizer< Model >::compute_estimate(), mappel::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::compute_profile_estimate(), and mappel::IterativeMaximizer< Model >::local_maximize().
template<class Model > void mappel::TrustRegionMaximizer< Model >::maximize (MaximizerData & data) protected
Definition at line 1059 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::delta, mappel::IterativeMaximizer< Model >::epsilon, mappel::methods::objective::hessian(), mappel::Estimator< Model >::model, mappel::ThreadedEstimator< Model >::record_exit_code(), and mappel::methods::objective::rllh().
template<class Model > double mappel::IterativeMaximizer< Model >::mean_backtracks () inherited
template<class Model > double mappel::IterativeMaximizer< Model >::mean_der_evals () inherited
template<class Model > double mappel::IterativeMaximizer< Model >::mean_fun_evals () inherited
template<class Model > double mappel::IterativeMaximizer< Model >::mean_iterations () inherited
template<class Model > std::string mappel::TrustRegionMaximizer< Model >::name () const inline virtual
Implements mappel::Estimator< Model >.
Definition at line 395 of file estimator.h.
References mappel::methods::objective::grad(), and mappel::methods::objective::grad2().
template<class Model > double mappel::TrustRegionMaximizer< Model >::quadratic_model_value (const VecT & step, const VecT & grad, const MatT & hess) inline static protected
Quadratic model value at given step Compute a quadratic model.
Definition at line 1251 of file estimator_impl.h.
template<class Model > void mappel::ThreadedEstimator< Model >::record_exit_code (ExitCode code) protected virtual inherited
Implements mappel::Estimator< Model >.
Definition at line 386 of file estimator_impl.h.
References mappel::Estimator< Model >::exit_counts, mappel::Estimator< Model >::model, mappel::ThreadedEstimator< Model >::mtx, and mappel::methods::objective::rllh().
Referenced by mappel::IterativeMaximizer< Model >::backtrack(), mappel::CGaussMLE< Model >::compute_estimate(), mappel::CGaussMLE< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::convergence_test(), mappel::ThreadedEstimator< Model >::estimate_max_stack(), mappel::ThreadedEstimator< Model >::estimate_profile_stack(), mappel::HeuristicEstimator< Model >::get_debug_stats(), mappel::NewtonDiagonalMaximizer< Model >::maximize(), mappel::NewtonMaximizer< Model >::maximize(), mappel::QuasiNewtonMaximizer< Model >::maximize(), and mappel::TrustRegionMaximizer< Model >::maximize().
template<class Model > void mappel::IterativeMaximizer< Model >::record_run_statistics (const MaximizerData & data) protected inherited
Definition at line 636 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::MaximizerData::get_backtrack_idxs(), mappel::IterativeMaximizer< Model >::last_backtrack_idxs, mappel::ThreadedEstimator< Model >::mtx, mappel::IterativeMaximizer< Model >::MaximizerData::nBacktracks, mappel::IterativeMaximizer< Model >::MaximizerData::nIterations, mappel::IterativeMaximizer< Model >::MaximizerData::save_seq, mappel::IterativeMaximizer< Model >::total_backtracks, mappel::IterativeMaximizer< Model >::total_der_evals, mappel::IterativeMaximizer< Model >::total_fun_evals, and mappel::IterativeMaximizer< Model >::total_iterations.
Referenced by mappel::IterativeMaximizer< Model >::compute_estimate(), mappel::IterativeMaximizer< Model >::compute_estimate_debug(), and mappel::IterativeMaximizer< Model >::compute_profile_estimate().
template<class Model > void mappel::Estimator< Model >::record_walltime (ClockT::time_point start_walltime, int nimages) protected inherited
Definition at line 266 of file estimator_impl.h.
References mappel::Estimator< Model >::num_estimations, and mappel::Estimator< Model >::total_walltime.
Referenced by mappel::Estimator< Model >::estimate_max(), mappel::Estimator< Model >::estimate_max_debug(), mappel::ThreadedEstimator< Model >::estimate_max_stack(), and mappel::ThreadedEstimator< Model >::estimate_profile_stack().
template<class Model > void mappel::Estimator< Model >::set_model (Model & new_model) inherited
Definition at line 54 of file estimator_impl.h.
References mappel::Estimator< Model >::model.
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > VecT mappel::TrustRegionMaximizer< Model >::solve_restricted_step_length_newton (const VecT & g, const MatT & H, double delta, double lambda_lb, double lambda_ub, double epsilon) static protected
Definition at line 1451 of file estimator_impl.h.
References mappel::cholesky(), mappel::cholesky_convert_lower_triangular(), mappel::cholesky_solve(), mappel::IterativeMaximizer< Model >::delta, mappel::IterativeMaximizer< Model >::epsilon, and mappel::IterativeMaximizer< Model >::lambda_min.
template<class Model > VecT mappel::TrustRegionMaximizer< Model >::solve_TR_subproblem (const VecT & g, const MatT & H, double delta, double epsilon) static protected
Exactly solver the TR subproblem even for non-positive definite H.
This method is a hybrid technique mixing ideas from Geyer (2013) and the "trust" R-package Nocetal and Wright (2000) More and Sorensen (1981)
Definition at line 1359 of file estimator_impl.h.
References mappel::cholesky(), mappel::cholesky_solve(), mappel::IterativeMaximizer< Model >::delta, and mappel::IterativeMaximizer< Model >::lambda_min.
Member Data Documentation
template<class Model > double mappel::IterativeMaximizer< Model >::alpha = 1e-4 protected inherited
Definition at line 245 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::backtrack(), and mappel::TrustRegionMaximizer< Model >::bound_step().
template<class Model > const double mappel::TrustRegionMaximizer< Model >::boundary_stepback_min_kappa = 1.0 - 1.0e-5 static
Definition at line 390 of file estimator.h.
template<class Model > double mappel::IterativeMaximizer< Model >::delta = 1e-6 protected inherited
Definition at line 242 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::convergence_test(), mappel::IterativeMaximizer< Model >::get_stats(), mappel::NewtonMaximizer< Model >::maximize(), mappel::QuasiNewtonMaximizer< Model >::maximize(), mappel::TrustRegionMaximizer< Model >::maximize(), mappel::TrustRegionMaximizer< Model >::solve_restricted_step_length_newton(), and mappel::TrustRegionMaximizer< Model >::solve_TR_subproblem().
template<class Model > const double mappel::TrustRegionMaximizer< Model >::delta_decrease = 0.25 static
Definition at line 383 of file estimator.h.
template<class Model > const double mappel::TrustRegionMaximizer< Model >::delta_decrease_min = 0.125 static
Definition at line 382 of file estimator.h.
template<class Model > const double mappel::TrustRegionMaximizer< Model >::delta_increase = 2 static
Definition at line 384 of file estimator.h.
template<class Model > const double mappel::TrustRegionMaximizer< Model >::delta_init_max = 1.0e3 static
Definition at line 389 of file estimator.h.
template<class Model > const double mappel::TrustRegionMaximizer< Model >::delta_init_min = 1.0e-3 static
Definition at line 388 of file estimator.h.
template<class Model > double mappel::IterativeMaximizer< Model >::epsilon = 1e-6 protected inherited
Definition at line 241 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::convergence_test(), mappel::IterativeMaximizer< Model >::get_stats(), mappel::TrustRegionMaximizer< Model >::maximize(), and mappel::TrustRegionMaximizer< Model >::solve_restricted_step_length_newton().
template<class Model > IdxVecT mappel::Estimator< Model >::exit_counts protected inherited
Definition at line 114 of file estimator.h.
Referenced by mappel::Estimator< Model >::clear_stats(), mappel::Estimator< Model >::get_stats(), and mappel::ThreadedEstimator< Model >::record_exit_code().
template<class Model > double mappel::IterativeMaximizer< Model >::lambda_min = 0.05 protected inherited
Definition at line 244 of file estimator.h.
Referenced by mappel::TrustRegionMaximizer< Model >::solve_restricted_step_length_newton(), and mappel::TrustRegionMaximizer< Model >::solve_TR_subproblem().
template<class Model > IdxVecT mappel::IterativeMaximizer< Model >::last_backtrack_idxs protected inherited
Definition at line 255 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::get_debug_stats(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::IterativeMaximizer< Model >::max_backtracks = 8 protected inherited
Definition at line 246 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::backtrack(), mappel::IterativeMaximizer< Model >::compute_estimate_debug(), and mappel::IterativeMaximizer< Model >::get_stats().
template<class Model > int mappel::IterativeMaximizer< Model >::max_iterations protected inherited
Definition at line 238 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::get_stats(), mappel::NewtonDiagonalMaximizer< Model >::maximize(), mappel::NewtonMaximizer< Model >::maximize(), and mappel::QuasiNewtonMaximizer< Model >::maximize().
template<class Model > const double mappel::TrustRegionMaximizer< Model >::max_scaling = 1.0e5 static
Definition at line 387 of file estimator.h.
template<class Model > int mappel::ThreadedEstimator< Model >::max_threads protected inherited
Definition at line 142 of file estimator.h.
template<class Model > const double mappel::TrustRegionMaximizer< Model >::min_scaling = 1.0e-5 static
Definition at line 386 of file estimator.h.
template<class Model > Model& mappel::Estimator< Model >::model protected inherited
Definition at line 109 of file estimator.h.
Referenced by mappel::SimulatedAnnealingMaximizer< Model >::anneal(), mappel::IterativeMaximizer< Model >::backtrack(), mappel::Estimator< Model >::compute_estimate(), mappel::CGaussMLE< Model >::compute_estimate(), mappel::SimulatedAnnealingMaximizer< Model >::compute_estimate(), mappel::IterativeMaximizer< Model >::compute_estimate(), mappel::Estimator< Model >::compute_estimate_debug(), mappel::CGaussMLE< Model >::compute_estimate_debug(), mappel::SimulatedAnnealingMaximizer< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::Estimator< Model >::compute_profile_estimate(), mappel::IterativeMaximizer< Model >::compute_profile_estimate(), mappel::Estimator< Model >::estimate_max(), mappel::Estimator< Model >::estimate_max_debug(), mappel::Estimator< Model >::estimate_max_stack(), mappel::ThreadedEstimator< Model >::estimate_max_stack(), mappel::ThreadedEstimator< Model >::estimate_profile_stack(), mappel::HeuristicEstimator< Model >::get_debug_stats(), mappel::Estimator< Model >::get_model(), mappel::IterativeMaximizer< Model >::local_maximize(), mappel::NewtonDiagonalMaximizer< Model >::maximize(), mappel::NewtonMaximizer< Model >::maximize(), mappel::QuasiNewtonMaximizer< Model >::maximize(), mappel::TrustRegionMaximizer< Model >::maximize(), mappel::ThreadedEstimator< Model >::record_exit_code(), and mappel::Estimator< Model >::set_model().
template<class Model > std::mutex mappel::ThreadedEstimator< Model >::mtx protected inherited
Definition at line 144 of file estimator.h.
Referenced by mappel::ThreadedEstimator< Model >::clear_stats(), mappel::IterativeMaximizer< Model >::clear_stats(), mappel::ThreadedEstimator< Model >::get_stats(), mappel::IterativeMaximizer< Model >::get_stats(), mappel::ThreadedEstimator< Model >::record_exit_code(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::Estimator< Model >::num_estimations = 0 protected inherited
Definition at line 112 of file estimator.h.
Referenced by mappel::Estimator< Model >::clear_stats(), mappel::Estimator< Model >::get_stats(), mappel::ThreadedEstimator< Model >::get_stats(), mappel::IterativeMaximizer< Model >::get_stats(), and mappel::Estimator< Model >::record_walltime().
template<class Model > int mappel::ThreadedEstimator< Model >::num_threads protected inherited
Definition at line 143 of file estimator.h.
Referenced by mappel::ThreadedEstimator< Model >::clear_stats(), mappel::ThreadedEstimator< Model >::estimate_max_stack(), mappel::ThreadedEstimator< Model >::estimate_profile_stack(), and mappel::ThreadedEstimator< Model >::get_stats().
template<class Model > constexpr int mappel::Estimator< Model >::NumExitCodes = 9 static inherited
Definition at line 39 of file estimator.h.
template<class Model > const double mappel::TrustRegionMaximizer< Model >::rho_cauchy_min = 0.1 static
Definition at line 379 of file estimator.h.
template<class Model > const double mappel::TrustRegionMaximizer< Model >::rho_obj_min = 0.25 static
Definition at line 380 of file estimator.h.
template<class Model > const double mappel::TrustRegionMaximizer< Model >::rho_obj_opt = 0.75 static
Definition at line 381 of file estimator.h.
template<class Model > int mappel::IterativeMaximizer< Model >::total_backtracks = 0 protected inherited
Definition at line 250 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::clear_stats(), mappel::IterativeMaximizer< Model >::get_stats(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::IterativeMaximizer< Model >::total_der_evals = 0 protected inherited
Definition at line 252 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::clear_stats(), mappel::IterativeMaximizer< Model >::get_stats(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::IterativeMaximizer< Model >::total_fun_evals = 0 protected inherited
Definition at line 251 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::clear_stats(), mappel::IterativeMaximizer< Model >::get_stats(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::IterativeMaximizer< Model >::total_iterations = 0 protected inherited
Definition at line 249 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::clear_stats(), mappel::IterativeMaximizer< Model >::get_stats(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > double mappel::Estimator< Model >::total_walltime = 0. protected inherited
Definition at line 113 of file estimator.h.
Referenced by mappel::Estimator< Model >::clear_stats(), mappel::Estimator< Model >::get_stats(), mappel::ThreadedEstimator< Model >::get_stats(), and mappel::Estimator< Model >::record_walltime().
The documentation for this class was generated from the following files:
estimator.h
estimator_impl.h