Mappel: mappel::Gauss1DModel::Stencil Class Reference
mappel::Gauss1DModel::Stencil Class Reference
Stencil for 1D fixed-sigma models.
#include </home/travis/build/markjolah/Mappel/include/Mappel/Gauss1DModel.h>
Public Types
using ParamT = Gauss1DModel::ParamT
Public Member Functions
Stencil ()
Stencil (const Gauss1DModel &model, const ParamT &theta, bool compute_derivatives=true)
void compute_derivatives ()
double x () const
double I () const
double bg () const
Public Attributes
bool derivatives_computed = false
Gauss1DModel const * model
ParamT theta
VecT dx
VecT Gx
VecT X
VecT DX
VecT DXS
Friends
std::ostream & operator<< (std::ostream &out, const Gauss1DModel::Stencil &s)
Detailed Description
Stencil for 1D fixed-sigma models.
Definition at line 29 of file Gauss1DModel.h.
Member Typedef Documentation
using mappel::Gauss1DModel::Stencil::ParamT = Gauss1DModel::ParamT
Definition at line 32 of file Gauss1DModel.h.
Constructor & Destructor Documentation
mappel::Gauss1DModel::Stencil::Stencil () inline
Definition at line 41 of file Gauss1DModel.h.
References compute_derivatives().
Referenced by mappel::Gauss1DModel::make_stencil().
mappel::Gauss1DModel::Stencil::Stencil (const Gauss1DModel & model, const ParamT & theta, bool compute_derivatives = true)
Definition at line 142 of file Gauss1DModel.cpp.
References compute_derivatives(), dx, mappel::make_d_stencil(), mappel::make_X_stencil(), model, mappel::Gauss1DModel::psf_sigma, mappel::ImageFormat1DBase::size, X, and x().
Member Function Documentation
double mappel::Gauss1DModel::Stencil::bg () const inline
Definition at line 46 of file Gauss1DModel.h.
References operator<<, and theta.
Referenced by mappel::Gauss1DModel::initial_theta_estimate(), and mappel::Gauss1DModel::pixel_model_value().
void mappel::Gauss1DModel::Stencil::compute_derivatives ()
Definition at line 153 of file Gauss1DModel.cpp.
References derivatives_computed, dx, DX, DXS, Gx, mappel::make_DX_stencil(), mappel::make_DXS_stencil(), mappel::make_G_stencil(), model, mappel::Gauss1DModel::psf_sigma, and mappel::ImageFormat1DBase::size.
Referenced by Stencil().
double mappel::Gauss1DModel::Stencil::I () const inline
Definition at line 45 of file Gauss1DModel.h.
References theta.
Referenced by mappel::Gauss1DModel::initial_theta_estimate(), mappel::Gauss1DModel::pixel_grad(), mappel::Gauss1DModel::pixel_grad2(), mappel::Gauss1DModel::pixel_hess(), mappel::Gauss1DModel::pixel_hess_update(), and mappel::Gauss1DModel::pixel_model_value().
double mappel::Gauss1DModel::Stencil::x () const inline
Definition at line 44 of file Gauss1DModel.h.
References theta.
Referenced by Stencil().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const Gauss1DModel::Stencil & s) friend
Definition at line 164 of file Gauss1DModel.cpp.
Referenced by bg().
Member Data Documentation
bool mappel::Gauss1DModel::Stencil::derivatives_computed = false
Definition at line 31 of file Gauss1DModel.h.
Referenced by compute_derivatives(), and mappel::operator<<().
VecT mappel::Gauss1DModel::Stencil::dx
Definition at line 36 of file Gauss1DModel.h.
Referenced by compute_derivatives(), mappel::operator<<(), and Stencil().
VecT mappel::Gauss1DModel::Stencil::DX
Definition at line 39 of file Gauss1DModel.h.
Referenced by compute_derivatives(), mappel::operator<<(), mappel::Gauss1DModel::pixel_grad(), and mappel::Gauss1DModel::pixel_hess().
VecT mappel::Gauss1DModel::Stencil::DXS
Definition at line 40 of file Gauss1DModel.h.
Referenced by compute_derivatives(), mappel::operator<<(), mappel::Gauss1DModel::pixel_grad2(), mappel::Gauss1DModel::pixel_hess(), and mappel::Gauss1DModel::pixel_hess_update().
VecT mappel::Gauss1DModel::Stencil::Gx
Definition at line 37 of file Gauss1DModel.h.
Referenced by compute_derivatives(), and mappel::operator<<().
Gauss1DModel const* mappel::Gauss1DModel::Stencil::model
Definition at line 33 of file Gauss1DModel.h.
Referenced by compute_derivatives(), and Stencil().
ParamT mappel::Gauss1DModel::Stencil::theta
Definition at line 35 of file Gauss1DModel.h.
Referenced by bg(), I(), mappel::Gauss1DModel::initial_theta_estimate(), mappel::operator<<(), and x().
VecT mappel::Gauss1DModel::Stencil::X
Definition at line 38 of file Gauss1DModel.h.
Referenced by mappel::operator<<(), mappel::Gauss1DModel::pixel_grad(), mappel::Gauss1DModel::pixel_model_value(), and Stencil().
The documentation for this class was generated from the following files:
Gauss1DModel.h
Gauss1DModel.cpp