Mappel: mappel::Estimator< Model > Class Template Reference
mappel::Estimator< Model > Class Template Reference abstract
#include </home/travis/build/markjolah/Mappel/include/Mappel/estimator.h>
Public Member Functions
Estimator (Model &_model)
virtual ~Estimator ()
virtual std::string name () const =0
Model & get_model ()
void set_model (Model &new_model)
StencilT< Model > estimate_max (const ModelDataT< Model > &im)
StencilT< Model > estimate_max (const ModelDataT< Model > &im, const ParamT< Model > &theta_init)
StencilT< Model > estimate_max (const ModelDataT< Model > &im, double &rllh)
StencilT< Model > estimate_max (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, double &rllh)
void estimate_max (const ModelDataT< Model > &im, ParamT< Model > &theta, double &rllh, MatT &obsI)
void estimate_max (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamT< Model > &theta, double &rllh, MatT &obsI)
void estimate_max_debug (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamT< Model > &theta_est, double &rllh, MatT &obsI, MatT &sequence, VecT &sequence_rllh)
virtual void estimate_max_stack (const ModelDataStackT< Model > &im_stack, const ParamVecT< Model > &theta_init_stack, ParamVecT< Model > &theta_est_stack, VecT &rllh_stack, CubeT &obsI_stack)=0
void estimate_max_stack (const ModelDataStackT< Model > &im_stack, ParamVecT< Model > &theta_est_stack, VecT &rllh_stack, CubeT &obsI_stack)
virtual void estimate_profile_stack (const ModelDataT< Model > &data, const IdxVecT &fixed_parameters, const MatT &values, const ParamVecT< Model > &theta_init, VecT &profile_likelihood, ParamVecT< Model > &profile_parameters)=0
virtual StatsT get_stats ()
virtual StatsT get_debug_stats ()=0
virtual void clear_stats ()
Protected Member Functions
virtual StencilT< Model > compute_estimate (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, double &rllh)=0
virtual StencilT< Model > compute_estimate_debug (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamVecT< Model > &sequence, VecT &sequence_rllh)
virtual void compute_estimate (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamT< Model > &theta_est, double &rllh, MatT &obsI)
Default base class implementation computes rllh and obsI seperately from stencil This should be overridden by Estimator subclasses that already have access to this information.
virtual void compute_profile_estimate (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, const IdxVecT &fixed_parameters, ParamT< Model > &theta_est, double &rllh)
void record_walltime (ClockT::time_point start_walltime, int nimages)
Protected Attributes
Model & model
int num_estimations = 0
double total_walltime = 0.
Friends
template<class T >
std::ostream & operator<< (std::ostream &out, Estimator< T > &estimator)
Detailed Description
template<class Model>
class mappel::Estimator< Model >
Definition at line 37 of file estimator.h.
Constructor & Destructor Documentation
template<class Model > mappel::Estimator< Model >::Estimator (Model & _model) inline
Definition at line 39 of file estimator.h.
template<class Model > virtual mappel::Estimator< Model >::~Estimator () inline virtual
Definition at line 40 of file estimator.h.
References mappel::Estimator< Model >::clear_stats(), mappel::Estimator< Model >::compute_estimate(), mappel::Estimator< Model >::compute_estimate_debug(), mappel::Estimator< Model >::compute_profile_estimate(), mappel::Estimator< Model >::estimate_max(), mappel::Estimator< Model >::estimate_max_debug(), mappel::Estimator< Model >::estimate_max_stack(), mappel::Estimator< Model >::estimate_profile_stack(), mappel::Estimator< Model >::get_debug_stats(), mappel::Estimator< Model >::get_model(), mappel::Estimator< Model >::get_stats(), mappel::Estimator< Model >::name(), mappel::methods::objective::rllh(), mappel::methods::objective::openmp::rllh_stack(), and mappel::Estimator< Model >::set_model().
Member Function Documentation
template<class Model > void mappel::Estimator< Model >::clear_stats () virtual
Reimplemented in mappel::IterativeMaximizer< Model >, and mappel::ThreadedEstimator< Model >.
Definition at line 168 of file estimator_impl.h.
Referenced by mappel::ThreadedEstimator< Model >::clear_stats(), and mappel::Estimator< Model >::~Estimator().
template<class Model > virtual StencilT<Model> mappel::Estimator< Model >::compute_estimate (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, double & rllh) protected pure virtual
Implemented in mappel::IterativeMaximizer< Model >, mappel::SimulatedAnnealingMaximizer< Model >, and mappel::CGaussMLE< Model >.
Referenced by mappel::HeuristicEstimator< Model >::name(), mappel::CGaussHeuristicEstimator< Model >::name(), mappel::CGaussMLE< Model >::name(), mappel::SimulatedAnnealingMaximizer< Model >::SimulatedAnnealingMaximizer(), and mappel::Estimator< Model >::~Estimator().
template<class Model > void mappel::Estimator< Model >::compute_estimate (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamT< Model > & theta_est, double & rllh, MatT & obsI) protected virtual
Default base class implementation computes rllh and obsI seperately from stencil This should be overridden by Estimator subclasses that already have access to this information.
Definition at line 142 of file estimator_impl.h.
References mappel::methods::observed_information().
template<class Model > StencilT< Model > mappel::Estimator< Model >::compute_estimate_debug (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamVecT< Model > & sequence, VecT & sequence_rllh) inline protected virtual
Estimators that produce a sequence of results (e.g. IterativeEstimators) can override this dummy debug implementation.
Reimplemented in mappel::IterativeMaximizer< Model >, mappel::SimulatedAnnealingMaximizer< Model >, and mappel::CGaussMLE< Model >.
Definition at line 192 of file estimator_impl.h.
Referenced by mappel::CGaussMLE< Model >::name(), mappel::SimulatedAnnealingMaximizer< Model >::SimulatedAnnealingMaximizer(), and mappel::Estimator< Model >::~Estimator().
template<class Model > void mappel::Estimator< Model >::compute_profile_estimate (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, const IdxVecT & fixed_parameters, ParamT< Model > & theta_est, double & rllh) protected virtual
Reimplemented in mappel::IterativeMaximizer< Model >.
Definition at line 151 of file estimator_impl.h.
References mappel::Estimator< Model >::name().
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im)
Definition at line 59 of file estimator_impl.h.
References mappel::methods::estimate_max().
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, const ParamT< Model > & theta_init)
Definition at line 77 of file estimator_impl.h.
References mappel::methods::estimate_max(), and mappel::methods::objective::rllh().
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, double & rllh)
Definition at line 68 of file estimator_impl.h.
References mappel::methods::estimate_max().
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, double & rllh)
Definition at line 85 of file estimator_impl.h.
template<class Model > void mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, ParamT< Model > & theta, double & rllh, MatT & obsI)
Definition at line 97 of file estimator_impl.h.
References mappel::methods::estimate_max().
template<class Model > void mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamT< Model > & theta, double & rllh, MatT & obsI)
Definition at line 106 of file estimator_impl.h.
template<class Model > void mappel::Estimator< Model >::estimate_max_debug (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamT< Model > & theta_est, double & rllh, MatT & obsI, MatT & sequence, VecT & sequence_rllh)
Definition at line 117 of file estimator_impl.h.
References mappel::methods::observed_information(), and mappel::methods::objective::rllh().
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > virtual void mappel::Estimator< Model >::estimate_max_stack (const ModelDataStackT< Model > & im_stack, const ParamVecT< Model > & theta_init_stack, ParamVecT< Model > & theta_est_stack, VecT & rllh_stack, CubeT & obsI_stack) pure virtual
Implemented in mappel::ThreadedEstimator< Model >.
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > void mappel::Estimator< Model >::estimate_max_stack (const ModelDataStackT< Model > & im_stack, ParamVecT< Model > & theta_est_stack, VecT & rllh_stack, CubeT & obsI_stack)
Definition at line 129 of file estimator_impl.h.
References mappel::methods::openmp::estimate_max_stack().
template<class Model > virtual void mappel::Estimator< Model >::estimate_profile_stack (const ModelDataT< Model > & data, const IdxVecT & fixed_parameters, const MatT & values, const ParamVecT< Model > & theta_init, VecT & profile_likelihood, ParamVecT< Model > & profile_parameters) pure virtual
Implemented in mappel::ThreadedEstimator< Model >.
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > virtual StatsT mappel::Estimator< Model >::get_debug_stats () pure virtual
Implemented in mappel::IterativeMaximizer< Model >, mappel::CGaussMLE< Model >, and mappel::ThreadedEstimator< Model >.
Referenced by mappel::CGaussMLE< Model >::CGaussMLE(), and mappel::Estimator< Model >::~Estimator().
template<class Model > Model & mappel::Estimator< Model >::get_model ()
Definition at line 45 of file estimator_impl.h.
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > StatsT mappel::Estimator< Model >::get_stats () virtual
Reimplemented in mappel::IterativeMaximizer< Model >, mappel::CGaussMLE< Model >, and mappel::ThreadedEstimator< Model >.
Definition at line 159 of file estimator_impl.h.
Referenced by mappel::CGaussMLE< Model >::CGaussMLE(), mappel::ThreadedEstimator< Model >::get_stats(), mappel::operator<<(), and mappel::Estimator< Model >::~Estimator().
template<class Model > virtual std::string mappel::Estimator< Model >::name () const pure virtual
Implemented in mappel::TrustRegionMaximizer< Model >, mappel::QuasiNewtonMaximizer< Model >, mappel::NewtonMaximizer< Model >, mappel::NewtonDiagonalMaximizer< Model >, mappel::SimulatedAnnealingMaximizer< Model >, mappel::CGaussMLE< Model >, mappel::CGaussHeuristicEstimator< Model >, and mappel::HeuristicEstimator< Model >.
Referenced by mappel::Estimator< Model >::compute_profile_estimate(), and mappel::Estimator< Model >::~Estimator().
template<class Model > void mappel::Estimator< Model >::record_walltime (ClockT::time_point start_walltime, int nimages) protected
Definition at line 203 of file estimator_impl.h.
Referenced by mappel::ThreadedEstimator< Model >::estimate_max_stack(), and mappel::ThreadedEstimator< Model >::estimate_profile_stack().
template<class Model > void mappel::Estimator< Model >::set_model (Model & new_model)
Definition at line 49 of file estimator_impl.h.
Referenced by mappel::Estimator< Model >::~Estimator().
Friends And Related Function Documentation
template<class Model > template<class T > std::ostream& operator<< (std::ostream & out, Estimator< T > & estimator) friend
Member Data Documentation
template<class Model > Model& mappel::Estimator< Model >::model protected
Definition at line 97 of file estimator.h.
Referenced by mappel::SimulatedAnnealingMaximizer< Model >::anneal(), mappel::IterativeMaximizer< Model >::backtrack(), mappel::ThreadedEstimator< Model >::clear_stats(), mappel::CGaussMLE< Model >::compute_estimate(), mappel::SimulatedAnnealingMaximizer< Model >::compute_estimate(), mappel::IterativeMaximizer< Model >::compute_estimate(), mappel::CGaussMLE< Model >::compute_estimate_debug(), mappel::SimulatedAnnealingMaximizer< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::compute_profile_estimate(), mappel::ThreadedEstimator< Model >::estimate_max_stack(), mappel::ThreadedEstimator< Model >::estimate_profile_stack(), mappel::IterativeMaximizer< Model >::local_maximize(), mappel::NewtonDiagonalMaximizer< Model >::maximize(), mappel::NewtonMaximizer< Model >::maximize(), mappel::QuasiNewtonMaximizer< Model >::maximize(), and mappel::TrustRegionMaximizer< Model >::maximize().
template<class Model > int mappel::Estimator< Model >::num_estimations = 0 protected
Definition at line 100 of file estimator.h.
Referenced by mappel::ThreadedEstimator< Model >::get_stats(), and mappel::IterativeMaximizer< Model >::get_stats().
template<class Model > double mappel::Estimator< Model >::total_walltime = 0. protected
Definition at line 101 of file estimator.h.
Referenced by mappel::ThreadedEstimator< Model >::get_stats().
The documentation for this class was generated from the following files:
estimator.h
estimator_impl.h