Mappel: mappel::ThreadedEstimator< Model > Class Template Reference
mappel::ThreadedEstimator< Model > Class Template Reference abstract
#include </home/travis/build/markjolah/Mappel/include/Mappel/estimator.h>
Public Types
enum ExitCode : IdxT {
ExitCode::Unassigned = 8, ExitCode::MaxIter = 7, ExitCode::MaxBacktracks = 6, ExitCode::TrustRegionRadius = 5,
ExitCode::GradRatio = 4, ExitCode::FunctionChange = 3, ExitCode::StepSize = 2, ExitCode::Success = 1,
ExitCode::Error = 0
}
Public Member Functions
ThreadedEstimator (Model &model)
void estimate_max_stack (const ModelDataStackT< Model > &im, const ParamVecT< Model > &theta_init, ParamVecT< Model > &theta, VecT &rllh, CubeT &obsI)
void estimate_profile_stack (const ModelDataT< Model > &data, const IdxVecT &fixed_parameters, const MatT &values, const ParamVecT< Model > &theta_init, VecT &profile_likelihood, ParamVecT< Model > &profile_parameters)
StatsT get_stats ()
StatsT get_debug_stats ()
void clear_stats ()
virtual std::string name () const =0
Model & get_model ()
void set_model (Model &new_model)
StencilT< Model > estimate_max (const ModelDataT< Model > &im)
StencilT< Model > estimate_max (const ModelDataT< Model > &im, const ParamT< Model > &theta_init)
StencilT< Model > estimate_max (const ModelDataT< Model > &im, double &rllh)
StencilT< Model > estimate_max (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, double &rllh)
void estimate_max (const ModelDataT< Model > &im, ParamT< Model > &theta, double &rllh, MatT &obsI)
void estimate_max (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamT< Model > &theta, double &rllh, MatT &obsI)
void estimate_max_debug (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamT< Model > &theta_est, double &rllh, MatT &obsI, MatT &sequence, VecT &sequence_rllh)
void estimate_max_stack (const ModelDataStackT< Model > &im_stack, ParamVecT< Model > &theta_est_stack, VecT &rllh_stack, CubeT &obsI_stack)
Static Public Attributes
static constexpr int NumExitCodes = 9
Protected Member Functions
void record_exit_code (ExitCode code)
virtual StencilT< Model > compute_estimate (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, double &rllh)=0
virtual void compute_estimate (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamT< Model > &theta_est, double &rllh, MatT &obsI)
Default base class implementation computes rllh and obsI seperately from stencil This should be overridden by Estimator subclasses that already have access to this information.
virtual StencilT< Model > compute_estimate_debug (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, ParamVecT< Model > &sequence, VecT &sequence_rllh)
virtual void compute_profile_estimate (const ModelDataT< Model > &im, const ParamT< Model > &theta_init, const IdxVecT &fixed_parameters, ParamT< Model > &theta_est, double &rllh)
void record_walltime (ClockT::time_point start_walltime, int nimages)
Protected Attributes
int max_threads
int num_threads
std::mutex mtx
Model & model
int num_estimations = 0
double total_walltime = 0.
IdxVecT exit_counts
Detailed Description
template<class Model>
class mappel::ThreadedEstimator< Model >
We avoid combining Estimator and ThreadedEstimator classes so that a future GPU implementation can inherit directly from Estimator as it will present a differnt method for estimate_stack pure virtual member function. For now all other (CPU) estimators inherit from ThreadedEstimator.
Definition at line 127 of file estimator.h.
Member Enumeration Documentation
template<class Model > enum mappel::Estimator::ExitCode : IdxT strong inherited
Enumerator
Unassigned
MaxIter
MaxBacktracks
TrustRegionRadius
GradRatio
FunctionChange
StepSize
Success
Error
Definition at line 40 of file estimator.h.
Constructor & Destructor Documentation
template<class Model > mappel::ThreadedEstimator< Model >::ThreadedEstimator (Model & model)
Definition at line 276 of file estimator_impl.h.
Member Function Documentation
template<class Model > void mappel::ThreadedEstimator< Model >::clear_stats () virtual
Reimplemented from mappel::Estimator< Model >.
Reimplemented in mappel::IterativeMaximizer< Model >.
Definition at line 378 of file estimator_impl.h.
References mappel::Estimator< Model >::clear_stats(), mappel::ThreadedEstimator< Model >::mtx, and mappel::ThreadedEstimator< Model >::num_threads.
Referenced by mappel::IterativeMaximizer< Model >::clear_stats().
template<class Model > virtual StencilT<Model> mappel::Estimator< Model >::compute_estimate (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, double & rllh) protected pure virtual inherited
Implemented in mappel::IterativeMaximizer< Model >, mappel::SimulatedAnnealingMaximizer< Model >, and mappel::CGaussMLE< Model >.
Referenced by mappel::Estimator< Model >::compute_estimate(), mappel::Estimator< Model >::compute_estimate_debug(), mappel::Estimator< Model >::estimate_max(), mappel::ThreadedEstimator< Model >::estimate_max_stack(), mappel::HeuristicEstimator< Model >::name(), mappel::CGaussHeuristicEstimator< Model >::name(), mappel::CGaussMLE< Model >::name(), mappel::SimulatedAnnealingMaximizer< Model >::name(), and mappel::Estimator< Model >::~Estimator().
template<class Model > void mappel::Estimator< Model >::compute_estimate (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamT< Model > & theta_est, double & rllh, MatT & obsI) protected virtual inherited
Default base class implementation computes rllh and obsI seperately from stencil This should be overridden by Estimator subclasses that already have access to this information.
Definition at line 183 of file estimator_impl.h.
References mappel::Estimator< Model >::compute_estimate(), mappel::Estimator< Model >::model, and mappel::methods::observed_information().
template<class Model > StencilT< Model > mappel::Estimator< Model >::compute_estimate_debug (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamVecT< Model > & sequence, VecT & sequence_rllh) protected virtual inherited
Estimators that produce a sequence of results (e.g. IterativeEstimators) can override this dummy debug implementation.
Reimplemented in mappel::IterativeMaximizer< Model >, mappel::SimulatedAnnealingMaximizer< Model >, and mappel::CGaussMLE< Model >.
Definition at line 242 of file estimator_impl.h.
References mappel::Estimator< Model >::compute_estimate(), mappel::Estimator< Model >::Error, mappel::Estimator< Model >::model, mappel::print_image(), and mappel::Estimator< Model >::record_exit_code().
Referenced by mappel::Estimator< Model >::estimate_max_debug(), mappel::CGaussMLE< Model >::name(), mappel::SimulatedAnnealingMaximizer< Model >::name(), and mappel::Estimator< Model >::~Estimator().
template<class Model > void mappel::Estimator< Model >::compute_profile_estimate (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, const IdxVecT & fixed_parameters, ParamT< Model > & theta_est, double & rllh) protected virtual inherited
Reimplemented in mappel::IterativeMaximizer< Model >.
Definition at line 192 of file estimator_impl.h.
References mappel::Estimator< Model >::model.
Referenced by mappel::ThreadedEstimator< Model >::estimate_profile_stack(), and mappel::Estimator< Model >::~Estimator().
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im) inherited
Definition at line 64 of file estimator_impl.h.
References mappel::Estimator< Model >::model.
Referenced by mappel::Estimator< Model >::estimate_max(), and mappel::Estimator< Model >::~Estimator().
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, const ParamT< Model > & theta_init) inherited
Definition at line 82 of file estimator_impl.h.
References mappel::Estimator< Model >::estimate_max(), and mappel::methods::objective::rllh().
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, double & rllh) inherited
Definition at line 73 of file estimator_impl.h.
References mappel::Estimator< Model >::estimate_max(), and mappel::Estimator< Model >::model.
template<class Model > StencilT< Model > mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, double & rllh) inherited
Definition at line 90 of file estimator_impl.h.
References mappel::Estimator< Model >::compute_estimate(), mappel::Estimator< Model >::Error, mappel::Estimator< Model >::model, mappel::print_image(), mappel::Estimator< Model >::record_exit_code(), and mappel::Estimator< Model >::record_walltime().
template<class Model > void mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, ParamT< Model > & theta, double & rllh, MatT & obsI) inherited
Definition at line 119 of file estimator_impl.h.
References mappel::Estimator< Model >::estimate_max(), and mappel::Estimator< Model >::model.
template<class Model > void mappel::Estimator< Model >::estimate_max (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamT< Model > & theta, double & rllh, MatT & obsI) inherited
Definition at line 128 of file estimator_impl.h.
References mappel::Estimator< Model >::compute_estimate(), mappel::Estimator< Model >::Error, mappel::print_image(), mappel::Estimator< Model >::record_exit_code(), mappel::Estimator< Model >::record_walltime(), and mappel::methods::objective::rllh().
template<class Model > void mappel::Estimator< Model >::estimate_max_debug (const ModelDataT< Model > & im, const ParamT< Model > & theta_init, ParamT< Model > & theta_est, double & rllh, MatT & obsI, MatT & sequence, VecT & sequence_rllh) inherited
Definition at line 158 of file estimator_impl.h.
References mappel::Estimator< Model >::compute_estimate_debug(), mappel::Estimator< Model >::model, mappel::methods::observed_information(), mappel::Estimator< Model >::record_walltime(), and mappel::methods::objective::rllh().
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > void mappel::Estimator< Model >::estimate_max_stack (const ModelDataStackT< Model > & im_stack, ParamVecT< Model > & theta_est_stack, VecT & rllh_stack, CubeT & obsI_stack) inherited
Definition at line 170 of file estimator_impl.h.
References mappel::Estimator< Model >::estimate_max_stack(), and mappel::Estimator< Model >::model.
template<class Model > void mappel::ThreadedEstimator< Model >::estimate_max_stack (const ModelDataStackT< Model > & im, const ParamVecT< Model > & theta_init, ParamVecT< Model > & theta, VecT & rllh, CubeT & obsI) virtual
Implements mappel::Estimator< Model >.
Definition at line 285 of file estimator_impl.h.
References mappel::Estimator< Model >::compute_estimate(), mappel::Estimator< Model >::Error, mappel::Estimator< Model >::model, mappel::ThreadedEstimator< Model >::num_threads, mappel::print_image(), mappel::ThreadedEstimator< Model >::record_exit_code(), mappel::Estimator< Model >::record_walltime(), and mappel::methods::objective::openmp::rllh_stack().
template<class Model > void mappel::ThreadedEstimator< Model >::estimate_profile_stack (const ModelDataT< Model > & data, const IdxVecT & fixed_parameters, const MatT & values, const ParamVecT< Model > & theta_init, VecT & profile_likelihood, ParamVecT< Model > & profile_parameters) virtual
Implements mappel::Estimator< Model >.
Definition at line 323 of file estimator_impl.h.
References mappel::Estimator< Model >::compute_profile_estimate(), mappel::Estimator< Model >::Error, mappel::Estimator< Model >::model, mappel::ThreadedEstimator< Model >::num_threads, mappel::print_image(), mappel::ThreadedEstimator< Model >::record_exit_code(), and mappel::Estimator< Model >::record_walltime().
template<class Model > StatsT mappel::ThreadedEstimator< Model >::get_debug_stats () virtual
Implements mappel::Estimator< Model >.
Reimplemented in mappel::IterativeMaximizer< Model >, mappel::SimulatedAnnealingMaximizer< Model >, mappel::CGaussMLE< Model >, mappel::CGaussHeuristicEstimator< Model >, and mappel::HeuristicEstimator< Model >.
Definition at line 372 of file estimator_impl.h.
References mappel::ThreadedEstimator< Model >::get_stats().
template<class Model > Model & mappel::Estimator< Model >::get_model () inherited
Definition at line 50 of file estimator_impl.h.
References mappel::Estimator< Model >::model.
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > StatsT mappel::ThreadedEstimator< Model >::get_stats () virtual
Reimplemented from mappel::Estimator< Model >.
Reimplemented in mappel::IterativeMaximizer< Model >, mappel::SimulatedAnnealingMaximizer< Model >, mappel::CGaussMLE< Model >, mappel::CGaussHeuristicEstimator< Model >, and mappel::HeuristicEstimator< Model >.
Definition at line 361 of file estimator_impl.h.
References mappel::Estimator< Model >::get_stats(), mappel::ThreadedEstimator< Model >::mtx, mappel::Estimator< Model >::num_estimations, mappel::ThreadedEstimator< Model >::num_threads, and mappel::Estimator< Model >::total_walltime.
Referenced by mappel::ThreadedEstimator< Model >::get_debug_stats(), mappel::HeuristicEstimator< Model >::get_debug_stats(), mappel::CGaussHeuristicEstimator< Model >::get_debug_stats(), mappel::CGaussMLE< Model >::get_debug_stats(), mappel::HeuristicEstimator< Model >::get_stats(), mappel::CGaussHeuristicEstimator< Model >::get_stats(), mappel::CGaussMLE< Model >::get_stats(), mappel::SimulatedAnnealingMaximizer< Model >::get_stats(), and mappel::IterativeMaximizer< Model >::get_stats().
template<class Model > virtual std::string mappel::Estimator< Model >::name () const pure virtual inherited
Implemented in mappel::TrustRegionMaximizer< Model >, mappel::QuasiNewtonMaximizer< Model >, mappel::NewtonMaximizer< Model >, mappel::NewtonDiagonalMaximizer< Model >, mappel::SimulatedAnnealingMaximizer< Model >, mappel::CGaussMLE< Model >, mappel::CGaussHeuristicEstimator< Model >, and mappel::HeuristicEstimator< Model >.
Referenced by mappel::Estimator< Model >::~Estimator().
template<class Model > void mappel::ThreadedEstimator< Model >::record_exit_code (ExitCode code) protected virtual
Implements mappel::Estimator< Model >.
Definition at line 386 of file estimator_impl.h.
References mappel::Estimator< Model >::exit_counts, mappel::Estimator< Model >::model, mappel::ThreadedEstimator< Model >::mtx, and mappel::methods::objective::rllh().
Referenced by mappel::IterativeMaximizer< Model >::backtrack(), mappel::CGaussMLE< Model >::compute_estimate(), mappel::CGaussMLE< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::convergence_test(), mappel::ThreadedEstimator< Model >::estimate_max_stack(), mappel::ThreadedEstimator< Model >::estimate_profile_stack(), mappel::HeuristicEstimator< Model >::get_debug_stats(), mappel::NewtonDiagonalMaximizer< Model >::maximize(), mappel::NewtonMaximizer< Model >::maximize(), mappel::QuasiNewtonMaximizer< Model >::maximize(), and mappel::TrustRegionMaximizer< Model >::maximize().
template<class Model > void mappel::Estimator< Model >::record_walltime (ClockT::time_point start_walltime, int nimages) protected inherited
Definition at line 266 of file estimator_impl.h.
References mappel::Estimator< Model >::num_estimations, and mappel::Estimator< Model >::total_walltime.
Referenced by mappel::Estimator< Model >::estimate_max(), mappel::Estimator< Model >::estimate_max_debug(), mappel::ThreadedEstimator< Model >::estimate_max_stack(), and mappel::ThreadedEstimator< Model >::estimate_profile_stack().
template<class Model > void mappel::Estimator< Model >::set_model (Model & new_model) inherited
Definition at line 54 of file estimator_impl.h.
References mappel::Estimator< Model >::model.
Referenced by mappel::Estimator< Model >::~Estimator().
Member Data Documentation
template<class Model > IdxVecT mappel::Estimator< Model >::exit_counts protected inherited
Definition at line 114 of file estimator.h.
Referenced by mappel::Estimator< Model >::clear_stats(), mappel::Estimator< Model >::get_stats(), and mappel::ThreadedEstimator< Model >::record_exit_code().
template<class Model > int mappel::ThreadedEstimator< Model >::max_threads protected
Definition at line 142 of file estimator.h.
template<class Model > Model& mappel::Estimator< Model >::model protected inherited
Definition at line 109 of file estimator.h.
Referenced by mappel::SimulatedAnnealingMaximizer< Model >::anneal(), mappel::IterativeMaximizer< Model >::backtrack(), mappel::Estimator< Model >::compute_estimate(), mappel::CGaussMLE< Model >::compute_estimate(), mappel::SimulatedAnnealingMaximizer< Model >::compute_estimate(), mappel::IterativeMaximizer< Model >::compute_estimate(), mappel::Estimator< Model >::compute_estimate_debug(), mappel::CGaussMLE< Model >::compute_estimate_debug(), mappel::SimulatedAnnealingMaximizer< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::Estimator< Model >::compute_profile_estimate(), mappel::IterativeMaximizer< Model >::compute_profile_estimate(), mappel::Estimator< Model >::estimate_max(), mappel::Estimator< Model >::estimate_max_debug(), mappel::Estimator< Model >::estimate_max_stack(), mappel::ThreadedEstimator< Model >::estimate_max_stack(), mappel::ThreadedEstimator< Model >::estimate_profile_stack(), mappel::HeuristicEstimator< Model >::get_debug_stats(), mappel::Estimator< Model >::get_model(), mappel::IterativeMaximizer< Model >::local_maximize(), mappel::NewtonDiagonalMaximizer< Model >::maximize(), mappel::NewtonMaximizer< Model >::maximize(), mappel::QuasiNewtonMaximizer< Model >::maximize(), mappel::TrustRegionMaximizer< Model >::maximize(), mappel::ThreadedEstimator< Model >::record_exit_code(), and mappel::Estimator< Model >::set_model().
template<class Model > std::mutex mappel::ThreadedEstimator< Model >::mtx protected
Definition at line 144 of file estimator.h.
Referenced by mappel::ThreadedEstimator< Model >::clear_stats(), mappel::IterativeMaximizer< Model >::clear_stats(), mappel::ThreadedEstimator< Model >::get_stats(), mappel::IterativeMaximizer< Model >::get_stats(), mappel::ThreadedEstimator< Model >::record_exit_code(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::Estimator< Model >::num_estimations = 0 protected inherited
Definition at line 112 of file estimator.h.
Referenced by mappel::Estimator< Model >::clear_stats(), mappel::Estimator< Model >::get_stats(), mappel::ThreadedEstimator< Model >::get_stats(), mappel::IterativeMaximizer< Model >::get_stats(), and mappel::Estimator< Model >::record_walltime().
template<class Model > int mappel::ThreadedEstimator< Model >::num_threads protected
Definition at line 143 of file estimator.h.
Referenced by mappel::ThreadedEstimator< Model >::clear_stats(), mappel::ThreadedEstimator< Model >::estimate_max_stack(), mappel::ThreadedEstimator< Model >::estimate_profile_stack(), and mappel::ThreadedEstimator< Model >::get_stats().
template<class Model > constexpr int mappel::Estimator< Model >::NumExitCodes = 9 static inherited
Definition at line 39 of file estimator.h.
template<class Model > double mappel::Estimator< Model >::total_walltime = 0. protected inherited
Definition at line 113 of file estimator.h.
Referenced by mappel::Estimator< Model >::clear_stats(), mappel::Estimator< Model >::get_stats(), mappel::ThreadedEstimator< Model >::get_stats(), and mappel::Estimator< Model >::record_walltime().
The documentation for this class was generated from the following files:
estimator.h
estimator_impl.h