Mappel: mappel::Gauss1DMLE Class Reference
mappel::Gauss1DMLE Class Reference
A 1D Gaussian with fixed PSF under an Poisson noise assumption and maximum-likelihood objective.
#include </home/travis/build/markjolah/Mappel/include/Mappel/Gauss1DMLE.h>
Public Types
using StencilVecT = std::vector< Stencil >
using ParamT = arma::vec
using ParamVecT = arma::mat
using ImageCoordT = uint32_t
using ImagePixelT = double
template<class CoordT >
using ImageSizeShapeT = CoordT
template<class CoordT >
using ImageSizeVecShapeT = arma::Col< CoordT >
using ImageSizeT = ImageSizeShapeT< ImageCoordT >
using ImageSizeVecT = ImageSizeVecShapeT< ImageCoordT >
template<class PixelT >
using ImageShapeT = arma::Col< PixelT >
template<class PixelT >
using ImageStackShapeT = arma::Mat< PixelT >
using ImageT = ImageShapeT< ImagePixelT >
using ImageStackT = ImageStackShapeT< ImagePixelT >
using ModelDataT = ImageT
using ModelDataStackT = ImageStackT
Public Member Functions
Gauss1DMLE (arma::Col< ImageCoordT > size, VecT psf_sigma, const std::string &prior_type=DefaultPriorType)
Gauss1DMLE (ImageSizeT size, double psf_sigma, const std::string &prior_type=DefaultPriorType)
Gauss1DMLE (ImageSizeT size, double psf_sigma, CompositeDist &&prior)
Gauss1DMLE (ImageSizeT size, double psf_sigma, const CompositeDist &prior)
Gauss1DMLE (const Gauss1DMLE &o)
Gauss1DMLE & operator= (const Gauss1DMLE &o)
Gauss1DMLE (Gauss1DMLE &&o)
Gauss1DMLE & operator= (Gauss1DMLE &&o)
double get_psf_sigma () const
double get_psf_sigma (IdxT idx) const
void set_psf_sigma (double new_psf_sigma)
void set_psf_sigma (const VecT &new_psf_sigma)
StatsT get_stats () const
Stencil make_stencil (const ParamT &theta, bool compute_derivatives=true) const
Make a new Model::Stencil object at theta.
double pixel_model_value (IdxT i, const Stencil &s) const
void pixel_grad (IdxT i, const Stencil &s, ParamT &pgrad) const
void pixel_grad2 (IdxT i, const Stencil &s, ParamT &pgrad2) const
void pixel_hess (IdxT i, const Stencil &s, MatT &hess) const
void pixel_hess_update (IdxT i, const Stencil &s, double dm_ratio_m1, double dmm_ratio, ParamT &grad, MatT &hess) const
pixel derivative inner loop calculations.
Stencil initial_theta_estimate (const ImageT &im) const
Fast, heuristic estimate of initial theta.
Stencil initial_theta_estimate (const ImageT &im, const ParamT &theta_init) const
IdxT get_num_params () const
void check_param_shape (const ParamT &theta) const
void check_param_shape (const ParamVecT &theta) const
void check_psf_sigma (double psf_sigma) const
void check_psf_sigma (const VecT &psf_sigma) const
ParamT make_param () const
template<class FillT >
ParamT make_param (FillT fill) const
ParamVecT make_param_stack (IdxT n) const
template<class FillT >
ParamVecT make_param_stack (IdxT n, FillT fill) const
MatT make_param_mat () const
template<class FillT >
MatT make_param_mat (FillT fill) const
CubeT make_param_mat_stack (IdxT n) const
template<class FillT >
CubeT make_param_mat_stack (IdxT n, FillT fill) const
CompositeDist & get_prior ()
const CompositeDist & get_prior () const
void set_prior (CompositeDist &&prior_)
void set_prior (const CompositeDist &prior_)
IdxT get_num_hyperparams () const
void set_hyperparams (const VecT &hyperparams)
VecT get_hyperparams () const
bool has_hyperparam (const std::string &name) const
double get_hyperparam_value (const std::string &name) const
int get_hyperparam_index (const std::string &name) const
void set_hyperparam_value (const std::string &name, double value)
void rename_hyperparam (const std::string &old_name, const std::string &new_name)
StringVecT get_param_names () const
void set_param_names (const StringVecT &desc)
StringVecT get_hyperparam_names () const
void set_hyperparam_names (const StringVecT &desc)
template<class RngT >
ParamT sample_prior (RngT &rng)
ParamT sample_prior ()
void set_bounds (const ParamT &lbound, const ParamT &ubound)
void set_lbound (const ParamT &lbound)
void set_ubound (const ParamT &ubound)
const ParamT & get_lbound () const
const ParamT & get_ubound () const
bool theta_in_bounds (const ParamT &theta) const
void bound_theta (ParamT &theta, double epsilon=bounds_epsilon) const
ParamT bounded_theta (const ParamT &theta, double epsilon=bounds_epsilon) const
ParamT reflected_theta (const ParamT &theta) const
BoolVecT theta_stack_in_bounds (const ParamVecT &theta) const
ParamVecT bounded_theta_stack (const ParamVecT &theta, double epsilon=bounds_epsilon) const
ParamVecT reflected_theta_stack (const ParamVecT &theta) const
ImageT make_image () const
ImageStackT make_image_stack (ImageCoordT n) const
ImageCoordT get_size_image_stack (const ImageStackT &stack) const
ImageT get_image_from_stack (const ImageStackT &stack, ImageCoordT n) const
template<class ImT >
void set_image_in_stack (ImageStackT &stack, ImageCoordT n, const ImT &im) const
ImageSizeT get_size () const
ImageCoordT get_size (IdxT idx) const
ImageCoordT get_num_pixels () const
void set_size (const ImageSizeT &size_)
void set_size (const arma::Col< ImageCoordT > &sz)
void check_image_shape (const ImageT &im) const
Check the shape of a single images is correct for model size.
void check_image_shape (const ImageStackT &ims) const
Check the shape of a stack of images is correct for model size.
void sample_mcmc_candidate (IdxT sample_index, ParamT &candidate, double step_scale=1.0)
void set_intensity_mcmc_sampling (double eta_I=-1)
void set_background_mcmc_sampling (double eta_bg=-1)
void set_mcmc_sigma_scale (double scale)
double get_mcmc_sigma_scale () const
IdxT get_mcmc_num_phases () const
Static Public Member Functions
static CompositeDist make_default_prior (IdxT size, const std::string &prior_type)
static CompositeDist make_default_prior_beta_position (IdxT size)
static CompositeDist make_default_prior_normal_position (IdxT size)
static CompositeDist make_prior_beta_position (IdxT size, double beta_xpos, double mean_I, double kappa_I, double mean_bg, double kappa_bg)
static CompositeDist make_prior_normal_position (IdxT size, double sigma_xpos, double mean_I, double kappa_I, double mean_bg, double kappa_bg)
static prior_hessian::TruncatedNormalDist make_prior_component_position_normal (IdxT size, double pos_sigma=default_sigma_pos)
static prior_hessian::ScaledSymmetricBetaDist make_prior_component_position_beta (IdxT size, double pos_beta=default_beta_pos)
static prior_hessian::TruncatedGammaDist make_prior_component_intensity (double mean=default_mean_I, double kappa=default_intensity_kappa)
static prior_hessian::TruncatedParetoDist make_prior_component_sigma (double min_sigma, double max_sigma, double alpha=default_alpha_sigma)
static void set_rng_seed (RngSeedT seed)
static ParallelRngManagerT & get_rng_manager ()
static ParallelRngGeneratorT & get_rng_generator ()
static void check_size (const ImageSizeT &size_)
Check the size argument for the model.
Static Public Attributes
static const std::string name
static const StringVecT prior_types
static const std::string DefaultPriorType = "Normal"
static const std::string DefaultSeperableInitEstimator = "TrustRegion"
static const double bounds_epsilon = 1.0E-6
static const double global_min_psf_sigma = 1E-1
static const double global_max_psf_sigma = 1E2
static const double default_beta_pos = 3
static const double default_sigma_pos = 1
static const double default_mean_I = 300
static const double default_max_I = INFINITY
static const double default_intensity_kappa = 2
static const double default_pixel_mean_bg = 4
static const double default_alpha_sigma = 2
static const ImageCoordT num_dim = 1
static const ImageCoordT global_min_size = 3
static const ImageCoordT global_max_size = 512
static const double global_default_mcmc_sigma_scale = 0.05
static const double global_max_mcmc_sigma_scale = 0.5
static const std::vector< std::string > estimator_names
Protected Member Functions
void set_mcmc_num_phases (IdxT num_phases)
Protected Attributes
double psf_sigma
CompositeDist prior
IdxT num_params
IdxT num_hyperparams
ParamT lbound
ParamT ubound
ImageSizeT size
double eta_x =0
double eta_I =0
double eta_bg =0
IdxT num_phases
double sigma_scale
Detailed Description
A 1D Gaussian with fixed PSF under an Poisson noise assumption and maximum-likelihood objective.
Model: Gauss1DModel - 1D Gaussian PSF with fixed PSF sigma Objective: PoissonNoise1DObjective - Poisson noise model for 1D Estimator: MLEstimator - Pure-likelihood estimator
Definition at line 23 of file Gauss1DMLE.h.
Member Typedef Documentation
using mappel::ImageFormat1DBase::ImageCoordT = uint32_t inherited
Image size coordinate storage type
Definition at line 25 of file ImageFormat1DBase.h.
using mappel::ImageFormat1DBase::ImagePixelT = double inherited
Image pixel storage type
Definition at line 26 of file ImageFormat1DBase.h.
template<class PixelT > using mappel::ImageFormat1DBase::ImageShapeT = arma::Col<PixelT> inherited
Shape of the data type for a single image
Definition at line 33 of file ImageFormat1DBase.h.
template<class CoordT > using mappel::ImageFormat1DBase::ImageSizeShapeT = CoordT inherited
Shape of the data type to store 1-image's coordinates
Definition at line 28 of file ImageFormat1DBase.h.
using mappel::ImageFormat1DBase::ImageSizeT = ImageSizeShapeT<ImageCoordT> inherited
Data type for a single image size
Definition at line 30 of file ImageFormat1DBase.h.
template<class CoordT > using mappel::ImageFormat1DBase::ImageSizeVecShapeT = arma::Col<CoordT> inherited
Shape of the data type to store a vector of image's coordinates
Definition at line 29 of file ImageFormat1DBase.h.
using mappel::ImageFormat1DBase::ImageSizeVecT = ImageSizeVecShapeT<ImageCoordT> inherited
Data type for a sequence of image sizes
Definition at line 31 of file ImageFormat1DBase.h.
template<class PixelT > using mappel::ImageFormat1DBase::ImageStackShapeT = arma::Mat<PixelT> inherited
Shape of the data type for a sequence of images
Definition at line 34 of file ImageFormat1DBase.h.
using mappel::ImageFormat1DBase::ImageStackT = ImageStackShapeT<ImagePixelT> inherited
Data type to represent a sequence of images
Definition at line 36 of file ImageFormat1DBase.h.
using mappel::ImageFormat1DBase::ImageT = ImageShapeT<ImagePixelT> inherited
Data type to represent single image
Definition at line 35 of file ImageFormat1DBase.h.
using mappel::PoissonNoise1DObjective::ModelDataStackT = ImageStackT inherited
Objective function data stack type: 1D double precision image stack, of images gain-corrected to approximate photons counts
Definition at line 26 of file PoissonNoise1DObjective.h.
using mappel::PoissonNoise1DObjective::ModelDataT = ImageT inherited
Objective function data type: 1D double precision image, gain-corrected to approximate photons counts
Definition at line 25 of file PoissonNoise1DObjective.h.
using mappel::PointEmitterModel::ParamT = arma::vec inherited
Parameter vector
Definition at line 47 of file PointEmitterModel.h.
using mappel::PointEmitterModel::ParamVecT = arma::mat inherited
Vector of parameter vectors
Definition at line 48 of file PointEmitterModel.h.
using mappel::Gauss1DModel::StencilVecT = std::vector<Stencil> inherited
Definition at line 49 of file Gauss1DModel.h.
Constructor & Destructor Documentation
mappel::Gauss1DMLE::Gauss1DMLE (arma::Col< ImageCoordT > size, VecT psf_sigma, const std::string & prior_type = DefaultPriorType)
Definition at line 11 of file Gauss1DMLE.cpp.
mappel::Gauss1DMLE::Gauss1DMLE (ImageSizeT size, double psf_sigma, const std::string & prior_type = DefaultPriorType)
Definition at line 15 of file Gauss1DMLE.cpp.
mappel::Gauss1DMLE::Gauss1DMLE (ImageSizeT size, double psf_sigma, CompositeDist && prior)
Definition at line 19 of file Gauss1DMLE.cpp.
mappel::Gauss1DMLE::Gauss1DMLE (ImageSizeT size, double psf_sigma, const CompositeDist & prior)
Definition at line 27 of file Gauss1DMLE.cpp.
mappel::Gauss1DMLE::Gauss1DMLE (const Gauss1DMLE & o)
Definition at line 35 of file Gauss1DMLE.cpp.
mappel::Gauss1DMLE::Gauss1DMLE (Gauss1DMLE && o)
Definition at line 43 of file Gauss1DMLE.cpp.
Member Function Documentation
void mappel::PointEmitterModel::bound_theta (ParamT & theta, double epsilon = bounds_epsilon) const inherited
Definition at line 248 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::check_param_shape(), mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, and mappel::PointEmitterModel::ubound.
PointEmitterModel::ParamT mappel::PointEmitterModel::bounded_theta (const ParamT & theta, double epsilon = bounds_epsilon) const inherited
Definition at line 265 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::check_param_shape(), mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, and mappel::PointEmitterModel::ubound.
Referenced by mappel::PointEmitterModel::bounded_theta_stack().
PointEmitterModel::ParamVecT mappel::PointEmitterModel::bounded_theta_stack (const ParamVecT & theta, double epsilon = bounds_epsilon) const inherited
Definition at line 307 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::bounded_theta(), mappel::PointEmitterModel::check_param_shape(), and mappel::PointEmitterModel::make_param_stack().
void ImageFormat1DBase::check_image_shape (const ImageT & im) const inherited
Check the shape of a single images is correct for model size.
Definition at line 59 of file ImageFormat1DBase.cpp.
References mappel::ImageFormat1DBase::size.
void ImageFormat1DBase::check_image_shape (const ImageStackT & ims) const inherited
Check the shape of a stack of images is correct for model size.
Definition at line 71 of file ImageFormat1DBase.cpp.
References mappel::ImageFormat1DBase::size.
void mappel::PointEmitterModel::check_param_shape (const ParamT & theta) const inherited
Definition at line 167 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::num_params.
Referenced by mappel::PointEmitterModel::bound_theta(), mappel::PointEmitterModel::bounded_theta(), mappel::PointEmitterModel::bounded_theta_stack(), mappel::PointEmitterModel::reflected_theta(), mappel::PointEmitterModel::reflected_theta_stack(), mappel::PointEmitterModel::theta_in_bounds(), and mappel::PointEmitterModel::theta_stack_in_bounds().
void mappel::PointEmitterModel::check_param_shape (const ParamVecT & theta) const inherited
Definition at line 176 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::num_params.
void mappel::PointEmitterModel::check_psf_sigma (double psf_sigma) const inherited
Definition at line 185 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::global_max_psf_sigma, and mappel::PointEmitterModel::global_min_psf_sigma.
Referenced by mappel::Gauss1DModel::Gauss1DModel(), mappel::Gauss2DModel::Gauss2DModel(), mappel::Gauss2DsModel::Gauss2DsModel(), mappel::Gauss1DsModel::set_max_sigma(), mappel::Gauss2DsModel::set_max_sigma(), mappel::Gauss1DsModel::set_min_sigma(), mappel::Gauss2DsModel::set_min_sigma(), mappel::Gauss1DModel::set_psf_sigma(), and mappel::Gauss2DModel::set_psf_sigma().
void mappel::PointEmitterModel::check_psf_sigma (const VecT & psf_sigma) const inherited
Definition at line 197 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::global_max_psf_sigma, and mappel::PointEmitterModel::global_min_psf_sigma.
void ImageFormat1DBase::check_size (const ImageSizeT & size_) static inherited
Check the size argument for the model.
Definition at line 39 of file ImageFormat1DBase.cpp.
References mappel::ImageFormat1DBase::global_max_size, and mappel::ImageFormat1DBase::global_min_size.
Referenced by mappel::ImageFormat1DBase::ImageFormat1DBase(), and mappel::ImageFormat1DBase::set_size().
int mappel::PointEmitterModel::get_hyperparam_index (const std::string & name) const inline inherited
Definition at line 236 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
StringVecT mappel::PointEmitterModel::get_hyperparam_names () const inline inherited
Definition at line 256 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
double mappel::PointEmitterModel::get_hyperparam_value (const std::string & name) const inline inherited
Definition at line 232 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
Referenced by mappel::MCMCAdaptor1D::set_background_mcmc_sampling(), and mappel::MCMCAdaptor1D::set_intensity_mcmc_sampling().
PointEmitterModel::ParamT mappel::PointEmitterModel::get_hyperparams () const inline inherited
Definition at line 224 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
ImageFormat1DBase::ImageT ImageFormat1DBase::get_image_from_stack (const ImageStackT & stack, ImageCoordT n) const inline inherited
Definition at line 108 of file ImageFormat1DBase.h.
const PointEmitterModel::ParamT & mappel::PointEmitterModel::get_lbound () const inline inherited
Definition at line 212 of file PointEmitterModel.h.
References mappel::PointEmitterModel::lbound.
Referenced by mappel::MCMCAdaptor1D::MCMCAdaptor1D(), mappel::MCMCAdaptor2D::MCMCAdaptor2D(), and mappel::MCMCAdaptor1D::set_background_mcmc_sampling().
IdxT mappel::MCMCAdaptorBase::get_mcmc_num_phases () const inherited
Definition at line 56 of file MCMCAdaptorBase.cpp.
References mappel::MCMCAdaptorBase::num_phases.
double mappel::MCMCAdaptorBase::get_mcmc_sigma_scale () const inherited
Definition at line 53 of file MCMCAdaptorBase.cpp.
References mappel::MCMCAdaptorBase::sigma_scale.
IdxT mappel::PointEmitterModel::get_num_hyperparams () const inline inherited
Definition at line 208 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_hyperparams.
IdxT mappel::PointEmitterModel::get_num_params () const inline inherited
Definition at line 160 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
ImageFormat1DBase::ImageCoordT ImageFormat1DBase::get_num_pixels () const inline inherited
Definition at line 82 of file ImageFormat1DBase.h.
References mappel::ImageFormat1DBase::size.
Referenced by mappel::ImageFormat1DBase::get_stats().
StringVecT mappel::PointEmitterModel::get_param_names () const inline inherited
Definition at line 248 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
CompositeDist & mappel::PointEmitterModel::get_prior () inline inherited
Definition at line 200 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
Referenced by mappel::Gauss2DModel::update_internal_1Dsum_estimators(), and mappel::Gauss2DsModel::update_internal_1Dsum_estimators().
const CompositeDist & mappel::PointEmitterModel::get_prior () const inline inherited
Definition at line 204 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
double mappel::Gauss1DModel::get_psf_sigma () const inline inherited
Definition at line 127 of file Gauss1DModel.h.
References mappel::Gauss1DModel::psf_sigma.
Referenced by mappel::Gauss1DModel::get_stats().
double mappel::Gauss1DModel::get_psf_sigma (IdxT idx) const inherited
Definition at line 131 of file Gauss1DModel.cpp.
References mappel::Gauss1DModel::psf_sigma.
ParallelRngGeneratorT & mappel::PointEmitterModel::get_rng_generator () static inherited
Definition at line 120 of file PointEmitterModel.cpp.
References mappel::rng_manager.
ParallelRngManagerT & mappel::PointEmitterModel::get_rng_manager () static inherited
Definition at line 115 of file PointEmitterModel.cpp.
References mappel::rng_manager.
ImageFormat1DBase::ImageSizeT ImageFormat1DBase::get_size () const inline inherited
Definition at line 71 of file ImageFormat1DBase.h.
References mappel::ImageFormat1DBase::size.
Referenced by mappel::ImageFormat1DBase::get_stats().
ImageFormat1DBase::ImageCoordT ImageFormat1DBase::get_size (IdxT idx) const inherited
Definition at line 20 of file ImageFormat1DBase.cpp.
References mappel::ImageFormat1DBase::size.
ImageFormat1DBase::ImageCoordT ImageFormat1DBase::get_size_image_stack (const ImageStackT & stack) const inline inherited
Definition at line 101 of file ImageFormat1DBase.h.
StatsT mappel::Gauss1DModel::get_stats () const inherited
Definition at line 178 of file Gauss1DModel.cpp.
References mappel::Gauss1DModel::get_psf_sigma(), mappel::MCMCAdaptor1D::get_stats(), mappel::ImageFormat1DBase::get_stats(), and mappel::PointEmitterModel::get_stats().
const PointEmitterModel::ParamT & mappel::PointEmitterModel::get_ubound () const inline inherited
Definition at line 216 of file PointEmitterModel.h.
References mappel::PointEmitterModel::ubound.
Referenced by mappel::Gauss2DsxyModel::get_max_sigma_ratio(), mappel::Gauss2DsModel::get_max_sigma_ratio(), mappel::MCMCAdaptor1D::MCMCAdaptor1D(), mappel::MCMCAdaptor2D::MCMCAdaptor2D(), mappel::MCMCAdaptor1D::set_background_mcmc_sampling(), and mappel::Gauss2DsModel::set_max_sigma_ratio().
bool mappel::PointEmitterModel::has_hyperparam (const std::string & name) const inline inherited
Definition at line 228 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
Gauss1DModel::Stencil mappel::Gauss1DModel::initial_theta_estimate (const ImageT & im) const inline inherited
Fast, heuristic estimate of initial theta.
Definition at line 169 of file Gauss1DModel.h.
References mappel::PointEmitterModel::make_param(), and mappel::Gauss1DModel::Stencil::theta.
Gauss1DModel::Stencil mappel::Gauss1DModel::initial_theta_estimate (const ImageT & im, const ParamT & theta_init) const inherited
Definition at line 207 of file Gauss1DModel.cpp.
References mappel::Gauss1DModel::Stencil::bg(), mappel::Gauss1DModel::Stencil::I(), mappel::Gauss1DModel::make_stencil(), mappel::PointEmitterModel::num_params, and mappel::ImageFormat1DBase::size.
CompositeDist mappel::Gauss1DModel::make_default_prior (IdxT size, const std::string & prior_type) static inherited
Definition at line 59 of file Gauss1DModel.cpp.
References mappel::istarts_with(), mappel::Gauss1DModel::make_default_prior_beta_position(), and mappel::Gauss1DModel::make_default_prior_normal_position().
CompositeDist mappel::Gauss1DModel::make_default_prior_beta_position (IdxT size) static inherited
Definition at line 80 of file Gauss1DModel.cpp.
References mappel::PointEmitterModel::default_pixel_mean_bg, mappel::PointEmitterModel::make_prior_component_intensity(), and mappel::PointEmitterModel::make_prior_component_position_beta().
Referenced by mappel::Gauss1DModel::make_default_prior().
CompositeDist mappel::Gauss1DModel::make_default_prior_normal_position (IdxT size) static inherited
Definition at line 90 of file Gauss1DModel.cpp.
References mappel::PointEmitterModel::default_pixel_mean_bg, mappel::PointEmitterModel::make_prior_component_intensity(), and mappel::PointEmitterModel::make_prior_component_position_normal().
Referenced by mappel::Gauss1DModel::make_default_prior().
ImageFormat1DBase::ImageT ImageFormat1DBase::make_image () const inline inherited
Definition at line 87 of file ImageFormat1DBase.h.
References mappel::ImageFormat1DBase::size.
ImageFormat1DBase::ImageStackT ImageFormat1DBase::make_image_stack (ImageCoordT n) const inline inherited
Definition at line 94 of file ImageFormat1DBase.h.
References mappel::ImageFormat1DBase::size.
PointEmitterModel::ParamT mappel::PointEmitterModel::make_param () const inline inherited
Definition at line 164 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
Referenced by mappel::Gauss1DModel::initial_theta_estimate(), mappel::Gauss1DsModel::initial_theta_estimate(), mappel::Gauss2DModel::initial_theta_estimate(), mappel::Gauss2DsxyModel::initial_theta_estimate(), mappel::Gauss2DsModel::initial_theta_estimate(), mappel::Gauss1DModel::pixel_hess_update(), mappel::Gauss1DsModel::pixel_hess_update(), mappel::Gauss2DModel::pixel_hess_update(), and mappel::Gauss2DsModel::pixel_hess_update().
template<class FillT > PointEmitterModel::ParamT mappel::PointEmitterModel::make_param (FillT fill) const inherited
Definition at line 181 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
MatT mappel::PointEmitterModel::make_param_mat () const inline inherited
Definition at line 172 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
template<class FillT > MatT mappel::PointEmitterModel::make_param_mat (FillT fill) const inherited
Definition at line 191 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
CubeT mappel::PointEmitterModel::make_param_mat_stack (IdxT n) const inline inherited
Definition at line 176 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
template<class FillT > CubeT mappel::PointEmitterModel::make_param_mat_stack (IdxT n, FillT fill) const inherited
Definition at line 196 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
PointEmitterModel::ParamVecT mappel::PointEmitterModel::make_param_stack (IdxT n) const inline inherited
Definition at line 168 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
Referenced by mappel::PointEmitterModel::bounded_theta_stack(), and mappel::PointEmitterModel::reflected_theta_stack().
template<class FillT > PointEmitterModel::ParamVecT mappel::PointEmitterModel::make_param_stack (IdxT n, FillT fill) const inherited
Definition at line 186 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
CompositeDist mappel::Gauss1DModel::make_prior_beta_position (IdxT size, double beta_xpos, double mean_I, double kappa_I, double mean_bg, double kappa_bg) static inherited
Definition at line 101 of file Gauss1DModel.cpp.
References mappel::PointEmitterModel::make_prior_component_intensity(), and mappel::PointEmitterModel::make_prior_component_position_beta().
Referenced by mappel::Gauss2DModel::make_internal_1Dsum_estimator().
prior_hessian::TruncatedGammaDist mappel::PointEmitterModel::make_prior_component_intensity (double mean = default_mean_I, double kappa = default_intensity_kappa) static inherited
Definition at line 98 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::default_max_I.
Referenced by mappel::Gauss1DsModel::make_default_prior_beta_position(), mappel::Gauss2DModel::make_default_prior_beta_position(), mappel::Gauss1DModel::make_default_prior_beta_position(), mappel::Gauss2DsModel::make_default_prior_beta_position(), mappel::Gauss2DModel::make_default_prior_normal_position(), mappel::Gauss1DsModel::make_default_prior_normal_position(), mappel::Gauss1DModel::make_default_prior_normal_position(), mappel::Gauss2DsModel::make_default_prior_normal_position(), mappel::Gauss2DModel::make_prior_beta_position(), mappel::Gauss1DsModel::make_prior_beta_position(), mappel::Gauss1DModel::make_prior_beta_position(), mappel::Gauss2DsModel::make_prior_beta_position(), mappel::Gauss2DModel::make_prior_normal_position(), mappel::Gauss1DsModel::make_prior_normal_position(), mappel::Gauss1DModel::make_prior_normal_position(), and mappel::Gauss2DsModel::make_prior_normal_position().
prior_hessian::ScaledSymmetricBetaDist mappel::PointEmitterModel::make_prior_component_position_beta (IdxT size, double pos_beta = default_beta_pos) static inherited
Definition at line 92 of file PointEmitterModel.cpp.
Referenced by mappel::Gauss1DsModel::make_default_prior_beta_position(), mappel::Gauss2DModel::make_default_prior_beta_position(), mappel::Gauss1DModel::make_default_prior_beta_position(), mappel::Gauss2DsModel::make_default_prior_beta_position(), mappel::Gauss1DsModel::make_prior_beta_position(), mappel::Gauss2DModel::make_prior_beta_position(), mappel::Gauss1DModel::make_prior_beta_position(), and mappel::Gauss2DsModel::make_prior_beta_position().
prior_hessian::TruncatedNormalDist mappel::PointEmitterModel::make_prior_component_position_normal (IdxT size, double pos_sigma = default_sigma_pos) static inherited
Definition at line 85 of file PointEmitterModel.cpp.
Referenced by mappel::Gauss1DsModel::make_default_prior_normal_position(), mappel::Gauss2DModel::make_default_prior_normal_position(), mappel::Gauss1DModel::make_default_prior_normal_position(), mappel::Gauss2DsModel::make_default_prior_normal_position(), mappel::Gauss2DModel::make_prior_normal_position(), mappel::Gauss1DsModel::make_prior_normal_position(), mappel::Gauss1DModel::make_prior_normal_position(), and mappel::Gauss2DsModel::make_prior_normal_position().
prior_hessian::TruncatedParetoDist mappel::PointEmitterModel::make_prior_component_sigma (double min_sigma, double max_sigma, double alpha = default_alpha_sigma) static inherited
Definition at line 104 of file PointEmitterModel.cpp.
Referenced by mappel::Gauss1DsModel::make_default_prior_beta_position(), mappel::Gauss2DsModel::make_default_prior_beta_position(), mappel::Gauss1DsModel::make_default_prior_normal_position(), mappel::Gauss2DsModel::make_default_prior_normal_position(), mappel::Gauss1DsModel::make_prior_beta_position(), mappel::Gauss2DsModel::make_prior_beta_position(), mappel::Gauss1DsModel::make_prior_normal_position(), and mappel::Gauss2DsModel::make_prior_normal_position().
CompositeDist mappel::Gauss1DModel::make_prior_normal_position (IdxT size, double sigma_xpos, double mean_I, double kappa_I, double mean_bg, double kappa_bg) static inherited
Definition at line 114 of file Gauss1DModel.cpp.
References mappel::PointEmitterModel::make_prior_component_intensity(), and mappel::PointEmitterModel::make_prior_component_position_normal().
Referenced by mappel::Gauss2DModel::make_internal_1Dsum_estimator().
Gauss1DModel::Stencil mappel::Gauss1DModel::make_stencil (const ParamT & theta, bool compute_derivatives = true) const inline inherited
Make a new Model::Stencil object at theta.
Stencils store all of the important calculations necessary for evaluating the log-likelihood and its derivatives at a particular theta (parameter) value.
This allows re-use of the most expensive computations. Stencils can be easily passed around by reference, and most functions in the mappel::methods namespace accept a const Stencil reference in place of the model parameter.
Throws mappel::ModelBoundsError if not model.theta_in_bounds(theta).
If derivatives will not be computed with this stencil set compute_derivatives=false
Parameters
theta Prameter to evaluate at
compute_derivatives True to also prepare for derivative computations
Returns
A new Stencil object ready to compute with
Definition at line 116 of file Gauss1DModel.h.
References mappel::Gauss1DModel::Stencil::Stencil(), and mappel::PointEmitterModel::theta_in_bounds().
Referenced by mappel::Gauss1DModel::initial_theta_estimate().
Gauss1DMLE & mappel::Gauss1DMLE::operator= (const Gauss1DMLE & o)
Definition at line 51 of file Gauss1DMLE.cpp.
References mappel::MLEstimator::operator=(), mappel::PoissonNoise1DObjective::operator=(), mappel::Gauss1DModel::operator=(), and mappel::PointEmitterModel::operator=().
Gauss1DMLE & mappel::Gauss1DMLE::operator= (Gauss1DMLE && o)
Definition at line 62 of file Gauss1DMLE.cpp.
References mappel::MLEstimator::operator=(), mappel::PoissonNoise1DObjective::operator=(), mappel::Gauss1DModel::operator=(), and mappel::PointEmitterModel::operator=().
void mappel::Gauss1DModel::pixel_grad (IdxT i, const Stencil & s, ParamT & pgrad) const inline inherited
Definition at line 141 of file Gauss1DModel.h.
References mappel::Gauss1DModel::Stencil::DX, mappel::Gauss1DModel::Stencil::I(), and mappel::Gauss1DModel::Stencil::X.
Referenced by mappel::Gauss1DModel::pixel_hess_update().
void mappel::Gauss1DModel::pixel_grad2 (IdxT i, const Stencil & s, ParamT & pgrad2) const inline inherited
Definition at line 150 of file Gauss1DModel.h.
References mappel::Gauss1DModel::Stencil::DXS, mappel::Gauss1DModel::Stencil::I(), and mappel::Gauss1DModel::psf_sigma.
void mappel::Gauss1DModel::pixel_hess (IdxT i, const Stencil & s, MatT & hess) const inline inherited
Definition at line 159 of file Gauss1DModel.h.
References mappel::Gauss1DModel::Stencil::DX, mappel::Gauss1DModel::Stencil::DXS, mappel::Gauss1DModel::Stencil::I(), and mappel::Gauss1DModel::psf_sigma.
void mappel::Gauss1DModel::pixel_hess_update (IdxT i, const Stencil & s, double dm_ratio_m1, double dmm_ratio, ParamT & grad, MatT & hess) const inherited
pixel derivative inner loop calculations.
Definition at line 191 of file Gauss1DModel.cpp.
References mappel::Gauss1DModel::Stencil::DXS, mappel::Gauss1DModel::Stencil::I(), mappel::PointEmitterModel::make_param(), mappel::Gauss1DModel::pixel_grad(), and mappel::Gauss1DModel::psf_sigma.
double mappel::Gauss1DModel::pixel_model_value (IdxT i, const Stencil & s) const inline inherited
Definition at line 135 of file Gauss1DModel.h.
References mappel::Gauss1DModel::Stencil::bg(), mappel::Gauss1DModel::Stencil::I(), and mappel::Gauss1DModel::Stencil::X.
PointEmitterModel::ParamT mappel::PointEmitterModel::reflected_theta (const ParamT & theta) const inherited
Definition at line 276 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::check_param_shape(), mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, and mappel::PointEmitterModel::ubound.
Referenced by mappel::PointEmitterModel::reflected_theta_stack().
PointEmitterModel::ParamVecT mappel::PointEmitterModel::reflected_theta_stack (const ParamVecT & theta) const inherited
Definition at line 317 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::check_param_shape(), mappel::PointEmitterModel::make_param_stack(), and mappel::PointEmitterModel::reflected_theta().
void mappel::PointEmitterModel::rename_hyperparam (const std::string & old_name, const std::string & new_name) inline inherited
Definition at line 244 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
void mappel::MCMCAdaptor1D::sample_mcmc_candidate (IdxT sample_index, ParamT & candidate, double step_scale = 1.0) inherited
Definition at line 108 of file MCMCAdaptor1D.cpp.
References mappel::MCMCAdaptor1D::eta_bg, mappel::MCMCAdaptor1D::eta_I, mappel::MCMCAdaptor1D::eta_x, mappel::MCMCAdaptorBase::num_phases, and mappel::rng_manager.
template<class RngT > PointEmitterModel::ParamT mappel::PointEmitterModel::sample_prior (RngT & rng) inherited
Definition at line 264 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
PointEmitterModel::ParamT mappel::PointEmitterModel::sample_prior () inline inherited
Definition at line 268 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior, and mappel::rng_manager.
void mappel::MCMCAdaptor1D::set_background_mcmc_sampling (double eta_bg = -1) inherited
Definition at line 81 of file MCMCAdaptor1D.cpp.
References mappel::PointEmitterModel::default_pixel_mean_bg, mappel::MCMCAdaptor1D::eta_bg, mappel::PointEmitterModel::get_hyperparam_value(), mappel::PointEmitterModel::get_lbound(), mappel::PointEmitterModel::get_ubound(), and mappel::MCMCAdaptorBase::sigma_scale.
Referenced by mappel::MCMCAdaptor1D::MCMCAdaptor1D().
void mappel::PointEmitterModel::set_bounds (const ParamT & lbound_, const ParamT & ubound_) inherited
Box-type parameter bounds
Modifies the prior bounds to prevent sampling outside the valid box-constraints.
Definition at line 213 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::bounds_epsilon, mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, mappel::PointEmitterModel::prior, and mappel::PointEmitterModel::ubound.
void mappel::PointEmitterModel::set_hyperparam_names (const StringVecT & desc) inline inherited
Definition at line 260 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
void mappel::PointEmitterModel::set_hyperparam_value (const std::string & name, double value) inline inherited
Definition at line 240 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
void mappel::PointEmitterModel::set_hyperparams (const VecT & hyperparams) inline inherited
Definition at line 220 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
Referenced by mappel::Gauss2DModel::set_hyperparams(), and mappel::Gauss2DsModel::set_hyperparams().
template<class ImT > void ImageFormat1DBase::set_image_in_stack (ImageStackT & stack, ImageCoordT n, const ImT & im) const inherited
Definition at line 115 of file ImageFormat1DBase.h.
void mappel::MCMCAdaptor1D::set_intensity_mcmc_sampling (double eta_I = -1) inherited
Definition at line 65 of file MCMCAdaptor1D.cpp.
References mappel::PointEmitterModel::default_mean_I, mappel::MCMCAdaptor1D::eta_I, mappel::PointEmitterModel::get_hyperparam_value(), and mappel::MCMCAdaptorBase::sigma_scale.
Referenced by mappel::MCMCAdaptor1D::MCMCAdaptor1D().
void mappel::PointEmitterModel::set_lbound (const ParamT & lbound) inherited
Definition at line 226 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::bounds_epsilon, mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, mappel::PointEmitterModel::prior, and mappel::PointEmitterModel::ubound.
Referenced by mappel::Gauss1DsModel::set_min_sigma().
void mappel::MCMCAdaptorBase::set_mcmc_num_phases (IdxT num_phases) protected inherited
Definition at line 59 of file MCMCAdaptorBase.cpp.
References mappel::MCMCAdaptorBase::num_phases.
Referenced by mappel::MCMCAdaptor1Ds::MCMCAdaptor1Ds(), and mappel::MCMCAdaptor2Ds::MCMCAdaptor2Ds().
void mappel::MCMCAdaptorBase::set_mcmc_sigma_scale (double scale) inherited
Definition at line 39 of file MCMCAdaptorBase.cpp.
References mappel::MCMCAdaptorBase::global_max_mcmc_sigma_scale, and mappel::MCMCAdaptorBase::sigma_scale.
void mappel::PointEmitterModel::set_param_names (const StringVecT & desc) inline inherited
Definition at line 252 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
void mappel::PointEmitterModel::set_prior (CompositeDist && prior_) inherited
Definition at line 158 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_hyperparams, mappel::PointEmitterModel::num_params, mappel::PointEmitterModel::prior, and mappel::PointEmitterModel::ubound.
Referenced by mappel::Gauss2DModel::set_prior(), and mappel::Gauss2DsModel::set_prior().
void mappel::PointEmitterModel::set_prior (const CompositeDist & prior_) inherited
Definition at line 149 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_hyperparams, mappel::PointEmitterModel::num_params, mappel::PointEmitterModel::prior, and mappel::PointEmitterModel::ubound.
void mappel::Gauss1DModel::set_psf_sigma (double new_psf_sigma) inherited
Definition at line 125 of file Gauss1DModel.cpp.
References mappel::PointEmitterModel::check_psf_sigma(), and mappel::Gauss1DModel::psf_sigma.
Referenced by mappel::Gauss1DModel::set_psf_sigma(), and mappel::Gauss2DModel::set_psf_sigma().
void mappel::Gauss1DModel::set_psf_sigma (const VecT & new_psf_sigma) inline inherited
Definition at line 131 of file Gauss1DModel.h.
References mappel::Gauss1DModel::set_psf_sigma().
void mappel::PointEmitterModel::set_rng_seed (RngSeedT seed) static inherited
Definition at line 110 of file PointEmitterModel.cpp.
References mappel::rng_manager.
void ImageFormat1DBase::set_size (const ImageSizeT & size_) inherited
Definition at line 30 of file ImageFormat1DBase.cpp.
References mappel::ImageFormat1DBase::check_size(), and mappel::ImageFormat1DBase::size.
Referenced by mappel::ImageFormat1DBase::set_size(), mappel::Gauss2DModel::set_size(), and mappel::Gauss2DsModel::set_size().
void ImageFormat1DBase::set_size (const arma::Col< ImageCoordT > & sz) inline inherited
Definition at line 75 of file ImageFormat1DBase.h.
References mappel::ImageFormat1DBase::set_size().
void mappel::PointEmitterModel::set_ubound (const ParamT & ubound) inherited
Definition at line 237 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::bounds_epsilon, mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, mappel::PointEmitterModel::prior, and mappel::PointEmitterModel::ubound.
Referenced by mappel::Gauss1DsModel::set_max_sigma(), and mappel::Gauss2DsModel::set_max_sigma_ratio().
bool mappel::PointEmitterModel::theta_in_bounds (const ParamT & theta) const inherited
Definition at line 257 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::check_param_shape(), mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, and mappel::PointEmitterModel::ubound.
Referenced by mappel::Gauss2DModel::initial_theta_estimate(), mappel::Gauss2DsModel::initial_theta_estimate(), mappel::Gauss1DModel::make_stencil(), mappel::Gauss1DsModel::make_stencil(), mappel::Gauss2DModel::make_stencil(), mappel::Gauss2DsxyModel::make_stencil(), mappel::Gauss2DsModel::make_stencil(), and mappel::PointEmitterModel::theta_stack_in_bounds().
BoolVecT mappel::PointEmitterModel::theta_stack_in_bounds (const ParamVecT & theta) const inherited
Definition at line 297 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::check_param_shape(), and mappel::PointEmitterModel::theta_in_bounds().
Member Data Documentation
const double mappel::PointEmitterModel::bounds_epsilon = 1.0E-6 static inherited
Distance from the boundary to constrain in bound_theta and bounded_theta methods
Definition at line 52 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::set_bounds(), mappel::PointEmitterModel::set_lbound(), mappel::Gauss2DsModel::set_max_sigma_ratio(), and mappel::PointEmitterModel::set_ubound().
const double mappel::PointEmitterModel::default_alpha_sigma = 2 static inherited
Default per-pixel background gamma distribution shape
Definition at line 62 of file PointEmitterModel.h.
const double mappel::PointEmitterModel::default_beta_pos = 3 static inherited
Default position parameter in symmetric beta-distributions
Definition at line 56 of file PointEmitterModel.h.
const double mappel::PointEmitterModel::default_intensity_kappa = 2 static inherited
Default shape for intensity gamma distributions
Definition at line 60 of file PointEmitterModel.h.
const double mappel::PointEmitterModel::default_max_I = INFINITY static inherited
Default maximum emitter intensity
Definition at line 59 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::make_prior_component_intensity().
const double mappel::PointEmitterModel::default_mean_I = 300 static inherited
Default emitter intensity mean
Definition at line 58 of file PointEmitterModel.h.
Referenced by mappel::MCMCAdaptor1D::set_intensity_mcmc_sampling().
const double mappel::PointEmitterModel::default_pixel_mean_bg = 4 static inherited
Default per-pixel mean background counts
Definition at line 61 of file PointEmitterModel.h.
Referenced by mappel::Gauss1DsModel::make_default_prior_beta_position(), mappel::Gauss2DModel::make_default_prior_beta_position(), mappel::Gauss1DModel::make_default_prior_beta_position(), mappel::Gauss2DsModel::make_default_prior_beta_position(), mappel::Gauss1DsModel::make_default_prior_normal_position(), mappel::Gauss2DModel::make_default_prior_normal_position(), mappel::Gauss1DModel::make_default_prior_normal_position(), mappel::Gauss2DsModel::make_default_prior_normal_position(), and mappel::MCMCAdaptor1D::set_background_mcmc_sampling().
const double mappel::PointEmitterModel::default_sigma_pos = 1 static inherited
Default position parameter in symmetric beta-distributions
Definition at line 57 of file PointEmitterModel.h.
const std::string mappel::Gauss1DModel::DefaultPriorType = "Normal" static inherited
Definition at line 53 of file Gauss1DModel.h.
Referenced by mappel::Gauss1DModel::operator=().
const std::string mappel::PointEmitterModel::DefaultSeperableInitEstimator = "TrustRegion" static inherited
Estimator name to use in 1D separable initializations
Definition at line 49 of file PointEmitterModel.h.
Referenced by mappel::Gauss2DModel::initial_theta_estimate(), mappel::Gauss2DsxyModel::initial_theta_estimate(), and mappel::Gauss2DsModel::initial_theta_estimate().
const std::vector< std::string > mappel::PoissonNoise1DObjective::estimator_names static inherited
Definition at line 24 of file PoissonNoise1DObjective.h.
double mappel::MCMCAdaptor1D::eta_bg =0 protected inherited
The standard deviation for the normally distributed perturbation to theta_bg in the random walk MCMC sampling
Definition at line 32 of file MCMCAdaptor1D.h.
Referenced by mappel::MCMCAdaptor1D::get_stats(), mappel::MCMCAdaptor1D::MCMCAdaptor1D(), mappel::MCMCAdaptor1D::operator=(), mappel::MCMCAdaptor2D::sample_mcmc_candidate(), mappel::MCMCAdaptor2Ds::sample_mcmc_candidate(), mappel::MCMCAdaptor1Ds::sample_mcmc_candidate(), mappel::MCMCAdaptor1D::sample_mcmc_candidate(), and mappel::MCMCAdaptor1D::set_background_mcmc_sampling().
double mappel::MCMCAdaptor1D::eta_I =0 protected inherited
The standard deviation for the normally distributed perturbation to theta_I in the random walk MCMC sampling
Definition at line 31 of file MCMCAdaptor1D.h.
Referenced by mappel::MCMCAdaptor1D::get_stats(), mappel::MCMCAdaptor1D::MCMCAdaptor1D(), mappel::MCMCAdaptor1D::operator=(), mappel::MCMCAdaptor2D::sample_mcmc_candidate(), mappel::MCMCAdaptor2Ds::sample_mcmc_candidate(), mappel::MCMCAdaptor1Ds::sample_mcmc_candidate(), mappel::MCMCAdaptor1D::sample_mcmc_candidate(), and mappel::MCMCAdaptor1D::set_intensity_mcmc_sampling().
double mappel::MCMCAdaptor1D::eta_x =0 protected inherited
The standard deviation for the normally distributed perturbation to theta_x in the random walk MCMC sampling
Definition at line 30 of file MCMCAdaptor1D.h.
Referenced by mappel::MCMCAdaptor1D::get_stats(), mappel::MCMCAdaptor1D::MCMCAdaptor1D(), mappel::MCMCAdaptor1D::operator=(), mappel::MCMCAdaptor2D::sample_mcmc_candidate(), mappel::MCMCAdaptor1Ds::sample_mcmc_candidate(), mappel::MCMCAdaptor2Ds::sample_mcmc_candidate(), and mappel::MCMCAdaptor1D::sample_mcmc_candidate().
const double mappel::MCMCAdaptorBase::global_default_mcmc_sigma_scale = 0.05 static inherited
Definition at line 16 of file MCMCAdaptorBase.h.
Referenced by mappel::MCMCAdaptor1Ds::MCMCAdaptor1Ds(), mappel::MCMCAdaptor2D::MCMCAdaptor2D(), and mappel::MCMCAdaptor2Ds::MCMCAdaptor2Ds().
const double mappel::MCMCAdaptorBase::global_max_mcmc_sigma_scale = 0.5 static inherited
Definition at line 17 of file MCMCAdaptorBase.h.
Referenced by mappel::MCMCAdaptorBase::MCMCAdaptorBase(), and mappel::MCMCAdaptorBase::set_mcmc_sigma_scale().
const double mappel::PointEmitterModel::global_max_psf_sigma = 1E2 static inherited
Global maxmimum for any psf_sigma. Sizes above this value are invalid, and nowhere near useful for practical point emitter localization
Definition at line 54 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::check_psf_sigma().
const ImageFormat1DBase::ImageCoordT ImageFormat1DBase::global_max_size = 512 static inherited
Maximum size along any dimension of the image. This is insanely big to catch obvious errors
Definition at line 40 of file ImageFormat1DBase.h.
Referenced by mappel::ImageFormat1DBase::check_size().
const double mappel::PointEmitterModel::global_min_psf_sigma = 1E-1 static inherited
Global minimum for any psf_sigma. Sizes below this value are invalid, and nowhere near useful for practical point emitter localization
Definition at line 53 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::check_psf_sigma().
const ImageFormat1DBase::ImageCoordT ImageFormat1DBase::global_min_size = 3 static inherited
Minimum size along any dimension of the image.
Definition at line 39 of file ImageFormat1DBase.h.
Referenced by mappel::ImageFormat1DBase::check_size().
ParamT mappel::PointEmitterModel::lbound protected inherited
Definition at line 148 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::bound_theta(), mappel::PointEmitterModel::bounded_theta(), mappel::PointEmitterModel::get_lbound(), mappel::PointEmitterModel::get_stats(), mappel::Gauss1DsModel::initial_theta_estimate(), mappel::Gauss2DModel::initial_theta_estimate(), mappel::Gauss2DsModel::initial_theta_estimate(), mappel::PointEmitterModel::operator=(), mappel::PointEmitterModel::reflected_theta(), mappel::PointEmitterModel::set_bounds(), mappel::PointEmitterModel::set_lbound(), mappel::PointEmitterModel::set_prior(), mappel::PointEmitterModel::set_ubound(), and mappel::PointEmitterModel::theta_in_bounds().
const std::string mappel::Gauss1DMLE::name static
Definition at line 34 of file Gauss1DMLE.h.
const ImageFormat1DBase::ImageCoordT ImageFormat1DBase::num_dim = 1 static inherited
Number of image dimensions.
Definition at line 38 of file ImageFormat1DBase.h.
Referenced by mappel::ImageFormat1DBase::get_stats().
IdxT mappel::PointEmitterModel::num_hyperparams protected inherited
Definition at line 147 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::get_num_hyperparams(), mappel::PointEmitterModel::get_stats(), mappel::PointEmitterModel::operator=(), and mappel::PointEmitterModel::set_prior().
IdxT mappel::PointEmitterModel::num_params protected inherited
Definition at line 146 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::bound_theta(), mappel::PointEmitterModel::bounded_theta(), mappel::PointEmitterModel::check_param_shape(), mappel::PointEmitterModel::get_num_params(), mappel::PointEmitterModel::get_stats(), mappel::Gauss1DModel::initial_theta_estimate(), mappel::Gauss2DModel::initial_theta_estimate(), mappel::Gauss2DsModel::initial_theta_estimate(), mappel::PointEmitterModel::make_param(), mappel::PointEmitterModel::make_param_mat(), mappel::PointEmitterModel::make_param_mat_stack(), mappel::PointEmitterModel::make_param_stack(), mappel::PointEmitterModel::operator=(), mappel::PointEmitterModel::reflected_theta(), mappel::PointEmitterModel::set_bounds(), mappel::PointEmitterModel::set_lbound(), mappel::PointEmitterModel::set_prior(), mappel::PointEmitterModel::set_ubound(), and mappel::PointEmitterModel::theta_in_bounds().
IdxT mappel::MCMCAdaptorBase::num_phases protected inherited
The number of different sampling phases for candidate selection MCMC. Each phase changes a different subset of variables.
Definition at line 29 of file MCMCAdaptorBase.h.
Referenced by mappel::MCMCAdaptorBase::get_mcmc_num_phases(), mappel::MCMCAdaptorBase::get_stats(), mappel::MCMCAdaptor2Ds::sample_mcmc_candidate(), mappel::MCMCAdaptor2D::sample_mcmc_candidate(), mappel::MCMCAdaptor1Ds::sample_mcmc_candidate(), mappel::MCMCAdaptor1D::sample_mcmc_candidate(), and mappel::MCMCAdaptorBase::set_mcmc_num_phases().
CompositeDist mappel::PointEmitterModel::prior protected inherited
Definition at line 145 of file PointEmitterModel.h.
Referenced by mappel::Gauss2DModel::debug_internal_sum_model_y(), mappel::Gauss2DsModel::debug_internal_sum_model_y(), mappel::Gauss2DModel::Gauss2DModel(), mappel::Gauss2DsModel::Gauss2DsModel(), mappel::PointEmitterModel::get_hyperparam_index(), mappel::PointEmitterModel::get_hyperparam_names(), mappel::PointEmitterModel::get_hyperparam_value(), mappel::PointEmitterModel::get_hyperparams(), mappel::Gauss1DsModel::get_max_sigma(), mappel::Gauss1DsModel::get_min_sigma(), mappel::PointEmitterModel::get_param_names(), mappel::PointEmitterModel::get_prior(), mappel::PointEmitterModel::get_stats(), mappel::PointEmitterModel::has_hyperparam(), mappel::PointEmitterModel::operator=(), mappel::PointEmitterModel::PointEmitterModel(), mappel::PointEmitterModel::rename_hyperparam(), mappel::PointEmitterModel::sample_prior(), mappel::PointEmitterModel::set_bounds(), mappel::PointEmitterModel::set_hyperparam_names(), mappel::PointEmitterModel::set_hyperparam_value(), mappel::PointEmitterModel::set_hyperparams(), mappel::PointEmitterModel::set_lbound(), mappel::Gauss1DsModel::set_max_sigma(), mappel::Gauss1DsModel::set_min_sigma(), mappel::PointEmitterModel::set_param_names(), mappel::PointEmitterModel::set_prior(), and mappel::PointEmitterModel::set_ubound().
const StringVecT mappel::Gauss1DModel::prior_types static inherited
Initial value:
= { "Beta",
                                                       "Normal"
                                                      }
Definition at line 52 of file Gauss1DModel.h.
Referenced by mappel::Gauss1DModel::operator=().
double mappel::Gauss1DModel::psf_sigma protected inherited
Standard deviation of the fixed-sigma 1D Gaussian PSF in pixels
Definition at line 90 of file Gauss1DModel.h.
Referenced by mappel::Gauss1DModel::Stencil::compute_derivatives(), mappel::Gauss1DModel::get_psf_sigma(), mappel::Gauss1DModel::operator=(), mappel::Gauss1DModel::pixel_grad2(), mappel::Gauss1DModel::pixel_hess(), mappel::Gauss1DModel::pixel_hess_update(), mappel::Gauss1DModel::set_psf_sigma(), and mappel::Gauss1DModel::Stencil::Stencil().
double mappel::MCMCAdaptorBase::sigma_scale protected inherited
A scaling factor for step sizes as a fraction of the size of the domain dimension we are walking in. (0.05 default)
Definition at line 30 of file MCMCAdaptorBase.h.
Referenced by mappel::MCMCAdaptorBase::get_mcmc_sigma_scale(), mappel::MCMCAdaptorBase::get_stats(), mappel::MCMCAdaptor1D::MCMCAdaptor1D(), mappel::MCMCAdaptor1Ds::MCMCAdaptor1Ds(), mappel::MCMCAdaptor2D::MCMCAdaptor2D(), mappel::MCMCAdaptor2Ds::MCMCAdaptor2Ds(), mappel::MCMCAdaptor1D::set_background_mcmc_sampling(), mappel::MCMCAdaptor1D::set_intensity_mcmc_sampling(), and mappel::MCMCAdaptorBase::set_mcmc_sigma_scale().
ImageSizeT mappel::ImageFormat1DBase::size protected inherited
Number of pixels in X dimension for 1D image
Definition at line 65 of file ImageFormat1DBase.h.
Referenced by mappel::ImageFormat1DBase::check_image_shape(), mappel::Gauss1DsModel::Stencil::compute_derivatives(), mappel::Gauss1DModel::Stencil::compute_derivatives(), mappel::ImageFormat1DBase::get_num_pixels(), mappel::ImageFormat1DBase::get_size(), mappel::Gauss1DModel::initial_theta_estimate(), mappel::Gauss1DsModel::initial_theta_estimate(), mappel::ImageFormat1DBase::make_image(), mappel::ImageFormat1DBase::make_image_stack(), mappel::ImageFormat1DBase::set_size(), mappel::Gauss1DsModel::Stencil::Stencil(), and mappel::Gauss1DModel::Stencil::Stencil().
ParamT mappel::PointEmitterModel::ubound protected inherited
Definition at line 148 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::bound_theta(), mappel::PointEmitterModel::bounded_theta(), mappel::PointEmitterModel::get_stats(), mappel::PointEmitterModel::get_ubound(), mappel::Gauss1DsModel::initial_theta_estimate(), mappel::Gauss2DModel::initial_theta_estimate(), mappel::Gauss2DsModel::initial_theta_estimate(), mappel::PointEmitterModel::operator=(), mappel::PointEmitterModel::reflected_theta(), mappel::PointEmitterModel::set_bounds(), mappel::PointEmitterModel::set_lbound(), mappel::PointEmitterModel::set_prior(), mappel::PointEmitterModel::set_ubound(), and mappel::PointEmitterModel::theta_in_bounds().
The documentation for this class was generated from the following files:
Gauss1DMLE.h
Gauss1DMLE.cpp