Mappel: mappel::Gauss2DsModel Class Reference
mappel::Gauss2DsModel Class Reference
A base class for 2D Gaussian PSF where the gaussian sigma is controlled by a single scalar parameter which is called sigma_ratio. The size of the gaussian psf is sigma_ratio*psf_sigma, where psf_sigma is considered as a vector [psf_sigmaX, psf_sigmaY].
#include </home/travis/build/markjolah/Mappel/include/Mappel/Gauss2DsModel.h>
Classes
class Stencil
Stencil for 2D scalar-sigma models.
Public Types
using Gauss1DSumModelT = Gauss1DsMAP
using StencilVecT = std::vector< Stencil >
using ParamT = arma::vec
using ParamVecT = arma::mat
using ImageCoordT = uint32_t
using ImagePixelT = double
template<class CoordT >
using ImageSizeShapeT = arma::Col< CoordT >
template<class CoordT >
using ImageSizeVecShapeT = arma::Mat< CoordT >
using ImageSizeT = ImageSizeShapeT< ImageCoordT >
using ImageSizeVecT = ImageSizeVecShapeT< ImageCoordT >
template<class PixelT >
using ImageShapeT = arma::Mat< PixelT >
template<class PixelT >
using ImageStackShapeT = arma::Cube< PixelT >
using ImageT = ImageShapeT< ImagePixelT >
using ImageStackT = ImageStackShapeT< ImagePixelT >
Public Member Functions
void set_hyperparams (const VecT &hyperparams)
void set_prior (CompositeDist &&prior_)
void set_prior (const CompositeDist &prior_)
void set_size (const ImageSizeT &size_)
VecT get_min_sigma () const
double get_min_sigma (IdxT dim) const
VecT get_max_sigma () const
double get_max_sigma (IdxT dim) const
double get_max_sigma_ratio () const
void set_min_sigma (const VecT &min_sigma)
void set_max_sigma (const VecT &max_sigma)
void set_max_sigma_ratio (double max_sigma_ratio)
StatsT get_stats () const
Stencil make_stencil (const ParamT &theta, bool compute_derivatives=true) const
Make a new Model::Stencil object at theta.
double pixel_model_value (int i, int j, const Stencil &s) const
void pixel_grad (int i, int j, const Stencil &s, ParamT &pgrad) const
void pixel_grad2 (int i, int j, const Stencil &s, ParamT &pgrad2) const
void pixel_hess (int i, int j, const Stencil &s, MatT &hess) const
void pixel_hess_update (int i, int j, const Stencil &s, double dm_ratio_m1, double dmm_ratio, ParamT &grad, MatT &hess) const
pixel derivative inner loop calculations.
Stencil initial_theta_estimate (const ImageT &im)
Fast, heuristic estimate of initial theta.
Stencil initial_theta_estimate (const ImageT &im, const ParamT &theta_init)
Stencil initial_theta_estimate (const ImageT &im, const ParamT &theta_init, const std::string &estimator)
Gauss1DSumModelT debug_internal_sum_model_x () const
Gauss1DSumModelT debug_internal_sum_model_y () const
IdxT get_num_params () const
void check_param_shape (const ParamT &theta) const
void check_param_shape (const ParamVecT &theta) const
void check_psf_sigma (double psf_sigma) const
void check_psf_sigma (const VecT &psf_sigma) const
ParamT make_param () const
template<class FillT >
ParamT make_param (FillT fill) const
ParamVecT make_param_stack (IdxT n) const
template<class FillT >
ParamVecT make_param_stack (IdxT n, FillT fill) const
MatT make_param_mat () const
template<class FillT >
MatT make_param_mat (FillT fill) const
CubeT make_param_mat_stack (IdxT n) const
template<class FillT >
CubeT make_param_mat_stack (IdxT n, FillT fill) const
CompositeDist & get_prior ()
const CompositeDist & get_prior () const
IdxT get_num_hyperparams () const
VecT get_hyperparams () const
bool has_hyperparam (const std::string &name) const
double get_hyperparam_value (const std::string &name) const
int get_hyperparam_index (const std::string &name) const
void set_hyperparam_value (const std::string &name, double value)
void rename_hyperparam (const std::string &old_name, const std::string &new_name)
StringVecT get_param_names () const
void set_param_names (const StringVecT &desc)
StringVecT get_hyperparam_names () const
void set_hyperparam_names (const StringVecT &desc)
template<class RngT >
ParamT sample_prior (RngT &rng)
ParamT sample_prior ()
void set_bounds (const ParamT &lbound, const ParamT &ubound)
void set_lbound (const ParamT &lbound)
void set_ubound (const ParamT &ubound)
const ParamT & get_lbound () const
const ParamT & get_ubound () const
bool theta_in_bounds (const ParamT &theta) const
void bound_theta (ParamT &theta, double epsilon=bounds_epsilon) const
ParamT bounded_theta (const ParamT &theta, double epsilon=bounds_epsilon) const
ParamT reflected_theta (const ParamT &theta) const
BoolVecT theta_stack_in_bounds (const ParamVecT &theta) const
ParamVecT bounded_theta_stack (const ParamVecT &theta, double epsilon=bounds_epsilon) const
ParamVecT reflected_theta_stack (const ParamVecT &theta) const
ImageT make_image () const
ImageStackT make_image_stack (ImageCoordT n) const
ImageCoordT get_size_image_stack (const ImageStackT &stack) const
ImageT get_image_from_stack (const ImageStackT &stack, ImageCoordT n) const
template<class ImT >
void set_image_in_stack (ImageStackT &stack, ImageCoordT n, const ImT &im) const
const ImageSizeT & get_size () const
ImageCoordT get_size (IdxT idx) const
ImageCoordT get_num_pixels () const
void check_image_shape (const ImageT &im) const
Check the shape of a single images is correct for model size.
void check_image_shape (const ImageStackT &ims) const
Check the shape of a stack of images is correct for model size.
void sample_mcmc_candidate (IdxT sample_index, ParamT &candidate, double step_scale=1.0)
void set_intensity_mcmc_sampling (double eta_I=-1)
void set_background_mcmc_sampling (double eta_bg=-1)
void set_mcmc_sigma_scale (double scale)
double get_mcmc_sigma_scale () const
IdxT get_mcmc_num_phases () const
Static Public Member Functions
static CompositeDist make_default_prior (const ImageSizeT &size, double max_sigma_ratio, const std::string &prior_type)
static CompositeDist make_default_prior_beta_position (const ImageSizeT &size, double max_sigma_ratio)
static CompositeDist make_default_prior_normal_position (const ImageSizeT &size, double max_sigma_ratio)
static CompositeDist make_prior_beta_position (const ImageSizeT &size, double beta_xpos, double beta_ypos, double mean_I, double kappa_I, double mean_bg, double kappa_bg, double max_sigma_ratio, double alpha_sigma)
static CompositeDist make_prior_normal_position (const ImageSizeT &size, double sigma_xpos, double sigma_ypos, double mean_I, double kappa_I, double mean_bg, double kappa_bg, double max_sigma_ratio, double alpha_sigma)
static prior_hessian::TruncatedNormalDist make_prior_component_position_normal (IdxT size, double pos_sigma=default_sigma_pos)
static prior_hessian::ScaledSymmetricBetaDist make_prior_component_position_beta (IdxT size, double pos_beta=default_beta_pos)
static prior_hessian::TruncatedGammaDist make_prior_component_intensity (double mean=default_mean_I, double kappa=default_intensity_kappa)
static prior_hessian::TruncatedParetoDist make_prior_component_sigma (double min_sigma, double max_sigma, double alpha=default_alpha_sigma)
static void set_rng_seed (RngSeedT seed)
static ParallelRngManagerT & get_rng_manager ()
static ParallelRngGeneratorT & get_rng_generator ()
static void check_size (const ImageSizeT &size_)
Check the size argument for the model.
Static Public Attributes
static const StringVecT prior_types
static const std::string DefaultPriorType = "Normal"
static const std::string DefaultSeperableInitEstimator = "TrustRegion"
static const double bounds_epsilon = 1.0E-6
static const double global_min_psf_sigma = 1E-1
static const double global_max_psf_sigma = 1E2
static const double default_beta_pos = 3
static const double default_sigma_pos = 1
static const double default_mean_I = 300
static const double default_max_I = INFINITY
static const double default_intensity_kappa = 2
static const double default_pixel_mean_bg = 4
static const double default_alpha_sigma = 2
static const ImageCoordT num_dim =2
static const ImageCoordT global_min_size =3
static const ImageCoordT global_max_size =512
static const double global_default_mcmc_sigma_scale = 0.05
static const double global_max_mcmc_sigma_scale = 0.5
Protected Member Functions
Gauss2DsModel (const ImageSizeT &size, const VecT &min_sigma, const VecT &max_sigma)
Gauss2DsModel (const Gauss2DsModel &o)
Gauss2DsModel (Gauss2DsModel &&o)
Gauss2DsModel & operator= (const Gauss2DsModel &o)
Gauss2DsModel & operator= (Gauss2DsModel &&o)
void update_internal_1Dsum_estimators ()
void set_mcmc_num_phases (IdxT num_phases)
Static Protected Member Functions
static Gauss1DSumModelT make_internal_1Dsum_estimator (IdxT dim, const ImageSizeT &size, const VecT &min_sigma, const VecT &max_sigma, const CompositeDist &prior)
static double compute_max_sigma_ratio (const VecT &min_sigma, const VecT &max_sigma)
Protected Attributes
VecT min_sigma
Gauss1DSumModelT x_model
Gauss1DSumModelT y_model
CompositeDist prior
IdxT num_params
IdxT num_hyperparams
ParamT lbound
ParamT ubound
ImageSizeT size
double eta_sigma =0
double eta_y =0
double eta_x =0
double eta_I =0
double eta_bg =0
IdxT num_phases
double sigma_scale
Detailed Description
A base class for 2D Gaussian PSF where the gaussian sigma is controlled by a single scalar parameter which is called sigma_ratio. The size of the gaussian psf is sigma_ratio*psf_sigma, where psf_sigma is considered as a vector [psf_sigmaX, psf_sigmaY].
Definition at line 23 of file Gauss2DsModel.h.
Member Typedef Documentation
using mappel::Gauss2DsModel::Gauss1DSumModelT = Gauss1DsMAP
Definition at line 26 of file Gauss2DsModel.h.
using mappel::ImageFormat2DBase::ImageCoordT = uint32_t inherited
Image size coordinate storage type
Definition at line 24 of file ImageFormat2DBase.h.
using mappel::ImageFormat2DBase::ImagePixelT = double inherited
Image pixel storage type
Definition at line 25 of file ImageFormat2DBase.h.
template<class PixelT > using mappel::ImageFormat2DBase::ImageShapeT = arma::Mat<PixelT> inherited
Shape of the data type for a single image
Definition at line 32 of file ImageFormat2DBase.h.
template<class CoordT > using mappel::ImageFormat2DBase::ImageSizeShapeT = arma::Col<CoordT> inherited
Shape of the data type to store a single image's coordinates
Definition at line 27 of file ImageFormat2DBase.h.
using mappel::ImageFormat2DBase::ImageSizeT = ImageSizeShapeT<ImageCoordT> inherited
Data type for a single image size
Definition at line 29 of file ImageFormat2DBase.h.
template<class CoordT > using mappel::ImageFormat2DBase::ImageSizeVecShapeT = arma::Mat<CoordT> inherited
Shape of the data type to store a vector of image's coordinates
Definition at line 28 of file ImageFormat2DBase.h.
using mappel::ImageFormat2DBase::ImageSizeVecT = ImageSizeVecShapeT<ImageCoordT> inherited
Data type for a sequence of image sizes
Definition at line 30 of file ImageFormat2DBase.h.
template<class PixelT > using mappel::ImageFormat2DBase::ImageStackShapeT = arma::Cube<PixelT> inherited
Shape of the data type for a sequence of images
Definition at line 33 of file ImageFormat2DBase.h.
using mappel::ImageFormat2DBase::ImageStackT = ImageStackShapeT<ImagePixelT> inherited
Data type to represent a sequence of images
Definition at line 35 of file ImageFormat2DBase.h.
using mappel::ImageFormat2DBase::ImageT = ImageShapeT<ImagePixelT> inherited
Data type to represent single image
Definition at line 34 of file ImageFormat2DBase.h.
using mappel::PointEmitterModel::ParamT = arma::vec inherited
Parameter vector
Definition at line 47 of file PointEmitterModel.h.
using mappel::PointEmitterModel::ParamVecT = arma::mat inherited
Vector of parameter vectors
Definition at line 48 of file PointEmitterModel.h.
using mappel::Gauss2DsModel::StencilVecT = std::vector<Stencil>
Definition at line 55 of file Gauss2DsModel.h.
Constructor & Destructor Documentation
mappel::Gauss2DsModel::Gauss2DsModel (const ImageSizeT & size, const VecT & min_sigma, const VecT & max_sigma) protected
Definition at line 12 of file Gauss2DsModel.cpp.
References mappel::PointEmitterModel::check_psf_sigma(), make_internal_1Dsum_estimator(), min_sigma, mappel::PointEmitterModel::prior, mappel::ImageFormat2DBase::size, and y_model.
Referenced by debug_internal_sum_model_y().
mappel::Gauss2DsModel::Gauss2DsModel (const Gauss2DsModel & o) protected
Definition at line 28 of file Gauss2DsModel.cpp.
References get_max_sigma(), make_internal_1Dsum_estimator(), min_sigma, mappel::PointEmitterModel::prior, mappel::ImageFormat2DBase::size, and y_model.
mappel::Gauss2DsModel::Gauss2DsModel (Gauss2DsModel && o) protected
Definition at line 36 of file Gauss2DsModel.cpp.
References get_max_sigma(), make_internal_1Dsum_estimator(), min_sigma, mappel::PointEmitterModel::prior, mappel::ImageFormat2DBase::size, and y_model.
Member Function Documentation
void mappel::PointEmitterModel::bound_theta (ParamT & theta, double epsilon = bounds_epsilon) const inherited
Definition at line 247 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::check_param_shape(), mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, and mappel::PointEmitterModel::ubound.
PointEmitterModel::ParamT mappel::PointEmitterModel::bounded_theta (const ParamT & theta, double epsilon = bounds_epsilon) const inherited
Definition at line 264 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::check_param_shape(), mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, and mappel::PointEmitterModel::ubound.
Referenced by mappel::PointEmitterModel::bounded_theta_stack().
PointEmitterModel::ParamVecT mappel::PointEmitterModel::bounded_theta_stack (const ParamVecT & theta, double epsilon = bounds_epsilon) const inherited
Definition at line 306 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::bounded_theta(), and mappel::PointEmitterModel::check_param_shape().
void mappel::ImageFormat2DBase::check_image_shape (const ImageT & im) const inherited
Check the shape of a single images is correct for model size.
Definition at line 80 of file ImageFormat2DBase.cpp.
References mappel::ImageFormat2DBase::size.
void mappel::ImageFormat2DBase::check_image_shape (const ImageStackT & ims) const inherited
Check the shape of a stack of images is correct for model size.
Definition at line 93 of file ImageFormat2DBase.cpp.
References mappel::ImageFormat2DBase::size.
void mappel::PointEmitterModel::check_param_shape (const ParamT & theta) const inherited
Definition at line 166 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::num_params.
Referenced by mappel::PointEmitterModel::bound_theta(), mappel::PointEmitterModel::bounded_theta(), mappel::PointEmitterModel::bounded_theta_stack(), mappel::PointEmitterModel::reflected_theta(), mappel::PointEmitterModel::reflected_theta_stack(), mappel::PointEmitterModel::theta_in_bounds(), and mappel::PointEmitterModel::theta_stack_in_bounds().
void mappel::PointEmitterModel::check_param_shape (const ParamVecT & theta) const inherited
Definition at line 175 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::num_params.
void mappel::PointEmitterModel::check_psf_sigma (double psf_sigma) const inherited
Definition at line 184 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::global_max_psf_sigma, and mappel::PointEmitterModel::global_min_psf_sigma.
Referenced by mappel::Gauss1DModel::Gauss1DModel(), mappel::Gauss2DModel::Gauss2DModel(), Gauss2DsModel(), mappel::Gauss1DsModel::set_max_sigma(), set_max_sigma(), mappel::Gauss1DsModel::set_min_sigma(), set_min_sigma(), mappel::Gauss1DModel::set_psf_sigma(), and mappel::Gauss2DModel::set_psf_sigma().
void mappel::PointEmitterModel::check_psf_sigma (const VecT & psf_sigma) const inherited
Definition at line 196 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::global_max_psf_sigma, and mappel::PointEmitterModel::global_min_psf_sigma.
void mappel::ImageFormat2DBase::check_size (const ImageSizeT & size_) static inherited
Check the size argument for the model.
Definition at line 60 of file ImageFormat2DBase.cpp.
References mappel::ImageFormat2DBase::global_max_size, and mappel::ImageFormat2DBase::global_min_size.
Referenced by mappel::ImageFormat2DBase::ImageFormat2DBase(), and mappel::ImageFormat2DBase::set_size().
double mappel::Gauss2DsModel::compute_max_sigma_ratio (const VecT & min_sigma, const VecT & max_sigma) static protected
Definition at line 162 of file Gauss2DsModel.cpp.
References min_sigma.
Referenced by debug_internal_sum_model_y(), mappel::Gauss2DsMAP::Gauss2DsMAP(), mappel::Gauss2DsMLE::Gauss2DsMLE(), and set_max_sigma().
Gauss1DSumModelT mappel::Gauss2DsModel::debug_internal_sum_model_x () const inline
Definition at line 104 of file Gauss2DsModel.h.
References x_model.
Gauss1DSumModelT mappel::Gauss2DsModel::debug_internal_sum_model_y () const inline
Definition at line 105 of file Gauss2DsModel.h.
References compute_max_sigma_ratio(), Gauss2DsModel(), make_internal_1Dsum_estimator(), min_sigma, operator=(), mappel::PointEmitterModel::prior, mappel::ImageFormat2DBase::size, update_internal_1Dsum_estimators(), and y_model.
int mappel::PointEmitterModel::get_hyperparam_index (const std::string & name) const inline inherited
Definition at line 236 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
StringVecT mappel::PointEmitterModel::get_hyperparam_names () const inline inherited
Definition at line 256 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
double mappel::PointEmitterModel::get_hyperparam_value (const std::string & name) const inline inherited
Definition at line 232 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
Referenced by mappel::MCMCAdaptor1D::set_background_mcmc_sampling(), and mappel::MCMCAdaptor1D::set_intensity_mcmc_sampling().
PointEmitterModel::ParamT mappel::PointEmitterModel::get_hyperparams () const inline inherited
Definition at line 224 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
ImageFormat2DBase::ImageT mappel::ImageFormat2DBase::get_image_from_stack (const ImageStackT & stack, ImageCoordT n) const inline inherited
Definition at line 106 of file ImageFormat2DBase.h.
const PointEmitterModel::ParamT & mappel::PointEmitterModel::get_lbound () const inline inherited
Definition at line 212 of file PointEmitterModel.h.
References mappel::PointEmitterModel::lbound.
Referenced by mappel::MCMCAdaptor1D::MCMCAdaptor1D(), mappel::MCMCAdaptor2D::MCMCAdaptor2D(), and mappel::MCMCAdaptor1D::set_background_mcmc_sampling().
VecT mappel::Gauss2DsModel::get_max_sigma () const inline
Definition at line 132 of file Gauss2DsModel.h.
References get_max_sigma_ratio(), and get_min_sigma().
Referenced by Gauss2DsModel(), get_stats(), operator=(), set_max_sigma_ratio(), set_min_sigma(), and update_internal_1Dsum_estimators().
double mappel::Gauss2DsModel::get_max_sigma (IdxT dim) const inline
Definition at line 136 of file Gauss2DsModel.h.
References get_max_sigma_ratio(), and get_min_sigma().
double mappel::Gauss2DsModel::get_max_sigma_ratio () const inline
Definition at line 140 of file Gauss2DsModel.h.
References mappel::PointEmitterModel::get_ubound().
Referenced by get_max_sigma(), and get_stats().
IdxT mappel::MCMCAdaptorBase::get_mcmc_num_phases () const inherited
Definition at line 56 of file MCMCAdaptorBase.cpp.
References mappel::MCMCAdaptorBase::num_phases.
double mappel::MCMCAdaptorBase::get_mcmc_sigma_scale () const inherited
Definition at line 53 of file MCMCAdaptorBase.cpp.
References mappel::MCMCAdaptorBase::sigma_scale.
VecT mappel::Gauss2DsModel::get_min_sigma () const inline
Definition at line 128 of file Gauss2DsModel.h.
References min_sigma.
Referenced by get_max_sigma(), get_stats(), and set_max_sigma().
double mappel::Gauss2DsModel::get_min_sigma (IdxT dim) const
Definition at line 191 of file Gauss2DsModel.cpp.
References DefaultPriorType, min_sigma, and prior_types.
IdxT mappel::PointEmitterModel::get_num_hyperparams () const inline inherited
Definition at line 208 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_hyperparams.
IdxT mappel::PointEmitterModel::get_num_params () const inline inherited
Definition at line 160 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
ImageFormat2DBase::ImageCoordT mappel::ImageFormat2DBase::get_num_pixels () const inline inherited
Definition at line 79 of file ImageFormat2DBase.h.
References mappel::ImageFormat2DBase::size.
Referenced by mappel::ImageFormat2DBase::get_stats().
StringVecT mappel::PointEmitterModel::get_param_names () const inline inherited
Definition at line 248 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
CompositeDist & mappel::PointEmitterModel::get_prior () inline inherited
Definition at line 200 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
Referenced by mappel::Gauss2DModel::update_internal_1Dsum_estimators(), and update_internal_1Dsum_estimators().
const CompositeDist & mappel::PointEmitterModel::get_prior () const inline inherited
Definition at line 204 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
ParallelRngGeneratorT & mappel::PointEmitterModel::get_rng_generator () static inherited
Definition at line 119 of file PointEmitterModel.cpp.
References mappel::rng_manager.
ParallelRngManagerT & mappel::PointEmitterModel::get_rng_manager () static inherited
Definition at line 114 of file PointEmitterModel.cpp.
References mappel::rng_manager.
const ImageFormat2DBase::ImageSizeT & mappel::ImageFormat2DBase::get_size () const inline inherited
Definition at line 74 of file ImageFormat2DBase.h.
References mappel::ImageFormat2DBase::size.
ImageFormat2DBase::ImageCoordT mappel::ImageFormat2DBase::get_size (IdxT idx) const inherited
Definition at line 41 of file ImageFormat2DBase.cpp.
References mappel::ImageFormat2DBase::size.
ImageFormat2DBase::ImageCoordT mappel::ImageFormat2DBase::get_size_image_stack (const ImageStackT & stack) const inline inherited
Definition at line 99 of file ImageFormat2DBase.h.
StatsT mappel::Gauss2DsModel::get_stats () const
Definition at line 341 of file Gauss2DsModel.cpp.
References get_max_sigma(), get_max_sigma_ratio(), get_min_sigma(), mappel::MCMCAdaptor2Ds::get_stats(), mappel::ImageFormat2DBase::get_stats(), and mappel::PointEmitterModel::get_stats().
const PointEmitterModel::ParamT & mappel::PointEmitterModel::get_ubound () const inline inherited
Definition at line 216 of file PointEmitterModel.h.
References mappel::PointEmitterModel::ubound.
Referenced by mappel::Gauss2DsxyModel::get_max_sigma_ratio(), get_max_sigma_ratio(), mappel::MCMCAdaptor1D::MCMCAdaptor1D(), mappel::MCMCAdaptor2D::MCMCAdaptor2D(), mappel::MCMCAdaptor1D::set_background_mcmc_sampling(), and set_max_sigma_ratio().
bool mappel::PointEmitterModel::has_hyperparam (const std::string & name) const inline inherited
Definition at line 228 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
Gauss2DsModel::Stencil mappel::Gauss2DsModel::initial_theta_estimate (const ImageT & im) inline
Fast, heuristic estimate of initial theta.
Definition at line 224 of file Gauss2DsModel.h.
References mappel::PointEmitterModel::DefaultSeperableInitEstimator, and mappel::PointEmitterModel::make_param().
Referenced by initial_theta_estimate().
Gauss2DsModel::Stencil mappel::Gauss2DsModel::initial_theta_estimate (const ImageT & im, const ParamT & theta_init) inline
Definition at line 231 of file Gauss2DsModel.h.
References mappel::PointEmitterModel::DefaultSeperableInitEstimator, and initial_theta_estimate().
Gauss2DsModel::Stencil mappel::Gauss2DsModel::initial_theta_estimate (const ImageT & im, const ParamT & theta_init, const std::string & estimator)
Definition at line 385 of file Gauss2DsModel.cpp.
References mappel::Gauss2DsModel::Stencil::bg(), mappel::methods::estimate_max(), mappel::Gauss2DsModel::Stencil::I(), mappel::PointEmitterModel::lbound, make_stencil(), min_sigma, mappel::PointEmitterModel::num_params, mappel::Gauss2DsModel::Stencil::sigma_ratio(), mappel::ImageFormat2DBase::size, mappel::PointEmitterModel::theta_in_bounds(), mappel::PointEmitterModel::ubound, x_model, and y_model.
CompositeDist mappel::Gauss2DsModel::make_default_prior (const ImageSizeT & size, double max_sigma_ratio, const std::string & prior_type) static
Definition at line 208 of file Gauss2DsModel.cpp.
References mappel::istarts_with(), make_default_prior_beta_position(), and make_default_prior_normal_position().
Referenced by mappel::Gauss2DsMAP::Gauss2DsMAP(), and mappel::Gauss2DsMLE::Gauss2DsMLE().
CompositeDist mappel::Gauss2DsModel::make_default_prior_beta_position (const ImageSizeT & size, double max_sigma_ratio) static
Definition at line 230 of file Gauss2DsModel.cpp.
References mappel::PointEmitterModel::default_pixel_mean_bg, mappel::PointEmitterModel::make_prior_component_intensity(), mappel::PointEmitterModel::make_prior_component_position_beta(), mappel::PointEmitterModel::make_prior_component_sigma(), and mappel::ImageFormat2DBase::size.
Referenced by make_default_prior().
CompositeDist mappel::Gauss2DsModel::make_default_prior_normal_position (const ImageSizeT & size, double max_sigma_ratio) static
Definition at line 243 of file Gauss2DsModel.cpp.
References mappel::PointEmitterModel::default_pixel_mean_bg, mappel::PointEmitterModel::make_prior_component_intensity(), mappel::PointEmitterModel::make_prior_component_position_normal(), mappel::PointEmitterModel::make_prior_component_sigma(), and mappel::ImageFormat2DBase::size.
Referenced by make_default_prior().
ImageFormat2DBase::ImageT mappel::ImageFormat2DBase::make_image () const inline inherited
Definition at line 85 of file ImageFormat2DBase.h.
References mappel::ImageFormat2DBase::size.
ImageFormat2DBase::ImageStackT mappel::ImageFormat2DBase::make_image_stack (ImageCoordT n) const inline inherited
Definition at line 92 of file ImageFormat2DBase.h.
References mappel::ImageFormat2DBase::size.
Gauss2DsModel::Gauss1DSumModelT mappel::Gauss2DsModel::make_internal_1Dsum_estimator (IdxT dim, const ImageSizeT & size, const VecT & min_sigma, const VecT & max_sigma, const CompositeDist & prior) static protected
Definition at line 69 of file Gauss2DsModel.cpp.
References mappel::Gauss1DsModel::make_prior_beta_position(), mappel::Gauss1DsModel::make_prior_normal_position(), min_sigma, and mappel::ImageFormat2DBase::size.
Referenced by debug_internal_sum_model_y(), Gauss2DsModel(), and update_internal_1Dsum_estimators().
PointEmitterModel::ParamT mappel::PointEmitterModel::make_param () const inline inherited
Definition at line 164 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
Referenced by mappel::Gauss1DModel::initial_theta_estimate(), mappel::Gauss1DsModel::initial_theta_estimate(), mappel::Gauss2DModel::initial_theta_estimate(), mappel::Gauss2DsxyModel::initial_theta_estimate(), initial_theta_estimate(), mappel::Gauss1DModel::pixel_hess_update(), mappel::Gauss1DsModel::pixel_hess_update(), mappel::Gauss2DModel::pixel_hess_update(), and pixel_hess_update().
template<class FillT > PointEmitterModel::ParamT mappel::PointEmitterModel::make_param (FillT fill) const inherited
Definition at line 181 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
MatT mappel::PointEmitterModel::make_param_mat () const inline inherited
Definition at line 172 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
template<class FillT > MatT mappel::PointEmitterModel::make_param_mat (FillT fill) const inherited
Definition at line 191 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
CubeT mappel::PointEmitterModel::make_param_mat_stack (IdxT n) const inline inherited
Definition at line 176 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
template<class FillT > CubeT mappel::PointEmitterModel::make_param_mat_stack (IdxT n, FillT fill) const inherited
Definition at line 196 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
PointEmitterModel::ParamVecT mappel::PointEmitterModel::make_param_stack (IdxT n) const inline inherited
Definition at line 168 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
template<class FillT > PointEmitterModel::ParamVecT mappel::PointEmitterModel::make_param_stack (IdxT n, FillT fill) const inherited
Definition at line 186 of file PointEmitterModel.h.
References mappel::PointEmitterModel::num_params.
CompositeDist mappel::Gauss2DsModel::make_prior_beta_position (const ImageSizeT & size, double beta_xpos, double beta_ypos, double mean_I, double kappa_I, double mean_bg, double kappa_bg, double max_sigma_ratio, double alpha_sigma) static
Definition at line 255 of file Gauss2DsModel.cpp.
References mappel::PointEmitterModel::make_prior_component_intensity(), mappel::PointEmitterModel::make_prior_component_position_beta(), mappel::PointEmitterModel::make_prior_component_sigma(), and mappel::ImageFormat2DBase::size.
prior_hessian::TruncatedGammaDist mappel::PointEmitterModel::make_prior_component_intensity (double mean = default_mean_I, double kappa = default_intensity_kappa) static inherited
Definition at line 97 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::default_max_I.
Referenced by mappel::Gauss1DsModel::make_default_prior_beta_position(), mappel::Gauss2DModel::make_default_prior_beta_position(), mappel::Gauss1DModel::make_default_prior_beta_position(), make_default_prior_beta_position(), mappel::Gauss2DModel::make_default_prior_normal_position(), mappel::Gauss1DsModel::make_default_prior_normal_position(), mappel::Gauss1DModel::make_default_prior_normal_position(), make_default_prior_normal_position(), mappel::Gauss2DModel::make_prior_beta_position(), mappel::Gauss1DsModel::make_prior_beta_position(), mappel::Gauss1DModel::make_prior_beta_position(), make_prior_beta_position(), mappel::Gauss2DModel::make_prior_normal_position(), mappel::Gauss1DsModel::make_prior_normal_position(), mappel::Gauss1DModel::make_prior_normal_position(), and make_prior_normal_position().
prior_hessian::ScaledSymmetricBetaDist mappel::PointEmitterModel::make_prior_component_position_beta (IdxT size, double pos_beta = default_beta_pos) static inherited
Definition at line 91 of file PointEmitterModel.cpp.
Referenced by mappel::Gauss1DsModel::make_default_prior_beta_position(), mappel::Gauss2DModel::make_default_prior_beta_position(), mappel::Gauss1DModel::make_default_prior_beta_position(), make_default_prior_beta_position(), mappel::Gauss1DsModel::make_prior_beta_position(), mappel::Gauss2DModel::make_prior_beta_position(), mappel::Gauss1DModel::make_prior_beta_position(), and make_prior_beta_position().
prior_hessian::TruncatedNormalDist mappel::PointEmitterModel::make_prior_component_position_normal (IdxT size, double pos_sigma = default_sigma_pos) static inherited
Definition at line 84 of file PointEmitterModel.cpp.
Referenced by mappel::Gauss1DsModel::make_default_prior_normal_position(), mappel::Gauss2DModel::make_default_prior_normal_position(), mappel::Gauss1DModel::make_default_prior_normal_position(), make_default_prior_normal_position(), mappel::Gauss2DModel::make_prior_normal_position(), mappel::Gauss1DsModel::make_prior_normal_position(), mappel::Gauss1DModel::make_prior_normal_position(), and make_prior_normal_position().
prior_hessian::TruncatedParetoDist mappel::PointEmitterModel::make_prior_component_sigma (double min_sigma, double max_sigma, double alpha = default_alpha_sigma) static inherited
Definition at line 103 of file PointEmitterModel.cpp.
Referenced by mappel::Gauss1DsModel::make_default_prior_beta_position(), make_default_prior_beta_position(), mappel::Gauss1DsModel::make_default_prior_normal_position(), make_default_prior_normal_position(), mappel::Gauss1DsModel::make_prior_beta_position(), make_prior_beta_position(), mappel::Gauss1DsModel::make_prior_normal_position(), and make_prior_normal_position().
CompositeDist mappel::Gauss2DsModel::make_prior_normal_position (const ImageSizeT & size, double sigma_xpos, double sigma_ypos, double mean_I, double kappa_I, double mean_bg, double kappa_bg, double max_sigma_ratio, double alpha_sigma) static
Definition at line 271 of file Gauss2DsModel.cpp.
References mappel::PointEmitterModel::make_prior_component_intensity(), mappel::PointEmitterModel::make_prior_component_position_normal(), mappel::PointEmitterModel::make_prior_component_sigma(), and mappel::ImageFormat2DBase::size.
Gauss2DsModel::Stencil mappel::Gauss2DsModel::make_stencil (const ParamT & theta, bool compute_derivatives = true) const inline
Make a new Model::Stencil object at theta.
Stencils store all of the important calculations necessary for evaluating the log-likelihood and its derivatives at a particular theta (parameter) value.
This allows re-use of the most expensive computations. Stencils can be easily passed around by reference, and most functions in the mappel::methods namespace accept a const Stencil reference in place of the model parameter.
Throws mappel::ModelBoundsError if not model.theta_in_bounds(theta).
If derivatives will not be computed with this stencil set compute_derivatives=false
Parameters
theta Prameter to evaluate at
compute_derivatives True to also prepare for derivative computations
Returns
A new Stencil object ready to compute with
Definition at line 162 of file Gauss2DsModel.h.
References mappel::Gauss2DsModel::Stencil::Stencil(), and mappel::PointEmitterModel::theta_in_bounds().
Referenced by initial_theta_estimate().
Gauss2DsModel & mappel::Gauss2DsModel::operator= (const Gauss2DsModel & o) protected
Definition at line 44 of file Gauss2DsModel.cpp.
References get_max_sigma(), min_sigma, mappel::MCMCAdaptor2Ds::operator=(), x_model, and y_model.
Referenced by debug_internal_sum_model_y(), mappel::Gauss2DsMAP::operator=(), and mappel::Gauss2DsMLE::operator=().
Gauss2DsModel & mappel::Gauss2DsModel::operator= (Gauss2DsModel && o) protected
Definition at line 56 of file Gauss2DsModel.cpp.
References min_sigma, mappel::MCMCAdaptor2Ds::operator=(), x_model, and y_model.
void mappel::Gauss2DsModel::pixel_grad (int i, int j, const Stencil & s, ParamT & pgrad) const inline
Definition at line 180 of file Gauss2DsModel.h.
References mappel::Gauss2DsModel::Stencil::DX, mappel::Gauss2DsModel::Stencil::DXS, mappel::Gauss2DsModel::Stencil::DY, mappel::Gauss2DsModel::Stencil::DYS, mappel::Gauss2DsModel::Stencil::I(), mappel::Gauss2DsModel::Stencil::X, and mappel::Gauss2DsModel::Stencil::Y.
Referenced by pixel_hess_update().
void mappel::Gauss2DsModel::pixel_grad2 (int i, int j, const Stencil & s, ParamT & pgrad2) const inline
Definition at line 192 of file Gauss2DsModel.h.
References mappel::Gauss2DsModel::Stencil::DXS, mappel::Gauss2DsModel::Stencil::DXS2, mappel::Gauss2DsModel::Stencil::DYS, mappel::Gauss2DsModel::Stencil::DYS2, mappel::Gauss2DsModel::Stencil::I(), mappel::Gauss2DsModel::Stencil::sigmaX(), mappel::Gauss2DsModel::Stencil::sigmaY(), mappel::Gauss2DsModel::Stencil::X, and mappel::Gauss2DsModel::Stencil::Y.
void mappel::Gauss2DsModel::pixel_hess (int i, int j, const Stencil & s, MatT & hess) const inline
Definition at line 204 of file Gauss2DsModel.h.
References mappel::Gauss2DsModel::Stencil::DX, mappel::Gauss2DsModel::Stencil::DXS, mappel::Gauss2DsModel::Stencil::DXS2, mappel::Gauss2DsModel::Stencil::DXSX, mappel::Gauss2DsModel::Stencil::DY, mappel::Gauss2DsModel::Stencil::DYS, mappel::Gauss2DsModel::Stencil::DYS2, mappel::Gauss2DsModel::Stencil::DYSY, mappel::Gauss2DsModel::Stencil::I(), mappel::Gauss2DsModel::Stencil::sigmaX(), mappel::Gauss2DsModel::Stencil::sigmaY(), mappel::Gauss2DsModel::Stencil::X, and mappel::Gauss2DsModel::Stencil::Y.
void mappel::Gauss2DsModel::pixel_hess_update (int i, int j, const Stencil & s, double dm_ratio_m1, double dmm_ratio, ParamT & grad, MatT & hess) const
pixel derivative inner loop calculations.
Definition at line 358 of file Gauss2DsModel.cpp.
References mappel::Gauss2DsModel::Stencil::DX, mappel::Gauss2DsModel::Stencil::DXS, mappel::Gauss2DsModel::Stencil::DXS2, mappel::Gauss2DsModel::Stencil::DXSX, mappel::Gauss2DsModel::Stencil::DY, mappel::Gauss2DsModel::Stencil::DYS, mappel::Gauss2DsModel::Stencil::DYS2, mappel::Gauss2DsModel::Stencil::DYSY, mappel::Gauss2DsModel::Stencil::I(), mappel::PointEmitterModel::make_param(), pixel_grad(), mappel::Gauss2DsModel::Stencil::sigmaX(), mappel::Gauss2DsModel::Stencil::sigmaY(), mappel::Gauss2DsModel::Stencil::X, and mappel::Gauss2DsModel::Stencil::Y.
double mappel::Gauss2DsModel::pixel_model_value (int i, int j, const Stencil & s) const inline
Definition at line 173 of file Gauss2DsModel.h.
References mappel::Gauss2DsModel::Stencil::bg(), mappel::Gauss2DsModel::Stencil::I(), mappel::Gauss2DsModel::Stencil::X, and mappel::Gauss2DsModel::Stencil::Y.
PointEmitterModel::ParamT mappel::PointEmitterModel::reflected_theta (const ParamT & theta) const inherited
Definition at line 275 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::check_param_shape(), mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, and mappel::PointEmitterModel::ubound.
Referenced by mappel::PointEmitterModel::reflected_theta_stack().
PointEmitterModel::ParamVecT mappel::PointEmitterModel::reflected_theta_stack (const ParamVecT & theta) const inherited
Definition at line 316 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::check_param_shape(), and mappel::PointEmitterModel::reflected_theta().
void mappel::PointEmitterModel::rename_hyperparam (const std::string & old_name, const std::string & new_name) inline inherited
Definition at line 244 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
void mappel::MCMCAdaptor2Ds::sample_mcmc_candidate (IdxT sample_index, ParamT & candidate, double step_scale = 1.0) inherited
Definition at line 56 of file MCMCAdaptor2Ds.cpp.
References mappel::MCMCAdaptor1D::eta_bg, mappel::MCMCAdaptor1D::eta_I, mappel::MCMCAdaptor2Ds::eta_sigma, mappel::MCMCAdaptor1D::eta_x, mappel::MCMCAdaptor2D::eta_y, mappel::MCMCAdaptorBase::num_phases, and mappel::rng_manager.
template<class RngT > PointEmitterModel::ParamT mappel::PointEmitterModel::sample_prior (RngT & rng) inherited
Definition at line 264 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
PointEmitterModel::ParamT mappel::PointEmitterModel::sample_prior () inline inherited
Definition at line 268 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior, and mappel::rng_manager.
void mappel::MCMCAdaptor1D::set_background_mcmc_sampling (double eta_bg = -1) inherited
Definition at line 81 of file MCMCAdaptor1D.cpp.
References mappel::PointEmitterModel::default_pixel_mean_bg, mappel::MCMCAdaptor1D::eta_bg, mappel::PointEmitterModel::get_hyperparam_value(), mappel::PointEmitterModel::get_lbound(), mappel::PointEmitterModel::get_ubound(), and mappel::MCMCAdaptorBase::sigma_scale.
Referenced by mappel::MCMCAdaptor1D::MCMCAdaptor1D().
void mappel::PointEmitterModel::set_bounds (const ParamT & lbound_, const ParamT & ubound_) inherited
Box-type parameter bounds
Modifies the prior bounds to prevent sampling outside the valid box-constraints.
Definition at line 212 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::bounds_epsilon, mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, mappel::PointEmitterModel::prior, and mappel::PointEmitterModel::ubound.
void mappel::PointEmitterModel::set_hyperparam_names (const StringVecT & desc) inline inherited
Definition at line 260 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
void mappel::PointEmitterModel::set_hyperparam_value (const std::string & name, double value) inline inherited
Definition at line 240 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
void mappel::Gauss2DsModel::set_hyperparams (const VecT & hyperparams)
Definition at line 119 of file Gauss2DsModel.cpp.
References mappel::PointEmitterModel::set_hyperparams(), and update_internal_1Dsum_estimators().
template<class ImT > void mappel::ImageFormat2DBase::set_image_in_stack (ImageStackT & stack, ImageCoordT n, const ImT & im) const inherited
Definition at line 113 of file ImageFormat2DBase.h.
void mappel::MCMCAdaptor1D::set_intensity_mcmc_sampling (double eta_I = -1) inherited
Definition at line 65 of file MCMCAdaptor1D.cpp.
References mappel::PointEmitterModel::default_mean_I, mappel::MCMCAdaptor1D::eta_I, mappel::PointEmitterModel::get_hyperparam_value(), and mappel::MCMCAdaptorBase::sigma_scale.
Referenced by mappel::MCMCAdaptor1D::MCMCAdaptor1D().
void mappel::PointEmitterModel::set_lbound (const ParamT & lbound) inherited
Definition at line 225 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::bounds_epsilon, mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, mappel::PointEmitterModel::prior, and mappel::PointEmitterModel::ubound.
Referenced by mappel::Gauss1DsModel::set_min_sigma().
void mappel::Gauss2DsModel::set_max_sigma (const VecT & new_sigma)
Set the max_sigma_ratio based on the new max_sigma's ratio with the current min_sigma.
Definition at line 155 of file Gauss2DsModel.cpp.
References mappel::PointEmitterModel::check_psf_sigma(), compute_max_sigma_ratio(), get_min_sigma(), and set_max_sigma_ratio().
void mappel::Gauss2DsModel::set_max_sigma_ratio (double max_sigma_ratio)
Definition at line 176 of file Gauss2DsModel.cpp.
References mappel::PointEmitterModel::bounds_epsilon, get_max_sigma(), mappel::PointEmitterModel::get_ubound(), mappel::Gauss1DsModel::set_max_sigma(), mappel::PointEmitterModel::set_ubound(), x_model, and y_model.
Referenced by set_max_sigma().
void mappel::MCMCAdaptorBase::set_mcmc_num_phases (IdxT num_phases) protected inherited
Definition at line 59 of file MCMCAdaptorBase.cpp.
References mappel::MCMCAdaptorBase::num_phases.
Referenced by mappel::MCMCAdaptor1Ds::MCMCAdaptor1Ds(), and mappel::MCMCAdaptor2Ds::MCMCAdaptor2Ds().
void mappel::MCMCAdaptorBase::set_mcmc_sigma_scale (double scale) inherited
Definition at line 39 of file MCMCAdaptorBase.cpp.
References mappel::MCMCAdaptorBase::global_max_mcmc_sigma_scale, and mappel::MCMCAdaptorBase::sigma_scale.
void mappel::Gauss2DsModel::set_min_sigma (const VecT & new_sigma)
Set the minimum sigma, keeping the max_sigma_ratio the same.
Definition at line 137 of file Gauss2DsModel.cpp.
References mappel::PointEmitterModel::check_psf_sigma(), get_max_sigma(), min_sigma, mappel::Gauss1DsModel::set_max_sigma(), mappel::Gauss1DsModel::set_min_sigma(), x_model, and y_model.
void mappel::PointEmitterModel::set_param_names (const StringVecT & desc) inline inherited
Definition at line 252 of file PointEmitterModel.h.
References mappel::PointEmitterModel::prior.
void mappel::Gauss2DsModel::set_prior (CompositeDist && prior_)
Definition at line 107 of file Gauss2DsModel.cpp.
References mappel::PointEmitterModel::set_prior(), and update_internal_1Dsum_estimators().
void mappel::Gauss2DsModel::set_prior (const CompositeDist & prior_)
Definition at line 113 of file Gauss2DsModel.cpp.
References mappel::PointEmitterModel::set_prior(), and update_internal_1Dsum_estimators().
void mappel::PointEmitterModel::set_rng_seed (RngSeedT seed) static inherited
Definition at line 109 of file PointEmitterModel.cpp.
References mappel::rng_manager.
void mappel::Gauss2DsModel::set_size (const ImageSizeT & size_)
Definition at line 125 of file Gauss2DsModel.cpp.
References mappel::ImageFormat2DBase::set_size(), mappel::ImageFormat1DBase::set_size(), mappel::ImageFormat2DBase::size, x_model, and y_model.
void mappel::PointEmitterModel::set_ubound (const ParamT & ubound) inherited
Definition at line 236 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::bounds_epsilon, mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, mappel::PointEmitterModel::prior, and mappel::PointEmitterModel::ubound.
Referenced by mappel::Gauss1DsModel::set_max_sigma(), and set_max_sigma_ratio().
bool mappel::PointEmitterModel::theta_in_bounds (const ParamT & theta) const inherited
Definition at line 256 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::check_param_shape(), mappel::PointEmitterModel::lbound, mappel::PointEmitterModel::num_params, and mappel::PointEmitterModel::ubound.
Referenced by mappel::Gauss2DModel::initial_theta_estimate(), initial_theta_estimate(), mappel::Gauss1DModel::make_stencil(), mappel::Gauss1DsModel::make_stencil(), mappel::Gauss2DModel::make_stencil(), mappel::Gauss2DsxyModel::make_stencil(), make_stencil(), and mappel::PointEmitterModel::theta_stack_in_bounds().
BoolVecT mappel::PointEmitterModel::theta_stack_in_bounds (const ParamVecT & theta) const inherited
Definition at line 296 of file PointEmitterModel.cpp.
References mappel::PointEmitterModel::check_param_shape(), and mappel::PointEmitterModel::theta_in_bounds().
void mappel::Gauss2DsModel::update_internal_1Dsum_estimators () protected
Definition at line 100 of file Gauss2DsModel.cpp.
References get_max_sigma(), mappel::PointEmitterModel::get_prior(), make_internal_1Dsum_estimator(), min_sigma, mappel::ImageFormat2DBase::size, x_model, and y_model.
Referenced by debug_internal_sum_model_y(), set_hyperparams(), and set_prior().
Member Data Documentation
const double mappel::PointEmitterModel::bounds_epsilon = 1.0E-6 static inherited
Distance from the boundary to constrain in bound_theta and bounded_theta methods
Definition at line 52 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::set_bounds(), mappel::PointEmitterModel::set_lbound(), set_max_sigma_ratio(), and mappel::PointEmitterModel::set_ubound().
const double mappel::PointEmitterModel::default_alpha_sigma = 2 static inherited
Default per-pixel background gamma distribution shape
Definition at line 62 of file PointEmitterModel.h.
const double mappel::PointEmitterModel::default_beta_pos = 3 static inherited
Default position parameter in symmetric beta-distributions
Definition at line 56 of file PointEmitterModel.h.
const double mappel::PointEmitterModel::default_intensity_kappa = 2 static inherited
Default shape for intensity gamma distributions
Definition at line 60 of file PointEmitterModel.h.
const double mappel::PointEmitterModel::default_max_I = INFINITY static inherited
Default emitter intensity mean
Definition at line 59 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::make_prior_component_intensity().
const double mappel::PointEmitterModel::default_mean_I = 300 static inherited
Default emitter intensity mean
Definition at line 58 of file PointEmitterModel.h.
Referenced by mappel::MCMCAdaptor1D::set_intensity_mcmc_sampling().
const double mappel::PointEmitterModel::default_pixel_mean_bg = 4 static inherited
Default per-pixel mean background counts
Definition at line 61 of file PointEmitterModel.h.
Referenced by mappel::Gauss1DsModel::make_default_prior_beta_position(), mappel::Gauss2DModel::make_default_prior_beta_position(), mappel::Gauss1DModel::make_default_prior_beta_position(), make_default_prior_beta_position(), mappel::Gauss1DsModel::make_default_prior_normal_position(), mappel::Gauss2DModel::make_default_prior_normal_position(), mappel::Gauss1DModel::make_default_prior_normal_position(), make_default_prior_normal_position(), and mappel::MCMCAdaptor1D::set_background_mcmc_sampling().
const double mappel::PointEmitterModel::default_sigma_pos = 1 static inherited
Default position parameter in symmetric beta-distributions
Definition at line 57 of file PointEmitterModel.h.
const std::string mappel::Gauss2DsModel::DefaultPriorType = "Normal" static
Definition at line 59 of file Gauss2DsModel.h.
Referenced by get_min_sigma().
const std::string mappel::PointEmitterModel::DefaultSeperableInitEstimator = "TrustRegion" static inherited
Estimator name to use in 1D separable initializations
Definition at line 49 of file PointEmitterModel.h.
Referenced by mappel::Gauss2DModel::initial_theta_estimate(), mappel::Gauss2DsxyModel::initial_theta_estimate(), and initial_theta_estimate().
double mappel::MCMCAdaptor1D::eta_bg =0 protected inherited
The standard deviation for the normally distributed perturbation to theta_bg in the random walk MCMC sampling
Definition at line 32 of file MCMCAdaptor1D.h.
Referenced by mappel::MCMCAdaptor1D::get_stats(), mappel::MCMCAdaptor1D::MCMCAdaptor1D(), mappel::MCMCAdaptor1D::operator=(), mappel::MCMCAdaptor2D::sample_mcmc_candidate(), mappel::MCMCAdaptor2Ds::sample_mcmc_candidate(), mappel::MCMCAdaptor1Ds::sample_mcmc_candidate(), mappel::MCMCAdaptor1D::sample_mcmc_candidate(), and mappel::MCMCAdaptor1D::set_background_mcmc_sampling().
double mappel::MCMCAdaptor1D::eta_I =0 protected inherited
The standard deviation for the normally distributed perturbation to theta_I in the random walk MCMC sampling
Definition at line 31 of file MCMCAdaptor1D.h.
Referenced by mappel::MCMCAdaptor1D::get_stats(), mappel::MCMCAdaptor1D::MCMCAdaptor1D(), mappel::MCMCAdaptor1D::operator=(), mappel::MCMCAdaptor2D::sample_mcmc_candidate(), mappel::MCMCAdaptor2Ds::sample_mcmc_candidate(), mappel::MCMCAdaptor1Ds::sample_mcmc_candidate(), mappel::MCMCAdaptor1D::sample_mcmc_candidate(), and mappel::MCMCAdaptor1D::set_intensity_mcmc_sampling().
double mappel::MCMCAdaptor2Ds::eta_sigma =0 protected inherited
The standard deviation for the normally distributed perturbation to theta_bg in the random walk MCMC sampling
Definition at line 26 of file MCMCAdaptor2Ds.h.
Referenced by mappel::MCMCAdaptor2Ds::get_stats(), mappel::MCMCAdaptor2Ds::MCMCAdaptor2Ds(), mappel::MCMCAdaptor2Ds::operator=(), and mappel::MCMCAdaptor2Ds::sample_mcmc_candidate().
double mappel::MCMCAdaptor1D::eta_x =0 protected inherited
The standard deviation for the normally distributed perturbation to theta_x in the random walk MCMC sampling
Definition at line 30 of file MCMCAdaptor1D.h.
Referenced by mappel::MCMCAdaptor1D::get_stats(), mappel::MCMCAdaptor1D::MCMCAdaptor1D(), mappel::MCMCAdaptor1D::operator=(), mappel::MCMCAdaptor2D::sample_mcmc_candidate(), mappel::MCMCAdaptor1Ds::sample_mcmc_candidate(), mappel::MCMCAdaptor2Ds::sample_mcmc_candidate(), and mappel::MCMCAdaptor1D::sample_mcmc_candidate().
double mappel::MCMCAdaptor2D::eta_y =0 protected inherited
The standard deviation for the normally distributed perturbation to theta_y in the random walk MCMC sampling
Definition at line 27 of file MCMCAdaptor2D.h.
Referenced by mappel::MCMCAdaptor2D::get_stats(), mappel::MCMCAdaptor2D::MCMCAdaptor2D(), mappel::MCMCAdaptor2D::operator=(), mappel::MCMCAdaptor2Ds::sample_mcmc_candidate(), and mappel::MCMCAdaptor2D::sample_mcmc_candidate().
const double mappel::MCMCAdaptorBase::global_default_mcmc_sigma_scale = 0.05 static inherited
Definition at line 16 of file MCMCAdaptorBase.h.
Referenced by mappel::MCMCAdaptor1Ds::MCMCAdaptor1Ds(), mappel::MCMCAdaptor2D::MCMCAdaptor2D(), and mappel::MCMCAdaptor2Ds::MCMCAdaptor2Ds().
const double mappel::MCMCAdaptorBase::global_max_mcmc_sigma_scale = 0.5 static inherited
Definition at line 17 of file MCMCAdaptorBase.h.
Referenced by mappel::MCMCAdaptorBase::MCMCAdaptorBase(), and mappel::MCMCAdaptorBase::set_mcmc_sigma_scale().
const double mappel::PointEmitterModel::global_max_psf_sigma = 1E2 static inherited
Global maxmimum for any psf_sigma. Sizes above this value are invalid, and nowhere near useful for practical point emitter localization
Definition at line 54 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::check_psf_sigma().
const ImageFormat2DBase::ImageCoordT mappel::ImageFormat2DBase::global_max_size =512 static inherited
Maximum size along any dimension of the image. This is insanely big to catch obvious errors
Definition at line 39 of file ImageFormat2DBase.h.
Referenced by mappel::ImageFormat2DBase::check_size().
const double mappel::PointEmitterModel::global_min_psf_sigma = 1E-1 static inherited
Global minimum for any psf_sigma. Sizes below this value are invalid, and nowhere near useful for practical point emitter localization
Definition at line 53 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::check_psf_sigma().
const ImageFormat2DBase::ImageCoordT mappel::ImageFormat2DBase::global_min_size =3 static inherited
Minimum size along any dimension of the image.
Definition at line 38 of file ImageFormat2DBase.h.
Referenced by mappel::ImageFormat2DBase::check_size().
ParamT mappel::PointEmitterModel::lbound protected inherited
Definition at line 148 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::bound_theta(), mappel::PointEmitterModel::bounded_theta(), mappel::PointEmitterModel::get_lbound(), mappel::PointEmitterModel::get_stats(), mappel::Gauss1DsModel::initial_theta_estimate(), mappel::Gauss2DModel::initial_theta_estimate(), initial_theta_estimate(), mappel::PointEmitterModel::operator=(), mappel::PointEmitterModel::reflected_theta(), mappel::PointEmitterModel::set_bounds(), mappel::PointEmitterModel::set_lbound(), mappel::PointEmitterModel::set_prior(), mappel::PointEmitterModel::set_ubound(), and mappel::PointEmitterModel::theta_in_bounds().
VecT mappel::Gauss2DsModel::min_sigma protected
Gaussian PSF in pixels
Definition at line 118 of file Gauss2DsModel.h.
Referenced by compute_max_sigma_ratio(), debug_internal_sum_model_y(), mappel::Gauss2DsMAP::Gauss2DsMAP(), mappel::Gauss2DsMLE::Gauss2DsMLE(), Gauss2DsModel(), get_min_sigma(), initial_theta_estimate(), make_internal_1Dsum_estimator(), operator=(), set_min_sigma(), mappel::Gauss2DsModel::Stencil::sigmaX(), mappel::Gauss2DsModel::Stencil::sigmaY(), and update_internal_1Dsum_estimators().
const ImageFormat2DBase::ImageCoordT mappel::ImageFormat2DBase::num_dim =2 static inherited
Number of image dimensions.
Definition at line 37 of file ImageFormat2DBase.h.
Referenced by mappel::ImageFormat2DBase::get_stats().
IdxT mappel::PointEmitterModel::num_hyperparams protected inherited
Definition at line 147 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::get_num_hyperparams(), mappel::PointEmitterModel::get_stats(), mappel::PointEmitterModel::operator=(), and mappel::PointEmitterModel::set_prior().
IdxT mappel::PointEmitterModel::num_params protected inherited
Definition at line 146 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::bound_theta(), mappel::PointEmitterModel::bounded_theta(), mappel::PointEmitterModel::check_param_shape(), mappel::PointEmitterModel::get_num_params(), mappel::PointEmitterModel::get_stats(), mappel::Gauss1DModel::initial_theta_estimate(), mappel::Gauss2DModel::initial_theta_estimate(), initial_theta_estimate(), mappel::PointEmitterModel::make_param(), mappel::PointEmitterModel::make_param_mat(), mappel::PointEmitterModel::make_param_mat_stack(), mappel::PointEmitterModel::make_param_stack(), mappel::PointEmitterModel::operator=(), mappel::PointEmitterModel::reflected_theta(), mappel::PointEmitterModel::set_bounds(), mappel::PointEmitterModel::set_lbound(), mappel::PointEmitterModel::set_prior(), mappel::PointEmitterModel::set_ubound(), and mappel::PointEmitterModel::theta_in_bounds().
IdxT mappel::MCMCAdaptorBase::num_phases protected inherited
The number of different sampling phases for candidate selection MCMC. Each phase changes a different subset of variables.
Definition at line 29 of file MCMCAdaptorBase.h.
Referenced by mappel::MCMCAdaptorBase::get_mcmc_num_phases(), mappel::MCMCAdaptorBase::get_stats(), mappel::MCMCAdaptor2D::sample_mcmc_candidate(), mappel::MCMCAdaptor1Ds::sample_mcmc_candidate(), mappel::MCMCAdaptor2Ds::sample_mcmc_candidate(), mappel::MCMCAdaptor1D::sample_mcmc_candidate(), and mappel::MCMCAdaptorBase::set_mcmc_num_phases().
CompositeDist mappel::PointEmitterModel::prior protected inherited
Definition at line 145 of file PointEmitterModel.h.
Referenced by mappel::Gauss2DModel::debug_internal_sum_model_y(), debug_internal_sum_model_y(), mappel::Gauss2DModel::Gauss2DModel(), Gauss2DsModel(), mappel::PointEmitterModel::get_hyperparam_index(), mappel::PointEmitterModel::get_hyperparam_names(), mappel::PointEmitterModel::get_hyperparam_value(), mappel::PointEmitterModel::get_hyperparams(), mappel::Gauss1DsModel::get_max_sigma(), mappel::Gauss1DsModel::get_min_sigma(), mappel::PointEmitterModel::get_param_names(), mappel::PointEmitterModel::get_prior(), mappel::PointEmitterModel::get_stats(), mappel::PointEmitterModel::has_hyperparam(), mappel::PointEmitterModel::operator=(), mappel::PointEmitterModel::PointEmitterModel(), mappel::PointEmitterModel::rename_hyperparam(), mappel::PointEmitterModel::sample_prior(), mappel::PointEmitterModel::set_bounds(), mappel::PointEmitterModel::set_hyperparam_names(), mappel::PointEmitterModel::set_hyperparam_value(), mappel::PointEmitterModel::set_hyperparams(), mappel::PointEmitterModel::set_lbound(), mappel::Gauss1DsModel::set_max_sigma(), mappel::Gauss1DsModel::set_min_sigma(), mappel::PointEmitterModel::set_param_names(), mappel::PointEmitterModel::set_prior(), and mappel::PointEmitterModel::set_ubound().
const StringVecT mappel::Gauss2DsModel::prior_types static
Initial value:
= { "Beta",
                                                "Normal"
                                                 }
Definition at line 58 of file Gauss2DsModel.h.
Referenced by get_min_sigma().
double mappel::MCMCAdaptorBase::sigma_scale protected inherited
A scaling factor for step sizes as a fraction of the size of the domain dimension we are walking in. (0.05 default)
Definition at line 30 of file MCMCAdaptorBase.h.
Referenced by mappel::MCMCAdaptorBase::get_mcmc_sigma_scale(), mappel::MCMCAdaptorBase::get_stats(), mappel::MCMCAdaptor1D::MCMCAdaptor1D(), mappel::MCMCAdaptor1Ds::MCMCAdaptor1Ds(), mappel::MCMCAdaptor2D::MCMCAdaptor2D(), mappel::MCMCAdaptor2Ds::MCMCAdaptor2Ds(), mappel::MCMCAdaptor1D::set_background_mcmc_sampling(), mappel::MCMCAdaptor1D::set_intensity_mcmc_sampling(), and mappel::MCMCAdaptorBase::set_mcmc_sigma_scale().
ImageSizeT mappel::ImageFormat2DBase::size protected inherited
Number of pixels in X dimension for 1D image
Definition at line 67 of file ImageFormat2DBase.h.
Referenced by mappel::cgauss_compute_estimate(), mappel::cgauss_compute_estimate_debug(), mappel::cgauss_heuristic_compute_estimate(), mappel::ImageFormat2DBase::check_image_shape(), mappel::Gauss2DModel::Stencil::compute_derivatives(), mappel::Gauss2DsModel::Stencil::compute_derivatives(), mappel::Gauss2DModel::debug_internal_sum_model_y(), debug_internal_sum_model_y(), mappel::methods::expected_information(), mappel::Gauss2DModel::Gauss2DModel(), mappel::Gauss2DsMAP::Gauss2DsMAP(), mappel::Gauss2DsMLE::Gauss2DsMLE(), Gauss2DsModel(), mappel::ImageFormat2DBase::get_num_pixels(), mappel::ImageFormat2DBase::get_size(), mappel::ImageFormat2DBase::get_stats(), mappel::methods::likelihood::grad(), mappel::methods::likelihood::grad2(), mappel::methods::likelihood::debug::grad_components(), mappel::methods::likelihood::hessian(), mappel::methods::likelihood::debug::hessian_components(), mappel::Gauss2DModel::initial_theta_estimate(), initial_theta_estimate(), mappel::methods::likelihood::llh(), mappel::methods::likelihood::debug::llh_components(), mappel::Gauss2DModel::make_default_prior_beta_position(), make_default_prior_beta_position(), mappel::Gauss2DModel::make_default_prior_normal_position(), make_default_prior_normal_position(), mappel::ImageFormat2DBase::make_image(), mappel::ImageFormat2DBase::make_image_stack(), mappel::Gauss2DModel::make_internal_1Dsum_estimator(), make_internal_1Dsum_estimator(), mappel::Gauss2DModel::make_prior_beta_position(), make_prior_beta_position(), mappel::Gauss2DModel::make_prior_normal_position(), make_prior_normal_position(), mappel::methods::model_image(), mappel::ImageFormat2DBase::operator=(), mappel::methods::likelihood::rllh(), mappel::methods::likelihood::debug::rllh_components(), mappel::ImageFormat2DBase::set_size(), mappel::Gauss2DModel::set_size(), set_size(), mappel::methods::simulate_image(), mappel::methods::simulate_image_from_model(), mappel::Gauss2DModel::Stencil::Stencil(), mappel::Gauss2DsModel::Stencil::Stencil(), mappel::Gauss2DModel::update_internal_1Dsum_estimators(), and update_internal_1Dsum_estimators().
ParamT mappel::PointEmitterModel::ubound protected inherited
Definition at line 148 of file PointEmitterModel.h.
Referenced by mappel::PointEmitterModel::bound_theta(), mappel::PointEmitterModel::bounded_theta(), mappel::PointEmitterModel::get_stats(), mappel::PointEmitterModel::get_ubound(), mappel::Gauss1DsModel::initial_theta_estimate(), mappel::Gauss2DModel::initial_theta_estimate(), initial_theta_estimate(), mappel::PointEmitterModel::operator=(), mappel::PointEmitterModel::reflected_theta(), mappel::PointEmitterModel::set_bounds(), mappel::PointEmitterModel::set_lbound(), mappel::PointEmitterModel::set_prior(), mappel::PointEmitterModel::set_ubound(), and mappel::PointEmitterModel::theta_in_bounds().
Gauss1DSumModelT mappel::Gauss2DsModel::x_model protected
X-model fits 2D images X-axis (column sum). Using variable sigma 1D model.
Definition at line 119 of file Gauss2DsModel.h.
Referenced by debug_internal_sum_model_x(), initial_theta_estimate(), operator=(), set_max_sigma_ratio(), set_min_sigma(), set_size(), and update_internal_1Dsum_estimators().
Gauss1DSumModelT mappel::Gauss2DsModel::y_model protected
Y-model fits 2D images Y-axis (row sum). Using variable sigma 1D model.
Definition at line 120 of file Gauss2DsModel.h.
Referenced by debug_internal_sum_model_y(), Gauss2DsModel(), initial_theta_estimate(), operator=(), set_max_sigma_ratio(), set_min_sigma(), set_size(), and update_internal_1Dsum_estimators().
The documentation for this class was generated from the following files:
Gauss2DsModel.h
Gauss2DsModel.cpp