Mappel: mappel::PriorMAP1DObjective Class Reference
mappel::PriorMAP1DObjective Class Reference
A Mixin class to configure a Gauss1DModel for MAP estimation (default 1D prior).
#include </home/travis/build/markjolah/Mappel/include/Mappel/PriorMAP1DObjective.h>
Protected Types
using ParamT = arma::vec
using ParamMatT = arma::mat
Protected Member Functions
void set_hyperparameters (double beta_x, double mean_I, double kappa_I, double mean_bg, double kappa_bg) public
double prior_log_likelihood (const ParamT &theta) const
double prior_relative_log_likelihood (const ParamT &theta) const
void prior_grad_update (const ParamT &theta, ParamT &grad) const
void prior_grad2_update (const ParamT &theta, ParamT &grad2) const
void prior_hess_update (const ParamT &theta, ParamMatT &hess) const
Protected Attributes
double log_prior_pos_const
double log_prior_I_const
double log_prior_bg_const
Detailed Description
A Mixin class to configure a Gauss1DModel for MAP estimation (default 1D prior).
Definition at line 18 of file PriorMAP1DObjective.h.
Member Typedef Documentation
using mappel::PriorMAP1DObjective::ParamMatT = arma::mat protected
Definition at line 22 of file PriorMAP1DObjective.h.
using mappel::PriorMAP1DObjective::ParamT = arma::vec protected
Definition at line 21 of file PriorMAP1DObjective.h.
Member Function Documentation
void mappel::PriorMAP1DObjective::prior_grad2_update (const ParamT & theta, ParamT & grad2) const inline protected
Definition at line 72 of file PriorMAP1DObjective.h.
References mappel::beta_prior_grad2(), mappel::gamma_prior_grad2(), and mappel::methods::objective::grad2().
Referenced by set_hyperparameters().
void mappel::PriorMAP1DObjective::prior_grad_update (const ParamT & theta, ParamT & grad) const inline protected
Definition at line 64 of file PriorMAP1DObjective.h.
References mappel::beta_prior_grad(), mappel::gamma_prior_grad(), and mappel::methods::objective::grad().
Referenced by set_hyperparameters().
void mappel::PriorMAP1DObjective::prior_hess_update (const ParamT & theta, ParamMatT & hess) const inline protected
Definition at line 80 of file PriorMAP1DObjective.h.
References mappel::beta_prior_grad2(), and mappel::gamma_prior_grad2().
Referenced by set_hyperparameters().
double mappel::PriorMAP1DObjective::prior_log_likelihood (const ParamT & theta) const inline protected
Definition at line 48 of file PriorMAP1DObjective.h.
References log_prior_bg_const, log_prior_I_const, log_prior_pos_const, prior_relative_log_likelihood(), and mappel::methods::objective::rllh().
Referenced by set_hyperparameters().
double mappel::PriorMAP1DObjective::prior_relative_log_likelihood (const ParamT & theta) const inline protected
Definition at line 55 of file PriorMAP1DObjective.h.
References mappel::rllh_beta_prior(), and mappel::rllh_gamma_prior().
Referenced by prior_log_likelihood(), and set_hyperparameters().
void mappel::PriorMAP1DObjective::set_hyperparameters (double beta_x, double mean_I, double kappa_I, double mean_bg, double kappa_bg) inline protected
Definition at line 31 of file PriorMAP1DObjective.h.
References mappel::methods::objective::grad(), mappel::methods::objective::grad2(), prior_grad2_update(), prior_grad_update(), prior_hess_update(), prior_log_likelihood(), and prior_relative_log_likelihood().
Member Data Documentation
double mappel::PriorMAP1DObjective::log_prior_bg_const protected
This is kappa_bg*(log(kappa_bg)-1/mean_bg-log(mean_bg))-lgamma(kappa_bg)
Definition at line 30 of file PriorMAP1DObjective.h.
Referenced by prior_log_likelihood().
double mappel::PriorMAP1DObjective::log_prior_I_const protected
This is kappa_I*(log(kappa_I)-1/mean_I-log(mean_I))-lgamma(kappa_I)
Definition at line 29 of file PriorMAP1DObjective.h.
Referenced by prior_log_likelihood().
double mappel::PriorMAP1DObjective::log_prior_pos_const protected
This is -2*lgamma(beta_x)-lgamma(2*beta_x)
Definition at line 28 of file PriorMAP1DObjective.h.
Referenced by prior_log_likelihood().
The documentation for this class was generated from the following file:
PriorMAP1DObjective.h