Mappel: mappel::ImageFormat1DBase Class Reference
mappel::ImageFormat1DBase Class Reference
A virtual base class for 2D image localization objectives.
#include </home/travis/build/markjolah/Mappel/include/Mappel/ImageFormat1DBase.h>
Public Types
using ImageCoordT = uint32_t
using ImagePixelT = double
template<class CoordT >
using ImageSizeShapeT = CoordT
template<class CoordT >
using ImageSizeVecShapeT = arma::Col< CoordT >
using ImageSizeT = ImageSizeShapeT< ImageCoordT >
using ImageSizeVecT = ImageSizeVecShapeT< ImageCoordT >
template<class PixelT >
using ImageShapeT = arma::Col< PixelT >
template<class PixelT >
using ImageStackShapeT = arma::Mat< PixelT >
using ImageT = ImageShapeT< ImagePixelT >
using ImageStackT = ImageStackShapeT< ImagePixelT >
Public Member Functions
StatsT get_stats () const
ImageT make_image () const
ImageStackT make_image_stack (ImageCoordT n) const
ImageCoordT get_size_image_stack (const ImageStackT &stack) const
ImageT get_image_from_stack (const ImageStackT &stack, ImageCoordT n) const
template<class ImT >
void set_image_in_stack (ImageStackT &stack, ImageCoordT n, const ImT &im) const
ImageSizeT get_size () const
ImageCoordT get_size (IdxT idx) const
ImageCoordT get_num_pixels () const
void set_size (const ImageSizeT &size_)
void set_size (const arma::Col< ImageCoordT > &sz)
void check_image_shape (const ImageT &im) const
Check the shape of a single images is correct for model size.
void check_image_shape (const ImageStackT &ims) const
Check the shape of a stack of images is correct for model size.
Static Public Member Functions
static void check_size (const ImageSizeT &size_)
Check the size argument for the model.
Static Public Attributes
static const ImageCoordT num_dim = 1
static const ImageCoordT global_min_size = 3
static const ImageCoordT global_max_size = 512
Protected Member Functions
ImageFormat1DBase ()=default
ImageFormat1DBase (ImageSizeT size_)
Protected Attributes
ImageSizeT size
Detailed Description
A virtual base class for 2D image localization objectives.
This class should be inherited virtually by both the model and the objective so that the common image information and functions are available in both Model and Objective classes hierarchies
Definition at line 23 of file ImageFormat1DBase.h.
Member Typedef Documentation
using mappel::ImageFormat1DBase::ImageCoordT = uint32_t
Image size coordinate storage type
Definition at line 25 of file ImageFormat1DBase.h.
using mappel::ImageFormat1DBase::ImagePixelT = double
Image pixel storage type
Definition at line 26 of file ImageFormat1DBase.h.
template<class PixelT > using mappel::ImageFormat1DBase::ImageShapeT = arma::Col<PixelT>
Shape of the data type for a single image
Definition at line 33 of file ImageFormat1DBase.h.
template<class CoordT > using mappel::ImageFormat1DBase::ImageSizeShapeT = CoordT
Shape of the data type to store 1-image's coordinates
Definition at line 28 of file ImageFormat1DBase.h.
using mappel::ImageFormat1DBase::ImageSizeT = ImageSizeShapeT<ImageCoordT>
Data type for a single image size
Definition at line 30 of file ImageFormat1DBase.h.
template<class CoordT > using mappel::ImageFormat1DBase::ImageSizeVecShapeT = arma::Col<CoordT>
Shape of the data type to store a vector of image's coordinates
Definition at line 29 of file ImageFormat1DBase.h.
using mappel::ImageFormat1DBase::ImageSizeVecT = ImageSizeVecShapeT<ImageCoordT>
Data type for a sequence of image sizes
Definition at line 31 of file ImageFormat1DBase.h.
template<class PixelT > using mappel::ImageFormat1DBase::ImageStackShapeT = arma::Mat<PixelT>
Shape of the data type for a sequence of images
Definition at line 34 of file ImageFormat1DBase.h.
using mappel::ImageFormat1DBase::ImageStackT = ImageStackShapeT<ImagePixelT>
Data type to represent a sequence of images
Definition at line 36 of file ImageFormat1DBase.h.
using mappel::ImageFormat1DBase::ImageT = ImageShapeT<ImagePixelT>
Data type to represent single image
Definition at line 35 of file ImageFormat1DBase.h.
Constructor & Destructor Documentation
mappel::ImageFormat1DBase::ImageFormat1DBase () protected default
ImageFormat1DBase::ImageFormat1DBase (ImageSizeT size_) explicit protected
Definition at line 13 of file ImageFormat1DBase.cpp.
References check_size().
Member Function Documentation
void ImageFormat1DBase::check_image_shape (const ImageT & im) const
Check the shape of a single images is correct for model size.
Definition at line 59 of file ImageFormat1DBase.cpp.
References size.
void ImageFormat1DBase::check_image_shape (const ImageStackT & ims) const
Check the shape of a stack of images is correct for model size.
Definition at line 71 of file ImageFormat1DBase.cpp.
References size.
void ImageFormat1DBase::check_size (const ImageSizeT & size_) static
Check the size argument for the model.
Definition at line 39 of file ImageFormat1DBase.cpp.
References global_max_size, and global_min_size.
Referenced by ImageFormat1DBase(), and set_size().
ImageFormat1DBase::ImageT ImageFormat1DBase::get_image_from_stack (const ImageStackT & stack, ImageCoordT n) const inline
Definition at line 108 of file ImageFormat1DBase.h.
ImageFormat1DBase::ImageCoordT ImageFormat1DBase::get_num_pixels () const inline
Definition at line 82 of file ImageFormat1DBase.h.
References size.
Referenced by get_stats().
ImageFormat1DBase::ImageSizeT ImageFormat1DBase::get_size () const inline
Definition at line 71 of file ImageFormat1DBase.h.
References size.
Referenced by get_stats().
ImageFormat1DBase::ImageCoordT ImageFormat1DBase::get_size (IdxT idx) const
Definition at line 20 of file ImageFormat1DBase.cpp.
References size.
ImageFormat1DBase::ImageCoordT ImageFormat1DBase::get_size_image_stack (const ImageStackT & stack) const inline
Definition at line 101 of file ImageFormat1DBase.h.
StatsT ImageFormat1DBase::get_stats () const
Definition at line 81 of file ImageFormat1DBase.cpp.
References get_num_pixels(), get_size(), and num_dim.
Referenced by mappel::Gauss1DModel::get_stats(), and mappel::Gauss1DsModel::get_stats().
ImageFormat1DBase::ImageT ImageFormat1DBase::make_image () const inline
Definition at line 87 of file ImageFormat1DBase.h.
References size.
ImageFormat1DBase::ImageStackT ImageFormat1DBase::make_image_stack (ImageCoordT n) const inline
Definition at line 94 of file ImageFormat1DBase.h.
References size.
template<class ImT > void ImageFormat1DBase::set_image_in_stack (ImageStackT & stack, ImageCoordT n, const ImT & im) const
Definition at line 115 of file ImageFormat1DBase.h.
void ImageFormat1DBase::set_size (const ImageSizeT & size_)
Definition at line 30 of file ImageFormat1DBase.cpp.
References check_size(), and size.
Referenced by set_size(), mappel::Gauss2DModel::set_size(), and mappel::Gauss2DsModel::set_size().
void ImageFormat1DBase::set_size (const arma::Col< ImageCoordT > & sz) inline
Definition at line 75 of file ImageFormat1DBase.h.
References set_size().
Member Data Documentation
const ImageFormat1DBase::ImageCoordT ImageFormat1DBase::global_max_size = 512 static
Maximum size along any dimension of the image. This is insanely big to catch obvious errors
Definition at line 40 of file ImageFormat1DBase.h.
Referenced by check_size().
const ImageFormat1DBase::ImageCoordT ImageFormat1DBase::global_min_size = 3 static
Minimum size along any dimension of the image.
Definition at line 39 of file ImageFormat1DBase.h.
Referenced by check_size().
const ImageFormat1DBase::ImageCoordT ImageFormat1DBase::num_dim = 1 static
Number of image dimensions.
Definition at line 38 of file ImageFormat1DBase.h.
Referenced by get_stats().
ImageSizeT mappel::ImageFormat1DBase::size protected
Number of pixels in X dimension for 1D image
Definition at line 65 of file ImageFormat1DBase.h.
Referenced by check_image_shape(), mappel::Gauss1DsModel::Stencil::compute_derivatives(), mappel::Gauss1DModel::Stencil::compute_derivatives(), get_num_pixels(), get_size(), mappel::Gauss1DModel::initial_theta_estimate(), mappel::Gauss1DsModel::initial_theta_estimate(), make_image(), make_image_stack(), set_size(), mappel::Gauss1DsModel::Stencil::Stencil(), and mappel::Gauss1DModel::Stencil::Stencil().
The documentation for this class was generated from the following files:
ImageFormat1DBase.h
ImageFormat1DBase.cpp