Mappel: mappel::Gauss1DsModel::Stencil Class Reference
mappel::Gauss1DsModel::Stencil Class Reference
Stencil for 1D variable-sigma models.
#include </home/travis/build/markjolah/Mappel/include/Mappel/Gauss1DsModel.h>
Public Types
using ParamT = Gauss1DsModel::ParamT
Public Member Functions
Stencil ()
Stencil (const Gauss1DsModel &model, const ParamT &theta, bool _compute_derivatives=true)
void compute_derivatives ()
double x () const
double I () const
double bg () const
double sigma () const
Public Attributes
bool derivatives_computed = false
Gauss1DsModel const * model
ParamT theta
VecT dx
VecT Gx
VecT X
VecT DX
VecT DXS
VecT DXS2
VecT DXSX
Friends
std::ostream & operator<< (std::ostream &out, const Gauss1DsModel::Stencil &s)
Detailed Description
Stencil for 1D variable-sigma models.
Definition at line 24 of file Gauss1DsModel.h.
Member Typedef Documentation
using mappel::Gauss1DsModel::Stencil::ParamT = Gauss1DsModel::ParamT
Definition at line 27 of file Gauss1DsModel.h.
Constructor & Destructor Documentation
mappel::Gauss1DsModel::Stencil::Stencil () inline
Definition at line 38 of file Gauss1DsModel.h.
References compute_derivatives().
Referenced by mappel::Gauss1DsModel::make_stencil().
mappel::Gauss1DsModel::Stencil::Stencil (const Gauss1DsModel & model, const ParamT & theta, bool _compute_derivatives = true)
Definition at line 159 of file Gauss1DsModel.cpp.
References compute_derivatives(), dx, mappel::make_d_stencil(), mappel::make_X_stencil(), model, sigma(), mappel::ImageFormat1DBase::size, X, and x().
Member Function Documentation
double mappel::Gauss1DsModel::Stencil::bg () const inline
Definition at line 43 of file Gauss1DsModel.h.
References theta.
Referenced by mappel::Gauss1DsModel::initial_theta_estimate(), and mappel::Gauss1DsModel::pixel_model_value().
void mappel::Gauss1DsModel::Stencil::compute_derivatives ()
Definition at line 170 of file Gauss1DsModel.cpp.
References derivatives_computed, dx, DX, DXS, DXS2, DXSX, Gx, mappel::make_DX_stencil(), mappel::make_DXS2_stencil(), mappel::make_DXS_stencil(), mappel::make_DXSX_stencil(), mappel::make_G_stencil(), model, sigma(), and mappel::ImageFormat1DBase::size.
Referenced by Stencil().
double mappel::Gauss1DsModel::Stencil::I () const inline
Definition at line 42 of file Gauss1DsModel.h.
References theta.
Referenced by mappel::Gauss1DsModel::initial_theta_estimate(), mappel::Gauss1DsModel::pixel_grad(), mappel::Gauss1DsModel::pixel_grad2(), mappel::Gauss1DsModel::pixel_hess(), mappel::Gauss1DsModel::pixel_hess_update(), and mappel::Gauss1DsModel::pixel_model_value().
double mappel::Gauss1DsModel::Stencil::sigma () const inline
Definition at line 44 of file Gauss1DsModel.h.
References operator<<, and theta.
Referenced by compute_derivatives(), mappel::Gauss1DsModel::initial_theta_estimate(), mappel::Gauss1DsModel::pixel_grad2(), mappel::Gauss1DsModel::pixel_hess(), mappel::Gauss1DsModel::pixel_hess_update(), and Stencil().
double mappel::Gauss1DsModel::Stencil::x () const inline
Definition at line 41 of file Gauss1DsModel.h.
References theta.
Referenced by Stencil().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const Gauss1DsModel::Stencil & s) friend
Definition at line 182 of file Gauss1DsModel.cpp.
Referenced by sigma().
Member Data Documentation
bool mappel::Gauss1DsModel::Stencil::derivatives_computed = false
Definition at line 26 of file Gauss1DsModel.h.
Referenced by compute_derivatives(), and mappel::operator<<().
VecT mappel::Gauss1DsModel::Stencil::dx
Definition at line 31 of file Gauss1DsModel.h.
Referenced by compute_derivatives(), mappel::operator<<(), and Stencil().
VecT mappel::Gauss1DsModel::Stencil::DX
Definition at line 34 of file Gauss1DsModel.h.
Referenced by compute_derivatives(), mappel::operator<<(), mappel::Gauss1DsModel::pixel_grad(), mappel::Gauss1DsModel::pixel_hess(), and mappel::Gauss1DsModel::pixel_hess_update().
VecT mappel::Gauss1DsModel::Stencil::DXS
Definition at line 35 of file Gauss1DsModel.h.
Referenced by compute_derivatives(), mappel::operator<<(), mappel::Gauss1DsModel::pixel_grad(), mappel::Gauss1DsModel::pixel_grad2(), mappel::Gauss1DsModel::pixel_hess(), and mappel::Gauss1DsModel::pixel_hess_update().
VecT mappel::Gauss1DsModel::Stencil::DXS2
Definition at line 36 of file Gauss1DsModel.h.
Referenced by compute_derivatives(), mappel::operator<<(), mappel::Gauss1DsModel::pixel_grad2(), mappel::Gauss1DsModel::pixel_hess(), and mappel::Gauss1DsModel::pixel_hess_update().
VecT mappel::Gauss1DsModel::Stencil::DXSX
Definition at line 37 of file Gauss1DsModel.h.
Referenced by compute_derivatives(), mappel::operator<<(), mappel::Gauss1DsModel::pixel_hess(), and mappel::Gauss1DsModel::pixel_hess_update().
VecT mappel::Gauss1DsModel::Stencil::Gx
Definition at line 32 of file Gauss1DsModel.h.
Referenced by compute_derivatives(), and mappel::operator<<().
Gauss1DsModel const* mappel::Gauss1DsModel::Stencil::model
Definition at line 28 of file Gauss1DsModel.h.
Referenced by compute_derivatives(), and Stencil().
ParamT mappel::Gauss1DsModel::Stencil::theta
Definition at line 30 of file Gauss1DsModel.h.
Referenced by bg(), I(), mappel::operator<<(), sigma(), and x().
VecT mappel::Gauss1DsModel::Stencil::X
Definition at line 33 of file Gauss1DsModel.h.
Referenced by mappel::operator<<(), mappel::Gauss1DsModel::pixel_grad(), mappel::Gauss1DsModel::pixel_model_value(), and Stencil().
The documentation for this class was generated from the following files:
Gauss1DsModel.h
Gauss1DsModel.cpp