Mappel: mappel::estimator::IterativeMaximizer< Model >::MaximizerData Class Reference
mappel::estimator::IterativeMaximizer< Model >::MaximizerData Class Reference
#include </home/travis/build/markjolah/Mappel/include/Mappel/estimator.h>
Public Member Functions
MaximizerData (const Model &model, const ModelDataT< Model > &im, const StencilT< Model > &s, bool save_seq=false)
MaximizerData (const Model &model, const ModelDataT< Model > &im, const StencilT< Model > &s, double rllh, bool save_seq=false)
void record_iteration ()
void record_iteration (const ParamT< Model > &accepted_theta)
Record an iteration point (derivatives computed)
void record_backtrack (double rejected_rllh)
Record a backtracked point (no derivative computations performed) Using the saved theta as the default.
void record_backtrack (const ParamT< Model > &rejected_theta, double rejected_rllh)
Record a backtracked point (no derivative computations performed)
bool has_theta_sequence () const
Return the saved theta sequence.
IdxT get_sequence_len () const
ParamVecT< Model > get_theta_sequence () const
IdxVecT get_backtrack_idxs () const
VecT get_theta_sequence_rllh () const
StencilT< Model > & stencil ()
Get the current stencil.
void set_stencil (const StencilT< Model > &s)
void save_stencil ()
Save the current stencil to the single reserve spot. Overwrites any previously saved stencil. This is used to save a stencil when backtracking.
void restore_stencil ()
Restore the single reserved stencil to the current stencil spot. Overwrites any previously saved stencil. This is used to restore a last good iterate (and associated stencil data) when backtracking.
const StencilT< Model > & saved_stencil () const
Get the saved stencil.
const ParamT< Model > & theta () const
Get the current stencil's theta.
const ParamT< Model > & saved_theta () const
Get the saved stencil's theta.
void set_fixed_parameters (const IdxVecT &fixed_parameters_idxs)
bool has_fixed_parameters () const
IdxT num_fixed_parameters () const
Public Attributes
const ModelDataT< Model > & im
ParamT< Model > grad
ParamT< Model > step
double rllh
int nBacktracks =0
int nIterations =0
IdxVecT fixed_idxs
IdxVecT free_idxs
Protected Member Functions
void expand_max_seq_len ()
Protected Attributes
const IdxT num_params
StencilT< Model > s0
StencilT< Model > s1
bool current_stencil
int max_seq_len =0
int seq_len =0
ParamVecT< Model > theta_seq
VecT seq_rllh
IdxVecT backtrack_idxs
Static Protected Attributes
static const int DefaultMaxSeqLength = 50
Default maximum length of sequence to perpare to save if debugging.
Detailed Description
template<class Model>
class mappel::estimator::IterativeMaximizer< Model >::MaximizerData
Definition at line 479 of file estimator.h.
Constructor & Destructor Documentation
template<class Model > mappel::estimator::IterativeMaximizer< Model >::MaximizerData::MaximizerData (const Model & model, const ModelDataT< Model > & im, const StencilT< Model > & s, bool save_seq = false)
Definition at line 738 of file estimator_impl.h.
template<class Model > mappel::estimator::IterativeMaximizer< Model >::MaximizerData::MaximizerData (const Model & model, const ModelDataT< Model > & im, const StencilT< Model > & s, double rllh, bool save_seq = false)
Definition at line 744 of file estimator_impl.h.
References mappel::estimator::IterativeMaximizer< Model >::MaximizerData::backtrack_idxs, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::DefaultMaxSeqLength, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::max_seq_len, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_iteration(), mappel::methods::objective::rllh(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::rllh, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::seq_rllh, and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::theta_seq.
Member Function Documentation
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::MaximizerData::expand_max_seq_len () protected
Definition at line 766 of file estimator_impl.h.
References mappel::estimator::IterativeMaximizer< Model >::MaximizerData::backtrack_idxs, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::max_seq_len, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::seq_rllh, and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::theta_seq.
Referenced by mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_backtrack(), and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_iteration().
template<class Model > IdxVecT mappel::estimator::IterativeMaximizer< Model >::MaximizerData::get_backtrack_idxs () const inline
Definition at line 506 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > IdxT mappel::estimator::IterativeMaximizer< Model >::MaximizerData::get_sequence_len () const inline
Definition at line 504 of file estimator.h.
template<class Model > ParamVecT<Model> mappel::estimator::IterativeMaximizer< Model >::MaximizerData::get_theta_sequence () const inline
Definition at line 505 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::estimator::IterativeMaximizer< Model >::local_maximize(), and mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > VecT mappel::estimator::IterativeMaximizer< Model >::MaximizerData::get_theta_sequence_rllh () const inline
Definition at line 507 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::estimator::IterativeMaximizer< Model >::local_maximize(), and mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > bool mappel::estimator::IterativeMaximizer< Model >::MaximizerData::has_fixed_parameters () const inline
Definition at line 530 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > bool mappel::estimator::IterativeMaximizer< Model >::MaximizerData::has_theta_sequence () const inline
Return the saved theta sequence.
Definition at line 503 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > IdxT mappel::estimator::IterativeMaximizer< Model >::MaximizerData::num_fixed_parameters () const inline
Definition at line 531 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_backtrack (double rejected_rllh) inline
Record a backtracked point (no derivative computations performed) Using the saved theta as the default.
Definition at line 498 of file estimator.h.
References mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_backtrack(), and mappel::estimator::MLEData::theta.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack(), and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_backtrack().
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_backtrack (const ParamT< Model > & rejected_theta, double rejected_rllh)
Record a backtracked point (no derivative computations performed)
Definition at line 787 of file estimator_impl.h.
References mappel::estimator::IterativeMaximizer< Model >::MaximizerData::backtrack_idxs, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::expand_max_seq_len(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::max_seq_len, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::nBacktracks, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::seq_len, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::seq_rllh, and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::theta_seq.
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_iteration () inline
Definition at line 494 of file estimator.h.
References mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_iteration(), and mappel::estimator::MLEData::theta.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::MaximizerData(), mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack(), and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_iteration().
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_iteration (const ParamT< Model > & accepted_theta)
Record an iteration point (derivatives computed)
Definition at line 775 of file estimator_impl.h.
References mappel::estimator::IterativeMaximizer< Model >::MaximizerData::expand_max_seq_len(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::max_seq_len, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::nIterations, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::rllh, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::seq_len, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::seq_rllh, and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::theta_seq.
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::MaximizerData::restore_stencil () inline
Restore the single reserved stencil to the current stencil spot. Overwrites any previously saved stencil. This is used to restore a last good iterate (and associated stencil data) when backtracking.
Definition at line 521 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack().
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::MaximizerData::save_stencil () inline
Save the current stencil to the single reserve spot. Overwrites any previously saved stencil. This is used to save a stencil when backtracking.
Definition at line 516 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack().
template<class Model > const StencilT<Model>& mappel::estimator::IterativeMaximizer< Model >::MaximizerData::saved_stencil () const inline
Get the saved stencil.
Definition at line 523 of file estimator.h.
template<class Model > const ParamT<Model>& mappel::estimator::IterativeMaximizer< Model >::MaximizerData::saved_theta () const inline
Get the saved stencil's theta.
Definition at line 527 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack().
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::MaximizerData::set_fixed_parameters (const IdxVecT & fixed_parameters_idxs)
Definition at line 800 of file estimator_impl.h.
References mappel::estimator::IterativeMaximizer< Model >::MaximizerData::fixed_idxs, mappel::estimator::IterativeMaximizer< Model >::MaximizerData::free_idxs, and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::num_params.
Referenced by mappel::estimator::IterativeMaximizer< Model >::compute_profile_estimate(), and mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > void mappel::estimator::IterativeMaximizer< Model >::MaximizerData::set_stencil (const StencilT< Model > & s) inline
Definition at line 511 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack().
template<class Model > StencilT<Model>& mappel::estimator::IterativeMaximizer< Model >::MaximizerData::stencil () inline
Get the current stencil.
Definition at line 510 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::IterativeMaximizer< Model >::compute_estimate(), mappel::estimator::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::estimator::IterativeMaximizer< Model >::compute_profile_estimate(), mappel::estimator::IterativeMaximizer< Model >::local_maximize(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack().
template<class Model > const ParamT<Model>& mappel::estimator::IterativeMaximizer< Model >::MaximizerData::theta () const inline
Get the current stencil's theta.
Definition at line 525 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::IterativeMaximizer< Model >::compute_estimate(), mappel::estimator::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::estimator::IterativeMaximizer< Model >::local_maximize(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack().
Member Data Documentation
template<class Model > IdxVecT mappel::estimator::IterativeMaximizer< Model >::MaximizerData::backtrack_idxs protected
Definition at line 542 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::MaximizerData::expand_max_seq_len(), mappel::estimator::IterativeMaximizer< Model >::get_debug_stats(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::MaximizerData(), and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_backtrack().
template<class Model > bool mappel::estimator::IterativeMaximizer< Model >::MaximizerData::current_stencil protected
Definition at line 536 of file estimator.h.
template<class Model > const int mappel::estimator::IterativeMaximizer< Model >::MaximizerData::DefaultMaxSeqLength = 50 static protected
Default maximum length of sequence to perpare to save if debugging.
Definition at line 533 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::MaximizerData::MaximizerData().
template<class Model > IdxVecT mappel::estimator::IterativeMaximizer< Model >::MaximizerData::fixed_idxs
Definition at line 489 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::set_fixed_parameters().
template<class Model > IdxVecT mappel::estimator::IterativeMaximizer< Model >::MaximizerData::free_idxs
Definition at line 489 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::set_fixed_parameters().
template<class Model > ParamT<Model> mappel::estimator::IterativeMaximizer< Model >::MaximizerData::grad
Definition at line 482 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), and mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > const ModelDataT<Model>& mappel::estimator::IterativeMaximizer< Model >::MaximizerData::im
Definition at line 481 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack().
template<class Model > int mappel::estimator::IterativeMaximizer< Model >::MaximizerData::max_seq_len =0 protected
Definition at line 538 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::MaximizerData::expand_max_seq_len(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::MaximizerData(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_backtrack(), and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_iteration().
template<class Model > int mappel::estimator::IterativeMaximizer< Model >::MaximizerData::nBacktracks =0
Definition at line 486 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_backtrack(), and mappel::estimator::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::estimator::IterativeMaximizer< Model >::MaximizerData::nIterations =0
Definition at line 487 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_iteration(), and mappel::estimator::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > const IdxT mappel::estimator::IterativeMaximizer< Model >::MaximizerData::num_params protected
Definition at line 534 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::MaximizerData::set_fixed_parameters().
template<class Model > double mappel::estimator::IterativeMaximizer< Model >::MaximizerData::rllh
Definition at line 484 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::IterativeMaximizer< Model >::compute_estimate(), mappel::estimator::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::estimator::IterativeMaximizer< Model >::compute_profile_estimate(), mappel::estimator::IterativeMaximizer< Model >::local_maximize(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::MaximizerData(), mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack(), and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_iteration().
template<class Model > StencilT<Model> mappel::estimator::IterativeMaximizer< Model >::MaximizerData::s0 protected
Definition at line 535 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > StencilT<Model> mappel::estimator::IterativeMaximizer< Model >::MaximizerData::s1 protected
Definition at line 535 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
template<class Model > int mappel::estimator::IterativeMaximizer< Model >::MaximizerData::seq_len =0 protected
Definition at line 539 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_backtrack(), and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_iteration().
template<class Model > VecT mappel::estimator::IterativeMaximizer< Model >::MaximizerData::seq_rllh protected
Definition at line 541 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::MaximizerData::expand_max_seq_len(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::MaximizerData(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_backtrack(), and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_iteration().
template<class Model > ParamT<Model> mappel::estimator::IterativeMaximizer< Model >::MaximizerData::step
Definition at line 483 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::backtrack(), mappel::estimator::IterativeMaximizer< Model >::compute_profile_bound_debug(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::IterativeMaximizer< Model >::profile_bound_backtrack().
template<class Model > ParamVecT<Model> mappel::estimator::IterativeMaximizer< Model >::MaximizerData::theta_seq protected
Definition at line 540 of file estimator.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::MaximizerData::expand_max_seq_len(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::MaximizerData(), mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_backtrack(), and mappel::estimator::IterativeMaximizer< Model >::MaximizerData::record_iteration().
The documentation for this class was generated from the following files:
estimator.h
estimator_impl.h