Mappel: mappel::Gauss2DsModel::Stencil Class Reference
mappel::Gauss2DsModel::Stencil Class Reference
Stencil for 2D scalar-sigma models.
#include </home/travis/build/markjolah/Mappel/include/Mappel/Gauss2DsModel.h>
Public Types
typedef Gauss2DsModel::ParamT ParamT
Public Member Functions
Stencil ()
Stencil (const Gauss2DsModel &model, const ParamT &theta, bool _compute_derivatives=true)
void compute_derivatives ()
double x () const
double y () const
double I () const
double bg () const
double sigma_ratio () const
double sigmaX () const
double sigmaY () const
Public Attributes
bool derivatives_computed =false
Gauss2DsModel const * model
ParamT theta
VecT dx
VecT dy
VecT Gx
VecT Gy
VecT X
VecT Y
VecT DX
VecT DY
VecT DXS
VecT DYS
VecT DXS2
VecT DYS2
VecT DXSX
VecT DYSY
Friends
std::ostream & operator<< (std::ostream &out, const Gauss2DsModel::Stencil &s)
Detailed Description
Stencil for 2D scalar-sigma models.
Definition at line 29 of file Gauss2DsModel.h.
Member Typedef Documentation
typedef Gauss2DsModel::ParamT mappel::Gauss2DsModel::Stencil::ParamT
Definition at line 32 of file Gauss2DsModel.h.
Constructor & Destructor Documentation
mappel::Gauss2DsModel::Stencil::Stencil () inline
Definition at line 43 of file Gauss2DsModel.h.
References compute_derivatives().
Referenced by mappel::Gauss2DsModel::make_stencil().
mappel::Gauss2DsModel::Stencil::Stencil (const Gauss2DsModel & model, const ParamT & theta, bool _compute_derivatives = true)
Definition at line 286 of file Gauss2DsModel.cpp.
References compute_derivatives(), dx, dy, mappel::make_d_stencil(), mappel::make_X_stencil(), model, sigmaX(), sigmaY(), mappel::ImageFormat2DBase::size, X, x(), Y, and y().
Member Function Documentation
double mappel::Gauss2DsModel::Stencil::bg () const inline
Definition at line 49 of file Gauss2DsModel.h.
References theta.
Referenced by mappel::Gauss2DsModel::initial_theta_estimate(), and mappel::Gauss2DsModel::pixel_model_value().
void mappel::Gauss2DsModel::Stencil::compute_derivatives ()
Definition at line 300 of file Gauss2DsModel.cpp.
References derivatives_computed, dx, DX, DXS, DXS2, DXSX, dy, DY, DYS, DYS2, DYSY, Gx, Gy, mappel::make_DX_stencil(), mappel::make_DXS2_stencil(), mappel::make_DXS_stencil(), mappel::make_DXSX_stencil(), mappel::make_G_stencil(), model, sigmaX(), sigmaY(), and mappel::ImageFormat2DBase::size.
Referenced by Stencil().
double mappel::Gauss2DsModel::Stencil::I () const inline
Definition at line 48 of file Gauss2DsModel.h.
References theta.
Referenced by mappel::Gauss2DsModel::initial_theta_estimate(), mappel::Gauss2DsModel::pixel_grad(), mappel::Gauss2DsModel::pixel_grad2(), mappel::Gauss2DsModel::pixel_hess(), mappel::Gauss2DsModel::pixel_hess_update(), and mappel::Gauss2DsModel::pixel_model_value().
double mappel::Gauss2DsModel::Stencil::sigma_ratio () const inline
Definition at line 50 of file Gauss2DsModel.h.
References theta.
Referenced by mappel::Gauss2DsModel::initial_theta_estimate(), sigmaX(), and sigmaY().
double mappel::Gauss2DsModel::Stencil::sigmaX () const inline
Definition at line 51 of file Gauss2DsModel.h.
References mappel::Gauss2DsModel::min_sigma, and sigma_ratio().
Referenced by compute_derivatives(), mappel::Gauss2DsModel::pixel_grad2(), mappel::Gauss2DsModel::pixel_hess(), mappel::Gauss2DsModel::pixel_hess_update(), and Stencil().
double mappel::Gauss2DsModel::Stencil::sigmaY () const inline
Definition at line 52 of file Gauss2DsModel.h.
References mappel::Gauss2DsModel::min_sigma, operator<<, and sigma_ratio().
Referenced by compute_derivatives(), mappel::Gauss2DsModel::pixel_grad2(), mappel::Gauss2DsModel::pixel_hess(), mappel::Gauss2DsModel::pixel_hess_update(), and Stencil().
double mappel::Gauss2DsModel::Stencil::x () const inline
Definition at line 46 of file Gauss2DsModel.h.
References theta.
Referenced by Stencil().
double mappel::Gauss2DsModel::Stencil::y () const inline
Definition at line 47 of file Gauss2DsModel.h.
References theta.
Referenced by Stencil().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const Gauss2DsModel::Stencil & s) friend
Definition at line 318 of file Gauss2DsModel.cpp.
Referenced by sigmaY().
Member Data Documentation
bool mappel::Gauss2DsModel::Stencil::derivatives_computed =false
Definition at line 31 of file Gauss2DsModel.h.
Referenced by compute_derivatives(), and mappel::operator<<().
VecT mappel::Gauss2DsModel::Stencil::dx
Definition at line 36 of file Gauss2DsModel.h.
Referenced by compute_derivatives(), mappel::operator<<(), and Stencil().
VecT mappel::Gauss2DsModel::Stencil::DX
Definition at line 39 of file Gauss2DsModel.h.
Referenced by compute_derivatives(), mappel::operator<<(), mappel::Gauss2DsModel::pixel_grad(), mappel::Gauss2DsModel::pixel_hess(), and mappel::Gauss2DsModel::pixel_hess_update().
VecT mappel::Gauss2DsModel::Stencil::DXS
Definition at line 40 of file Gauss2DsModel.h.
Referenced by compute_derivatives(), mappel::operator<<(), mappel::Gauss2DsModel::pixel_grad(), mappel::Gauss2DsModel::pixel_grad2(), mappel::Gauss2DsModel::pixel_hess(), and mappel::Gauss2DsModel::pixel_hess_update().
VecT mappel::Gauss2DsModel::Stencil::DXS2
Definition at line 41 of file Gauss2DsModel.h.
Referenced by compute_derivatives(), mappel::operator<<(), mappel::Gauss2DsModel::pixel_grad2(), mappel::Gauss2DsModel::pixel_hess(), and mappel::Gauss2DsModel::pixel_hess_update().
VecT mappel::Gauss2DsModel::Stencil::DXSX
Definition at line 42 of file Gauss2DsModel.h.
Referenced by compute_derivatives(), mappel::operator<<(), mappel::Gauss2DsModel::pixel_hess(), and mappel::Gauss2DsModel::pixel_hess_update().
VecT mappel::Gauss2DsModel::Stencil::dy
Definition at line 36 of file Gauss2DsModel.h.
Referenced by compute_derivatives(), mappel::operator<<(), and Stencil().
VecT mappel::Gauss2DsModel::Stencil::DY
Definition at line 39 of file Gauss2DsModel.h.
Referenced by compute_derivatives(), mappel::operator<<(), mappel::Gauss2DsModel::pixel_grad(), mappel::Gauss2DsModel::pixel_hess(), and mappel::Gauss2DsModel::pixel_hess_update().
VecT mappel::Gauss2DsModel::Stencil::DYS
Definition at line 40 of file Gauss2DsModel.h.
Referenced by compute_derivatives(), mappel::operator<<(), mappel::Gauss2DsModel::pixel_grad(), mappel::Gauss2DsModel::pixel_grad2(), mappel::Gauss2DsModel::pixel_hess(), and mappel::Gauss2DsModel::pixel_hess_update().
VecT mappel::Gauss2DsModel::Stencil::DYS2
Definition at line 41 of file Gauss2DsModel.h.
Referenced by compute_derivatives(), mappel::operator<<(), mappel::Gauss2DsModel::pixel_grad2(), mappel::Gauss2DsModel::pixel_hess(), and mappel::Gauss2DsModel::pixel_hess_update().
VecT mappel::Gauss2DsModel::Stencil::DYSY
Definition at line 42 of file Gauss2DsModel.h.
Referenced by compute_derivatives(), mappel::operator<<(), mappel::Gauss2DsModel::pixel_hess(), and mappel::Gauss2DsModel::pixel_hess_update().
VecT mappel::Gauss2DsModel::Stencil::Gx
Definition at line 37 of file Gauss2DsModel.h.
Referenced by compute_derivatives(), and mappel::operator<<().
VecT mappel::Gauss2DsModel::Stencil::Gy
Definition at line 37 of file Gauss2DsModel.h.
Referenced by compute_derivatives(), and mappel::operator<<().
Gauss2DsModel const* mappel::Gauss2DsModel::Stencil::model
Definition at line 33 of file Gauss2DsModel.h.
Referenced by compute_derivatives(), and Stencil().
ParamT mappel::Gauss2DsModel::Stencil::theta
Definition at line 35 of file Gauss2DsModel.h.
Referenced by bg(), I(), mappel::operator<<(), sigma_ratio(), x(), and y().
VecT mappel::Gauss2DsModel::Stencil::X
Definition at line 38 of file Gauss2DsModel.h.
Referenced by mappel::operator<<(), mappel::Gauss2DsModel::pixel_grad(), mappel::Gauss2DsModel::pixel_grad2(), mappel::Gauss2DsModel::pixel_hess(), mappel::Gauss2DsModel::pixel_hess_update(), mappel::Gauss2DsModel::pixel_model_value(), and Stencil().
VecT mappel::Gauss2DsModel::Stencil::Y
Definition at line 38 of file Gauss2DsModel.h.
Referenced by mappel::operator<<(), mappel::Gauss2DsModel::pixel_grad(), mappel::Gauss2DsModel::pixel_grad2(), mappel::Gauss2DsModel::pixel_hess(), mappel::Gauss2DsModel::pixel_hess_update(), mappel::Gauss2DsModel::pixel_model_value(), and Stencil().
The documentation for this class was generated from the following files:
Gauss2DsModel.h
Gauss2DsModel.cpp