Mappel: omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy > Class Template Reference
omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy > Class Template Reference
#include </home/travis/build/markjolah/Mappel/include/Mappel/OMPExceptionCatcher/OMPExceptionCatcher.h>
Public Member Functions
OMPExceptionCatcher ()
OMPExceptionCatcher (Strategy strategy_)
void rethrow () const
template<class Function , class... Parameters>
void run (Function func, Parameters...params)
Static Public Member Functions
static void setGlobalDefaultStrategy (Strategy s)
Detailed Description
template<class _dummy = void>
class omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >
Implementation of OMPExceptionCatcher
Note: The template variable is a dummy. It exists solely to allow this class to be a template, which makes it header-only and allows static member initialization to be defined in the header file.
Definition at line 47 of file OMPExceptionCatcher.h.
Constructor & Destructor Documentation
template<class _dummy = void> omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::OMPExceptionCatcher () inline
Construct a new OMPExceptionCatcher using the GlobalDefaultStrategy
Definition at line 55 of file OMPExceptionCatcher.h.
template<class _dummy = void> omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::OMPExceptionCatcher (Strategy strategy_) inline
Construct a new OMPExceptionCatcher using the given strategy
Definition at line 59 of file OMPExceptionCatcher.h.
Member Function Documentation
template<class _dummy = void> void omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::rethrow () const inline
Rethrow any stored exceptions Should only be called from single-threaded blocks of code
Definition at line 64 of file OMPExceptionCatcher.h.
References omp_exception_catcher::RethrowFirst.
Referenced by mappel::methods::openmp::cr_lower_bound_stack(), mappel::methods::openmp::error_bounds_expected_stack(), mappel::methods::openmp::estimate_posterior_stack(), mappel::methods::openmp::expected_information_stack(), mappel::methods::objective::openmp::grad_stack(), mappel::methods::objective::openmp::hessian_stack(), mappel::methods::objective::openmp::llh_stack(), mappel::methods::openmp::model_image_stack(), mappel::methods::objective::openmp::negative_definite_hessian_stack(), mappel::methods::objective::openmp::rllh_stack(), mappel::methods::openmp::sample_prior_stack(), and mappel::methods::openmp::simulate_image_stack().
template<class _dummy = void> template<class Function , class... Parameters> void omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::run (Function func, Parameters... params) inline
Run a function in parallel code and prevent exceptions escaping.
Runs any function with any set of parameters and applies the chosen exception catching Strategy to prevent any exceptions escaping. This function is thread-safe designed to be called in parallel code blocks.
Parameters
[in] func function to call
[in] params... Possibly empty variadic set of parameters to call.
Definition at line 76 of file OMPExceptionCatcher.h.
References omp_exception_catcher::Abort, omp_exception_catcher::Continue, omp_exception_catcher::DoNotTry, and omp_exception_catcher::RethrowFirst.
Referenced by mappel::methods::openmp::cr_lower_bound_stack(), mappel::methods::openmp::error_bounds_expected_stack(), mappel::methods::openmp::error_bounds_observed_stack(), mappel::methods::openmp::estimate_posterior_stack(), mappel::methods::openmp::expected_information_stack(), mappel::methods::objective::openmp::grad_stack(), mappel::methods::objective::openmp::hessian_stack(), mappel::methods::objective::openmp::llh_stack(), mappel::methods::openmp::model_image_stack(), mappel::methods::objective::openmp::negative_definite_hessian_stack(), mappel::methods::objective::openmp::rllh_stack(), mappel::methods::openmp::sample_prior_stack(), and mappel::methods::openmp::simulate_image_stack().
template<class _dummy = void> static void omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::setGlobalDefaultStrategy (Strategy s) inline static
Definition at line 51 of file OMPExceptionCatcher.h.
The documentation for this class was generated from the following file:
OMPExceptionCatcher.h