Mappel: mappel::IterativeMaximizer< Model >::MaximizerData Class Reference
mappel::IterativeMaximizer< Model >::MaximizerData Class Reference
#include </home/travis/build/markjolah/Mappel/include/Mappel/estimator.h>
Public Member Functions
MaximizerData (const Model &model, const ModelDataT< Model > &im, const StencilT< Model > &s, bool save_seq=false, int max_seq_len=0)
void record_exit (ExitCode code)
void record_iteration ()
Record an iteration point (derivatives computed) Using the saved theta as the default.
void record_iteration (const ParamT< Model > &accepted_theta)
Record an iteration point (derivatives computed)
void record_backtrack (double rejected_rllh)
Record a backtracked point (no derivative computations performed) Using the saved theta as the default.
void record_backtrack (const ParamT< Model > &rejected_theta, double rejected_rllh)
Record a backtracked point (no derivative computations performed)
ParamVecT< Model > get_theta_sequence () const
Return the saved theta sequence.
IdxVecT get_backtrack_idxs () const
VecT get_theta_sequence_rllh () const
StencilT< Model > & stencil ()
Get the current stencil.
void set_stencil (const StencilT< Model > &s)
void save_stencil ()
Save the current stencil to the single reserve spot. Overwrites any previously saved stencil. This is used to save a stencil when backtracking.
void restore_stencil ()
Restore the single reserved stencil to the current stencil spot. Overwrites any previously saved stencil. This is used to restore a last good iterate (and associated stencil data) when backtracking.
StencilT< Model > & saved_stencil ()
Get the saved stencil.
ParamT< Model > & theta ()
Get the current stencil's theta.
ParamT< Model > & saved_theta ()
Get the saved stencil's theta.
int getIteration () const
void set_fixed_parameters (const IdxVecT &fixed_parameters)
Public Attributes
const ModelDataT< Model > & im
ParamT< Model > grad
ParamT< Model > step
VecT lbound
VecT ubound
double rllh
int nBacktracks =0
int nIterations =0
bool save_seq
ExitCode exit_code =ExitCode::Unassigned
VecT fixed_parameter_scalar
bool has_fixed_parameters =false
Protected Attributes
StencilT< Model > s0
StencilT< Model > s1
bool current_stencil
ParamVecT< Model > theta_seq
VecT seq_rllh
IdxVecT backtrack_idxs
int seq_len =0
const int max_seq_len
Detailed Description
template<class Model>
class mappel::IterativeMaximizer< Model >::MaximizerData
Definition at line 244 of file estimator.h.
Constructor & Destructor Documentation
template<class Model > mappel::IterativeMaximizer< Model >::MaximizerData::MaximizerData (const Model & model, const ModelDataT< Model > & im, const StencilT< Model > & s, bool save_seq = false, int max_seq_len = 0)
Definition at line 398 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::MaximizerData::backtrack_idxs, mappel::IterativeMaximizer< Model >::MaximizerData::record_iteration(), mappel::IterativeMaximizer< Model >::MaximizerData::seq_rllh, and mappel::IterativeMaximizer< Model >::MaximizerData::theta_seq.
Member Function Documentation
template<class Model > IdxVecT mappel::IterativeMaximizer< Model >::MaximizerData::get_backtrack_idxs () const inline
Definition at line 270 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > ParamVecT<Model> mappel::IterativeMaximizer< Model >::MaximizerData::get_theta_sequence () const inline
Return the saved theta sequence.
Definition at line 269 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::compute_estimate(), and mappel::IterativeMaximizer< Model >::compute_estimate_debug().
template<class Model > VecT mappel::IterativeMaximizer< Model >::MaximizerData::get_theta_sequence_rllh () const inline
Definition at line 271 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::compute_estimate_debug().
template<class Model > int mappel::IterativeMaximizer< Model >::MaximizerData::getIteration () const inline
Definition at line 291 of file estimator.h.
template<class Model > void mappel::IterativeMaximizer< Model >::MaximizerData::record_backtrack (double rejected_rllh) inline
Record a backtracked point (no derivative computations performed) Using the saved theta as the default.
Definition at line 264 of file estimator.h.
References mappel::IterativeMaximizer< Model >::MaximizerData::record_backtrack().
Referenced by mappel::IterativeMaximizer< Model >::backtrack(), and mappel::IterativeMaximizer< Model >::MaximizerData::record_backtrack().
template<class Model > void mappel::IterativeMaximizer< Model >::MaximizerData::record_backtrack (const ParamT< Model > & rejected_theta, double rejected_rllh)
Record a backtracked point (no derivative computations performed)
Definition at line 433 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::MaximizerData::backtrack_idxs, mappel::IterativeMaximizer< Model >::MaximizerData::max_seq_len, mappel::IterativeMaximizer< Model >::MaximizerData::nBacktracks, mappel::IterativeMaximizer< Model >::MaximizerData::save_seq, mappel::IterativeMaximizer< Model >::MaximizerData::seq_len, mappel::IterativeMaximizer< Model >::MaximizerData::seq_rllh, and mappel::IterativeMaximizer< Model >::MaximizerData::theta_seq.
template<class Model > void mappel::IterativeMaximizer< Model >::MaximizerData::record_exit (ExitCode code)
Definition at line 446 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::MaximizerData::exit_code.
Referenced by mappel::IterativeMaximizer< Model >::backtrack(), mappel::IterativeMaximizer< Model >::compute_estimate(), mappel::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::compute_profile_estimate(), and mappel::IterativeMaximizer< Model >::convergence_test().
template<class Model > void mappel::IterativeMaximizer< Model >::MaximizerData::record_iteration () inline
Record an iteration point (derivatives computed) Using the saved theta as the default.
Definition at line 260 of file estimator.h.
References mappel::IterativeMaximizer< Model >::MaximizerData::record_iteration().
Referenced by mappel::IterativeMaximizer< Model >::backtrack(), mappel::IterativeMaximizer< Model >::MaximizerData::MaximizerData(), and mappel::IterativeMaximizer< Model >::MaximizerData::record_iteration().
template<class Model > void mappel::IterativeMaximizer< Model >::MaximizerData::record_iteration (const ParamT< Model > & accepted_theta)
Record an iteration point (derivatives computed)
Definition at line 421 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::MaximizerData::max_seq_len, mappel::IterativeMaximizer< Model >::MaximizerData::nIterations, mappel::IterativeMaximizer< Model >::MaximizerData::rllh, mappel::IterativeMaximizer< Model >::MaximizerData::save_seq, mappel::IterativeMaximizer< Model >::MaximizerData::seq_len, mappel::IterativeMaximizer< Model >::MaximizerData::seq_rllh, and mappel::IterativeMaximizer< Model >::MaximizerData::theta_seq.
template<class Model > void mappel::IterativeMaximizer< Model >::MaximizerData::restore_stencil () inline
Restore the single reserved stencil to the current stencil spot. Overwrites any previously saved stencil. This is used to restore a last good iterate (and associated stencil data) when backtracking.
Definition at line 284 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::backtrack().
template<class Model > void mappel::IterativeMaximizer< Model >::MaximizerData::save_stencil () inline
Save the current stencil to the single reserve spot. Overwrites any previously saved stencil. This is used to save a stencil when backtracking.
Definition at line 279 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::backtrack().
template<class Model > StencilT<Model>& mappel::IterativeMaximizer< Model >::MaximizerData::saved_stencil () inline
Get the saved stencil.
Definition at line 286 of file estimator.h.
template<class Model > ParamT<Model>& mappel::IterativeMaximizer< Model >::MaximizerData::saved_theta () inline
Get the saved stencil's theta.
Definition at line 290 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::backtrack(), and mappel::IterativeMaximizer< Model >::convergence_test().
template<class Model > void mappel::IterativeMaximizer< Model >::MaximizerData::set_fixed_parameters (const IdxVecT & fixed_parameters)
Definition at line 452 of file estimator_impl.h.
References mappel::IterativeMaximizer< Model >::MaximizerData::fixed_parameter_scalar, and mappel::IterativeMaximizer< Model >::MaximizerData::has_fixed_parameters.
Referenced by mappel::IterativeMaximizer< Model >::compute_profile_estimate().
template<class Model > void mappel::IterativeMaximizer< Model >::MaximizerData::set_stencil (const StencilT< Model > & s) inline
Definition at line 274 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::backtrack().
template<class Model > StencilT<Model>& mappel::IterativeMaximizer< Model >::MaximizerData::stencil () inline
Get the current stencil.
Definition at line 273 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::backtrack(), mappel::IterativeMaximizer< Model >::compute_estimate(), mappel::IterativeMaximizer< Model >::compute_estimate_debug(), and mappel::IterativeMaximizer< Model >::local_maximize().
template<class Model > ParamT<Model>& mappel::IterativeMaximizer< Model >::MaximizerData::theta () inline
Get the current stencil's theta.
Definition at line 288 of file estimator.h.
Referenced by mappel::TrustRegionMaximizer< Model >::compute_bound_scaling_vec(), mappel::IterativeMaximizer< Model >::compute_estimate(), mappel::IterativeMaximizer< Model >::compute_profile_estimate(), and mappel::IterativeMaximizer< Model >::convergence_test().
Member Data Documentation
template<class Model > IdxVecT mappel::IterativeMaximizer< Model >::MaximizerData::backtrack_idxs protected
Definition at line 302 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::get_debug_stats(), mappel::IterativeMaximizer< Model >::MaximizerData::MaximizerData(), and mappel::IterativeMaximizer< Model >::MaximizerData::record_backtrack().
template<class Model > bool mappel::IterativeMaximizer< Model >::MaximizerData::current_stencil protected
Definition at line 298 of file estimator.h.
template<class Model > ExitCode mappel::IterativeMaximizer< Model >::MaximizerData::exit_code =ExitCode::Unassigned
Definition at line 254 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::MaximizerData::record_exit(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > VecT mappel::IterativeMaximizer< Model >::MaximizerData::fixed_parameter_scalar
Definition at line 293 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::backtrack(), mappel::IterativeMaximizer< Model >::convergence_test(), and mappel::IterativeMaximizer< Model >::MaximizerData::set_fixed_parameters().
template<class Model > ParamT<Model> mappel::IterativeMaximizer< Model >::MaximizerData::grad
Definition at line 247 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::backtrack(), and mappel::IterativeMaximizer< Model >::convergence_test().
template<class Model > bool mappel::IterativeMaximizer< Model >::MaximizerData::has_fixed_parameters =false
Definition at line 294 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::backtrack(), mappel::IterativeMaximizer< Model >::convergence_test(), and mappel::IterativeMaximizer< Model >::MaximizerData::set_fixed_parameters().
template<class Model > const ModelDataT<Model>& mappel::IterativeMaximizer< Model >::MaximizerData::im
Definition at line 246 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::backtrack().
template<class Model > VecT mappel::IterativeMaximizer< Model >::MaximizerData::lbound
Definition at line 249 of file estimator.h.
Referenced by mappel::TrustRegionMaximizer< Model >::compute_bound_scaling_vec().
template<class Model > const int mappel::IterativeMaximizer< Model >::MaximizerData::max_seq_len protected
Definition at line 304 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::MaximizerData::record_backtrack(), and mappel::IterativeMaximizer< Model >::MaximizerData::record_iteration().
template<class Model > int mappel::IterativeMaximizer< Model >::MaximizerData::nBacktracks =0
Definition at line 251 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::MaximizerData::record_backtrack(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::IterativeMaximizer< Model >::MaximizerData::nIterations =0
Definition at line 252 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::MaximizerData::record_iteration(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > double mappel::IterativeMaximizer< Model >::MaximizerData::rllh
Definition at line 250 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::backtrack(), mappel::SimulatedAnnealingMaximizer< Model >::compute_estimate(), mappel::IterativeMaximizer< Model >::compute_estimate(), mappel::SimulatedAnnealingMaximizer< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::compute_profile_estimate(), mappel::IterativeMaximizer< Model >::convergence_test(), mappel::IterativeMaximizer< Model >::local_maximize(), and mappel::IterativeMaximizer< Model >::MaximizerData::record_iteration().
template<class Model > StencilT<Model> mappel::IterativeMaximizer< Model >::MaximizerData::s0 protected
Definition at line 297 of file estimator.h.
template<class Model > StencilT<Model> mappel::IterativeMaximizer< Model >::MaximizerData::s1 protected
Definition at line 297 of file estimator.h.
template<class Model > bool mappel::IterativeMaximizer< Model >::MaximizerData::save_seq
Definition at line 253 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::MaximizerData::record_backtrack(), mappel::IterativeMaximizer< Model >::MaximizerData::record_iteration(), and mappel::IterativeMaximizer< Model >::record_run_statistics().
template<class Model > int mappel::IterativeMaximizer< Model >::MaximizerData::seq_len =0 protected
Definition at line 303 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::MaximizerData::record_backtrack(), and mappel::IterativeMaximizer< Model >::MaximizerData::record_iteration().
template<class Model > VecT mappel::IterativeMaximizer< Model >::MaximizerData::seq_rllh protected
Definition at line 301 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::MaximizerData::MaximizerData(), mappel::IterativeMaximizer< Model >::MaximizerData::record_backtrack(), and mappel::IterativeMaximizer< Model >::MaximizerData::record_iteration().
template<class Model > ParamT<Model> mappel::IterativeMaximizer< Model >::MaximizerData::step
Definition at line 248 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::backtrack(), and mappel::TrustRegionMaximizer< Model >::bound_step().
template<class Model > ParamVecT<Model> mappel::IterativeMaximizer< Model >::MaximizerData::theta_seq protected
Definition at line 300 of file estimator.h.
Referenced by mappel::IterativeMaximizer< Model >::MaximizerData::MaximizerData(), mappel::IterativeMaximizer< Model >::MaximizerData::record_backtrack(), and mappel::IterativeMaximizer< Model >::MaximizerData::record_iteration().
template<class Model > VecT mappel::IterativeMaximizer< Model >::MaximizerData::ubound
Definition at line 249 of file estimator.h.
Referenced by mappel::TrustRegionMaximizer< Model >::compute_bound_scaling_vec().
The documentation for this class was generated from the following files:
estimator.h
estimator_impl.h