Mappel: mappel::methods::likelihood::debug Namespace Reference
mappel::methods::likelihood::debug Namespace Reference
Functions
template<class Model >
ReturnIfSubclassT< VecT, Model, PoissonNoise1DObjective > llh_components (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< VecT, Model, PoissonNoise1DObjective > rllh_components (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< MatT, Model, PoissonNoise1DObjective > grad_components (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< CubeT, Model, PoissonNoise1DObjective > hessian_components (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< VecT, Model, PoissonNoise2DObjective > llh_components (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< VecT, Model, PoissonNoise2DObjective > rllh_components (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< MatT, Model, PoissonNoise2DObjective > grad_components (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< CubeT, Model, PoissonNoise2DObjective > hessian_components (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
Function Documentation
template<class Model > ReturnIfSubclassT<MatT,Model,PoissonNoise1DObjective> mappel::methods::likelihood::debug::grad_components (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 230 of file PoissonNoise1DObjective.h.
template<class Model > ReturnIfSubclassT<MatT,Model,PoissonNoise2DObjective> mappel::methods::likelihood::debug::grad_components (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 255 of file PoissonNoise2DObjective.h.
References mappel::ImageFormat2DBase::size.
template<class Model > ReturnIfSubclassT<CubeT,Model,PoissonNoise1DObjective> mappel::methods::likelihood::debug::hessian_components (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 246 of file PoissonNoise1DObjective.h.
template<class Model > ReturnIfSubclassT<CubeT,Model,PoissonNoise2DObjective> mappel::methods::likelihood::debug::hessian_components (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 274 of file PoissonNoise2DObjective.h.
References mappel::ImageFormat2DBase::size.
template<class Model > ReturnIfSubclassT<VecT,Model,PoissonNoise1DObjective> mappel::methods::likelihood::debug::llh_components (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 206 of file PoissonNoise1DObjective.h.
References mappel::poisson_log_likelihood().
template<class Model > ReturnIfSubclassT<VecT,Model,PoissonNoise2DObjective> mappel::methods::likelihood::debug::llh_components (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 225 of file PoissonNoise2DObjective.h.
References mappel::poisson_log_likelihood(), and mappel::ImageFormat2DBase::size.
template<class Model > ReturnIfSubclassT<VecT,Model,PoissonNoise1DObjective> mappel::methods::likelihood::debug::rllh_components (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 218 of file PoissonNoise1DObjective.h.
References mappel::relative_poisson_log_likelihood().
template<class Model > ReturnIfSubclassT<VecT,Model,PoissonNoise2DObjective> mappel::methods::likelihood::debug::rllh_components (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 240 of file PoissonNoise2DObjective.h.
References mappel::relative_poisson_log_likelihood(), and mappel::ImageFormat2DBase::size.