Mappel: mappel::methods::objective::openmp Namespace Reference
mappel::methods::objective::openmp Namespace Reference
Functions
template<class Model >
void llh_stack (const Model &model, const ImageT< Model > &image, const ParamVecT< Model > &theta_stack, VecT &llh_stack)
Parallel log_likelihood calculations for a single image.
template<class Model >
void llh_stack (const Model &model, const ImageStackT< Model > &image_stack, const ParamVecT< Model > &theta_stack, VecT &llh_stack)
Parallel log_likelihood calculations for a stack of images.
template<class Model >
void rllh_stack (const Model &model, const ImageStackT< Model > &image_stack, const ParamVecT< Model > &theta_stack, VecT &rllh_stack)
Parallel relative log_likelihood calculations for a stack of images.
template<class Model >
void rllh_stack (const Model &model, const ImageT< Model > &image, const ParamVecT< Model > &theta_stack, VecT &rllh_stack)
template<class Model >
void grad_stack (const Model &model, const ImageStackT< Model > &image_stack, const ParamVecT< Model > &theta_stack, ParamVecT< Model > &grad_stack)
Parallel model gradient calculations for a stack of images.
template<class Model >
void hessian_stack (const Model &model, const ImageStackT< Model > &image_stack, const ParamVecT< Model > &theta_stack, CubeT &hessian_stack)
Parallel model Hessian calculations for a stack of images.
template<class Model >
void negative_definite_hessian_stack (const Model &model, const ImageStackT< Model > &image_stack, const ParamVecT< Model > &theta_stack, CubeT &hessian_stack)
Parallel model negative_definite Hessian approximation calculations for a stack of images.
Function Documentation
template<class Model > void mappel::methods::objective::openmp::grad_stack (const Model & model, const ImageStackT< Model > & image_stack, const ParamVecT< Model > & theta_stack, ParamVecT< Model > & grad_stack)
Parallel model gradient calculations for a stack of images.
Compute gradient of log-likelihood for multiple image, theta pairs.
Use: model.make_param_stack() to make a parameter stack of appropriate dimensions for the model gradients.
Template Parameters
Model A concrete subclass of PointEmitterModel
Parameters
[in] model A PointEmitterModel object.
[in] image_stack Sequence of images.
[in] theta_stack Sequence of thetas.
[out] grad_stack Sequence of grad vectors values computed. Size: [model.num_params, n]
Definition at line 542 of file openmp_methods.h.
References mappel::methods::objective::grad().
template<class Model > void mappel::methods::objective::openmp::hessian_stack (const Model & model, const ImageStackT< Model > & image_stack, const ParamVecT< Model > & theta_stack, CubeT & hessian_stack)
Parallel model Hessian calculations for a stack of images.
Compute Hessian of log-likelihood for multiple image, theta pairs.
Use: model.make_param_mat_stack() to make a parameter matrix stack of appropriate dimensions for the model Hessian.
Template Parameters
Model A concrete subclass of PointEmitterModel
Parameters
[in] model A PointEmitterModel object.
[in] image_stack Sequence of images.
[in] theta_stack Sequence of thetas. Size: [model.num_params, nThetas]
[out] hess_stack Sequence of Hessian matrices computed. Size: [model.num_params, model.num_params, n]
Definition at line 590 of file openmp_methods.h.
References mappel::methods::objective::hessian().
template<class Model > void mappel::methods::objective::openmp::llh_stack (const Model & model, const ImageT< Model > & image, const ParamVecT< Model > & theta_stack, VecT & llh_stack)
Parallel log_likelihood calculations for a single image.
Compute log-likelihood for multiple thetas using the same image
Use: model.make_param_stack() to make a parameter stack of appropriate dimensions for the model
Template Parameters
Model A concrete subclass of PointEmitterModel
Parameters
[in] model A PointEmitterModel object.
[in] image An image.
[in] theta_stack Sequence of thetas. Size: [model.num_params, nThetas]
[out] llh_stack Sequence of llh values computed.
Definition at line 406 of file openmp_methods.h.
Referenced by mappel::log_likelihood_stack().
template<class Model > void mappel::methods::objective::openmp::llh_stack (const Model & model, const ImageStackT< Model > & image_stack, const ParamVecT< Model > & theta_stack, VecT & llh_stack)
Parallel log_likelihood calculations for a stack of images.
Compute log-likelihood for multiple image, theta pairs.
Use: model.make_param_stack() to make a parameter stack of appropriate dimensions for the model
Template Parameters
Model A concrete subclass of PointEmitterModel
Parameters
[in] model A PointEmitterModel object.
[in] image_stack Sequence of images.
[in] theta_stack Sequence of thetas. Size: [model.num_params, nThetas]
[out] llh_stack Sequence of llh values computed. Size: [n]
Definition at line 431 of file openmp_methods.h.
References mappel::methods::objective::llh().
template<class Model > void mappel::methods::objective::openmp::negative_definite_hessian_stack (const Model & model, const ImageStackT< Model > & image_stack, const ParamVecT< Model > & theta_stack, CubeT & hessian_stack)
Parallel model negative_definite Hessian approximation calculations for a stack of images.
Compute Hessian a negative_definite Hessian using a modified cholesky decompositions. Computes for multiple image, theta pairs.
Use: model.make_param_mat_stack() to make a parameter matrix stack of appropriate dimensions for the model Hessian.
Template Parameters
Model A concrete subclass of PointEmitterModel
Parameters
[in] model A PointEmitterModel object.
[in] image_stack Sequence of images.
[in] theta_stack Sequence of thetas. Size: [model.num_params, nThetas]
[out] hess_stack Sequence of approximate Hessian negative definite matrices computed. Size: [model.num_params, model.num_params, n]
Definition at line 639 of file openmp_methods.h.
References mappel::methods::objective::negative_definite_hessian().
template<class Model > void mappel::methods::objective::openmp::rllh_stack (const Model & model, const ImageStackT< Model > & image_stack, const ParamVecT< Model > & theta_stack, VecT & rllh_stack)
Parallel relative log_likelihood calculations for a stack of images.
Compute relative log-likelihood for multiple image, theta pairs.
Use: model.make_param_stack() to make a parameter stack of appropriate dimensions for the model
Template Parameters
Model A concrete subclass of PointEmitterModel
Parameters
[in] model A PointEmitterModel object.
[in] image_stack Sequence of images.
[in] theta_stack Sequence of thetas. Size: [model.num_params, nThetas]
[out] rllh_stack Sequence of rllh values computed. Size: [n]
Definition at line 478 of file openmp_methods.h.
References mappel::methods::objective::rllh(), and rllh_stack().
Referenced by mappel::CGaussMLE< Model >::compute_estimate_debug(), and mappel::Estimator< Model >::~Estimator().
template<class Model > void mappel::methods::objective::openmp::rllh_stack (const Model & model, const ImageT< Model > & image, const ParamVecT< Model > & theta_stack, VecT & rllh_stack)
Definition at line 514 of file openmp_methods.h.
Referenced by rllh_stack().