Mappel: mappel::methods Namespace Reference
mappel::methods Namespace Reference
Templated functions for operating on a PointEmitterModel.
Namespaces
debug
likelihood
objective
openmp
Functions
template<class Model >
ReturnIfSubclassT< ImageT< Model >, Model, ImageFormat1DBase > model_image (const Model &model, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< ImageT< Model >, Model, ImageFormat2DBase > model_image (const Model &model, const typename Model::Stencil &s)
template<class Model >
ImageT< Model > model_image (const Model &model, const ParamT< Model > &theta)
template<class Model , class rng_t >
ModelDataT< Model > simulate_image (const Model &model, const ParamT< Model > &theta)
template<class Model , class rng_t >
ModelDataT< Model > simulate_image (const Model &model, const ParamT< Model > &theta, rng_t &rng)
template<class Model >
ModelDataT< Model > simulate_image (const Model &model, const StencilT< Model > &s)
template<class Model >
ModelDataT< Model > simulate_image_from_model (const Model &model, const ImageT< Model > &model_im)
template<class Model >
void aposteriori_objective (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s, double &rllh, ParamT< Model > &grad, MatT &hess)
template<class Model >
void aposteriori_objective (const Model &model, const ModelDataT< Model > &data_im, const ParamT< Model > &theta, double &rllh, ParamT< Model > &grad, MatT &hess)
template<class Model >
void prior_objective (const Model &model, const ParamT< Model > &theta, double &rllh, ParamT< Model > &grad, MatT &hess)
template<class Model >
void likelihood_objective (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s, double &rllh, ParamT< Model > &grad, MatT &hess)
template<class Model >
void likelihood_objective (const Model &model, const ModelDataT< Model > &data_im, const ParamT< Model > &theta, double &rllh, ParamT< Model > &grad, MatT &hess)
template<class Model >
ParamT< Model > cr_lower_bound (const Model &model, const typename Model::Stencil &s)
Calculate the Cramer-Rao lower bound at the given parameters.
template<class Model >
ParamT< Model > cr_lower_bound (const Model &model, const ParamT< Model > &theta)
template<class Model >
MatT expected_information (const Model &model, const ParamT< Model > &theta)
template<class Model >
MatT observed_information (const Model &model, const ModelDataT< Model > &data, const ParamT< Model > &theta_mle)
template<class Model >
MatT observed_information (const Model &model, const ModelDataT< Model > &data, const StencilT< Model > &theta_mle)
template<class Model >
void estimate_max (const Model &model, const ModelDataT< Model > &data, const std::string &method, estimator::MLEData &mle)
template<class Model >
void estimate_max (const Model &model, const ModelDataT< Model > &data, const std::string &method, const ParamT< Model > &theta_init, estimator::MLEData &mle)
template<class Model >
void estimate_max (const Model &model, const ModelDataT< Model > &data, const std::string &method, estimator::MLEData &mle, StatsT &stats)
template<class Model >
void estimate_max (const Model &model, const ModelDataT< Model > &data, const std::string &method, const ParamT< Model > &theta_init, estimator::MLEData &mle, StatsT &stats)
template<class Model >
double estimate_profile_likelihood (const Model &model, const ModelDataT< Model > &data, const std::string &method, const IdxVecT &fixed_idxs, const ParamT< Model > &fixed_theta_init)
template<class Model >
double estimate_profile_likelihood (const Model &model, const ModelDataT< Model > &data, const std::string &method, const IdxVecT &fixed_idxs, const ParamT< Model > &fixed_theta_init, StencilT< Model > &profile_max)
template<class Model >
double estimate_profile_likelihood (const Model &model, const ModelDataT< Model > &data, const std::string &method, const IdxVecT &fixed_idxs, const ParamT< Model > &fixed_theta_init, StencilT< Model > &profile_max, StatsT &stats)
template<class Model >
void estimate_profile_likelihood (const Model &model, const ModelDataT< Model > &data, const std::string &method, const ParamT< Model > &theta_init, estimator::ProfileLikelihoodData &profile_data)
template<class Model >
void estimate_posterior (const Model &model, const ModelDataT< Model > &data, mcmc::MCMCData &mcmc_est)
template<class Model >
void estimate_posterior (const Model &model, const ModelDataT< Model > &data, const ParamT< Model > &theta_init, mcmc::MCMCData &mcmc_est)
template<class Model >
void error_bounds_expected (const Model &model, const ParamT< Model > &theta_est, double confidence, ParamT< Model > &theta_lb, ParamT< Model > &theta_ub)
template<class Model >
void error_bounds_observed (const Model &model, const estimator::MLEData &mle, double confidence, ParamT< Model > &theta_lb, ParamT< Model > &theta_ub)
template<class Model >
void error_bounds_profile_likelihood (const Model &model, const ModelDataT< Model > &data, estimator::ProfileBoundsData &bounds)
template<class Model >
void error_bounds_profile_likelihood (const Model &model, const ModelDataT< Model > &data, estimator::ProfileBoundsData &bounds, StatsT &stats)
template<class Model >
void error_bounds_posterior_credible (const Model &model, const MatT &sample, double confidence, ParamT< Model > &theta_lb, ParamT< Model > &theta_ub)
template<class Model >
Model::ImageT model_image (const Model &model, const ParamT< Model > &theta)
template<class Model >
ModelDataT< Model > simulate_image (const Model &model, const ParamT< Model > &theta)
template<class Model , class RngT >
ModelDataT< Model > simulate_image (const Model &model, const ParamT< Model > &theta, RngT &rng)
template<class Model , class rng_t >
ReturnIfSubclassT< ModelDataT< Model >, Model, PoissonNoise1DObjective > simulate_image (const Model &model, const StencilT< Model > &s, rng_t &rng)
Simulate an image at a given theta stencil, by generating Poisson noise Enabled for PoissonNoise1DObjective.
template<class Model , class rng_t >
ReturnIfSubclassT< ModelDataT< Model >, Model, PoissonNoise1DObjective > simulate_image_from_model (const Model &model, const ImageT< Model > &model_im, rng_t &rng)
Simulate an image at a given theta stencil, by generating Poisson noise Enabled for PoissonNoise1DObjective.
template<class Model >
ReturnIfSubclassT< MatT, Model, PoissonNoise1DObjective > expected_information (const Model &model, const StencilT< Model > &s)
Compute the expected information (Fisher information at theta). Note: Expected information is an average quantity and is independent of the data. Enabled for PoissonNoise1DObjective.
template<class Model >
ReturnIfSubclassT< std::unique_ptr< estimator::Estimator< Model > >, Model, PoissonNoise1DObjective > make_estimator (Model &model, std::string ename)
template<class Model , class rng_t >
ReturnIfSubclassT< ImageT< Model >, Model, PoissonNoise2DObjective > simulate_image (const Model &model, const StencilT< Model > &s, rng_t &rng)
Simulate an image at a given theta stencil, by generating Poisson noise Enabled for PoissonNoise2DObjective.
template<class Model , class rng_t >
ReturnIfSubclassT< ImageT< Model >, Model, PoissonNoise2DObjective > simulate_image_from_model (const Model &model, const ImageT< Model > &model_im, rng_t &rng)
Simulate an image at a given theta stencil, by generating Poisson noise Enabled for PoissonNoise2DObjective.
template<class Model >
ReturnIfSubclassT< MatT, Model, PoissonNoise2DObjective > expected_information (const Model &model, const StencilT< Model > &s)
Compute the expected information (Fisher information at theta). Note: Expected information is an average quantity and is independent of the data. Enabled for PoissonNoise2DObjective.
template<class Model >
ReturnIfSubclassT< std::unique_ptr< estimator::Estimator< Model > >, Model, PoissonNoise2DObjective > make_estimator (Model &model, std::string ename)
Detailed Description
Templated functions for operating on a PointEmitterModel.
Most methods are overloaded to take a ParamT or a StencilT. The precomputed stencil for a theta value contains the common computational values needed by all methods that compute the likelihood function or its derivatives. Note that methods in model::prior:: namespace do not take a stencil (or data) a they are independent of the data and the likelihood function.
Methods with xxx_comonents return a sequence of values representing the results from each pixel in turn. The sum of these components is the overall model value. (e.g. sum(llh_components(...))==llh(...)). These methods are usefully for detailed inspection of the contributions of each pixel or prior component to the overall result.External template based methods for PointEmitterModel's. These are general or convenience functions that are included in this file. Those methods specific to other sub-types of Models should be included within that sub-type's .h file, using the enable_if mechanism to restrict their instantiation to the correct sub-types.
Function Documentation
template<class Model > void mappel::methods::aposteriori_objective (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s, double & rllh, ParamT< Model > & grad, MatT & hess)
Definition at line 218 of file model_methods_impl.h.
References mappel::methods::likelihood::hessian(), and mappel::methods::likelihood::rllh().
Referenced by aposteriori_objective().
template<class Model > void mappel::methods::aposteriori_objective (const Model & model, const ModelDataT< Model > & data_im, const ParamT< Model > & theta, double & rllh, ParamT< Model > & grad, MatT & hess)
Definition at line 256 of file model_methods_impl.h.
References aposteriori_objective(), mappel::methods::objective::grad(), and mappel::methods::objective::rllh().
template<class Model > ParamT< Model > mappel::methods::cr_lower_bound (const Model & model, const typename Model::Stencil & s)
Calculate the Cramer-Rao lower bound at the given parameters.
Parameters
[in] theta The parameters to evaluate the CRLB at
[out] crlb The calculated parameters
Definition at line 283 of file model_methods_impl.h.
References expected_information().
Referenced by cr_lower_bound(), and error_bounds_expected().
template<class Model > ParamT< Model > mappel::methods::cr_lower_bound (const Model & model, const ParamT< Model > & theta)
Definition at line 295 of file model_methods_impl.h.
References cr_lower_bound().
template<class Model > void mappel::methods::error_bounds_expected (const Model & model, const ParamT< Model > & theta_est, double confidence, ParamT< Model > & theta_lb, ParamT< Model > & theta_ub)
Definition at line 405 of file model_methods_impl.h.
References cr_lower_bound(), and mappel::normal_quantile_twosided().
template<class Model > void mappel::methods::error_bounds_observed (const Model & model, const estimator::MLEData & mle, double confidence, ParamT< Model > & theta_lb, ParamT< Model > & theta_ub)
Definition at line 416 of file model_methods_impl.h.
References mappel::normal_quantile_twosided(), mappel::estimator::MLEData::obsI, and mappel::estimator::MLEData::theta.
template<class Model > void mappel::methods::error_bounds_posterior_credible (const Model & model, const MatT & sample, double confidence, ParamT< Model > & theta_lb, ParamT< Model > & theta_ub)
Definition at line 444 of file model_methods_impl.h.
References mappel::mcmc::compute_posterior_credible().
template<class Model > void mappel::methods::error_bounds_profile_likelihood (const Model & model, const ModelDataT< Model > & data, estimator::ProfileBoundsData & bounds)
Definition at line 426 of file model_methods_impl.h.
References mappel::chisq_quantile(), mappel::estimator::ProfileBoundsData::confidence, mappel::estimator::Estimator< Model >::estimate_profile_bounds(), mappel::estimator::ProfileBoundsData::estimated_idxs, and mappel::estimator::ProfileBoundsData::target_rllh_delta.
template<class Model > void mappel::methods::error_bounds_profile_likelihood (const Model & model, const ModelDataT< Model > & data, estimator::ProfileBoundsData & bounds, StatsT & stats)
Definition at line 435 of file model_methods_impl.h.
References mappel::chisq_quantile(), mappel::estimator::ProfileBoundsData::confidence, mappel::estimator::ProfileBoundsData::estimated_idxs, mappel::estimator::IterativeMaximizer< Model >::get_stats(), and mappel::estimator::ProfileBoundsData::target_rllh_delta.
template<class Model > void mappel::methods::estimate_max (const Model & model, const ModelDataT< Model > & data, const std::string & method, estimator::MLEData & mle)
Definition at line 322 of file model_methods_impl.h.
References make_estimator().
Referenced by mappel::Gauss2DModel::initial_theta_estimate(), mappel::Gauss2DsModel::initial_theta_estimate(), and mappel::estimator::Estimator< Model >::~Estimator().
template<class Model > void mappel::methods::estimate_max (const Model & model, const ModelDataT< Model > & data, const std::string & method, const ParamT< Model > & theta_init, estimator::MLEData & mle)
Definition at line 331 of file model_methods_impl.h.
References make_estimator().
template<class Model > void mappel::methods::estimate_max (const Model & model, const ModelDataT< Model > & data, const std::string & method, estimator::MLEData & mle, StatsT & stats)
Definition at line 338 of file model_methods_impl.h.
References make_estimator().
template<class Model > void mappel::methods::estimate_max (const Model & model, const ModelDataT< Model > & data, const std::string & method, const ParamT< Model > & theta_init, estimator::MLEData & mle, StatsT & stats)
Definition at line 348 of file model_methods_impl.h.
References make_estimator().
template<class Model > void mappel::methods::estimate_posterior (const Model & model, const ModelDataT< Model > & data, mcmc::MCMCData & mcmc_est)
Definition at line 383 of file model_methods_impl.h.
template<class Model > void mappel::methods::estimate_posterior (const Model & model, const ModelDataT< Model > & data, const ParamT< Model > & theta_init, mcmc::MCMCData & mcmc_est)
Definition at line 391 of file model_methods_impl.h.
References mappel::mcmc::compute_posterior_credible(), mappel::mcmc::MCMCData::confidence, mappel::mcmc::MCMCData::credible_lb, mappel::mcmc::MCMCData::credible_ub, mappel::mcmc::estimate_sample_posterior(), mappel::mcmc::MCMCData::Nburnin, mappel::mcmc::MCMCData::Nsample, mappel::mcmc::num_oversample(), mappel::mcmc::MCMCData::sample, mappel::mcmc::MCMCData::sample_cov, mappel::mcmc::MCMCData::sample_mean, mappel::mcmc::sample_posterior(), mappel::mcmc::MCMCData::sample_rllh, mappel::mcmc::MCMCData::thin, and mappel::mcmc::thin_sample().
template<class Model > double mappel::methods::estimate_profile_likelihood (const Model & model, const ModelDataT< Model > & data, const std::string & method, const IdxVecT & fixed_idxs, const ParamT< Model > & fixed_theta_init)
Definition at line 357 of file model_methods_impl.h.
References make_estimator().
template<class Model > double mappel::methods::estimate_profile_likelihood (const Model & model, const ModelDataT< Model > & data, const std::string & method, const IdxVecT & fixed_idxs, const ParamT< Model > & fixed_theta_init, StencilT< Model > & profile_max)
Definition at line 365 of file model_methods_impl.h.
References make_estimator().
template<class Model > double mappel::methods::estimate_profile_likelihood (const Model & model, const ModelDataT< Model > & data, const std::string & method, const IdxVecT & fixed_idxs, const ParamT< Model > & fixed_theta_init, StencilT< Model > & profile_max, StatsT & stats)
Definition at line 373 of file model_methods_impl.h.
References make_estimator().
template<class Model > void mappel::methods::estimate_profile_likelihood (const Model & model, const ModelDataT< Model > & data, const std::string & method, const ParamT< Model > & theta_init, estimator::ProfileLikelihoodData & profile_data)
template<class Model > ReturnIfSubclassT<MatT, Model, PoissonNoise1DObjective> mappel::methods::expected_information (const Model & model, const StencilT< Model > & s)
Compute the expected information (Fisher information at theta). Note: Expected information is an average quantity and is independent of the data. Enabled for PoissonNoise1DObjective.
Parameters
model PointEmitterModel
s Stencil at desired theta
Returns
The fisher information matrix as an symmetric matrix in upper-triangular format
Definition at line 77 of file PoissonNoise1DObjective.h.
template<class Model > ReturnIfSubclassT<MatT, Model, PoissonNoise2DObjective> mappel::methods::expected_information (const Model & model, const StencilT< Model > & s)
Compute the expected information (Fisher information at theta). Note: Expected information is an average quantity and is independent of the data. Enabled for PoissonNoise2DObjective.
Parameters
model PoImageCoordTEmitterModel
s Stencil at desired theta
Returns
The fisher information matrix as an symmetric matrix in upper-triangular format
Definition at line 83 of file PoissonNoise2DObjective.h.
References mappel::ImageFormat2DBase::size.
template<class Model > MatT mappel::methods::expected_information (const Model & model, const ParamT< Model > & theta)
Definition at line 301 of file model_methods_impl.h.
Referenced by cr_lower_bound().
template<class Model > void mappel::methods::likelihood_objective (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s, double & rllh, ParamT< Model > & grad, MatT & hess)
Definition at line 247 of file model_methods_impl.h.
References mappel::methods::likelihood::hessian(), and mappel::methods::likelihood::rllh().
Referenced by likelihood_objective().
template<class Model > void mappel::methods::likelihood_objective (const Model & model, const ModelDataT< Model > & data_im, const ParamT< Model > & theta, double & rllh, ParamT< Model > & grad, MatT & hess)
Definition at line 270 of file model_methods_impl.h.
References mappel::methods::objective::grad(), likelihood_objective(), and mappel::methods::objective::rllh().
template<class Model > ReturnIfSubclassT<std::unique_ptr<estimator::Estimator<Model> >, Model, PoissonNoise1DObjective> mappel::methods::make_estimator (Model & model, std::string ename)
Definition at line 95 of file PoissonNoise1DObjective.h.
References mappel::istarts_with().
Referenced by estimate_max(), mappel::methods::debug::estimate_max_debug(), mappel::methods::openmp::estimate_max_stack(), estimate_profile_likelihood(), and mappel::methods::openmp::estimate_profile_likelihood_stack().
template<class Model > ReturnIfSubclassT<std::unique_ptr<estimator::Estimator<Model> >, Model, PoissonNoise2DObjective> mappel::methods::make_estimator (Model & model, std::string ename)
Definition at line 100 of file PoissonNoise2DObjective.h.
References mappel::istarts_with().
template<class Model > Model::ImageT mappel::methods::model_image (const Model & model, const ParamT< Model > & theta)
Expected number of photons at each pixel in image given the emitter model
Definition at line 16 of file model_methods_impl.h.
References model_image().
template<class Model > ImageT<Model> mappel::methods::model_image (const Model & model, const ParamT< Model > & theta)
Expected number of photons at each pixel in image given the emitter model
Definition at line 16 of file model_methods_impl.h.
References model_image().
template<class Model > ReturnIfSubclassT<ImageT<Model>, Model, ImageFormat2DBase> mappel::methods::model_image (const Model & model, const typename Model::Stencil & s)
Definition at line 122 of file ImageFormat2DBase.h.
References mappel::ImageFormat2DBase::size.
template<class Model > ReturnIfSubclassT<ImageT<Model>, Model, ImageFormat1DBase> mappel::methods::model_image (const Model & model, const StencilT< Model > & s)
Definition at line 125 of file ImageFormat1DBase.h.
Referenced by model_image(), and mappel::methods::openmp::simulate_image_stack().
template<class Model > MatT mappel::methods::observed_information (const Model & model, const ModelDataT< Model > & data, const ParamT< Model > & theta_mle)
Definition at line 315 of file model_methods_impl.h.
Referenced by mappel::estimator::IterativeMaximizer< Model >::compute_estimate(), mappel::estimator::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::estimator::HeuristicEstimator< Model >::get_debug_stats(), mappel::estimator::CGaussMLE< Model >::get_debug_stats(), mappel::estimator::IterativeMaximizer< Model >::local_maximize(), mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize(), and mappel::estimator::ThreadedEstimator< Model >::record_exit_code().
template<class Model > MatT mappel::methods::observed_information (const Model & model, const ModelDataT< Model > & data, const StencilT< Model > & theta_mle)
Definition at line 307 of file model_methods_impl.h.
References mappel::methods::objective::hessian().
template<class Model > void mappel::methods::prior_objective (const Model & model, const ParamT< Model > & theta, double & rllh, ParamT< Model > & grad, MatT & hess)
Definition at line 229 of file model_methods_impl.h.
template<class Model > ModelDataT<Model> mappel::methods::simulate_image (const Model & model, const ParamT< Model > & theta)
Definition at line 22 of file model_methods_impl.h.
References simulate_image().
Referenced by simulate_image(), and mappel::methods::openmp::simulate_image_stack().
template<class Model , class RngT > ModelDataT<Model> mappel::methods::simulate_image (const Model & model, const ParamT< Model > & theta, RngT & rng)
Definition at line 29 of file model_methods_impl.h.
References simulate_image().
template<class Model , class rng_t > ModelDataT<Model> mappel::methods::simulate_image (const Model & model, const ParamT< Model > & theta)
Definition at line 22 of file model_methods_impl.h.
References simulate_image().
Referenced by simulate_image(), and mappel::methods::openmp::simulate_image_stack().
template<class Model , class rng_t > ReturnIfSubclassT<ModelDataT<Model>, Model, PoissonNoise1DObjective> mappel::methods::simulate_image (const Model & model, const StencilT< Model > & s, rng_t & rng)
Simulate an image at a given theta stencil, by generating Poisson noise Enabled for PoissonNoise1DObjective.
Parameters
[in] model Model object
[in] s The stencil computed at theta.
[in,out] rng A random number generator
Returns
A simulated image at theta under the noise model.
Definition at line 45 of file PoissonNoise1DObjective.h.
References mappel::generate_poisson().
template<class Model , class rng_t > ReturnIfSubclassT<ImageT<Model>, Model, PoissonNoise2DObjective> mappel::methods::simulate_image (const Model & model, const StencilT< Model > & s, rng_t & rng)
Simulate an image at a given theta stencil, by generating Poisson noise Enabled for PoissonNoise2DObjective.
Parameters
[in] model Model object
[in] s The stencil computed at theta.
[in,out] rng A random number generator
Returns
A simulated image at theta under the noise model.
Definition at line 45 of file PoissonNoise2DObjective.h.
References mappel::generate_poisson(), and mappel::ImageFormat2DBase::size.
template<class Model , class rng_t > ModelDataT<Model> mappel::methods::simulate_image (const Model & model, const ParamT< Model > & theta, rng_t & rng)
template<class Model > ModelDataT< Model > mappel::methods::simulate_image (const Model & model, const StencilT< Model > & s)
Definition at line 35 of file model_methods_impl.h.
References simulate_image().
template<class Model > ModelDataT< Model > mappel::methods::simulate_image_from_model (const Model & model, const ImageT< Model > & model_im)
Definition at line 41 of file model_methods_impl.h.
template<class Model , class rng_t > ReturnIfSubclassT<ModelDataT<Model>, Model, PoissonNoise1DObjective> mappel::methods::simulate_image_from_model (const Model & model, const ImageT< Model > & model_im, rng_t & rng)
Simulate an image at a given theta stencil, by generating Poisson noise Enabled for PoissonNoise1DObjective.
Parameters
[in] model Model object
[in] model_im An image representing the expected (mean) at each pixel under the PSF model.
[in,out] rng A random number generator
Returns
A simulated image corresponding to model_im under the noise model.
Definition at line 61 of file PoissonNoise1DObjective.h.
References mappel::generate_poisson().
template<class Model , class rng_t > ReturnIfSubclassT<ImageT<Model>, Model, PoissonNoise2DObjective> mappel::methods::simulate_image_from_model (const Model & model, const ImageT< Model > & model_im, rng_t & rng)
Simulate an image at a given theta stencil, by generating Poisson noise Enabled for PoissonNoise2DObjective.
Parameters
[in] model Model object
[in] model_im An image representing the expected (mean) at each pixel under the PSF model.
[in,out] rng A random number generator
Returns
A simulated image corresponding to model_im under the noise model.
Definition at line 64 of file PoissonNoise2DObjective.h.
References mappel::generate_poisson(), and mappel::ImageFormat2DBase::size.