Mappel: mappel::methods::objective::debug Namespace Reference
mappel::methods::objective::debug Namespace Reference
Functions
template<class Model >
ReturnIfSubclassT< VecT, Model, MAPEstimator > llh_components (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< VecT, Model, MAPEstimator > rllh_components (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< MatT, Model, MAPEstimator > grad_components (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< CubeT, Model, MAPEstimator > hessian_components (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< VecT, Model, MLEstimator > llh_components (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< VecT, Model, MLEstimator > rllh_components (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< MatT, Model, MLEstimator > grad_components (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< CubeT, Model, MLEstimator > hessian_components (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
VecT llh_components (const Model &model, const ModelDataT< Model > &data_im, const ParamT< Model > &theta)
template<class Model >
VecT rllh_components (const Model &model, const ModelDataT< Model > &data_im, const ParamT< Model > &theta)
template<class Model >
MatT grad_components (const Model &model, const ModelDataT< Model > &data_im, const ParamT< Model > &theta)
template<class Model >
CubeT hessian_components (const Model &model, const ModelDataT< Model > &data_im, const ParamT< Model > &theta)
Function Documentation
template<class Model > ReturnIfSubclassT<MatT,Model,MLEstimator> mappel::methods::objective::debug::grad_components (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 88 of file MLEstimator.h.
template<class Model > ReturnIfSubclassT<MatT,Model,MAPEstimator> mappel::methods::objective::debug::grad_components (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 96 of file MAPEstimator.h.
Referenced by grad_components().
template<class Model > MatT mappel::methods::objective::debug::grad_components (const Model & model, const ModelDataT< Model > & data_im, const ParamT< Model > & theta)
Definition at line 170 of file model_methods_impl.h.
References grad_components().
template<class Model > ReturnIfSubclassT<CubeT,Model,MLEstimator> mappel::methods::objective::debug::hessian_components (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 95 of file MLEstimator.h.
template<class Model > ReturnIfSubclassT<CubeT,Model,MAPEstimator> mappel::methods::objective::debug::hessian_components (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 103 of file MAPEstimator.h.
Referenced by hessian_components().
template<class Model > CubeT mappel::methods::objective::debug::hessian_components (const Model & model, const ModelDataT< Model > & data_im, const ParamT< Model > & theta)
Definition at line 177 of file model_methods_impl.h.
References hessian_components().
template<class Model > ReturnIfSubclassT<VecT,Model,MLEstimator> mappel::methods::objective::debug::llh_components (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 74 of file MLEstimator.h.
template<class Model > ReturnIfSubclassT<VecT,Model,MAPEstimator> mappel::methods::objective::debug::llh_components (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 82 of file MAPEstimator.h.
Referenced by llh_components().
template<class Model > VecT mappel::methods::objective::debug::llh_components (const Model & model, const ModelDataT< Model > & data_im, const ParamT< Model > & theta)
Definition at line 156 of file model_methods_impl.h.
References llh_components().
template<class Model > ReturnIfSubclassT<VecT,Model,MLEstimator> mappel::methods::objective::debug::rllh_components (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 81 of file MLEstimator.h.
template<class Model > ReturnIfSubclassT<VecT,Model,MAPEstimator> mappel::methods::objective::debug::rllh_components (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 89 of file MAPEstimator.h.
Referenced by rllh_components().
template<class Model > VecT mappel::methods::objective::debug::rllh_components (const Model & model, const ModelDataT< Model > & data_im, const ParamT< Model > & theta)
Definition at line 163 of file model_methods_impl.h.
References rllh_components().