Mappel: mappel::estimator::subroutine Namespace Reference
mappel::estimator::subroutine Namespace Reference
Functions
VecT solve_profile_initial_step (const MatT &obsI, IdxT fixed_idx, double llh_delta)
VecT bound_step (const VecT &step, const VecT &theta, const VecT &lbound, const VecT &ubound)
void compute_bound_scaling_vec (const VecT &theta, const VecT &g, const VecT &lbound, const VecT &ubound, VecT &v, VecT &Jv)
VecT compute_D_scale (const VecT &oldDscale, const VecT &grad2)
void compute_scaled_problem (const MatT &H, const VecT &g, const VecT &Dinv, const VecT &Jv, MatT &Hhat, VecT &ghat)
double compute_initial_trust_radius (const VecT &ghat)
VecT compute_cauchy_point (const VecT &g, const MatT &H, double delta)
double compute_quadratic_model_value (const VecT &s, const VecT &g, const MatT &H)
Quadratic model value at given step Compute a quadratic model.
VecT solve_TR_subproblem (const VecT &g, const MatT &H, double delta)
Exact solver the TR sub-problem even for non-positive definite H.
VecT solve_restricted_step_length_newton (const VecT &g, const MatT &H, double delta, double lambda_lb, double lambda_ub)
Detailed Description
Estimation subroutines common to several estimators and independent of the Model
Common subroutines shared between estimators.
These methods are model agnostic.
Function Documentation
VecT mappel::estimator::subroutine::bound_step (const VecT & step, const VecT & theta, const VecT & lbound, const VecT & ubound)
Return a new step that is guaranteed to keep theta in the interior of the feasible region. Uses a relative backtracking technique to step away from the boundary into the interior.
Parameters
step proposed step
theta current theta
lbound lower bounds
ubound upper bounds
Returns
bounded step
Definition at line 91 of file estimator.cpp.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
void mappel::estimator::subroutine::compute_bound_scaling_vec (const VecT & theta, const VecT & g, const VecT & lbound, const VecT & ubound, VecT & v, VecT & Jv)
Bounds scaling vector for affine scaling of bounds constrained optimization problems. This v is from Coleman&Li (1996). It represents a scaling factor for bound constrained problems. For unconstrained problems v = sgn(grad);
Parameters
[in] theta current theta
[in] g gradient
[in] lbound lower bound
[in] ubound upper bound
[out] v Scaling vector
[out] Jv Jacobian
Definition at line 142 of file estimator.cpp.
References mappel::sgn(), and mappel::estimator::MLEDebugData::theta.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
VecT mappel::estimator::subroutine::compute_cauchy_point (const VecT & g, const MatT & H, double delta)
Definition at line 185 of file estimator.cpp.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
VecT mappel::estimator::subroutine::compute_D_scale (const VecT & oldDscale, const VecT & grad2)
Compute an affine scaling diagonal matrix to scale problem away from boundaries. This works for either minimization or maximization. sign(grad2) is not important
Parameters
oldDscale Last D scaling matrix
grad2 Diagonal of hessian matrix
Returns
Diagonal scaling matrix as a vector.
Definition at line 169 of file estimator.cpp.
References mappel::clamp().
double mappel::estimator::subroutine::compute_initial_trust_radius (const VecT & ghat)
Definition at line 180 of file estimator.cpp.
References mappel::clamp().
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
double mappel::estimator::subroutine::compute_quadratic_model_value (const VecT & s, const VecT & g, const MatT & H)
Quadratic model value at given step Compute a quadratic model.
Definition at line 193 of file estimator.cpp.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
void mappel::estimator::subroutine::compute_scaled_problem (const MatT & H, const VecT & g, const VecT & Dinv, const VecT & Jv, MatT & Hhat, VecT & ghat)
Definition at line 174 of file estimator.cpp.
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().
VecT mappel::estimator::subroutine::solve_profile_initial_step (const MatT & obsI, IdxT fixed_idx, double llh_delta)
Find initial step lengths in profile bounds estimation VM algorithm
Definition at line 61 of file estimator.cpp.
References mappel::estimator::MLEDebugData::obsI.
Referenced by mappel::estimator::IterativeMaximizer< Model >::compute_profile_bound_debug(), mappel::estimator::Estimator< Model >::estimate_profile_bounds(), mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_parallel(), and mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_stack().
VecT mappel::estimator::subroutine::solve_restricted_step_length_newton (const VecT & g, const MatT & H, double delta, double lambda_lb, double lambda_ub)
Definition at line 266 of file estimator.cpp.
References mappel::cholesky(), mappel::cholesky_convert_lower_triangular(), mappel::cholesky_solve(), and mappel::clamp().
Referenced by solve_TR_subproblem().
VecT mappel::estimator::subroutine::solve_TR_subproblem (const VecT & g, const MatT & H, double delta)
Exact solver the TR sub-problem even for non-positive definite H.
This method is a hybrid technique mixing ideas from Geyer (2013) and the "trust" R-package Nocetal and Wright (2000) More and Sorensen (1981)
Definition at line 199 of file estimator.cpp.
References mappel::cholesky(), mappel::cholesky_solve(), and solve_restricted_step_length_newton().
Referenced by mappel::estimator::IterativeMaximizer< Model >::local_profile_maximize().