Mappel: mappel::mcmc Namespace Reference
mappel::mcmc Namespace Reference
Classes
struct MCMCData
struct MCMCDataStack
struct MCMCDebugData
Functions
IdxT num_oversample (IdxT Nsample, IdxT Nburnin, IdxT thin)
MatT thin_sample (MatT &sample, IdxT Nburnin, IdxT thin)
void thin_sample (const MatT &sample, const VecT &sample_rllh, IdxT Nburnin, IdxT thin, MatT &subsample, VecT &subsample_rllh)
void estimate_sample_posterior (const MatT &sample, VecT &theta_posterior_mean, MatT &theta_posterior_cov)
template<class Mat , class Vec >
void compute_posterior_credible (const Mat &sample, double confidence, Vec &lb, Vec &ub)
template<class Model >
void sample_posterior (const Model &model, const ModelDataT< Model > &im, const StencilT< Model > &theta_init, MatT &sample, VecT &sample_rllh)
template<class Model >
void sample_posterior_debug (const Model &model, const ModelDataT< Model > &im, const StencilT< Model > &theta_init, MatT &sample, VecT &sample_rllh, MatT &candidate, VecT &candidate_rllh)
Function Documentation
template<class Mat , class Vec > void mappel::mcmc::compute_posterior_credible (const Mat & sample, double confidence, Vec & lb, Vec & ub)
Definition at line 32 of file mcmc.h.
Referenced by mappel::methods::error_bounds_posterior_credible(), and mappel::methods::estimate_posterior().
void mappel::mcmc::estimate_sample_posterior (const MatT & sample, VecT & theta_posterior_mean, MatT & theta_posterior_cov) inline
Definition at line 25 of file mcmc.h.
Referenced by mappel::methods::estimate_posterior().
IdxT mappel::mcmc::num_oversample (IdxT Nsample, IdxT Nburnin, IdxT thin)
Definition at line 40 of file mcmc.cpp.
Referenced by mappel::methods::estimate_posterior(), and mappel::methods::openmp::estimate_posterior_stack().
template<class Model > void mappel::mcmc::sample_posterior (const Model & model, const ModelDataT< Model > & im, const StencilT< Model > & theta_init, MatT & sample, VecT & sample_rllh)
Definition at line 41 of file mcmc.h.
References mappel::methods::objective::rllh().
Referenced by mappel::methods::estimate_posterior().
template<class Model > void mappel::mcmc::sample_posterior_debug (const Model & model, const ModelDataT< Model > & im, const StencilT< Model > & theta_init, MatT & sample, VecT & sample_rllh, MatT & candidate, VecT & candidate_rllh)
Definition at line 73 of file mcmc.h.
References mappel::methods::objective::rllh().
Referenced by mappel::methods::debug::estimate_posterior_debug().
MatT mappel::mcmc::thin_sample (MatT & sample, IdxT Nburnin, IdxT thin)
Definition at line 46 of file mcmc.cpp.
References mappel::mcmc::MCMCData::thin.
Referenced by mappel::methods::estimate_posterior().
void mappel::mcmc::thin_sample (const MatT & sample, const VecT & sample_rllh, IdxT Nburnin, IdxT thin, MatT & subsample, VecT & subsample_rllh)
Definition at line 57 of file mcmc.cpp.
References mappel::mcmc::MCMCData::sample_rllh, and mappel::mcmc::MCMCData::thin.