Mappel: mappel::methods::likelihood Namespace Reference
mappel::methods::likelihood Namespace Reference
Namespaces
debug
Functions
template<class Model >
ReturnIfSubclassT< double, Model, PoissonNoise1DObjective > llh (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< double, Model, PoissonNoise1DObjective > rllh (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< ParamT< Model >, Model, PoissonNoise1DObjective > grad (const Model &model, const ModelDataT< Model > &im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< void, Model, PoissonNoise1DObjective > grad2 (const Model &model, const ModelDataT< Model > &im, const StencilT< Model > &s, ParamT< Model > &grad_val, ParamT< Model > &grad2_val)
template<class Model >
ReturnIfSubclassT< void, Model, PoissonNoise1DObjective > hessian (const Model &model, const ModelDataT< Model > &im, const StencilT< Model > &s, ParamT< Model > &grad_val, MatT &hess_val)
template<class Model >
ReturnIfSubclassT< double, Model, PoissonNoise2DObjective > llh (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< double, Model, PoissonNoise2DObjective > rllh (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< ParamT< Model >, Model, PoissonNoise2DObjective > grad (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< void, Model, PoissonNoise2DObjective > grad2 (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s, ParamT< Model > &grad_val, ParamT< Model > &grad2_val)
template<class Model >
ReturnIfSubclassT< void, Model, PoissonNoise2DObjective > hessian (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s, ParamT< Model > &grad_val, MatT &hess_val)
Function Documentation
template<class Model > ReturnIfSubclassT<ParamT<Model>,Model,PoissonNoise1DObjective> mappel::methods::likelihood::grad (const Model & model, const ModelDataT< Model > & im, const StencilT< Model > & s)
Definition at line 146 of file PoissonNoise1DObjective.h.
template<class Model > ReturnIfSubclassT<ParamT<Model>,Model,PoissonNoise2DObjective> mappel::methods::likelihood::grad (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 159 of file PoissonNoise2DObjective.h.
References mappel::ImageFormat2DBase::size.
template<class Model > ReturnIfSubclassT<void,Model,PoissonNoise1DObjective> mappel::methods::likelihood::grad2 (const Model & model, const ModelDataT< Model > & im, const StencilT< Model > & s, ParamT< Model > & grad_val, ParamT< Model > & grad2_val)
Definition at line 163 of file PoissonNoise1DObjective.h.
template<class Model > ReturnIfSubclassT<void,Model,PoissonNoise2DObjective> mappel::methods::likelihood::grad2 (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s, ParamT< Model > & grad_val, ParamT< Model > & grad2_val)
Definition at line 177 of file PoissonNoise2DObjective.h.
References mappel::ImageFormat2DBase::size.
template<class Model > ReturnIfSubclassT<void,Model,PoissonNoise1DObjective> mappel::methods::likelihood::hessian (const Model & model, const ModelDataT< Model > & im, const StencilT< Model > & s, ParamT< Model > & grad_val, MatT & hess_val)
Definition at line 186 of file PoissonNoise1DObjective.h.
Referenced by mappel::methods::aposteriori_objective(), and mappel::methods::likelihood_objective().
template<class Model > ReturnIfSubclassT<void,Model,PoissonNoise2DObjective> mappel::methods::likelihood::hessian (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s, ParamT< Model > & grad_val, MatT & hess_val)
Definition at line 202 of file PoissonNoise2DObjective.h.
References mappel::ImageFormat2DBase::size.
template<class Model > ReturnIfSubclassT<double,Model,PoissonNoise1DObjective> mappel::methods::likelihood::llh (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 122 of file PoissonNoise1DObjective.h.
References mappel::poisson_log_likelihood().
template<class Model > ReturnIfSubclassT<double,Model,PoissonNoise2DObjective> mappel::methods::likelihood::llh (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 131 of file PoissonNoise2DObjective.h.
References mappel::poisson_log_likelihood(), and mappel::ImageFormat2DBase::size.
template<class Model > ReturnIfSubclassT<double,Model,PoissonNoise1DObjective> mappel::methods::likelihood::rllh (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 134 of file PoissonNoise1DObjective.h.
References mappel::relative_poisson_log_likelihood().
Referenced by mappel::methods::aposteriori_objective(), and mappel::methods::likelihood_objective().
template<class Model > ReturnIfSubclassT<double,Model,PoissonNoise2DObjective> mappel::methods::likelihood::rllh (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 145 of file PoissonNoise2DObjective.h.
References mappel::relative_poisson_log_likelihood(), and mappel::ImageFormat2DBase::size.