Mappel: mappel::methods::debug Namespace Reference
mappel::methods::debug Namespace Reference
Functions
template<class Model >
void estimate_max_debug (const Model &model, const ModelDataT< Model > &data, const std::string &method, const ParamT< Model > &theta_init, estimator::MLEDebugData &mle, StatsT &stats)
template<class Model >
void error_bounds_profile_likelihood_debug (const Model &model, const ModelDataT< Model > &data, estimator::ProfileBoundsDebugData &bounds, StatsT &stats)
template<class Model >
void estimate_posterior_debug (const Model &model, const ModelDataT< Model > &data, const ParamT< Model > &theta_init, mcmc::MCMCDebugData &mcmc_debug_sample)
Function Documentation
template<class Model > void mappel::methods::debug::error_bounds_profile_likelihood_debug (const Model & model, const ModelDataT< Model > & data, estimator::ProfileBoundsDebugData & bounds, StatsT & stats)
Definition at line 461 of file model_methods_impl.h.
References mappel::estimator::Estimator< Model >::estimate_profile_bounds_debug(), and mappel::estimator::IterativeMaximizer< Model >::get_stats().
template<class Model > void mappel::methods::debug::estimate_max_debug (const Model & model, const ModelDataT< Model > & data, const std::string & method, const ParamT< Model > & theta_init, estimator::MLEDebugData & mle, StatsT & stats)
Definition at line 452 of file model_methods_impl.h.
References mappel::methods::make_estimator().
Referenced by mappel::estimator::Estimator< Model >::~Estimator().
template<class Model > void mappel::methods::debug::estimate_posterior_debug (const Model & model, const ModelDataT< Model > & data, const ParamT< Model > & theta_init, mcmc::MCMCDebugData & mcmc_debug_sample)
Definition at line 470 of file model_methods_impl.h.
References mappel::mcmc::MCMCDebugData::candidate, mappel::mcmc::MCMCDebugData::candidate_rllh, mappel::mcmc::MCMCDebugData::initialize_arrays(), mappel::mcmc::MCMCDebugData::Nsample, mappel::mcmc::MCMCDebugData::sample, mappel::mcmc::sample_posterior_debug(), and mappel::mcmc::MCMCDebugData::sample_rllh.