Mappel: mappel::methods::openmp Namespace Reference
mappel::methods::openmp Namespace Reference
Functions
template<class Model >
void sample_prior_stack (const Model &model, ParamVecT< Model > &theta_stack)
Parallel sampling of the model prior.
template<class Model >
void model_image_stack (const Model &model, const ParamVecT< Model > &theta_stack, ImageStackT< Model > &image_stack)
Parallel computation of the model image.
template<class Model >
void simulate_image_stack (const Model &model, const ParamVecT< Model > &theta_stack, ImageStackT< Model > &image_stack)
Parallel simulation of images from one or more theta.
template<class Model >
void cr_lower_bound_stack (const Model &model, const ParamVecT< Model > &theta_stack, ParamVecT< Model > &crlb_stack)
template<class Model >
void expected_information_stack (const Model &model, const ParamVecT< Model > &theta_stack, CubeT &fisherI_stack)
template<class Model >
void estimate_max_stack (const Model &model, const ModelDataStackT< Model > &data_stack, const std::string &method, estimator::MLEDataStack &mle_data_stack)
template<class Model >
void estimate_max_stack (const Model &model, const ModelDataStackT< Model > &data_stack, const std::string &method, estimator::MLEDataStack &mle_data_stack, StatsT &stats)
template<class Model >
void estimate_max_stack (const Model &model, const ModelDataStackT< Model > &data_stack, const std::string &method, ParamVecT< Model > &theta_init_stack, estimator::MLEDataStack &mle_data_stack)
template<class Model >
void estimate_max_stack (const Model &model, const ModelDataStackT< Model > &data_stack, const std::string &method, ParamVecT< Model > &theta_init_stack, estimator::MLEDataStack &mle_data_stack, StatsT &stats)
template<class Model >
void estimate_profile_likelihood_stack (const Model &model, const ModelDataT< Model > &data, const std::string &method, const ParamVecT< Model > &fixed_theta_init, estimator::ProfileLikelihoodData &est)
template<class Model >
void estimate_profile_likelihood_stack (const Model &model, const ModelDataT< Model > &data, const std::string &method, const ParamVecT< Model > &fixed_theta_init, estimator::ProfileLikelihoodData &est, StatsT &stats)
template<class Model >
void estimate_posterior_stack (const Model &model, const ModelDataStackT< Model > &data_stack, const ParamVecT< Model > &theta_init_stack, mcmc::MCMCDataStack &est)
template<class Model >
void estimate_posterior_stack (const Model &model, const ModelDataStackT< Model > &data_stack, mcmc::MCMCDataStack &est)
template<class Model >
void error_bounds_expected_stack (const Model &model, const MatT &theta_est_stack, double confidence, MatT &theta_lb_stack, MatT &theta_ub_stack)
template<class Model >
void error_bounds_observed_stack (const Model &model, const MatT &theta_est_stack, CubeT &obsI_stack, double confidence, MatT &theta_lb_stack, MatT &theta_ub_stack)
template<class Model >
void error_bounds_profile_likelihood_parallel (const Model &model, const ModelDataStackT< Model > &image, estimator::ProfileBoundsData &est, StatsT &stats)
template<class Model >
void error_bounds_profile_likelihood_parallel (const Model &model, const ModelDataT< Model > &image, estimator::ProfileBoundsData &est)
template<class Model >
void error_bounds_profile_likelihood_stack (const Model &model, const ModelDataStackT< Model > &image, estimator::ProfileBoundsDataStack &est, StatsT &stats)
template<class Model >
void error_bounds_profile_likelihood_stack (const Model &model, const ModelDataStackT< Model > &image, estimator::ProfileBoundsDataStack &est)
Function Documentation
template<class Model > void mappel::methods::openmp::cr_lower_bound_stack (const Model & model, const ParamVecT< Model > & theta_stack, ParamVecT< Model > & crlb_stack)
Definition at line 138 of file openmp_methods.h.
References omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::rethrow(), and omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::run().
template<class Model > void mappel::methods::openmp::error_bounds_expected_stack (const Model & model, const MatT & theta_est_stack, double confidence, MatT & theta_lb_stack, MatT & theta_ub_stack)
Definition at line 273 of file openmp_methods.h.
References mappel::normal_quantile_twosided(), omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::rethrow(), and omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::run().
template<class Model > void mappel::methods::openmp::error_bounds_observed_stack (const Model & model, const MatT & theta_est_stack, CubeT & obsI_stack, double confidence, MatT & theta_lb_stack, MatT & theta_ub_stack)
Definition at line 294 of file openmp_methods.h.
References mappel::normal_quantile_twosided(), and omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::run().
template<class Model > void mappel::methods::openmp::error_bounds_profile_likelihood_parallel (const Model & model, const ModelDataStackT< Model > & image, estimator::ProfileBoundsData & est, StatsT & stats)
Profile likelihood bounds. Uses the Venzon and Moolgavkar (VM) algorithm for computing each of the bounds of the profile likelihood.
Definition at line 323 of file openmp_methods.h.
References mappel::chisq_quantile(), mappel::estimator::ProfileBoundsData::confidence, mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_parallel(), mappel::estimator::ProfileBoundsData::estimated_idxs, mappel::estimator::IterativeMaximizer< Model >::get_stats(), and mappel::estimator::ProfileBoundsData::target_rllh_delta.
template<class Model > void mappel::methods::openmp::error_bounds_profile_likelihood_parallel (const Model & model, const ModelDataT< Model > & image, estimator::ProfileBoundsData & est)
Definition at line 333 of file openmp_methods.h.
References mappel::chisq_quantile(), mappel::estimator::ProfileBoundsData::confidence, mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_parallel(), mappel::estimator::ProfileBoundsData::estimated_idxs, and mappel::estimator::ProfileBoundsData::target_rllh_delta.
template<class Model > void mappel::methods::openmp::error_bounds_profile_likelihood_stack (const Model & model, const ModelDataStackT< Model > & image, estimator::ProfileBoundsDataStack & est, StatsT & stats)
Definition at line 342 of file openmp_methods.h.
References mappel::chisq_quantile(), mappel::estimator::ProfileBoundsDataStack::confidence, mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_stack(), mappel::estimator::ProfileBoundsDataStack::estimated_idxs, mappel::estimator::IterativeMaximizer< Model >::get_stats(), and mappel::estimator::ProfileBoundsDataStack::target_rllh_delta.
template<class Model > void mappel::methods::openmp::error_bounds_profile_likelihood_stack (const Model & model, const ModelDataStackT< Model > & image, estimator::ProfileBoundsDataStack & est)
Definition at line 352 of file openmp_methods.h.
References mappel::chisq_quantile(), mappel::estimator::ProfileBoundsDataStack::confidence, mappel::estimator::ThreadedEstimator< Model >::estimate_profile_bounds_stack(), mappel::estimator::ProfileBoundsDataStack::estimated_idxs, and mappel::estimator::ProfileBoundsDataStack::target_rllh_delta.
template<class Model > void mappel::methods::openmp::estimate_max_stack (const Model & model, const ModelDataStackT< Model > & data_stack, const std::string & method, estimator::MLEDataStack & mle_data_stack)
Definition at line 168 of file openmp_methods.h.
References mappel::methods::make_estimator().
Referenced by mappel::estimator::Estimator< Model >::~Estimator().
template<class Model > void mappel::methods::openmp::estimate_max_stack (const Model & model, const ModelDataStackT< Model > & data_stack, const std::string & method, estimator::MLEDataStack & mle_data_stack, StatsT & stats)
Definition at line 178 of file openmp_methods.h.
References mappel::methods::make_estimator().
template<class Model > void mappel::methods::openmp::estimate_max_stack (const Model & model, const ModelDataStackT< Model > & data_stack, const std::string & method, ParamVecT< Model > & theta_init_stack, estimator::MLEDataStack & mle_data_stack)
Definition at line 189 of file openmp_methods.h.
References mappel::methods::make_estimator().
template<class Model > void mappel::methods::openmp::estimate_max_stack (const Model & model, const ModelDataStackT< Model > & data_stack, const std::string & method, ParamVecT< Model > & theta_init_stack, estimator::MLEDataStack & mle_data_stack, StatsT & stats)
Definition at line 198 of file openmp_methods.h.
References mappel::methods::make_estimator().
template<class Model > void mappel::methods::openmp::estimate_posterior_stack (const Model & model, const ModelDataStackT< Model > & data_stack, const ParamVecT< Model > & theta_init_stack, mcmc::MCMCDataStack & est)
Definition at line 227 of file openmp_methods.h.
References mappel::mcmc::MCMCDataStack::initialize_arrays(), mappel::mcmc::MCMCDataStack::Nburnin, mappel::mcmc::MCMCDataStack::Ndata, mappel::mcmc::MCMCDataStack::Nsample, mappel::mcmc::num_oversample(), omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::rethrow(), omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::run(), and mappel::mcmc::MCMCDataStack::thin.
Referenced by estimate_posterior_stack().
template<class Model > void mappel::methods::openmp::estimate_posterior_stack (const Model & model, const ModelDataStackT< Model > & data_stack, mcmc::MCMCDataStack & est)
Definition at line 265 of file openmp_methods.h.
References estimate_posterior_stack().
template<class Model > void mappel::methods::openmp::estimate_profile_likelihood_stack (const Model & model, const ModelDataT< Model > & data, const std::string & method, const ParamVecT< Model > & fixed_theta_init, estimator::ProfileLikelihoodData & est)
Definition at line 208 of file openmp_methods.h.
References mappel::methods::make_estimator().
template<class Model > void mappel::methods::openmp::estimate_profile_likelihood_stack (const Model & model, const ModelDataT< Model > & data, const std::string & method, const ParamVecT< Model > & fixed_theta_init, estimator::ProfileLikelihoodData & est, StatsT & stats)
Definition at line 217 of file openmp_methods.h.
References mappel::methods::make_estimator().
template<class Model > void mappel::methods::openmp::expected_information_stack (const Model & model, const ParamVecT< Model > & theta_stack, CubeT & fisherI_stack)
Definition at line 153 of file openmp_methods.h.
References omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::rethrow(), and omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::run().
template<class Model > void mappel::methods::openmp::model_image_stack (const Model & model, const ParamVecT< Model > & theta_stack, ImageStackT< Model > & image_stack)
Parallel computation of the model image.
The model image is the expected photon count at each pixel under parameter theta.
Use: model.make_param_stack() to make a parameter stack of appropriate dimensions for the model Use: model.make_image_stack() to make an image stack of appropriate dimensions for the model
Template Parameters
Model A concrete subclass of PointEmitterModel
Parameters
[in] model A PointEmitterModel object.
[in] theta_stack Sequence of thetas for which to generate images. Size: [model.num_params, nThetas]
[out] image_stack Sequence of model images generated.
Definition at line 73 of file openmp_methods.h.
References omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::rethrow(), and omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::run().
template<class Model > void mappel::methods::openmp::sample_prior_stack (const Model & model, ParamVecT< Model > & theta_stack)
Parallel sampling of the model prior.
Use: model.make_param_stack() to make a parameter stack of appropriate dimensions for the model
Template Parameters
Model A concrete subclass of PointEmitterModel
Parameters
[in] model,A PointEmitterModel object.
[out] theta_stack,A sequence of sampled thetas. Size: [model.num_params, nSamples]
Definition at line 45 of file openmp_methods.h.
References omp_exception_catcher::Continue, omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::rethrow(), and omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::run().
template<class Model > void mappel::methods::openmp::simulate_image_stack (const Model & model, const ParamVecT< Model > & theta_stack, ImageStackT< Model > & image_stack)
Parallel simulation of images from one or more theta.
This accepts either a single theta and a stack of images, or a stack of thetas and a stack of images.
Use: model.make_param_stack() to make a parameter stack of appropriate dimensions for the model Use: model.make_image_stack() to make an image stack of appropriate dimensions for the model
Template Parameters
Model A concrete subclass of PointEmitterModel
Parameters
[in] model A PointEmitterModel object.
[in] theta_stack Single theta or a sequence of thetas. Size: [model.num_params, nThetas]
[out] image_stack Sequence of model images generated.
Definition at line 100 of file openmp_methods.h.
References mappel::methods::model_image(), omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::rethrow(), omp_exception_catcher::impl_::OMPExceptionCatcher< _dummy >::run(), and mappel::methods::simulate_image().