Mappel: mappel Namespace Reference
mappel Namespace Reference
Namespaces
mcmc
methods
Templated functions for operating on a PointEmitterModel.
Classes
struct ArrayShapeError
Array is not of the right dimensionality.
struct ArraySizeError
Array is not of the right size.
class CGaussHeuristicEstimator
class CGaussMLE
class Estimator
class Gauss1DMAP
A 1D Gaussian with fixed PSF under an Poisson Read Noise assumption and MAP Objective.
class Gauss1DMLE
A 1D Gaussian with fixed PSF under an Poisson noise assumption and maximum-likelihood objective.
class Gauss1DModel
A base class for 1D Gaussian PSF with a fixed sigma (standard dev.)
class Gauss1DsMAP
A 1D Gaussian with variable PSF sigma under an Poisson read noise assumption and MAP Objective.
class Gauss1DsMLE
A 1D Gaussian with variable PSF under an Poisson noise assumption and maximum-likelihood estimator.
class Gauss1DsModel
Base class for 1D Gaussian PSF with variable Gaussian sigma (standard deviation) measured in units of pixels.
class Gauss2DMAP
A 2D Gaussian with fixed PSF under an Poisson Read Noise assumption and MAP Objective.
class Gauss2DMLE
A 2D Gaussian with fixed PSF under an Poisson noise assumption and maximum-likelihood objective.
class Gauss2DModel
A base class for 2D Gaussian PSF with fixed but possibly asymmetric sigma.
class Gauss2DsMAP
A 2D Gaussian with a variable scalar PSF sigma under a Poisson noise assumption using a maximum a-posteriori objective.
class Gauss2DsMLE
A 2D Gaussian with a variable scalar PSF sigma under a Poisson noise assumption using a maximum-likelihood objective.
class Gauss2DsModel
A base class for 2D Gaussian PSF where the gaussian sigma is controlled by a single scalar parameter which is called sigma_ratio. The size of the gaussian psf is sigma_ratio*psf_sigma, where psf_sigma is considered as a vector [psf_sigmaX, psf_sigmaY].
class Gauss2DsxyMAP
A 1D Gaussian with fixed PSF under an Poisson Read Noise assumption and MAP Objective.
class Gauss2DsxyModel
A base class for 2D Gaussian PSF with axis-aligned gaussian with free parameters for both sigma_x and sigma_y. Gaussian sigma parameters sigma_x and sigma_y are measured in units of pixels. The model has 6 parameters, [x,y,I,bg,sigma_x,sigma_y].
class HeuristicEstimator
class ImageFormat1DBase
A virtual base class for 2D image localization objectives.
class ImageFormat2DBase
A virtual base class for 2D image localization objectives.
class IterativeMaximizer
struct LogicalError
Failure of code or algorithm logic.
class MAPEstimator
A Mixin class to configure a for MLE estimation (null prior).
class MCMCAdaptor1D
class MCMCAdaptor1Ds
class MCMCAdaptor2D
class MCMCAdaptor2Ds
class MCMCAdaptorBase
class MLEstimator
A Mixin class to configure a for MLE estimation (null prior).
struct ModelBoundsError
Access outside the model bounds is attempted.
class NewtonDiagonalMaximizer
class NewtonMaximizer
struct NotImplementedError
Feature not yet implemented.
struct NumericalError
Expected numerical condition does not hold.
struct ParameterValueError
Parameter value is not valid.
class PointEmitterModel
A virtual Base type for point emitter localization models.
class PoissonNoise1DObjective
A base class for 1D objectives with Poisson read noise. This objective function and its subclasses are for models where the only source of noise is the "shot" or "counting" or Poisson noise inherent to a discrete capture of phontons given a certain mean rate of incidence on each pixel.
class PoissonNoise2DObjective
A base class for 2D objectives with Poisson read noise. This objective function and its subclasses are for models where the only source of noise is the "shot" or "counting" or Poisson noise inherent to a discrete capture of phontons given a certain mean rate of incidence on each pixel.
class PriorMAP1DObjective
A Mixin class to configure a Gauss1DModel for MAP estimation (default 1D prior).
class QuasiNewtonMaximizer
class SimulatedAnnealingMaximizer
class ThreadedEstimator
class TrustRegionMaximizer
Typedefs
using ParallelRngGeneratorT = trng::lcg64_shift
using ParallelRngManagerT = parallel_rng::ParallelRngManager< ParallelRngGeneratorT >
using RngSeedT = parallel_rng::SeedT
using UniformDistT = std::uniform_real_distribution< double >
using BoolT = uint16_t
using BoolVecT = arma::Col< uint16_t >
using IdxT = arma::uword
using IdxVecT = arma::Col< IdxT >
using IdxMatT = arma::Mat< IdxT >
using VecT = arma::vec
using MatT = arma::mat
using CubeT = arma::cube
using VecFieldT = arma::field< VecT >
using StatsT = std::map< std::string, double >
using StringVecT = std::vector< std::string >
template<class ModelT , class ModelBaseT >
using EnableIfSubclassT = typename std::enable_if< std::is_base_of< ModelBaseT, ModelT >::value, void >::type
template<class ReturnT , class ModelT , class ModelBaseT >
using ReturnIfSubclassT = typename std::enable_if< std::is_base_of< ModelBaseT, ModelT >::value, ReturnT >::type
template<class Model >
using ImageCoordT = typename Model::ImageCoordT
template<class Model >
using ImagePixelT = typename Model::ImagePixelT
template<class Model >
using ParamT = typename Model::ParamT
template<class Model >
using ParamVecT = typename Model::ParamVecT
template<class Model >
using ImageT = typename Model::ImageT
template<class Model >
using ModelDataT = typename Model::ModelDataT
template<class Model >
using StencilT = typename Model::Stencil
template<class Model >
using ImageStackT = typename Model::ImageStackT
template<class Model >
using ModelDataStackT = typename Model::ModelDataStackT
template<class Model >
using StencilVecT = typename Model::StencilVecT
using MappelError = backtrace_exception::BacktraceException
Functions
const char * lambda_term_color (int size, int Lidx)
ostream & print_centered_title (ostream &out, char fill, int width, const char *title=nullptr)
ostream & print_labeled_image (ostream &out, const arma::mat &im, const char *title, const char *color)
template<>
std::ostream & print_image (std::ostream &out, const arma::vec &im)
template<>
std::ostream & print_image (std::ostream &out, const arma::mat &im)
template<>
std::ostream & print_image (std::ostream &out, const arma::cube &im)
std::ostream & operator<< (std::ostream &out, const Gauss1DModel::Stencil &s)
std::ostream & operator<< (std::ostream &out, const Gauss1DsModel::Stencil &s)
std::ostream & operator<< (std::ostream &out, const Gauss2DModel::Stencil &s)
std::ostream & operator<< (std::ostream &out, const Gauss2DsModel::Stencil &s)
void copy_Usym_mat (arma::mat &usym)
void copy_Usym_mat_stack (arma::cube &usym_stack)
void copy_Lsym_mat (arma::mat &lsym)
void cholesky_make_negative_definite (arma::mat &m)
void cholesky_make_positive_definite (arma::mat &m)
bool is_negative_definite (const arma::mat &usym)
bool is_positive_definite (const arma::mat &usym)
bool is_symmetric (const arma::mat &A)
void cholesky_convert_lower_triangular (arma::mat &chol)
void cholesky_convert_full_matrix (arma::mat &chol)
bool cholesky (arma::mat &A)
bool modified_cholesky (arma::mat &A)
arma::vec cholesky_solve (const arma::mat &C, const arma::vec &b)
double normal_quantile_twosided (double confidence)
double normal_quantile_onesided (double confidence)
void fill_gaussian_stencil (int size, double stencil[], double sigma)
double gaussian_convolution (int x, int y, const MatT &data, const VecT &Xstencil, const VecT &Ystencil)
void estimate_gaussian_2Dmax (const MatT &data, const VecT &Xstencil, const VecT &Ystencil, int max_pos[], double &min_val)
void refine_gaussian_2Dmax (const MatT &data, const VecT &Xstencil, const VecT &Ystencil, int max_pos[])
double gaussian_3D_convolution (int x, int y, int z, const CubeT &data, const VecFieldT &stencils)
void estimate_gaussian_3Dmax (const CubeT &data, const VecFieldT &stencils, int max_pos[], double &min_val)
void refine_gaussian_3Dmax (const CubeT &data, const VecFieldT &stencils, int max_pos[])
double estimate_background (const MatT &im, const MatT &unit_model_im, double min_bg)
double estimate_intensity (const MatT &im, const MatT &unit_model_im, double bg)
double estimate_background (const CubeT &im, const CubeT &unit_model_im)
double estimate_intensity (const CubeT &im, const CubeT &unit_model_im, double bg)
void enable_all_cpus ()
bool istarts_with (const char *s, const char *pattern)
bool istarts_with (const std::string &str, const char *pattern)
const char * icontains (const char *s, const char *pattern)
int maxidx (const VecT &v)
std::ostream & operator<< (std::ostream &out, const StatsT &stats)
template<class ImageT >
std::ostream & print_image (std::ostream &out, const ImageT &im)
template<class Vec >
std::ostream & print_vec_row (std::ostream &out, const Vec &vec, const char *header, int header_width, const char *color=nullptr)
template<class Model >
std::ostream & operator<< (std::ostream &out, Estimator< Model > &estimator)
template<class Model >
std::enable_if< std::is_base_of< Gauss2DModel, Model >::value, ParamT< Model > >::type cgauss_heuristic_compute_estimate (const Model &model, const ModelDataT< Model > &im, const ParamT< Model > &theta_init)
template<class Model >
std::enable_if< std::is_base_of< Gauss2DModel, Model >::value, ParamT< Model > >::type cgauss_compute_estimate (Model &model, const ModelDataT< Model > &im, const ParamT< Model > &theta_init, int max_iterations)
template<class Model >
std::enable_if< std::is_base_of< Gauss2DModel, Model >::value, ParamT< Model > >::type cgauss_compute_estimate_debug (const Model &model, const ModelDataT< Model > &im, const ParamT< Model > &theta_init, int max_iterations, ParamVecT< Model > &sequence)
template<class Model >
std::enable_if< std::is_base_of< Gauss2DsModel, Model >::value, ParamT< Model > >::type cgauss_heuristic_compute_estimate (const Model &model, const ModelDataT< Model > &im, const ParamT< Model > &theta_init)
template<class Model >
std::enable_if< std::is_base_of< Gauss2DsModel, Model >::value, ParamT< Model > >::type cgauss_compute_estimate (Model &model, const ModelDataT< Model > &im, const ParamT< Model > &theta_init, int max_iterations)
template<class Model >
std::enable_if< std::is_base_of< Gauss2DsModel, Model >::value, ParamT< Model > >::type cgauss_compute_estimate_debug (const Model &model, const ModelDataT< Model > &im, const ParamT< Model > &theta_init, int max_iterations, ParamVecT< Model > &sequence)
template<class Model >
std::enable_if< std::is_base_of< Gauss2DsxyModel, Model >::value, ParamT< Model > >::type cgauss_heuristic_compute_estimate (const Model &model, const ModelDataT< Model > &im, const ParamT< Model > &theta_init)
template<class Model >
std::enable_if< std::is_base_of< Gauss2DsxyModel, Model >::value, ParamT< Model > >::type cgauss_compute_estimate (Model &model, const ModelDataT< Model > &im, const ParamT< Model > &theta_init, int max_iterations)
template<class Model >
std::enable_if< std::is_base_of< Gauss2DsxyModel, Model >::value, ParamT< Model > >::type cgauss_compute_estimate_debug (const Model &model, const ModelDataT< Model > &im, const ParamT< Model > &theta_init, int max_iterations, ParamVecT< Model > &sequence)
template<class Model , typename = EnableIfSubclassT<Model,PointEmitterModel>>
std::ostream & operator<< (std::ostream &out, const Model &model)
template<class RngT >
IdxT generate_poisson_small (RngT &rng, double mu)
Genrates a single poisson disributed int from distribution with mean mu.
template<class RngT >
IdxT generate_poisson_large (RngT &rng, double mu)
template<class RngT >
double generate_poisson (RngT &rng, double mu)
template<class Model >
void sample_prior_stack (Model &model, typename Model::ParamVecT &theta_stack)
Parallel sampling of the model prior.
template<class Model >
void model_image_stack (const Model &model, const typename Model::ParamVecT &theta_stack, typename Model::ImageStackT &image_stack)
Parallel computation of the model image.
template<class Model >
void simulate_image_stack (const Model &model, const typename Model::ParamVecT &theta_stack, typename Model::ImageStackT &image_stack)
Parallel simulation of images from one or more theta.
template<class Model >
void log_likelihood_stack (const Model &model, const typename Model::ImageT &image, const typename Model::ParamVecT &theta_stack, VecT &llh_stack)
Parallel log_likelihood calculations for a single image.
template<class Model >
void log_likelihood_stack (const Model &model, const typename Model::ImageStackT &image_stack, const typename Model::ParamVecT &theta_stack, VecT &llh_stack)
Parallel log_likelihood calculations for a stack of images.
template<class Model >
void model_grad_stack (const Model &model, const typename Model::ImageStackT &image_stack, const typename Model::ParamVecT &theta_stack, typename Model::ParamVecT &grad_stack)
Parallel model gradient calculations for a stack of images.
template<class Model >
void model_hessian_stack (const Model &model, const typename Model::ImageStackT &image_stack, const typename Model::ParamVecT &theta_stack, CubeT &hessian_stack)
Parallel model Hessian calculations for a stack of images.
template<class Model >
void model_positive_hessian_stack (const Model &model, const typename Model::ImageStackT &image_stack, const typename Model::ParamVecT &theta_stack, CubeT &hessian_stack)
Parallel model positive-definite Hessian approximation calculations for a stack of images.
template<class Model >
void cr_lower_bound_stack (const Model &model, const typename Model::ParamVecT &theta_stack, typename Model::ParamVecT &crlb_stack)
template<class Model >
void fisher_information_stack (const Model &model, const typename Model::ParamVecT &theta_stack, CubeT &fisherI_stack)
double gauss_norm (double sigma)
void fill_d_stencil (int size, double stencil[], double theta_x)
void fill_G_stencil (int size, double stencil[], const double dx[], double theta_sigma)
void fill_X_stencil (int size, double stencil[], const double dx[], double theta_sigma)
void fill_DX_stencil (int size, double stencil[], const double Gx[], double theta_sigma)
void fill_DXS_stencil (int size, double stencil[], const double dx[], const double Gx[], double theta_sigma)
void fill_DXS2_stencil (int size, double stencil[], const double dx[], const double Gx[], const double DXS[], double theta_sigma)
void fill_DXSX_stencil (int size, double stencil[], const double dx[], const double Gx[], const double DX[], double theta_sigma)
VecT make_d_stencil (int size, double theta_x)
VecT make_G_stencil (int size, const VecT &dx, double theta_sigma)
VecT make_X_stencil (int size, const VecT &dx, double theta_sigma)
VecT make_DX_stencil (int size, const VecT &Gx, double theta_sigma)
VecT make_DXS_stencil (int size, const VecT &dx, const VecT &Gx, double theta_sigma)
VecT make_DXS2_stencil (int size, const VecT &dx, const VecT &Gx, const VecT &DXS, double theta_sigma)
VecT make_DXSX_stencil (int size, const VecT &dx, const VecT &Gx, const VecT &DX, double theta_sigma)
VecT make_gaussian_stencil (int size, double sigma)
double poisson_log_likelihood (double model_val, double data_val)
double relative_poisson_log_likelihood (double model_val, double data_val)
double check_lower_bound_hyperparameter (const char *name, double value, double lower_bound)
double check_positive_hyperparameter (const char *name, double value, double hyperprior_epsilon=1E-6)
double check_unit_hyperparameter (const char *name, double value, double hyperprior_epsilon=1E-6)
double log_prior_beta_const (double beta)
double log_prior_beta2_const (double beta0, double beta1)
double log_prior_gamma_const (double kappa, double mean)
double log_prior_pareto_const (double alpha, double min)
double log_prior_normal_const (double sigma)
double rllh_beta_prior (double beta, double v, double max=1., double min=0.)
double rllh_beta2_prior (double beta0, double beta1, double v, double max=1., double min=0.)
double rllh_gamma_prior (double kappa, double mean, double v)
double rllh_pareto_prior (double alpha, double v)
double rllh_normal_prior (double mu, double sigma)
double beta_prior_grad (double beta, double v, double max=1., double min=0.)
double beta2_prior_grad (double beta0, double beta1, double v, double max=1., double min=0.)
double gamma_prior_grad (double kappa, double mean, double v)
double pareto_prior_grad (double alpha, double v)
double normal_prior_grad (double mu, double sigma)
double beta_prior_grad2 (double beta, double v, double max=1., double min=0.)
double beta2_prior_grad2 (double beta0, double beta1, double v, double max=1., double min=0.)
double gamma_prior_grad2 (double kappa, double v)
double pareto_prior_grad2 (double alpha, double v)
double normal_prior_grad (double sigma)
double rllh_normal_prior (double mu, double sigma, double v)
double normal_prior_grad (double mu, double sigma, double v)
double normal_prior_grad2 (double sigma)
template<typename T >
int sgn (T val)
sign (signum) function: -1/0/1
template<typename T >
T square (T x)
double restrict_value_range (double val, double minval, double maxval)
template<typename T , typename... Args>
std::unique_ptr< T > make_unique (Args &&...args)
Variables
const char * TERM_BLACK ="1;30"
const char * TERM_RED ="1;31"
const char * TERM_GREEN ="1;32"
const char * TERM_YELLOW ="1;33"
const char * TERM_BLUE ="1;34"
const char * TERM_MAGENTA ="1;35"
const char * TERM_CYAN ="1;36"
const char * TERM_WHITE ="1;37"
const char * TERM_DIM_BLACK ="0;30"
const char * TERM_DIM_RED ="0;31"
const char * TERM_DIM_GREEN ="0;32"
const char * TERM_DIM_YELLOW ="0;33"
const char * TERM_DIM_BLUE ="0;34"
const char * TERM_DIM_MAGENTA ="0;35"
const char * TERM_DIM_CYAN ="0;36"
const char * TERM_DIM_WHITE ="0;37"
ParallelRngManagerT rng_manager
Detailed Description
All models will call for maximization through this virtual function. All non-GPU based maximizers will use this version which spawns threads using a non-virual entry point member function Maximizer::thread_entry. GPU-based maximizers will want to do something custom, so they will declare their own virtual maximize_stack.
It is also because of the GPU-based mamixmizers that we are putting initilization, and CRLB/LLH calculations in here even though the Model knows how to do them.
We expect that those methods will need to also be paralellized and the GPU will need custom code, and the threaded CPU versions will want to also compute those in parallel, so in order to have a consitent call interface to the Maximizer classes, we put the CRLB/LLH and initialization work within the the maximize_stack method.
Typedef Documentation
using mappel::BoolT = typedef uint16_t
Definition at line 19 of file util.h.
using mappel::BoolVecT = typedef arma::Col<uint16_t>
Definition at line 20 of file util.h.
using mappel::CubeT = typedef arma::cube
A type to represent floating-point data cubes
Definition at line 26 of file util.h.
template<class ModelT , class ModelBaseT > using mappel::EnableIfSubclassT = typedef typename std::enable_if<std::is_base_of<ModelBaseT,ModelT>::value,void>::type
Definition at line 33 of file util.h.
using mappel::IdxMatT = typedef arma::Mat<IdxT>
A type to represent integer data arrays
Definition at line 23 of file util.h.
using mappel::IdxT = typedef arma::uword
Definition at line 21 of file util.h.
using mappel::IdxVecT = typedef arma::Col<IdxT>
A type to represent integer data arrays
Definition at line 22 of file util.h.
template<class Model > using mappel::ImageCoordT = typedef typename Model::ImageCoordT
Definition at line 38 of file util.h.
template<class Model > using mappel::ImagePixelT = typedef typename Model::ImagePixelT
Definition at line 39 of file util.h.
template<class Model > using mappel::ImageStackT = typedef typename Model::ImageStackT
Definition at line 47 of file util.h.
template<class Model > using mappel::ImageT = typedef typename Model::ImageT
Definition at line 43 of file util.h.
using mappel::MappelError = typedef backtrace_exception::BacktraceException
Definition at line 60 of file util.h.
using mappel::MatT = typedef arma::mat
A type to represent floating-point data matricies
Definition at line 25 of file util.h.
template<class Model > using mappel::ModelDataStackT = typedef typename Model::ModelDataStackT
Definition at line 48 of file util.h.
template<class Model > using mappel::ModelDataT = typedef typename Model::ModelDataT
Definition at line 44 of file util.h.
using mappel::ParallelRngGeneratorT = typedef trng::lcg64_shift
Definition at line 21 of file rng.h.
using mappel::ParallelRngManagerT = typedef parallel_rng::ParallelRngManager<ParallelRngGeneratorT>
Definition at line 22 of file rng.h.
template<class Model > using mappel::ParamT = typedef typename Model::ParamT
Definition at line 41 of file util.h.
template<class Model > using mappel::ParamVecT = typedef typename Model::ParamVecT
Definition at line 42 of file util.h.
template<class ReturnT , class ModelT , class ModelBaseT > using mappel::ReturnIfSubclassT = typedef typename std::enable_if<std::is_base_of<ModelBaseT,ModelT>::value,ReturnT>::type
Definition at line 36 of file util.h.
using mappel::RngSeedT = typedef parallel_rng::SeedT
Definition at line 23 of file rng.h.
using mappel::StatsT = typedef std::map<std::string,double>
A convenient form for reporting dictionaries of named FP data to matlab
Definition at line 28 of file util.h.
template<class Model > using mappel::StencilT = typedef typename Model::Stencil
Definition at line 45 of file util.h.
template<class Model > using mappel::StencilVecT = typedef typename Model::StencilVecT
Definition at line 49 of file util.h.
using mappel::StringVecT = typedef std::vector<std::string>
Definition at line 29 of file util.h.
using mappel::UniformDistT = typedef std::uniform_real_distribution<double>
Definition at line 24 of file rng.h.
using mappel::VecFieldT = typedef arma::field<VecT>
Definition at line 27 of file util.h.
using mappel::VecT = typedef arma::vec
A type to represent floating-point data arrays
Definition at line 24 of file util.h.
Function Documentation
double mappel::beta2_prior_grad (double beta0, double beta1, double v, double max = 1., double min = 0.) inline
Definition at line 314 of file stencil.h.
double mappel::beta2_prior_grad2 (double beta0, double beta1, double v, double max = 1., double min = 0.) inline
Definition at line 347 of file stencil.h.
double mappel::beta_prior_grad (double beta, double v, double max = 1., double min = 0.) inline
Definition at line 307 of file stencil.h.
Referenced by mappel::PriorMAP1DObjective::prior_grad_update().
double mappel::beta_prior_grad2 (double beta, double v, double max = 1., double min = 0.) inline
Definition at line 339 of file stencil.h.
Referenced by mappel::PriorMAP1DObjective::prior_grad2_update(), and mappel::PriorMAP1DObjective::prior_hess_update().
template<class Model > std::enable_if<std::is_base_of<Gauss2DModel,Model>::value, ParamT<Model> >::type mappel::cgauss_compute_estimate (Model & model, const ModelDataT< Model > & im, const ParamT< Model > & theta_init, int max_iterations)
Definition at line 223 of file Gauss2DModel.h.
References mappel::Gauss2DModel::psf_sigma, and mappel::ImageFormat2DBase::size.
Referenced by mappel::CGaussMLE< Model >::compute_estimate().
template<class Model > std::enable_if<std::is_base_of<Gauss2DsxyModel,Model>::value, ParamT<Model> >::type mappel::cgauss_compute_estimate (Model & model, const ModelDataT< Model > & im, const ParamT< Model > & theta_init, int max_iterations)
Definition at line 251 of file Gauss2DsxyModel.h.
References mappel::ImageFormat2DBase::size.
template<class Model > std::enable_if<std::is_base_of<Gauss2DsModel,Model>::value, ParamT<Model> >::type mappel::cgauss_compute_estimate (Model & model, const ModelDataT< Model > & im, const ParamT< Model > & theta_init, int max_iterations)
Definition at line 253 of file Gauss2DsModel.h.
References mappel::ImageFormat2DBase::size.
template<class Model > std::enable_if<std::is_base_of<Gauss2DModel,Model>::value, ParamT<Model> >::type mappel::cgauss_compute_estimate_debug (const Model & model, const ModelDataT< Model > & im, const ParamT< Model > & theta_init, int max_iterations, ParamVecT< Model > & sequence)
Definition at line 238 of file Gauss2DModel.h.
References mappel::Gauss2DModel::psf_sigma, and mappel::ImageFormat2DBase::size.
Referenced by mappel::CGaussMLE< Model >::compute_estimate_debug().
template<class Model > std::enable_if<std::is_base_of<Gauss2DsxyModel,Model>::value, ParamT<Model> >::type mappel::cgauss_compute_estimate_debug (const Model & model, const ModelDataT< Model > & im, const ParamT< Model > & theta_init, int max_iterations, ParamVecT< Model > & sequence)
Definition at line 266 of file Gauss2DsxyModel.h.
References mappel::ImageFormat2DBase::size.
template<class Model > std::enable_if<std::is_base_of<Gauss2DsModel,Model>::value, ParamT<Model> >::type mappel::cgauss_compute_estimate_debug (const Model & model, const ModelDataT< Model > & im, const ParamT< Model > & theta_init, int max_iterations, ParamVecT< Model > & sequence)
Definition at line 268 of file Gauss2DsModel.h.
References mappel::ImageFormat2DBase::size.
template<class Model > std::enable_if<std::is_base_of<Gauss2DModel,Model>::value,ParamT<Model> >::type mappel::cgauss_heuristic_compute_estimate (const Model & model, const ModelDataT< Model > & im, const ParamT< Model > & theta_init)
Definition at line 209 of file Gauss2DModel.h.
References mappel::Gauss2DModel::psf_sigma, and mappel::ImageFormat2DBase::size.
Referenced by mappel::CGaussMLE< Model >::compute_estimate(), mappel::CGaussMLE< Model >::compute_estimate_debug(), and mappel::HeuristicEstimator< Model >::get_debug_stats().
template<class Model > std::enable_if<std::is_base_of<Gauss2DsxyModel,Model>::value, ParamT<Model> >::type mappel::cgauss_heuristic_compute_estimate (const Model & model, const ModelDataT< Model > & im, const ParamT< Model > & theta_init)
Definition at line 237 of file Gauss2DsxyModel.h.
References mappel::ImageFormat2DBase::size.
template<class Model > std::enable_if<std::is_base_of<Gauss2DsModel,Model>::value, ParamT<Model> >::type mappel::cgauss_heuristic_compute_estimate (const Model & model, const ModelDataT< Model > & im, const ParamT< Model > & theta_init)
Definition at line 239 of file Gauss2DsModel.h.
References mappel::ImageFormat2DBase::size.
double mappel::check_lower_bound_hyperparameter (const char * name, double value, double lower_bound)
double mappel::check_positive_hyperparameter (const char * name, double value, double hyperprior_epsilon = 1E-6)
double mappel::check_unit_hyperparameter (const char * name, double value, double hyperprior_epsilon = 1E-6)
bool mappel::cholesky (arma::mat & usym)
Parameters
usym An upper triangular symmetric matrix stored in a full matrix format. This matrix will be overwritten with the upper triangle and diagonal elements of the modified cholesky decomposition.
Returns
true if usym was positive semi-definite. If false then Usym is left in arbitrary corrupted state.
Definition at line 97 of file numerical.cpp.
Referenced by is_positive_definite(), mappel::TrustRegionMaximizer< Model >::solve_restricted_step_length_newton(), and mappel::TrustRegionMaximizer< Model >::solve_TR_subproblem().
void mappel::cholesky_convert_full_matrix (arma::mat & chol)
Convert matrix in internal cholesky format into a full matrix M = L*L'
Definition at line 82 of file numerical.cpp.
References copy_Usym_mat().
Referenced by cholesky_make_negative_definite(), cholesky_make_positive_definite(), and mappel::NewtonMaximizer< Model >::maximize().
void mappel::cholesky_convert_lower_triangular (arma::mat & chol)
Convert matrix in internal cholesky format into a lower triangular matrix L where M = L*L'
Definition at line 71 of file numerical.cpp.
Referenced by mappel::TrustRegionMaximizer< Model >::solve_restricted_step_length_newton().
void mappel::cholesky_make_negative_definite (arma::mat & m)
Modify m inplace using modfied choslesky decomposition to ensure m is negative definite
Definition at line 38 of file numerical.cpp.
References cholesky_convert_full_matrix(), and modified_cholesky().
Referenced by mappel::methods::objective::negative_definite_hessian().
void mappel::cholesky_make_positive_definite (arma::mat & m)
Modify m inplace using modfied choslesky decomposition to ensure m is positive definite
Definition at line 46 of file numerical.cpp.
References cholesky_convert_full_matrix(), and modified_cholesky().
arma::vec mappel::cholesky_solve (const arma::mat & C, const arma::vec & b)
Given a matrix in modified cholesky format and a vector solve the linear system C x = b.
Parameters
C A matrix in lower modified cholesky format
b A vector representing the right hand side of the linear system.
Returns
x - the solution to the linear system
Definition at line 184 of file numerical.cpp.
Referenced by mappel::NewtonMaximizer< Model >::maximize(), mappel::TrustRegionMaximizer< Model >::solve_restricted_step_length_newton(), and mappel::TrustRegionMaximizer< Model >::solve_TR_subproblem().
void mappel::copy_Lsym_mat (arma::mat & lsym)
Convert symmetric matrix stored as lower triangular to full Matrix Assuming lsym is the main diagonal and lower triangle of a symmertic matrix, fill in the upper triangle by copying the lowerr triangle. This operation modifies the matrix.
Definition at line 30 of file numerical.cpp.
void mappel::copy_Usym_mat (arma::mat & usym)
Convert symmetric matrix stored as upper triangular to full Matrix Assuming usym is the main diagonal and upper triangle of a symmertic matrix, fill in the lower triangle by copying the upper triangle. This operation modifies the matrix.
Definition at line 13 of file numerical.cpp.
Referenced by cholesky_convert_full_matrix(), and mappel::NewtonMaximizer< Model >::maximize().
void mappel::copy_Usym_mat_stack (arma::cube & usym_stack)
Definition at line 20 of file numerical.cpp.
template<class Model > void mappel::cr_lower_bound_stack (const Model & model, const typename Model::ParamVecT & theta_stack, typename Model::ParamVecT & crlb_stack)
Definition at line 304 of file stackcomp.h.
References mappel::methods::cr_lower_bound().
void mappel::enable_all_cpus ()
Definition at line 10 of file util.cpp.
double mappel::estimate_background (const MatT & im, const MatT & unit_model_im, double min_bg)
Definition at line 263 of file stencil.cpp.
double mappel::estimate_background (const CubeT & im, const CubeT & unit_model_im)
Definition at line 282 of file stencil.cpp.
void mappel::estimate_gaussian_2Dmax (const MatT & data, const VecT & Xstencil, const VecT & Ystencil, int max_pos[], double & min_val)
Definition at line 141 of file stencil.cpp.
References gaussian_convolution().
void mappel::estimate_gaussian_3Dmax (const CubeT & data, const VecFieldT & stencils, int max_pos[], double & min_val)
Definition at line 205 of file stencil.cpp.
References gaussian_3D_convolution().
double mappel::estimate_intensity (const MatT & im, const MatT & unit_model_im, double bg)
Definition at line 277 of file stencil.cpp.
double mappel::estimate_intensity (const CubeT & im, const CubeT & unit_model_im, double bg)
Definition at line 292 of file stencil.cpp.
void mappel::fill_d_stencil (int size, double stencil[], double theta_x) inline
Definition at line 151 of file stencil.h.
Referenced by make_d_stencil().
void mappel::fill_DX_stencil (int size, double stencil[], const double Gx[], double theta_sigma) inline
Definition at line 176 of file stencil.h.
Referenced by make_DX_stencil().
void mappel::fill_DXS2_stencil (int size, double stencil[], const double dx[], const double Gx[], const double DXS[], double theta_sigma) inline
Definition at line 190 of file stencil.h.
Referenced by make_DXS2_stencil().
void mappel::fill_DXS_stencil (int size, double stencil[], const double dx[], const double Gx[], double theta_sigma) inline
Definition at line 183 of file stencil.h.
References square().
Referenced by make_DXS_stencil().
void mappel::fill_DXSX_stencil (int size, double stencil[], const double dx[], const double Gx[], const double DX[], double theta_sigma) inline
Definition at line 203 of file stencil.h.
Referenced by make_DXSX_stencil().
void mappel::fill_G_stencil (int size, double stencil[], const double dx[], double theta_sigma) inline
Definition at line 157 of file stencil.h.
References square().
Referenced by make_G_stencil().
void mappel::fill_gaussian_stencil (int size, double stencil[], double sigma)
Definition at line 40 of file stencil.cpp.
References gauss_norm().
Referenced by make_gaussian_stencil().
void mappel::fill_X_stencil (int size, double stencil[], const double dx[], double theta_sigma) inline
Definition at line 164 of file stencil.h.
Referenced by make_X_stencil().
template<class Model > void mappel::fisher_information_stack (const Model & model, const typename Model::ParamVecT & theta_stack, CubeT & fisherI_stack)
Definition at line 315 of file stackcomp.h.
References fisher_information().
double mappel::gamma_prior_grad (double kappa, double mean, double v) inline
Definition at line 320 of file stencil.h.
Referenced by mappel::PriorMAP1DObjective::prior_grad_update().
double mappel::gamma_prior_grad2 (double kappa, double v) inline
Definition at line 356 of file stencil.h.
Referenced by mappel::PriorMAP1DObjective::prior_grad2_update(), and mappel::PriorMAP1DObjective::prior_hess_update().
double mappel::gauss_norm (double sigma) inline
Definition at line 92 of file stencil.h.
Referenced by fill_gaussian_stencil().
double mappel::gaussian_3D_convolution (int x, int y, int z, const CubeT & data, const VecFieldT & stencils)
Definition at line 184 of file stencil.cpp.
Referenced by estimate_gaussian_3Dmax(), and refine_gaussian_3Dmax().
double mappel::gaussian_convolution (int x, int y, const MatT & data, const VecT & Xstencil, const VecT & Ystencil)
Definition at line 127 of file stencil.cpp.
Referenced by estimate_gaussian_2Dmax(), and refine_gaussian_2Dmax().
template<class RngT > double mappel::generate_poisson (RngT & rng, double mu)
Definition at line 81 of file rng.h.
References generate_poisson_large(), and generate_poisson_small().
Referenced by mappel::methods::simulate_image(), simulate_image(), and mappel::methods::simulate_image_from_model().
template<class RngT > IdxT mappel::generate_poisson_large (RngT & rng, double mu)
Definition at line 57 of file rng.h.
Referenced by generate_poisson().
template<class RngT > IdxT mappel::generate_poisson_small (RngT & rng, double mu)
Genrates a single poisson disributed int from distribution with mean mu.
Parameters
mu - mean of poisson distribution
sfmt - A pointer to the SFMT rng state.
Knuth method circa 1969. Trasformed to work ing log space. This is linear in mu. Works ok for small counts.
Definition at line 43 of file rng.h.
Referenced by generate_poisson().
const char * mappel::icontains (const char * s, const char * pattern)
Definition at line 39 of file util.cpp.
bool mappel::is_negative_definite (const arma::mat & usym)
Determine if C is negative definite (i.e., -C is positive definite)
Parameters
usym A symmetric matrix in upper triangular format.
Returns
True if C is negative definite
Definition at line 52 of file numerical.cpp.
References is_positive_definite().
bool mappel::is_positive_definite (const arma::mat & usym)
Determine if C is positive definite
Parameters
usym A symmetric matrix in upper triangular format.
Returns
True if C is positive definite
Definition at line 57 of file numerical.cpp.
References cholesky().
Referenced by is_negative_definite(), and mappel::QuasiNewtonMaximizer< Model >::maximize().
bool mappel::is_symmetric (const arma::mat & A)
Check that full 2D matrix A is symmetric and can thus be treated as either upper or lower triangular symmetric representation. This will obviously not work with matricies that are already implicitly stored as symmetric triangular format since those matricies won't have the other triangle of elements filled in correctly.
Definition at line 63 of file numerical.cpp.
bool mappel::istarts_with (const char * s, const char * pattern)
Definition at line 21 of file util.cpp.
Referenced by mappel::Gauss1DsModel::make_default_prior(), mappel::Gauss2DModel::make_default_prior(), mappel::Gauss1DModel::make_default_prior(), mappel::Gauss2DsModel::make_default_prior(), mappel::methods::make_estimator(), and make_estimator().
bool mappel::istarts_with (const std::string & str, const char * pattern)
Definition at line 29 of file util.cpp.
const char* mappel::lambda_term_color (int size, int Lidx)
Definition at line 33 of file display.cpp.
References TERM_BLUE, TERM_CYAN, TERM_DIM_BLUE, TERM_DIM_CYAN, TERM_DIM_GREEN, TERM_DIM_MAGENTA, TERM_DIM_RED, TERM_DIM_WHITE, TERM_DIM_YELLOW, TERM_GREEN, TERM_MAGENTA, TERM_RED, TERM_WHITE, and TERM_YELLOW.
Referenced by print_image().
template<class Model > void mappel::log_likelihood_stack (const Model & model, const typename Model::ImageT & image, const typename Model::ParamVecT & theta_stack, VecT & llh_stack)
Parallel log_likelihood calculations for a single image.
Compute log-likelihood for multiple thetas using the same image
Use: model.make_param_stack() to make a parameter stack of appropriate dimensions for the model
Template Parameters
Model A concrete subclass of PointEmitterModel
Parameters
[in] model A PointEmitterModel object.
[in] image An image.
[in] theta_stack Sequence of thetas. Size: [model.num_params, nThetas]
[out] llh_stack Sequence of llh values computed.
Definition at line 128 of file stackcomp.h.
References mappel::methods::objective::openmp::llh_stack(), and log_likelihood().
template<class Model > void mappel::log_likelihood_stack (const Model & model, const typename Model::ImageStackT & image_stack, const typename Model::ParamVecT & theta_stack, VecT & llh_stack)
Parallel log_likelihood calculations for a stack of images.
Compute log-likelihood for multiple image, theta pairs.
Use: model.make_param_stack() to make a parameter stack of appropriate dimensions for the model
Template Parameters
Model A concrete subclass of PointEmitterModel
Parameters
[in] model A PointEmitterModel object.
[in] image_stack Sequence of images.
[in] theta_stack Sequence of thetas. Size: [model.num_params, nThetas]
[out] llh_stack Sequence of llh values computed. Size: [n]
Definition at line 151 of file stackcomp.h.
References mappel::methods::objective::openmp::llh_stack(), and log_likelihood().
double mappel::log_prior_beta2_const (double beta0, double beta1) inline
Definition at line 248 of file stencil.h.
double mappel::log_prior_beta_const (double beta) inline
Definition at line 242 of file stencil.h.
double mappel::log_prior_gamma_const (double kappa, double mean) inline
Definition at line 255 of file stencil.h.
double mappel::log_prior_normal_const (double sigma) inline
Definition at line 267 of file stencil.h.
double mappel::log_prior_pareto_const (double alpha, double min) inline
Definition at line 261 of file stencil.h.
VecT mappel::make_d_stencil (int size, double theta_x) inline
Definition at line 97 of file stencil.h.
References fill_d_stencil().
Referenced by mappel::Gauss1DsModel::Stencil::Stencil(), mappel::Gauss2DModel::Stencil::Stencil(), mappel::Gauss1DModel::Stencil::Stencil(), and mappel::Gauss2DsModel::Stencil::Stencil().
VecT mappel::make_DX_stencil (int size, const VecT & Gx, double theta_sigma) inline
Definition at line 118 of file stencil.h.
References fill_DX_stencil().
Referenced by mappel::Gauss1DsModel::Stencil::compute_derivatives(), mappel::Gauss2DModel::Stencil::compute_derivatives(), mappel::Gauss1DModel::Stencil::compute_derivatives(), and mappel::Gauss2DsModel::Stencil::compute_derivatives().
VecT mappel::make_DXS2_stencil (int size, const VecT & dx, const VecT & Gx, const VecT & DXS, double theta_sigma) inline
Definition at line 133 of file stencil.h.
References fill_DXS2_stencil().
Referenced by mappel::Gauss1DsModel::Stencil::compute_derivatives(), and mappel::Gauss2DsModel::Stencil::compute_derivatives().
VecT mappel::make_DXS_stencil (int size, const VecT & dx, const VecT & Gx, double theta_sigma) inline
Definition at line 125 of file stencil.h.
References fill_DXS_stencil().
Referenced by mappel::Gauss1DsModel::Stencil::compute_derivatives(), mappel::Gauss2DModel::Stencil::compute_derivatives(), mappel::Gauss1DModel::Stencil::compute_derivatives(), and mappel::Gauss2DsModel::Stencil::compute_derivatives().
VecT mappel::make_DXSX_stencil (int size, const VecT & dx, const VecT & Gx, const VecT & DX, double theta_sigma) inline
Definition at line 141 of file stencil.h.
References fill_DXSX_stencil().
Referenced by mappel::Gauss1DsModel::Stencil::compute_derivatives(), and mappel::Gauss2DsModel::Stencil::compute_derivatives().
VecT mappel::make_G_stencil (int size, const VecT & dx, double theta_sigma) inline
Definition at line 104 of file stencil.h.
References fill_G_stencil().
Referenced by mappel::Gauss1DsModel::Stencil::compute_derivatives(), mappel::Gauss2DModel::Stencil::compute_derivatives(), mappel::Gauss1DModel::Stencil::compute_derivatives(), and mappel::Gauss2DsModel::Stencil::compute_derivatives().
VecT mappel::make_gaussian_stencil (int size, double sigma) inline
Definition at line 216 of file stencil.h.
References fill_gaussian_stencil().
template<typename T , typename... Args> std::unique_ptr<T> mappel::make_unique (Args &&... args)
Definition at line 130 of file util.h.
References operator<<().
VecT mappel::make_X_stencil (int size, const VecT & dx, double theta_sigma) inline
Definition at line 111 of file stencil.h.
References fill_X_stencil().
Referenced by mappel::Gauss1DsModel::Stencil::Stencil(), mappel::Gauss2DModel::Stencil::Stencil(), mappel::Gauss1DModel::Stencil::Stencil(), and mappel::Gauss2DsModel::Stencil::Stencil().
int mappel::maxidx (const VecT & v)
Definition at line 55 of file util.cpp.
template<class Model > void mappel::model_grad_stack (const Model & model, const typename Model::ImageStackT & image_stack, const typename Model::ParamVecT & theta_stack, typename Model::ParamVecT & grad_stack)
Parallel model gradient calculations for a stack of images.
Compute gradient of log-likelihood for multiple image, theta pairs.
Use: model.make_param_stack() to make a parameter stack of appropriate dimensions for the model gradients.
Template Parameters
Model A concrete subclass of PointEmitterModel
Parameters
[in] model A PointEmitterModel object.
[in] image_stack Sequence of images.
[in] theta_stack Sequence of thetas.
[out] grad_stack Sequence of grad vectors values computed. Size: [model.num_params, n]
Definition at line 188 of file stackcomp.h.
References mappel::methods::objective::grad(), and model_grad().
template<class Model > void mappel::model_hessian_stack (const Model & model, const typename Model::ImageStackT & image_stack, const typename Model::ParamVecT & theta_stack, CubeT & hessian_stack)
Parallel model Hessian calculations for a stack of images.
Compute Hessian of log-likelihood for multiple image, theta pairs.
Use: model.make_param_mat_stack() to make a parameter matrix stack of appropriate dimensions for the model Hessian.
Template Parameters
Model A concrete subclass of PointEmitterModel
Parameters
[in] model A PointEmitterModel object.
[in] image_stack Sequence of images.
[in] theta_stack Sequence of thetas. Size: [model.num_params, nThetas]
[out] hess_stack Sequence of Hessian matrices computed. Size: [model.num_params, model.num_params, n]
Definition at line 231 of file stackcomp.h.
References mappel::methods::objective::grad(), and model_hessian().
template<class Model > void mappel::model_image_stack (const Model & model, const typename Model::ParamVecT & theta_stack, typename Model::ImageStackT & image_stack)
Parallel computation of the model image.
The model image is the expected photon count at each pixel under parameter theta.
Use: model.make_param_stack() to make a parameter stack of appropriate dimensions for the model Use: model.make_image_stack() to make an image stack of appropriate dimensions for the model
Template Parameters
Model A concrete subclass of PointEmitterModel
Parameters
[in] model A PointEmitterModel object.
[in] theta_stack Sequence of thetas for which to generate images. Size: [model.num_params, nThetas]
[out] image_stack Sequence of model images generated.
Definition at line 62 of file stackcomp.h.
References model_image().
template<class Model > void mappel::model_positive_hessian_stack (const Model & model, const typename Model::ImageStackT & image_stack, const typename Model::ParamVecT & theta_stack, CubeT & hessian_stack)
Parallel model positive-definite Hessian approximation calculations for a stack of images.
Compute Hessian a positive-definite Hessian using a modified cholesky decompositions. Computes for multiple image, theta pairs.
Use: model.make_param_mat_stack() to make a parameter matrix stack of appropriate dimensions for the model Hessian.
Template Parameters
Model A concrete subclass of PointEmitterModel
Parameters
[in] model A PointEmitterModel object.
[in] image_stack Sequence of images.
[in] theta_stack Sequence of thetas. Size: [model.num_params, nThetas]
[out] hess_stack Sequence of approximate Hessian matrices computed. Size: [model.num_params, model.num_params, n]
Definition at line 276 of file stackcomp.h.
bool mappel::modified_cholesky (arma::mat & usym)
Parameters
usym An upper triangular symmetric matrix stored in a full matrix format. This matrix will be overwritten with the upper triangle and diagonal elements of the modified cholesky decomposition.
Returns
true if usym was positive semi-definite (no cholesky modification required). If false we made a modification
Definition at line 127 of file numerical.cpp.
Referenced by cholesky_make_negative_definite(), cholesky_make_positive_definite(), and mappel::NewtonMaximizer< Model >::maximize().
double mappel::normal_prior_grad (double mu, double sigma)
double mappel::normal_prior_grad (double sigma)
double mappel::normal_prior_grad (double mu, double sigma, double v) inline
Definition at line 332 of file stencil.h.
double mappel::normal_prior_grad2 (double sigma) inline
Definition at line 368 of file stencil.h.
double mappel::normal_quantile_onesided (double confidence)
Definition at line 29 of file stencil.cpp.
double mappel::normal_quantile_twosided (double confidence)
Definition at line 18 of file stencil.cpp.
Referenced by mappel::methods::error_bounds_expected(), mappel::methods::openmp::error_bounds_expected_stack(), and mappel::methods::error_bounds_observed().
std::ostream & mappel::operator<< (std::ostream & out, const StatsT & stats)
Definition at line 68 of file util.cpp.
template<class Model , typename = EnableIfSubclassT<Model,PointEmitterModel>> std::ostream & mappel::operator<< (std::ostream & out, const Model & model)
Definition at line 276 of file PointEmitterModel.h.
std::ostream& mappel::operator<< (std::ostream & out, const Gauss1DModel::Stencil & s)
Definition at line 164 of file Gauss1DModel.cpp.
References mappel::Gauss1DModel::Stencil::derivatives_computed, mappel::Gauss1DModel::Stencil::dx, mappel::Gauss1DModel::Stencil::DX, mappel::Gauss1DModel::Stencil::DXS, mappel::Gauss1DModel::Stencil::Gx, print_vec_row(), TERM_BLUE, TERM_CYAN, TERM_WHITE, mappel::Gauss1DModel::Stencil::theta, and mappel::Gauss1DModel::Stencil::X.
Referenced by make_unique().
std::ostream& mappel::operator<< (std::ostream & out, const Gauss1DsModel::Stencil & s)
Definition at line 182 of file Gauss1DsModel.cpp.
References mappel::Gauss1DsModel::Stencil::derivatives_computed, mappel::Gauss1DsModel::Stencil::dx, mappel::Gauss1DsModel::Stencil::DX, mappel::Gauss1DsModel::Stencil::DXS, mappel::Gauss1DsModel::Stencil::DXS2, mappel::Gauss1DsModel::Stencil::DXSX, mappel::Gauss1DsModel::Stencil::Gx, print_vec_row(), TERM_BLUE, TERM_CYAN, TERM_WHITE, mappel::Gauss1DsModel::Stencil::theta, and mappel::Gauss1DsModel::Stencil::X.
template<class Model > std::ostream& mappel::operator<< (std::ostream & out, Estimator< Model > & estimator)
Definition at line 226 of file estimator_impl.h.
std::ostream& mappel::operator<< (std::ostream & out, const Gauss2DModel::Stencil & s)
Definition at line 249 of file Gauss2DModel.cpp.
References mappel::Gauss2DModel::Stencil::derivatives_computed, mappel::Gauss2DModel::Stencil::dx, mappel::Gauss2DModel::Stencil::DX, mappel::Gauss2DModel::Stencil::DXS, mappel::Gauss2DModel::Stencil::dy, mappel::Gauss2DModel::Stencil::DY, mappel::Gauss2DModel::Stencil::DYS, mappel::Gauss2DModel::Stencil::Gx, mappel::Gauss2DModel::Stencil::Gy, print_vec_row(), TERM_BLUE, TERM_CYAN, TERM_WHITE, mappel::Gauss2DModel::Stencil::theta, mappel::Gauss2DModel::Stencil::X, and mappel::Gauss2DModel::Stencil::Y.
std::ostream& mappel::operator<< (std::ostream & out, const Gauss2DsModel::Stencil & s)
Definition at line 318 of file Gauss2DsModel.cpp.
References mappel::Gauss2DsModel::Stencil::derivatives_computed, mappel::Gauss2DsModel::Stencil::dx, mappel::Gauss2DsModel::Stencil::DX, mappel::Gauss2DsModel::Stencil::DXS, mappel::Gauss2DsModel::Stencil::DXS2, mappel::Gauss2DsModel::Stencil::DXSX, mappel::Gauss2DsModel::Stencil::dy, mappel::Gauss2DsModel::Stencil::DY, mappel::Gauss2DsModel::Stencil::DYS, mappel::Gauss2DsModel::Stencil::DYS2, mappel::Gauss2DsModel::Stencil::DYSY, mappel::Gauss2DsModel::Stencil::Gx, mappel::Gauss2DsModel::Stencil::Gy, print_vec_row(), TERM_BLUE, TERM_CYAN, TERM_WHITE, mappel::Gauss2DsModel::Stencil::theta, mappel::Gauss2DsModel::Stencil::X, and mappel::Gauss2DsModel::Stencil::Y.
double mappel::pareto_prior_grad (double alpha, double v) inline
Definition at line 326 of file stencil.h.
double mappel::pareto_prior_grad2 (double alpha, double v) inline
Definition at line 362 of file stencil.h.
double mappel::poisson_log_likelihood (double model_val, double data_val) inline
Definition at line 224 of file stencil.h.
Referenced by mappel::methods::likelihood::llh(), mappel::methods::likelihood::debug::llh_components(), and log_likelihood().
ostream& mappel::print_centered_title (ostream & out, char fill, int width, const char * title = nullptr)
Definition at line 83 of file display.cpp.
Referenced by print_image(), and print_labeled_image().
template<class ImageT > std::ostream& mappel::print_image (std::ostream & out, const ImageT & im)
template<> std::ostream& mappel::print_image (std::ostream & out, const arma::vec & im)
Definition at line 139 of file display.cpp.
References print_labeled_image().
Referenced by mappel::Estimator< Model >::compute_estimate_debug(), mappel::IterativeMaximizer< Model >::compute_estimate_debug(), mappel::Estimator< Model >::estimate_max(), mappel::ThreadedEstimator< Model >::estimate_max_stack(), and mappel::ThreadedEstimator< Model >::estimate_profile_stack().
template<> std::ostream& mappel::print_image (std::ostream & out, const arma::mat & im)
Definition at line 147 of file display.cpp.
References print_labeled_image().
template<> std::ostream& mappel::print_image (std::ostream & out, const arma::cube & im)
Definition at line 154 of file display.cpp.
References lambda_term_color(), print_centered_title(), and print_labeled_image().
ostream& mappel::print_labeled_image (ostream & out, const arma::mat & im, const char * title, const char * color)
Definition at line 95 of file display.cpp.
References print_centered_title().
Referenced by print_image().
template<class Vec > std::ostream& mappel::print_vec_row (std::ostream & out, const Vec & vec, const char * header, int header_width, const char * color = nullptr)
Definition at line 42 of file display.h.
Referenced by operator<<().
void mappel::refine_gaussian_2Dmax (const MatT & data, const VecT & Xstencil, const VecT & Ystencil, int max_pos[])
Definition at line 157 of file stencil.cpp.
References gaussian_convolution().
void mappel::refine_gaussian_3Dmax (const CubeT & data, const VecFieldT & stencils, int max_pos[])
Definition at line 225 of file stencil.cpp.
References gaussian_3D_convolution().
double mappel::relative_poisson_log_likelihood (double model_val, double data_val) inline
Definition at line 233 of file stencil.h.
Referenced by relative_log_likelihood(), mappel::methods::likelihood::rllh(), and mappel::methods::likelihood::debug::rllh_components().
double mappel::restrict_value_range (double val, double minval, double maxval) inline
Definition at line 123 of file util.h.
double mappel::rllh_beta2_prior (double beta0, double beta1, double v, double max = 1., double min = 0.) inline
Definition at line 280 of file stencil.h.
double mappel::rllh_beta_prior (double beta, double v, double max = 1., double min = 0.) inline
Definition at line 273 of file stencil.h.
Referenced by mappel::PriorMAP1DObjective::prior_relative_log_likelihood().
double mappel::rllh_gamma_prior (double kappa, double mean, double v) inline
Definition at line 287 of file stencil.h.
Referenced by mappel::PriorMAP1DObjective::prior_relative_log_likelihood().
double mappel::rllh_normal_prior (double mu, double sigma)
double mappel::rllh_normal_prior (double mu, double sigma, double v) inline
Definition at line 299 of file stencil.h.
double mappel::rllh_pareto_prior (double alpha, double v) inline
Definition at line 293 of file stencil.h.
template<class Model > void mappel::sample_prior_stack (Model & model, typename Model::ParamVecT & theta_stack)
Parallel sampling of the model prior.
Use: model.make_param_stack() to make a parameter stack of appropriate dimensions for the model
Template Parameters
Model A concrete subclass of PointEmitterModel
Parameters
[in] model,A PointEmitterModel object.
[out] theta_stack,A sequence of sampled thetas. Size: [model.num_params, nSamples]
Definition at line 36 of file stackcomp.h.
References rng_manager.
template<typename T > int mappel::sgn (T val)
sign (signum) function: -1/0/1
Definition at line 116 of file util.h.
Referenced by mappel::TrustRegionMaximizer< Model >::compute_bound_scaling_vec().
template<class Model > void mappel::simulate_image_stack (const Model & model, const typename Model::ParamVecT & theta_stack, typename Model::ImageStackT & image_stack)
Parallel simulation of images from one or more theta.
This accepts either a single theta and a stack of images, or a stack of thetas and a stack of images.
Use: model.make_param_stack() to make a parameter stack of appropriate dimensions for the model Use: model.make_image_stack() to make an image stack of appropriate dimensions for the model
Template Parameters
Model A concrete subclass of PointEmitterModel
Parameters
[in] model A PointEmitterModel object.
[in] theta_stack Single theta or a sequence of thetas. Size: [model.num_params, nThetas]
[out] image_stack Sequence of model images generated.
Definition at line 87 of file stackcomp.h.
References model_image(), rng_manager, mappel::methods::simulate_image(), and mappel::methods::simulate_image_from_model().
template<typename T > T mappel::square (T x)
Definition at line 121 of file util.h.
Referenced by fill_DXS_stencil(), and fill_G_stencil().
Variable Documentation
ParallelRngManagerT mappel::rng_manager
Definition at line 6 of file rng.cpp.
Referenced by mappel::PointEmitterModel::get_rng_generator(), mappel::PointEmitterModel::get_rng_manager(), mappel::PointEmitterModel::get_stats(), mappel::MCMCAdaptor2Ds::sample_mcmc_candidate(), mappel::MCMCAdaptor2D::sample_mcmc_candidate(), mappel::MCMCAdaptor1Ds::sample_mcmc_candidate(), mappel::MCMCAdaptor1D::sample_mcmc_candidate(), mappel::PointEmitterModel::sample_prior(), sample_prior_stack(), mappel::PointEmitterModel::set_rng_seed(), and simulate_image_stack().
const char * mappel::TERM_BLACK ="1;30"
Definition at line 13 of file display.cpp.
const char * mappel::TERM_BLUE ="1;34"
Definition at line 17 of file display.cpp.
Referenced by lambda_term_color(), and operator<<().
const char * mappel::TERM_CYAN ="1;36"
Definition at line 19 of file display.cpp.
Referenced by lambda_term_color(), and operator<<().
const char * mappel::TERM_DIM_BLACK ="0;30"
Definition at line 21 of file display.cpp.
const char * mappel::TERM_DIM_BLUE ="0;34"
Definition at line 25 of file display.cpp.
Referenced by lambda_term_color().
const char * mappel::TERM_DIM_CYAN ="0;36"
Definition at line 27 of file display.cpp.
Referenced by lambda_term_color().
const char * mappel::TERM_DIM_GREEN ="0;32"
Definition at line 23 of file display.cpp.
Referenced by lambda_term_color().
const char * mappel::TERM_DIM_MAGENTA ="0;35"
Definition at line 26 of file display.cpp.
Referenced by lambda_term_color().
const char * mappel::TERM_DIM_RED ="0;31"
Definition at line 22 of file display.cpp.
Referenced by lambda_term_color().
const char * mappel::TERM_DIM_WHITE ="0;37"
Definition at line 28 of file display.cpp.
Referenced by lambda_term_color().
const char * mappel::TERM_DIM_YELLOW ="0;33"
Definition at line 24 of file display.cpp.
Referenced by lambda_term_color().
const char * mappel::TERM_GREEN ="1;32"
Definition at line 15 of file display.cpp.
Referenced by lambda_term_color().
const char * mappel::TERM_MAGENTA ="1;35"
Definition at line 18 of file display.cpp.
Referenced by lambda_term_color().
const char * mappel::TERM_RED ="1;31"
Definition at line 14 of file display.cpp.
Referenced by lambda_term_color().
const char * mappel::TERM_WHITE ="1;37"
Definition at line 20 of file display.cpp.
Referenced by lambda_term_color(), and operator<<().
const char * mappel::TERM_YELLOW ="1;33"
Definition at line 16 of file display.cpp.
Referenced by lambda_term_color().