Mappel: mappel::methods::objective Namespace Reference
mappel::methods::objective Namespace Reference
Namespaces
debug
openmp
Functions
template<class Model >
ReturnIfSubclassT< double, Model, MAPEstimator > llh (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< double, Model, MAPEstimator > rllh (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< ParamT< Model >, Model, MAPEstimator > grad (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< void, Model, MAPEstimator > grad2 (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s, ParamT< Model > &grad, ParamT< Model > &grad2)
template<class Model >
ReturnIfSubclassT< void, Model, MAPEstimator > hessian (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s, ParamT< Model > &grad, MatT &hess)
template<class Model >
ReturnIfSubclassT< double, Model, MLEstimator > llh (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< double, Model, MLEstimator > rllh (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< ParamT< Model >, Model, MLEstimator > grad (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
ReturnIfSubclassT< void, Model, MLEstimator > grad2 (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s, ParamT< Model > &grad, ParamT< Model > &grad2)
template<class Model >
ReturnIfSubclassT< void, Model, MLEstimator > hessian (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s, ParamT< Model > &grad, MatT &hess)
template<class Model >
double llh (const Model &model, const ModelDataT< Model > &data_im, const ParamT< Model > &theta)
template<class Model >
double rllh (const Model &model, const ModelDataT< Model > &data_im, const ParamT< Model > &theta)
template<class Model >
ParamT< Model > grad (const Model &model, const ModelDataT< Model > &data_im, const ParamT< Model > &theta)
template<class Model >
ParamT< Model > grad2 (const Model &model, const ModelDataT< Model > &data_im, const ParamT< Model > &theta)
template<class Model >
void grad2 (const Model &model, const ModelDataT< Model > &data_im, const ParamT< Model > &theta, ParamT< Model > &grad_val, ParamT< Model > &grad2_val)
template<class Model >
MatT hessian (const Model &model, const ModelDataT< Model > &data_im, const ParamT< Model > &theta)
template<class Model >
MatT hessian (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
void hessian (const Model &model, const ModelDataT< Model > &data_im, const ParamT< Model > &theta, ParamT< Model > &grad, MatT &hess)
template<class Model >
void hessian (const Model &model, const ModelDataT< Model > &data_im, const ParamT< Model > &theta, MatT &hess)
template<class Model >
MatT negative_definite_hessian (const Model &model, const ModelDataT< Model > &data_im, const ParamT< Model > &theta)
template<class Model >
MatT negative_definite_hessian (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s)
template<class Model >
void negative_definite_hessian (const Model &model, const ModelDataT< Model > &data_im, const ParamT< Model > &theta, ParamT< Model > &grad, MatT &hess)
template<class Model >
void negative_definite_hessian (const Model &model, const ModelDataT< Model > &data_im, const StencilT< Model > &s, ParamT< Model > &grad, MatT &hess)
Function Documentation
template<class Model > ReturnIfSubclassT<ParamT<Model>, Model,MLEstimator> mappel::methods::objective::grad (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 51 of file MLEstimator.h.
template<class Model > ReturnIfSubclassT<ParamT<Model>,Model,MAPEstimator> mappel::methods::objective::grad (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 55 of file MAPEstimator.h.
Referenced by mappel::methods::aposteriori_objective(), grad(), mappel::methods::objective::openmp::grad_stack(), hessian(), mappel::methods::likelihood_objective(), mappel::QuasiNewtonMaximizer< Model >::maximize(), mappel::model_grad_stack(), mappel::model_hessian_stack(), mappel::TrustRegionMaximizer< Model >::name(), negative_definite_hessian(), mappel::PriorMAP1DObjective::prior_grad_update(), and mappel::PriorMAP1DObjective::set_hyperparameters().
template<class Model > ParamT< Model > mappel::methods::objective::grad (const Model & model, const ModelDataT< Model > & data_im, const ParamT< Model > & theta)
Definition at line 66 of file model_methods_impl.h.
References grad().
template<class Model > ReturnIfSubclassT<void,Model,MLEstimator> mappel::methods::objective::grad2 (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s, ParamT< Model > & grad, ParamT< Model > & grad2)
Definition at line 58 of file MLEstimator.h.
template<class Model > ReturnIfSubclassT<void,Model,MAPEstimator> mappel::methods::objective::grad2 (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s, ParamT< Model > & grad, ParamT< Model > & grad2)
Definition at line 64 of file MAPEstimator.h.
Referenced by grad2(), mappel::NewtonDiagonalMaximizer< Model >::maximize(), mappel::TrustRegionMaximizer< Model >::name(), mappel::PriorMAP1DObjective::prior_grad2_update(), and mappel::PriorMAP1DObjective::set_hyperparameters().
template<class Model > ParamT< Model > mappel::methods::objective::grad2 (const Model & model, const ModelDataT< Model > & data_im, const ParamT< Model > & theta)
Definition at line 78 of file model_methods_impl.h.
References grad2().
template<class Model > void mappel::methods::objective::grad2 (const Model & model, const ModelDataT< Model > & data_im, const ParamT< Model > & theta, ParamT< Model > & grad_val, ParamT< Model > & grad2_val)
Definition at line 93 of file model_methods_impl.h.
References grad2().
template<class Model > ReturnIfSubclassT<void,Model,MLEstimator> mappel::methods::objective::hessian (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s, ParamT< Model > & grad, MatT & hess)
Definition at line 65 of file MLEstimator.h.
template<class Model > ReturnIfSubclassT<void,Model,MAPEstimator> mappel::methods::objective::hessian (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s, ParamT< Model > & grad, MatT & hess)
Definition at line 72 of file MAPEstimator.h.
Referenced by hessian(), mappel::methods::objective::openmp::hessian_stack(), mappel::NewtonMaximizer< Model >::maximize(), mappel::QuasiNewtonMaximizer< Model >::maximize(), mappel::TrustRegionMaximizer< Model >::maximize(), negative_definite_hessian(), and mappel::methods::observed_information().
template<class Model > MatT mappel::methods::objective::hessian (const Model & model, const ModelDataT< Model > & data_im, const ParamT< Model > & theta)
Definition at line 101 of file model_methods_impl.h.
References hessian().
template<class Model > MatT mappel::methods::objective::hessian (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 113 of file model_methods_impl.h.
References grad(), and hessian().
template<class Model > void mappel::methods::objective::hessian (const Model & model, const ModelDataT< Model > & data_im, const ParamT< Model > & theta, ParamT< Model > & grad, MatT & hess)
Definition at line 123 of file model_methods_impl.h.
References grad(), and hessian().
template<class Model > void mappel::methods::objective::hessian (const Model & model, const ModelDataT< Model > & data_im, const ParamT< Model > & theta, MatT & hess)
Definition at line 135 of file model_methods_impl.h.
References grad(), and hessian().
template<class Model > ReturnIfSubclassT<double,Model,MAPEstimator> mappel::methods::objective::llh (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 36 of file MAPEstimator.h.
Referenced by llh(), mappel::methods::objective::openmp::llh_stack(), and log_likelihood().
template<class Model > ReturnIfSubclassT<double,Model,MLEstimator> mappel::methods::objective::llh (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 37 of file MLEstimator.h.
template<class Model > double mappel::methods::objective::llh (const Model & model, const ModelDataT< Model > & data_im, const ParamT< Model > & theta)
Definition at line 50 of file model_methods_impl.h.
References llh().
template<class Model > MatT mappel::methods::objective::negative_definite_hessian (const Model & model, const ModelDataT< Model > & data_im, const ParamT< Model > & theta)
Definition at line 143 of file model_methods_impl.h.
Referenced by negative_definite_hessian(), and mappel::methods::objective::openmp::negative_definite_hessian_stack().
template<class Model > MatT mappel::methods::objective::negative_definite_hessian (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 155 of file model_methods_impl.h.
References grad(), and negative_definite_hessian().
template<class Model > void mappel::methods::objective::negative_definite_hessian (const Model & model, const ModelDataT< Model > & data_im, const ParamT< Model > & theta, ParamT< Model > & grad, MatT & hess)
Definition at line 165 of file model_methods_impl.h.
References grad(), and negative_definite_hessian().
template<class Model > void mappel::methods::objective::negative_definite_hessian (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s, ParamT< Model > & grad, MatT & hess)
Definition at line 178 of file model_methods_impl.h.
References mappel::cholesky_make_negative_definite(), and hessian().
template<class Model > ReturnIfSubclassT<double,Model,MLEstimator> mappel::methods::objective::rllh (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 44 of file MLEstimator.h.
template<class Model > ReturnIfSubclassT<double,Model,MAPEstimator> mappel::methods::objective::rllh (const Model & model, const ModelDataT< Model > & data_im, const StencilT< Model > & s)
Definition at line 48 of file MAPEstimator.h.
Referenced by mappel::SimulatedAnnealingMaximizer< Model >::anneal(), mappel::methods::aposteriori_objective(), mappel::IterativeMaximizer< Model >::backtrack(), mappel::ThreadedEstimator< Model >::clear_stats(), mappel::CGaussMLE< Model >::compute_estimate(), mappel::Estimator< Model >::estimate_max(), mappel::Estimator< Model >::estimate_max_debug(), mappel::methods::likelihood_objective(), mappel::TrustRegionMaximizer< Model >::maximize(), mappel::HeuristicEstimator< Model >::name(), mappel::CGaussHeuristicEstimator< Model >::name(), mappel::CGaussMLE< Model >::name(), mappel::PriorMAP1DObjective::prior_log_likelihood(), relative_log_likelihood(), rllh(), mappel::methods::objective::openmp::rllh_stack(), mappel::mcmc::sample_posterior(), mappel::mcmc::sample_posterior_debug(), mappel::SimulatedAnnealingMaximizer< Model >::SimulatedAnnealingMaximizer(), and mappel::Estimator< Model >::~Estimator().
template<class Model > double mappel::methods::objective::rllh (const Model & model, const ModelDataT< Model > & data_im, const ParamT< Model > & theta)
Definition at line 58 of file model_methods_impl.h.
References rllh().