Mappel: PoissonGaussianNoise2DObjective.h File Reference
PoissonGaussianNoise2DObjective.h File Reference
The class declaration and inline and templated functions for PoissonGaussianNoise2DObjective.
#include "Mappel/PoissonNoise2D.h"
Classes
class PoissonGaussianNoise2DObjective< ModelBase >
A Base type for point emitter localization models that use 2d images.
Functions
template<class Model >
std::enable_if< std::is_base_of< PoissonGaussianNoise2DObjective, Model >::value, typename Model::ImageT >::type model_image (const Model &model, const typename Model::Stencil &s)
template<class Model , class rng_t >
std::enable_if< std::is_base_of< PoissonGaussianNoise2DObjective, Model >::value, typename Model::ImageT >::type simulate_image (const Model &model, const typename Model::Stencil &s, rng_t &rng)
Simulate an image using the PSF model, by generating Poisson noise.
template<class Model , class rng_t >
std::enable_if< std::is_base_of< PoissonGaussianNoise2DObjective, Model >::value, typename Model::ImageT >::type simulate_image (const Model &model, const typename Model::ImageT &model_im, rng_t &rng)
template<class Model >
std::enable_if< std::is_base_of< PoissonGaussianNoise2DObjective, Model >::value >::type model_grad (const Model &model, const typename Model::ImageT &im, const typename Model::Stencil &s, typename Model::ParamT &grad)
template<class Model >
std::enable_if< std::is_base_of< PoissonGaussianNoise2DObjective, Model >::value >::type model_grad2 (const Model &model, const typename Model::ImageT &im, const typename Model::Stencil &s, typename Model::ParamT &grad, typename Model::ParamT &grad2)
template<class Model >
std::enable_if< std::is_base_of< PoissonGaussianNoise2DObjective, Model >::value >::type model_hessian (const Model &model, const typename Model::ImageT &im, const typename Model::Stencil &s, typename Model::ParamT &grad, typename Model::MatT &hess)
template<class Model >
std::enable_if< std::is_base_of< PoissonGaussianNoise2DObjective, Model >::value, double >::type log_likelihood (const Model &model, const typename Model::ImageT &data_im, const typename Model::Stencil &s)
template<class Model >
std::enable_if< std::is_base_of< PoissonGaussianNoise2DObjective, Model >::value, double >::type relative_log_likelihood (const Model &model, const typename Model::ImageT &data_im, const typename Model::Stencil &s)
template<class Model >
std::enable_if< std::is_base_of< PoissonGaussianNoise2DObjective, Model >::value, typename Model::MatT >::type fisher_information (const Model &model, const typename Model::Stencil &s)
template<class Model >
std::enable_if< std::is_base_of< PoissonGaussianNoise2DObjective, Model >::value, std::shared_ptr< Estimator< Model > > >::type make_estimator (const Model &model, std::string ename)
Detailed Description
The class declaration and inline and templated functions for PoissonGaussianNoise2DObjective.
Author
Mark J. Olah (mjo@cs.unm DOT edu)
Date
04-2017
Definition in file PoissonGaussianNoise2DObjective.h.
Function Documentation
template<class Model > std::enable_if<std::is_base_of<PoissonGaussianNoise2DObjective,Model>::value,typename Model::MatT>::type fisher_information (const Model & model, const typename Model::Stencil & s)
Definition at line 200 of file PoissonGaussianNoise2DObjective.h.
Referenced by mappel::fisher_information_stack().
template<class Model > std::enable_if<std::is_base_of<PoissonGaussianNoise2DObjective,Model>::value,double>::type log_likelihood (const Model & model, const typename Model::ImageT & data_im, const typename Model::Stencil & s)
Definition at line 172 of file PoissonGaussianNoise2DObjective.h.
References mappel::methods::objective::llh(), and mappel::poisson_log_likelihood().
Referenced by mappel::log_likelihood_stack().
template<class Model > std::enable_if<std::is_base_of<PoissonGaussianNoise2DObjective,Model>::value,std::shared_ptr<Estimator<Model> > >::type make_estimator (const Model & model, std::string ename)
Definition at line 217 of file PoissonGaussianNoise2DObjective.h.
References mappel::istarts_with().
template<class Model > std::enable_if<std::is_base_of<PoissonGaussianNoise2DObjective,Model>::value>::type model_grad (const Model & model, const typename Model::ImageT & im, const typename Model::Stencil & s, typename Model::ParamT & grad)
Definition at line 101 of file PoissonGaussianNoise2DObjective.h.
Referenced by mappel::model_grad_stack().
template<class Model > std::enable_if<std::is_base_of<PoissonGaussianNoise2DObjective,Model>::value>::type model_grad2 (const Model & model, const typename Model::ImageT & im, const typename Model::Stencil & s, typename Model::ParamT & grad, typename Model::ParamT & grad2)
Definition at line 119 of file PoissonGaussianNoise2DObjective.h.
template<class Model > std::enable_if<std::is_base_of<PoissonGaussianNoise2DObjective,Model>::value>::type model_hessian (const Model & model, const typename Model::ImageT & im, const typename Model::Stencil & s, typename Model::ParamT & grad, typename Model::MatT & hess)
Definition at line 148 of file PoissonGaussianNoise2DObjective.h.
Referenced by mappel::model_hessian_stack().
template<class Model > std::enable_if<std::is_base_of<PoissonGaussianNoise2DObjective,Model>::value,typename Model::ImageT>::type model_image (const Model & model, const typename Model::Stencil & s)
Definition at line 59 of file PoissonGaussianNoise2DObjective.h.
Referenced by mappel::model_image_stack(), and mappel::simulate_image_stack().
template<class Model > std::enable_if<std::is_base_of<PoissonGaussianNoise2DObjective,Model>::value,double>::type relative_log_likelihood (const Model & model, const typename Model::ImageT & data_im, const typename Model::Stencil & s)
Definition at line 185 of file PoissonGaussianNoise2DObjective.h.
References mappel::relative_poisson_log_likelihood(), and mappel::methods::objective::rllh().
template<class Model , class rng_t > std::enable_if<std::is_base_of<PoissonGaussianNoise2DObjective,Model>::value,typename Model::ImageT>::type simulate_image (const Model & model, const typename Model::Stencil & s, rng_t & rng)
Simulate an image using the PSF model, by generating Poisson noise.
Parameters
[out] image An image to populate.
[in] theta The parameter values to us
[in,out] rng An initialized random number generator
Definition at line 78 of file PoissonGaussianNoise2DObjective.h.
References mappel::generate_poisson().
template<class Model , class rng_t > std::enable_if<std::is_base_of<PoissonGaussianNoise2DObjective,Model>::value,typename Model::ImageT>::type simulate_image (const Model & model, const typename Model::ImageT & model_im, rng_t & rng)
Definition at line 89 of file PoissonGaussianNoise2DObjective.h.
References mappel::generate_poisson().