var searchData=
[
  ['has_5ffixed_5fparameters',['has_fixed_parameters',['../classmappel_1_1IterativeMaximizer_1_1MaximizerData.html#a9f1c22b2c3065f92244230a74fc948aa',1,'mappel::IterativeMaximizer::MaximizerData']]],
  ['has_5fhyperparam',['has_hyperparam',['../classmappel_1_1PointEmitterModel.html#afba2b17a81a506b0acd41616c8604412',1,'mappel::PointEmitterModel']]],
  ['hessian',['hessian',['../namespacemappel_1_1methods_1_1objective.html#afbf93fa446606620d01747af3684f62d',1,'mappel::methods::objective::hessian(const Model &amp;model, const ModelDataT&lt; Model &gt; &amp;data_im, const StencilT&lt; Model &gt; &amp;s, ParamT&lt; Model &gt; &amp;grad, MatT &amp;hess)'],['../namespacemappel_1_1methods_1_1objective.html#ad7242f889fcefed1ec11c238cd3d22e3',1,'mappel::methods::objective::hessian(const Model &amp;model, const ModelDataT&lt; Model &gt; &amp;data_im, const StencilT&lt; Model &gt; &amp;s, ParamT&lt; Model &gt; &amp;grad, MatT &amp;hess)'],['../namespacemappel_1_1methods_1_1objective.html#aff0530b529e752a4c9039a8aef0eac20',1,'mappel::methods::objective::hessian(const Model &amp;model, const ModelDataT&lt; Model &gt; &amp;data_im, const ParamT&lt; Model &gt; &amp;theta)'],['../namespacemappel_1_1methods_1_1objective.html#a21e579dfc19a06952bf98bd9d684fbdc',1,'mappel::methods::objective::hessian(const Model &amp;model, const ModelDataT&lt; Model &gt; &amp;data_im, const StencilT&lt; Model &gt; &amp;s)'],['../namespacemappel_1_1methods_1_1objective.html#a5c451515f6ec9eae7ffd321b9b8f95f1',1,'mappel::methods::objective::hessian(const Model &amp;model, const ModelDataT&lt; Model &gt; &amp;data_im, const ParamT&lt; Model &gt; &amp;theta, ParamT&lt; Model &gt; &amp;grad, MatT &amp;hess)'],['../namespacemappel_1_1methods_1_1objective.html#a0c7b3cd5fa4327c8f75e56937b2e616d',1,'mappel::methods::objective::hessian(const Model &amp;model, const ModelDataT&lt; Model &gt; &amp;data_im, const ParamT&lt; Model &gt; &amp;theta, MatT &amp;hess)'],['../namespacemappel_1_1methods_1_1likelihood.html#a0233341d03d8f8d06cb852068942ba73',1,'mappel::methods::likelihood::hessian(const Model &amp;model, const ModelDataT&lt; Model &gt; &amp;im, const StencilT&lt; Model &gt; &amp;s, ParamT&lt; Model &gt; &amp;grad_val, MatT &amp;hess_val)'],['../namespacemappel_1_1methods_1_1likelihood.html#ac16ac7a26d0773dc9c074e8ad796e161',1,'mappel::methods::likelihood::hessian(const Model &amp;model, const ModelDataT&lt; Model &gt; &amp;data_im, const StencilT&lt; Model &gt; &amp;s, ParamT&lt; Model &gt; &amp;grad_val, MatT &amp;hess_val)']]],
  ['hessian_5fcomponents',['hessian_components',['../namespacemappel_1_1methods_1_1objective_1_1debug.html#ab6f1cb872d35213373fae3ad7fac035f',1,'mappel::methods::objective::debug::hessian_components(const Model &amp;model, const ModelDataT&lt; Model &gt; &amp;data_im, const StencilT&lt; Model &gt; &amp;s)'],['../namespacemappel_1_1methods_1_1objective_1_1debug.html#af8701356bd2b54d5e4c915e443cf95a4',1,'mappel::methods::objective::debug::hessian_components(const Model &amp;model, const ModelDataT&lt; Model &gt; &amp;data_im, const StencilT&lt; Model &gt; &amp;s)'],['../namespacemappel_1_1methods_1_1objective_1_1debug.html#a70fff3cc898fe86da323c773dba30ab2',1,'mappel::methods::objective::debug::hessian_components(const Model &amp;model, const ModelDataT&lt; Model &gt; &amp;data_im, const ParamT&lt; Model &gt; &amp;theta)'],['../namespacemappel_1_1methods_1_1likelihood_1_1debug.html#a3ce1dba1970e94b391b4a60792ee635a',1,'mappel::methods::likelihood::debug::hessian_components(const Model &amp;model, const ModelDataT&lt; Model &gt; &amp;data_im, const StencilT&lt; Model &gt; &amp;s)'],['../namespacemappel_1_1methods_1_1likelihood_1_1debug.html#ab4a28e66a2192d238960defbe85c0d4c',1,'mappel::methods::likelihood::debug::hessian_components(const Model &amp;model, const ModelDataT&lt; Model &gt; &amp;data_im, const StencilT&lt; Model &gt; &amp;s)']]],
  ['hessian_5fstack',['hessian_stack',['../namespacemappel_1_1methods_1_1objective_1_1openmp.html#a134e673cbfdb9ac4e2d9ebec23ca2841',1,'mappel::methods::objective::openmp']]],
  ['heuristicestimator',['HeuristicEstimator',['../classmappel_1_1HeuristicEstimator.html',1,'mappel']]],
  ['heuristicestimator',['HeuristicEstimator',['../classmappel_1_1HeuristicEstimator.html#a51e2263b42adf83c66a5b8d2348a6bd6',1,'mappel::HeuristicEstimator']]]
];
